-- Generated by tools/map_c6/build.cjs from layout.cjs; map geometry only.
return {
    map_name = "survival_c6",
    build_bounds = { min_x = -4096, max_x = 2048, min_y = 2304, max_y = 8448 },
    resource_tree = { x = 646, y = 6742, z = 400 },
}
