local M = {
    ability_build_wall = {
        abilityid = "ability_build_wall",
        abilityname = "建造城墙",
        abilitydesc = "在指定位置建造城墙。城墙整局只能建造一次，且可以被选中并继续升级。",
        abilityicon = "tusk_ice_shards",
    },
    ability_build_main_city = {
        abilityid = "ability_build_main_city",
        abilityname = "建造主城",
        abilitydesc = "建造主城。主城拥有升级和训练伐木工两个技能。",
        abilityicon = "keeper_of_the_light_will_o_wisp",
    },
    ability_build_arrow_tower = {
        abilityid = "ability_build_arrow_tower",
        abilityname = "建造防御塔",
        abilitydesc = "建造可自动攻击敌人的防御塔。防御塔5级后可以选择一个转职方向。",
        abilityicon = "drow_ranger_marksmanship",
    },
    ability_build_research_lab = {
        abilityid = "ability_build_research_lab",
        abilityname = "建造研究所",
        abilitydesc = "主城建成后解锁。建造费用读取建筑等级CSV；建成后可打开建筑与工人科技界面。",
        abilityicon = "tinker_rearm",
    },
    ability_build_farm = {
        abilityid = "ability_build_farm",
        abilityname = "建造人口农场",
        abilitydesc = "消耗100木材建造人口农场。主城建成后解锁，可重复建造；建成后可升级农场并训练人口以提高人口上限。",
        abilityicon = "chen_holy_persuasion",
    },
    ability_upgrade_farm = {
        abilityid = "ability_upgrade_farm",
        abilityname = "升级人口农场",
        abilitydesc = "消耗资源提升人口农场的等级、生命值和护甲。农场等级不能高于主城等级，最高5级；农场等级越高，可训练的人口等级越高。",
        abilityicon = "ogre_magi_bloodlust",
    },
    ability_train_population = {
        abilityid = "ability_train_population",
        abilityname = "训练人口",
        abilitydesc = "最多训练5次。每次消耗、增加人口和所需农场等级均读取人口训练配置；完成5次后技能不可再用。",
        abilityicon = "chen_holy_persuasion",
    },
    ability_open_research_lab = {
        abilityid = "ability_open_research_lab",
        abilityname = "研究科技",
        abilitydesc = "打开研究所科技界面。科技升级、资源扣除和前置条件均由服务器校验。",
        abilityicon = "tinker_rearm",
    },
    ability_build_gold_mine = {
        abilityid = "ability_build_gold_mine",
        abilityname = "建造金矿",
        abilitydesc = "主城达到3级后解锁。消耗2000木材并占用2人口，最多建造5座。",
        abilityicon = "alchemist_goblins_greed",
    },
    ability_upgrade_gold_mine = {
        abilityid = "ability_upgrade_gold_mine",
        abilityname = "升级金矿",
        abilitydesc = "提升金矿本体等级。等级上限、每秒产量和升级费用均以金矿等级配置表为准。满级后技能自动隐藏。",
        abilityicon = "tinker_rearm",
    },
    ability_upgrade_gold_mine_efficiency = {
        abilityid = "ability_upgrade_gold_mine_efficiency",
        abilityname = "金矿收益",
        abilitydesc = "共50级，每级使该玩家所有金矿收益提高5%；额外金币不足1时按1金币计算。第1级消耗20000木材，之后每级增加20000木材。",
        abilityicon = "alchemist_goblins_greed",
    },
    ability_upgrade_gold_mine_crit = {
        abilityid = "ability_upgrade_gold_mine_crit",
        abilityname = "提升采集暴击率",
        abilitydesc = "共10级，每级增加3%采集暴击率。第1级消耗2000金币，之后每级增加10000金币；采集暴击时获得正常采集金币的3倍。",
        abilityicon = "phantom_assassin_coup_de_grace",
    },
    ability_gold_mine_auto_upgrade = {
        abilityid = "ability_gold_mine_auto_upgrade",
        abilityname = "自动升级",
        abilitydesc = "自动按金矿本体、收益、暴击的顺序升级。开启后其他金矿技能隐藏。",
        abilityicon = "tinker_rearm",
    },
    ability_gold_mine_stop_auto_upgrade = {
        abilityid = "ability_gold_mine_stop_auto_upgrade",
        abilityname = "停止自动升级",
        abilitydesc = "停止金矿自动升级，并恢复所有尚未满级的金矿技能。",
        abilityicon = "tinker_rearm",
    },
    ability_upgrade_wall = {
        abilityid = "ability_upgrade_wall",
        abilityname = "升级城墙",
        abilitydesc = "消耗资源提升城墙等级、生命值和护甲。升级条件和费用由服务端实时校验。",
        abilityicon = "ogre_magi_bloodlust",
    },
    ability_upgrade_city = {
        abilityid = "ability_upgrade_city",
        abilityname = "升级主城",
        abilitydesc = "消耗木材和金币提升主城等级、生命、护甲和人口上限。",
        abilityicon = "alchemist_goblins_greed",
    },
    ability_train_lumberjack = {
        abilityid = "ability_train_lumberjack",
        abilityname = "训练伐木工",
        abilitydesc = "训练一名伐木工。伐木工会在主城外侧出生，并自动攻击资源树。当前每次有效攻击获得1点木材。",
        abilityicon = "furion_force_of_nature",
    },
    ability_train_repairer = {
        abilityid = "ability_train_repairer",
        abilityname = "训练修理工",
        abilitydesc = "训练普通修理工。每名修理工消耗1人口，最多训练5名；费用和修理效率读取训练配置。",
        abilityicon = "wisp_tether",
    },
    ability_train_advanced_repairer = {
        abilityid = "ability_train_advanced_repairer",
        abilityname = "训练高级修理工",
        abilitydesc = "直接训练高级修理工。每名消耗1人口，最多训练2名；无需先训练普通修理工。",
        abilityicon = "wisp_overcharge",
    },
    ability_upgrade_tower = { abilityid = "ability_upgrade_tower", abilityname = "升级防御塔", abilitydesc = "按当前等级升1级。金币和木材不足时不会消耗，也不会进入冷却。", abilityicon = "drow_ranger_multishot" },
    ability_upgrade_tower_lv01 = { abilityid = "ability_upgrade_tower_lv01", abilityname = "升级1级", abilitydesc = "按当前路线升1级；消耗由路线表自动计算。", abilityicon = "drow_ranger_multishot" },
    ability_upgrade_tower_max = { abilityid = "ability_upgrade_tower_max", abilityname = "升满级", abilitydesc = "一次升至当前阶段最高等级；自动累计计算金币和木材消耗。", abilityicon = "drow_ranger_multishot" },
    ability_tower_class_1 = { abilityid = "ability_tower_class_1", abilityname = "【N】死亡之塔", abilitydesc = "转职为【N】死亡之塔；转职后技能全部为被动技能。", abilityicon = "axe_battle_hunger" },
    ability_tower_class_2 = { abilityid = "ability_tower_class_2", abilityname = "【N】神秘之塔", abilitydesc = "转职为【N】神秘之塔；转职后技能全部为被动技能。", abilityicon = "drow_ranger_frost_arrows" },
    ability_tower_class_3 = { abilityid = "ability_tower_class_3", abilityname = "【N】闪电塔", abilitydesc = "转职为【N】闪电塔；转职后技能全部为被动技能。", abilityicon = "windrunner_focusfire" },
    ability_tower_class_4 = { abilityid = "ability_tower_class_4", abilityname = "【N】机枪塔", abilitydesc = "转职为【N】机枪塔；转职后技能全部为被动技能。", abilityicon = "sniper_take_aim" },
    ability_tower_class_5 = { abilityid = "ability_tower_class_5", abilityname = "【N】多重塔", abilitydesc = "转职为【N】多重塔；转职后技能全部为被动技能。", abilityicon = "zuus_arc_lightning" },
    ability_tower_class_6 = { abilityid = "ability_tower_class_6", abilityname = "【N】冰霜之塔", abilitydesc = "转职为【N】冰霜之塔；转职后技能全部为被动技能。", abilityicon = "lich_frost_nova" },
    ability_tower_class_7 = { abilityid = "ability_tower_class_7", abilityname = "【N】魔法塔", abilitydesc = "转职为【N】魔法塔；成长为大魔法塔与魔法至尊，使用魔法伤害克制高护甲敌人。", abilityicon = "rubick_arcane_supremacy" },
    ability_build_hero_altar = {
        abilityid = "ability_build_hero_altar",
        abilityname = "建造英雄祭坛",
        abilitydesc = "主城达到3级后可建造。祭坛可以召唤一个战斗英雄；召唤完成后祭坛停止工作，并解锁商店。",
        abilityicon = "omniknight_guardian_angel",
    },
    ability_open_hero_altar = {
        abilityid = "ability_open_hero_altar",
        abilityname = "召唤英雄",
        abilitydesc = "从斧王、斯拉克、主宰、齐天大圣和宙斯中选择一个英雄。每位玩家只能选择一次，齐天大圣和宙斯需要VIP。",
        abilityicon = "chen_holy_persuasion",
    },
    ability_enter_endless_training = {
        abilityid = "ability_enter_endless_training",
        abilityname = "进入无尽年轮圣殿",
        abilitydesc = "消耗50000金币传送。每秒再消耗50000金币；攻击练功建筑时攻击力与三围成长收益为15倍。",
        abilityicon = "faceless_void_time_walk",
        is_active = true,
    },
    ability_enter_shadow_realm = {
        abilityid = "ability_enter_shadow_realm",
        abilityname = "进入暗影界前庭",
        abilitydesc = "消耗50000金币传送至暗影界前庭。当前版本仅开放传送。",
        abilityicon = "spectre_reality",
        is_active = true,
    },

ability_summon_axe = {
    abilityid = "ability_summon_axe",
    abilityname = "召唤斧王",
    abilitydesc = "召唤斧王。专属技能固定显示在Q槽，完成一转后激活。",
    abilityicon = "axe_berserkers_call",
},
ability_summon_doom = {
    abilityid = "ability_summon_doom",
    abilityname = "召唤末日使者",
    abilitydesc = "召唤末日使者。专属技能固定显示在Q槽，完成一转后激活。",
    abilityicon = "doom_bringer_devour",
},
ability_summon_shadow_fiend = {
    abilityid = "ability_summon_shadow_fiend",
    abilityname = "召唤影魔",
    abilitydesc = "召唤影魔。专属技能固定显示在Q槽，完成一转后激活。",
    abilityicon = "nevermore_shadowraze1",
},
ability_summon_drow_ranger = {
    abilityid = "ability_summon_drow_ranger",
    abilityname = "召唤黑暗游侠",
    abilitydesc = "召唤黑暗游侠。专属技能固定显示在Q槽，完成一转后激活。",
    abilityicon = "drow_ranger_multishot",
},
ability_summon_monkey_king = {
    abilityid = "ability_summon_monkey_king",
    abilityname = "召唤齐天大圣（VIP）",
    abilitydesc = "召唤齐天大圣。需要VIP权限，攻击距离1000，清除原版技能后初始获得4个项目技能。",
    abilityicon = "monkey_king_boundless_strike",
},
ability_summon_blademaster = {
    abilityid = "ability_summon_blademaster",
    abilityname = "召唤剑圣（VIP）",
    abilitydesc = "召唤剑圣。需要VIP权限；当前使用Sven作为测试载体，初始获得4个项目技能。",
    abilityicon = "sven_gods_strength",
},
}

return M
