"use strict";
// Active payment XML and both checkout controllers; every request/browser call stays in local recorders.
const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict");
const cfg={},jobs=new Map(),subscriptions=new Map(),netSubscriptions=new Map(),requests=[],ticketVisits=[],effectTooltips=[],movies=[],logs=[];let serial=0,clock=0;
class Panel{
 constructor(type,parent,id=""){this.type=type;this.paneltype=type;this.parent=parent;this.id=id;this.children=[];this.classes=new Set();this.style={};this.events={};this.visible=true;this.enabled=true;if(parent)parent.children.push(this);}
 valid(){assert(!this.deleted,"Underlying panel is deleted");}IsValid(){return !this.deleted;}
 AddClass(c){this.valid();String(c).split(/\s+/).filter(Boolean).forEach(c=>this.classes.add(c));}RemoveClass(c){this.valid();this.classes.delete(c);}BHasClass(c){this.valid();return this.classes.has(c);}SetHasClass(c,v){v?this.AddClass(c):this.RemoveClass(c);}ToggleClass(c){this.SetHasClass(c,!this.BHasClass(c));}
 GetParent(){this.valid();return this.parent;}Children(){this.valid();return this.children;}GetChildCount(){return this.Children().length;}GetChild(i){return this.Children()[i];}GetClasses(){this.valid();return [...this.classes];}
 FindChildTraverse(id){this.valid();if(this.id===id)return this;for(const child of this.children){const found=child.FindChildTraverse(id);if(found)return found;}return null;}
 SetPanelEvent(n,f){this.valid();this.events[n]=f;}SetImage(v){this.valid();this.image=v;}SetScaling(){}SetFocus(){}SetAcceptsFocus(){}
 MoveChildBefore(child,before){this.valid();this.children=this.children.filter(c=>c!==child);const index=this.children.indexOf(before);this.children.splice(index<0?this.children.length:index,0,child);}
 SetParent(parent){this.valid();if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);this.parent=parent;parent.children.push(this);}
 RemoveAndDeleteChildren(){this.valid();for(const child of [...this.children])child.DeleteAsync();this.children=[];}DeleteAsync(){this.valid();this.RemoveAndDeleteChildren();this.deleted=true;if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);}
 GetPositionWithinWindow(){this.valid();return {x:320,y:140};}get actuallayoutwidth(){this.valid();return this.parent?parseFloat(this.style.width)||1280:this.width||1920;}get actuallayoutheight(){this.valid();return this.parent?parseFloat(this.style.height)||800:this.height||1080;}get actualuiscale_x(){return 1;}get actualuiscale_y(){return 1;}
 SetControls(v){this.controls=v;}SetRepeat(v){this.repeat=v;}SetPlaybackVolume(v){this.volume=v;}SetMovie(v){this.movie=v;}Play(){this.playing=true;movies.push(this);}Stop(){this.playing=false;}
}
function decode(v){return String(v).replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&");}
function assemble(xml,root){const stack=[root];for(const match of xml.replace(/<!--[\s\S]*?-->/g,"").matchAll(/<(\/?)([A-Za-z][\w]*)\b([^>]*)>/g)){const [,end,type,body]=match;if(["root","styles","scripts","include"].includes(type))continue;if(end){stack.pop();continue;}const attrs=Object.fromEntries([...body.matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],decode(m[2])]));const p=new Panel(type,stack.at(-1),attrs.id||"");if(attrs.class)p.AddClass(attrs.class);if(attrs.text)p.text=attrs.text;if(attrs.visible)p.visible=attrs.visible!=="false";if(attrs.checked)p.checked=attrs.checked==="true";if(attrs.enabled)p.enabled=attrs.enabled!=="false";if(attrs.onactivate)p.xmlAction=attrs.onactivate;if(!/\/\s*$/.test(body))stack.push(p);}}
const root=new Panel("Panel",null,"hud_context");assemble(fs.readFileSync("panorama/src/layout/custom_game/survival_hud.xml","utf8"),root);
function dollar(owner){function $(id){return owner.FindChildTraverse(String(id).replace(/^#/,""));}$.GetContextPanel=()=>owner;$.CreatePanel=(t,p,id)=>new Panel(t,p,id);$.Msg=s=>logs.push(String(s));$.DispatchEvent=()=>{};$.RegisterEventHandler=()=>{};$.Schedule=(delay,fn)=>{const id=++serial;jobs.set(id,{at:clock+delay,fn});return id;};$.CancelScheduled=id=>jobs.delete(id);return $;}
class TestDate extends Date{static now(){return Math.floor(clock*1000);}}
const env={Date:TestDate,$:dollar(root),GameUI:{CustomUIConfig:()=>cfg},Game:{GetLocalPlayerID:()=>0,IsInToolsMode:()=>false},GameEvents:{Subscribe:(n,f)=>{const id=++serial;subscriptions.set(id,{n,f});return id;},Unsubscribe:id=>subscriptions.delete(id),SendCustomGameEventToServer:(n,p)=>requests.push({n,p})},CustomNetTables:{GetTableValue:()=>({resources:{gold:100,wood:200}}),SubscribeNetTableListener:(n,f)=>{const id=++serial;netSubscriptions.set(id,{n,f});return id;},UnsubscribeNetTableListener:id=>netSubscriptions.delete(id)}};
function load(name,target=env){vm.runInNewContext(fs.readFileSync("panorama/src/scripts/custom_game/"+name,"utf8"),target,{filename:name});}
function emit(name,payload){for(const sub of [...subscriptions.values()])if(sub.n===name)sub.f(payload);}
function advance(seconds){const end=clock+seconds;let turns=0;while(true){const next=[...jobs].filter(([,job])=>job.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;assert(++turns<5000,"unexpected runaway UI timer");jobs.delete(next[0]);clock=next[1].at;next[1].fn();}clock=end;}
function all(p=root){return [p,...p.Children().flatMap(child=>all(child))];}const node=id=>root.FindChildTraverse(id),draws=()=>requests.filter(r=>r.n==="ui_lottery_draw_request"),danger=()=>requests.filter(r=>r.n!=="ui_lottery_snapshot_request");
require("../load_shared_ui_test.cjs")(env,Panel,root);

assemble(fs.readFileSync("panorama/src/layout/custom_game/payment_test.xml","utf8"),root);
const browserCalls=[],catalogs=[],notices=[];let shopOpens=0;
env.$.DispatchEvent=(name,...args)=>browserCalls.push({name,args});
cfg.SurvivalCommerceView={UpdateWalletCatalog:c=>catalogs.push({type:"wallet",c}),UpdateCatalog:c=>catalogs.push({type:"cash",c}),SetNotice:s=>notices.push(s),Open:()=>{shopOpens++;},IsOpen:()=>false};
for(const name of ["ui_layers.js","reference_windows.js","remaining_5d5c1152eb.js","commerce_wallet.js","payment_test.js"])load(name);
const cashRequests=()=>requests.filter(r=>r.n==="survival_payment_request"),walletRequests=()=>requests.filter(r=>r.n==="survival_commerce_request"),transactions=()=>requests.filter(r=>["create","purchase"].includes(r.p.action));
function activate(p){if(!p.enabled||!p.IsValid())return;if(p.events.onactivate)return p.events.onactivate();if(p.xmlAction)vm.runInNewContext(p.xmlAction,env);}
const walletProduct={sku:"wallet_compact",title:"寒霜印记",price:6800,currency:"u_coin",purchase_limit:1,enabled:1,description:"英雄护甲+2\n术式 <冰>&霜",category_id:"technology"};
function walletCatalog(product=walletProduct){cfg.SurvivalCommerceWallet.Refresh();const request=walletRequests().at(-1);emit("survival_commerce_result",{ok:1,action:"catalog",request_id:request.p.request_id,part:"begin",count:1,categories:[{id:"technology",label:"科技"}],balances:{u_coin:10000,shop_points:20,shop_gold:300}});emit("survival_commerce_result",{ok:1,action:"catalog",request_id:request.p.request_id,part:"product",index:1,product});emit("survival_commerce_result",{ok:1,action:"catalog",request_id:request.p.request_id,part:"end"});}
function walletReply(data){const request=walletRequests().at(-1);emit("survival_commerce_result",{action:request.p.action,request_id:request.p.request_id,...data});}
function confirmNode(cls){return all().filter(p=>p.BHasClass(cls)).at(-1);}
walletCatalog();assert.equal(transactions().length,0);assert(cfg.SurvivalCommerceWallet.Checkout(walletProduct.sku));
const walletDialog=confirmNode("CommerceConfirm"),walletCopy=confirmNode("CommerceConfirmCopy");
assert(walletDialog.BHasClass("CheckoutPurple"));assert(walletDialog.style.backgroundColor.includes("#211631"));assert(walletCopy.text.includes("6800 U币"));assert(walletCopy.text.includes("10000 U币"));assert(walletCopy.text.includes("&lt;冰&gt;&amp;霜"));assert(walletCopy.text.includes("<br>"));assert.equal(transactions().length,0,"Checkout/style/description never exchanges currency");
activate(confirmNode("CommerceConfirmBuy"));const exchange=walletRequests().at(-1);assert.deepEqual(Object.keys(exchange.p).sort(),["action","request_id","sku"]);activate(confirmNode("CommerceConfirmBuy"));assert.equal(transactions().length,1,"explicit exchange blocks repeated clicks");
emit("survival_commerce_result",{action:"purchase",ok:1,request_id:"unrelated",balance:1,currency:"u_coin"});assert(!confirmNode("CommerceConfirmBuy").enabled);walletReply({ok:0,terminal:0,error:"commerce_busy"});activate(confirmNode("CommerceConfirmBuy"));assert.equal(walletRequests().at(-1).p.request_id,exchange.p.request_id,"uncertain exchange retries the same server id");walletReply({ok:0,terminal:0,error:"archive_pending"});
load("commerce_wallet.js");walletCatalog();cfg.SurvivalCommerceWallet.Checkout(walletProduct.sku);activate(confirmNode("CommerceConfirmBuy"));assert.equal(walletRequests().at(-1).p.request_id,exchange.p.request_id,"hot reload retains uncertain transaction token");walletReply({ok:1,terminal:1,sku:walletProduct.sku,currency:"u_coin",price:6800,balance:3200});assert.equal(cfg.SurvivalCommercePending,null);assert.equal(cfg.SurvivalCommerceWallet.GetCatalog().balances.u_coin,3200);assert(confirmNode("CommerceConfirmStatus").text.includes("3200"));
advance(1.2);walletReply({ok:0,error:"commerce_busy"});walletCatalog({...walletProduct,enabled:0,disabled_reason:"already_owned"});cfg.SurvivalCommerceWallet.Checkout(walletProduct.sku);const beforeDisabled=transactions().length;activate(confirmNode("CommerceConfirmBuy"));assert.equal(transactions().length,beforeDisabled);assert(confirmNode("CommerceConfirmStatus").text.includes("已拥有"));
activate(confirmNode("CommerceConfirmBack"));assert.equal(shopOpens,1);assert.equal(cfg.SurvivalUILayers.Top(),null);cfg.SurvivalCommerceWallet.Checkout(walletProduct.sku);advance(.1);cfg.SurvivalUILayers.HandleEscape();assert.equal(cfg.SurvivalUILayers.Top(),null,"original ESC closes wallet popup");

const cashProduct={sku:"bundle_777",title:"冒险组合",description:"完整奖励组合",amount_fen:777,enabled:1,icon:"custom_game/commerce/item_01.png",reward_lines:[{kind:"stat",id:"initial_wood",label:"初始木材",quantity:200},{kind:"entitlement",id:"vip",label:"贵宾权限",quantity:1}],stat_preview:[{field_id:"initial_wood",value:100,after:300}]};
function cashReply(data){const request=cashRequests().at(-1);emit("survival_payment_result",{ok:1,action:request.p.action,request_id:request.p.request_id,...data});}
function cashCatalog(products=[cashProduct],overrides={}){cfg.SurvivalPayments.RefreshCatalog(true);cashReply({products,categories:[{id:"technology",label:"科技"}],wechat:1,alipay:1,...overrides});}
cfg.SurvivalPayments.Checkout(cashProduct.sku);assert.equal(cashRequests().at(-1).p.action,"catalog");cashReply({products:[cashProduct],categories:[],wechat:1,alipay:1,game_values:{initial_wood:100},wallet:{wood:999}});
const pay=node("PaymentDialog");assert(pay.BHasClass("CheckoutPurple"));assert(pay.style.backgroundColor.includes("#211631"));assert.equal(node("PaymentPrice").text,"¥7.77");assert(node("PaymentValues").text.includes("贵宾权限 ×1"));assert(node("PaymentValues").text.includes("100 → 300"));assert(node("PaymentValues").text.includes("<br>"));assert(!node("PaymentQuantityMinus").enabled&&!node("PaymentQuantityPlus").enabled);assert.equal(cashRequests().filter(r=>r.p.action==="create").length,0,"opening a cash popup never creates an order");
const beforeCash=cashRequests().length;env.PaymentChannel("alipay");env.PaymentChannel("wechat");assert.equal(cashRequests().length,beforeCash);activate(node("PaymentBuy"));const create=cashRequests().at(-1);assert.deepEqual(Object.keys(create.p).sort(),["action","provider","request_id","sku"]);assert.equal(create.p.provider,"wechat");activate(node("PaymentBuy"));env.PaymentBuy();assert.equal(cashRequests().at(-1),create,"cash buy guards duplicate activation");
const url="https://pay.xiaofengnet.com/checkout?order=WX"+"a".repeat(30)+"&token="+"b".repeat(64),matrix=Array.from({length:29},(_,i)=>Array.from({length:29},(_,j)=>(i+j)%2?"1":"0").join("")).join("|");
const order={...cashProduct,order_id:"local_fixture_order",state:"pending",provider:"wechat",sku:cashProduct.sku,checkout_url:url,qr_matrix:matrix,effects:{initial_wood:200}};cashReply(order);assert(pay.BHasClass("HasOrder"));assert.equal(node("PaymentHeading").text,"扫码支付");assert.equal(node("PaymentQR").GetChildCount(),29);assert(all(node("PaymentQR")).some(p=>p.style.backgroundColor==="#000000"),"QR still uses native black modules");assert.equal(browserCalls.filter(c=>c.name==="ExternalBrowserGoToURL").length,0,"QR response never opens a browser automatically");assert(!node("PaymentBuy").enabled);
env.PaymentChannel("alipay");assert(node("PaymentWeChat").BHasClass("Selected"));env.PaymentBuy();assert.equal(cashRequests().at(-1),create);activate(node("PaymentOpen"));assert.equal(browserCalls.filter(c=>c.name==="ExternalBrowserGoToURL").length,1);assert.equal(browserCalls.at(-1).args[0],url,"only explicit fallback dispatches the exact trusted local URL");
cashCatalog([{...cashProduct,amount_fen:9999,reward_lines:[{kind:"stat",id:"initial_wood",label:"初始木材",quantity:999}],stat_preview:[]}]);assert.equal(node("PaymentPrice").text,"¥7.77");assert(node("PaymentValues").text.includes("初始木材 ×200"));assert(node("PaymentValues").text.includes("本单加成：+200"));cashCatalog([]);assert.equal(node("PaymentTitle").text,cashProduct.title);assert.equal(node("PaymentPrice").text,"¥7.77","delisting preserves the server-created pending order");
env.PaymentRefresh();const statusRequest=cashRequests().at(-1);emit("survival_payment_result",{ok:1,action:"status",request_id:"old_request",...order,state:"delivered"});assert(!pay.BHasClass("Receipt"));cashReply({...order,state:"delivered",effect_changes:{initial_wood:{before:100,after:300,delta:200}},game_entitlements:{vip:{active:true}}});assert(pay.BHasClass("Receipt"));assert.equal(node("PaymentHeading").text,"支付结果");assert(node("PaymentValues").text.includes("本单存档：100 → 300（+200）"));assert(node("PaymentValues").text.includes("本局已生效"));assert.equal(node("PaymentPrice").text,"¥7.77");assert(!node("PaymentBuy").enabled);assert.equal(node("PaymentOpen").style.visibility,"collapse");assert.equal(cashRequests().filter(r=>r.p.action==="create").length,1);
advance(1.2);cashReply({products:[{...cashProduct,enabled:0,disabled_reason:"already_owned"}],categories:[],wechat:1,alipay:0});cfg.SurvivalPayments.Checkout(cashProduct.sku);activate(node("PaymentBuy"));assert.equal(cashRequests().filter(r=>r.p.action==="create").length,1);activate(node("PaymentBack"));assert.equal(shopOpens,2);assert.equal(cfg.SurvivalUILayers.Top(),null);cfg.SurvivalPayments.Checkout(cashProduct.sku);advance(.1);cfg.SurvivalUILayers.HandleEscape();assert.equal(cfg.SurvivalUILayers.Top(),null,"cash popup retains original ESC layer");

// Full native subtree deletion tests old APIs, pending timer and callbacks before a fresh XML reload.
const oldWallet=cfg.SurvivalCommerceWallet,oldCash=cfg.SurvivalPayments,callbacks=[...subscriptions.values()].filter(s=>/^survival_(commerce|payment)_/.test(s.n));
oldCash.RefreshCatalog(true);oldWallet.Refresh();const oldJobs=[...jobs.values()].map(j=>j.fn),beforeDelete=requests.length;root.DeleteAsync();
for(const fn of [()=>oldWallet.Checkout(walletProduct.sku),()=>oldWallet.Refresh(),()=>oldCash.Checkout(cashProduct.sku),()=>oldCash.Open(),()=>oldCash.RefreshCatalog(true),()=>env.PaymentBuy(),()=>env.PaymentOpen(),()=>env.PaymentToggle(),()=>env.PaymentCancel()])assert.doesNotThrow(fn);
for(const sub of callbacks)assert.doesNotThrow(()=>sub.f({ok:1,action:"catalog",request_id:"deleted"}));for(const fn of oldJobs)assert.doesNotThrow(fn);assert.equal(requests.length,beforeDelete,"deleted UI callbacks never create, exchange or query");
assert.doesNotThrow(()=>oldWallet.Dispose());assert.doesNotThrow(()=>oldCash.Dispose());assert.equal([...subscriptions.values()].filter(s=>/^survival_(commerce|payment)_/.test(s.n)).length,0);
const fresh=new Panel("Panel",null,"fresh_checkout_context");assemble(fs.readFileSync("panorama/src/layout/custom_game/payment_test.xml","utf8"),fresh);env.$=dollar(fresh);require("../load_shared_ui_test.cjs")(env,Panel,fresh);
for(let i=0;i<2;i++)for(const source of ["ui_layers.js","reference_windows.js","remaining_5d5c1152eb.js","commerce_wallet.js","payment_test.js"])load(source);
assert.equal([...subscriptions.values()].filter(s=>s.n==="survival_commerce_result").length,1);assert.equal([...subscriptions.values()].filter(s=>s.n==="survival_payment_result").length,1);assert.equal([...subscriptions.values()].filter(s=>s.n==="survival_payment_open").length,1);assert.equal(transactions().length,beforeDisabled+1,"two clean reloads cannot issue transactions");
console.log("CHECKOUT_PURPLE_PASS: active XML/controllers and shared shell; real currency/amount/rewards/immutable order/receipt/QR; explicit-only create/exchange/browser, repeated click guards, uncertain-id reload, disabled/ESC, complete native deletion and two reloads; no actual transactions");
