"use strict";
// Execute the active daily controller and shared shells; all requests stay local.
const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict"),{csv}=require("../shop_ui_12h/catalog.cjs");
const nodes={},subscriptions=new Map(),requests=[],jobs=new Map();let serial=0,sequence=0;
class Panel{
 constructor(type,parent,id){this.type=type;this.paneltype=type;this.parent=parent;this.id=id;this.children=[];this.classes=new Set();this.events={};this.style={};this.enabled=true;this.visible=true;if(parent)parent.children.push(this);if(id)nodes[id]=this;}
 AddClass(c){String(c).split(/\s+/).forEach(c=>this.classes.add(c));}RemoveClass(c){this.classes.delete(c);}BHasClass(c){return this.classes.has(c);}SetHasClass(c,v){v?this.AddClass(c):this.RemoveClass(c);}ToggleClass(c){this.SetHasClass(c,!this.BHasClass(c));}
 SetPanelEvent(n,f){this.events[n]=f;}SetImage(v){this.image=v;}SetScaling(v){this.scaling=v;}GetParent(){return this.parent;}Children(){return this.children;}GetChildCount(){return this.children.length;}GetChild(i){return this.children[i];}FindChildTraverse(id){return nodes[id]||null;}IsValid(){return !this.deleted;}SetFocus(){}SetAcceptsFocus(){}
 RemoveAndDeleteChildren(){this.children.forEach(p=>p.DeleteAsync());this.children=[];}DeleteAsync(){this.deleted=true;this.children.forEach(p=>p.DeleteAsync());if(this.parent)this.parent.children=this.parent.children.filter(p=>p!==this);}
 GetPositionWithinWindow(){return this.position||{x:320,y:140};}get actuallayoutwidth(){return this.parent?parseFloat(this.style.width)||138:1920;}get actuallayoutheight(){return this.parent?parseFloat(this.style.height)||168:1080;}get actualuiscale_x(){return 1;}get actualuiscale_y(){return 1;}
}
for(const name of ["AddClass","RemoveClass","BHasClass","SetHasClass","ToggleClass","SetPanelEvent","SetImage","SetScaling","GetParent","Children","GetChildCount","GetChild","FindChildTraverse","SetFocus","SetAcceptsFocus","RemoveAndDeleteChildren","DeleteAsync","GetPositionWithinWindow"]){const original=Panel.prototype[name];Panel.prototype[name]=function(...args){assert(!this.deleted,"native method invoked on a deleted Panel");return original.apply(this,args);};}
const root=new Panel("Panel",null,"root");function assembleIds(){for(const m of fs.readFileSync("panorama/src/layout/custom_game/archive.xml","utf8").matchAll(/<[A-Za-z]\w*\b[^>]*\bid="([^"]+)"[^>]*>/g)){const panel=new Panel("Panel",root,m[1]),cls=m[0].match(/\bclass="([^"]+)"/);if(cls)panel.AddClass(cls[1]);}}assembleIds();
const cfg={};function $(id){return nodes[String(id).replace(/^#/,"")];}$.GetContextPanel=()=>root;$.CreatePanel=(t,p,id)=>new Panel(t,p,id);$.DispatchEvent=()=>{};$.Msg=()=>{};$.RegisterEventHandler=()=>{};$.Schedule=(delay,fn)=>{jobs.set(++serial,{delay,fn});return serial;};$.CancelScheduled=id=>jobs.delete(id);
function tick(delay){for(const [id,job]of [...jobs])if(job.delay===delay){jobs.delete(id);job.fn();}}
const env={$,GameUI:{CustomUIConfig:()=>cfg},Game:{GetLocalPlayerID:()=>0},GameEvents:{Subscribe:(n,f)=>{subscriptions.set(++serial,{n,f});return serial;},Unsubscribe:id=>subscriptions.delete(id),SendCustomGameEventToServer:(n,p)=>requests.push({n,p})},CustomNetTables:{GetTableValue:()=>null,SubscribeNetTableListener:()=>1}};
require("../load_shared_ui_test.cjs")(env,Panel,root);
function load(file){vm.runInNewContext(fs.readFileSync("panorama/src/scripts/custom_game/"+file,"utf8"),env);}
for(const file of ["daily_resources.js","ui_layers.js","common/purple_shell.js","item_art_remaining_5d5c1152eb.js"])load(file);
cfg.RemainingHandoff={Window:p=>p.AddClass("RHWindow"),SizeWindow:(p,w,h)=>{p.style.width=w+"px";p.style.height=h+"px";},Action(){},DailyResourceInfo:id=>cfg.SurvivalUI.ResourceInfo(id),DailyImage:(p,id,cls)=>cfg.SurvivalUI.Image(p,id,cls),DailyCard:(p,last,today)=>p.SetHasClass("RHDailyCurrent",today),DailyPass:(p,on)=>{p.style.backgroundColor="#233e46";p.SetHasClass("UnifiedPassActive",on);}};
load("daily_remaining_5d5c1152eb.js");
assert(nodes.DailyRulesText.style.backgroundColor.includes("#211630"),"rules explicitly replace legacy inline teal skin");assert.equal(nodes.DailyRulesBody.style.width,"840px");assert.equal(nodes.DailyRulesBody.style.whiteSpace,"normal","rules wrap inside the padded popup");
assert.equal(nodes.DailyRulesText.style.height,"fit-children","short authoritative rules fit their content instead of reserving a blank 516px panel");assert.equal(nodes.DailyRulesText.style.maxHeight,"516px");assert.equal(nodes.DailyRulesText.style.position,"184px 164px 0px");assert.equal(nodes.DailyRulesText.style.width,"912px");assert.equal(nodes.DailyRulesBody.style.height,"fit-children");assert.equal(nodes.DailyRulesText.style.overflow,"squish scroll","long prose remains scrollable beneath the preserved height cap");
function opaque(surface){const colors=[...surface.matchAll(/#([0-9a-f]+)\b/gi)].map(m=>m[1]);return colors.length>0&&colors.every(hex=>hex.length===6||hex.length===8&&hex.endsWith("ff"));}
assert(opaque(nodes.DailyRulesText.style.backgroundColor),"actual inline rules background is fully opaque");
const dailyCss=fs.readFileSync("panorama/src/styles/custom_game/daily_purple.css","utf8"),dailyTipRule=dailyCss.match(/#DailyWindow\.RHWindow\.DailyPurple #DailyTooltip\s*\{([^}]+)\}/)[1];
assert(opaque(dailyTipRule.match(/background-color:([^;]+);/)[1]),"tooltip gradient cannot bleed underlying reward icons or names");
const dailyRulesRule=dailyCss.match(/#DailyWindow\.RHWindow\.DailyPurple #DailyRulesText\s*\{([^}]+)\}/)[1];assert(dailyRulesRule.includes("height:fit-children;")&&dailyRulesRule.includes("max-height:516px;")&&dailyRulesRule.includes("overflow:squish scroll;"),"stylesheet fallback keeps the same automatic-height/scroll contract as the native inline presentation");
function all(p=root){return [p,...p.children.flatMap(child=>all(child))];}function count(name){return requests.filter(r=>r.n===name).length;}function emit(data){for(const sub of subscriptions.values())if(sub.n==="survival_daily_snapshot")sub.f(data);}function send(changes={}){emit({...fixture,sequence:++sequence,...changes});}
cfg.SurvivalDaily.Open(false);assert.equal(nodes.DailyWindow.style.width,"1280px");assert.equal(nodes.DailyWindow.style.height,"800px");assert(nodes.DailyWindow.BHasClass("PurpleShell"));assert.equal(count("survival_daily_claim"),0);assert.equal(count("survival_pass_purchase"),0);assert.equal(nodes.DailyClaim.enabled,false,"loading prevents repeated fetch/claim");tick(8);assert.equal(nodes.DailyClaimText.text,"重试加载");nodes.DailyClaim.events.onactivate();assert.equal(count("survival_daily_request"),2);
const items=Object.fromEntries(csv("data/csv/存档系统/archive_daily_items.csv").map(row=>[row.item_id,row])),rule=csv("data/csv/存档系统/archive_daily_rules.csv")[0];
const fixture={ok:1,today:25003,count:2,period_id:"0",ordinary_status:"claimable",cycle_mode:"claim_count",has_pass:0,pending:0,missed:[],makeup_days:Number(rule.makeup_days),duration_days:Number(rule.duration_days),price:rule.price_text,purchase_enabled:Number(rule.purchase_enabled),rule_text:"每日零点刷新；断签不重置累计进度。通行证奖励按累计签到次数发放。",cycle:csv("data/csv/存档系统/archive_daily_schedule.csv").map(row=>({day:Number(row.day_id),is_today:Number(row.day_id)===3?1:0,status:Number(row.day_id)<3?"claimed":Number(row.day_id)===3?"claimable":"not_open",rewards:row.item_ids.split("|").map((id,i)=>({id,name:items[id].display_name,description:items[id].description,count:Number(row.item_counts.split("|")[i])}))})),specials:rule.pass_item_ids.split("|").map((id,i)=>({id,day:Number(rule.pass_milestones.split("|")[i]),name:items[id].display_name,description:items[id].description,owned:0})),premium:{status:"unconfigured",name:"周末高级装备",description:"周周期与装备候选池尚未配置"}};
send();assert.equal(nodes.DailyCards.children.length,7,"seven server days remain independent of premium slot");assert.equal(nodes.DailySpecials.children.length,3,"actual 7/14/21-day pass milestones remain configured");assert.equal(nodes.DailyPurplePremium.children.find(p=>p.BHasClass("DailyCardStatus")).text,"暂未开放");assert.equal(nodes.DailyMakeup.visible,false);assert.equal(count("survival_daily_claim"),0,"a server snapshot never claims automatically");assert(nodes.DailyRulesBody.html&&nodes.DailyRulesBody.text.includes('<br>累计14次：'),"explicit paragraph breaks survive wrapped rules");send({rule_text:'第一行 <未接入> &\n第二行'});assert(nodes.DailyRulesBody.text.includes('&lt;未接入&gt; &amp;<br>第二行'),"server rule prose is escaped before adding line breaks");
const slots=all(nodes.DailyCards).filter(p=>p.BHasClass("DailyReward"));assert.equal(slots.length,9,"real fifth and sixth days each contain two rewards");assert(slots.every(p=>p.children.some(c=>c.BHasClass("DailyRewardQuantity")&&c.text==="×3")));assert(slots.every(p=>p.children.find(c=>c.BHasClass("DailyRewardName")).text.indexOf("×")<0));assert(slots[0].children.find(c=>c.BHasClass("DailyItemArt")).image.includes("daily_growth_gem"),"original project reward art is used");
const beforeLongRules=requests.length,longRules=Array.from({length:50},(_,i)=>'服务端规则第'+(i+1)+'行：<条款> & 保留全部真实规则。').join('\n');send({rule_text:longRules});assert(nodes.DailyRulesBody.text.startsWith('服务端规则第1行：&lt;条款&gt; &amp;'));assert(nodes.DailyRulesBody.text.includes('服务端规则第50行：&lt;条款&gt; &amp; 保留全部真实规则。<br>补签范围：'));assert.equal(nodes.DailyRulesBody.text.match(/服务端规则第\d+行/g).length,50,"long rule content is not truncated to fit the compact frame");assert.equal(nodes.DailyRulesText.style.maxHeight,"516px");assert.equal(nodes.DailyRulesText.style.overflow,"squish scroll");assert.equal(requests.length,beforeLongRules,"rendering long rules creates no extra request, claim or pass purchase");send();
nodes.DailyTooltip.style.width="330px";nodes.DailyTooltip.style.height="240px";slots[0].position={x:1500,y:920};slots[0].events.onmouseover();tick(.03);assert(!nodes.DailyTooltip.BHasClass("ArchiveHidden"));assert(nodes.DailyTooltipEffect.text.includes("英雄每秒攻击+1"));assert.equal(count("survival_daily_claim"),0,"hover only describes");slots[0].events.onmouseout();nodes.DailyTooltip.events.onmouseover();tick(.18);assert(!nodes.DailyTooltip.BHasClass("ArchiveHidden"),"tooltip remains readable across the gap");nodes.DailyTooltip.events.onmouseout();tick(.18);assert(nodes.DailyTooltip.BHasClass("ArchiveHidden"));
slots[0].events.onmouseover();const stalePlacement=[...jobs.values()].filter(j=>j.delay===.03).map(j=>j.fn),beforeRulesRequests=requests.length;
nodes.DailyRules.events.onactivate();assert(!nodes.DailyRulesText.BHasClass("ArchiveHidden"));assert(nodes.DailyTooltip.BHasClass("ArchiveHidden"));assert(!nodes.DailyTooltip.hittest&&!nodes.DailyTooltip.hittestchildren);
slots[1].events.onmouseover();nodes.DailyTooltip.events.onmouseover();stalePlacement.forEach(fn=>fn());tick(.03);tick(.18);
assert(nodes.DailyTooltip.BHasClass("ArchiveHidden"),"opening actual rules blocks later behind-card hover and stale tooltip jobs");assert.equal(requests.length,beforeRulesRequests,"rules and blocked tooltip never claim, request or purchase");
nodes.DailyRules.events.onactivate();assert(nodes.DailyRulesText.BHasClass("ArchiveHidden"));assert(nodes.DailyTooltip.BHasClass("ArchiveHidden"));slots[1].events.onmouseover();tick(.03);
assert(!nodes.DailyTooltip.BHasClass("ArchiveHidden"),"closing rules restores a fresh reward hover");slots[1].events.onmouseout();tick(.18);
nodes.DailyClaim.events.onactivate();nodes.DailyClaim.events.onactivate();assert.equal(count("survival_daily_claim"),1,"busy guard prevents duplicate claims");assert.equal(requests.at(-1).p.target_day,fixture.today);assert.equal(Object.keys(requests.at(-1).p).length,1);send({claim_result:{target_day:fixture.today,ok:false,error:"保存失败"}});assert.equal(nodes.DailyClaimText.text,"重试领取");assert(nodes.DailyClaim.enabled);nodes.DailyClaim.events.onactivate();send({ordinary_status:"claimed",count:3});assert(!nodes.DailyClaim.enabled);emit({...fixture,sequence:1});assert(!nodes.DailyClaim.enabled,"stale snapshots cannot re-enable a confirmed claim");
send({today:25004,ordinary_status:"claimed",premium:{status:"claimable",name:"独立通行证槽"}});assert(nodes.DailyClaim.enabled);assert.equal(nodes.DailyClaimText.text,"领取通行证奖励");send({today:25004,ordinary_status:"claimed",premium:{status:"claimed"}});assert(!nodes.DailyClaim.enabled);send({today:25005,has_pass:1,missed:[25001,25002]});assert(nodes.DailyMakeup.visible&&nodes.DailyMakeup.enabled);nodes.DailyMakeup.events.onactivate();assert.equal(requests.at(-1).p.target_day,25001,"makeup keeps the earliest server-provided day");
cfg.SurvivalDaily.Open(true);assert(nodes.DailyClaimPage.BHasClass("ArchiveHidden"));assert(!nodes.PassPurchase.enabled);nodes.PassPurchase.events.onactivate();assert.equal(count("survival_pass_purchase"),0,"unconfigured purchase remains disabled");send({today:25006,has_pass:1,purchase_enabled:1});nodes.PassPurchase.events.onactivate();nodes.PassPurchase.events.onactivate();assert.equal(count("survival_pass_purchase"),1);assert.equal(Object.keys(requests.at(-1).p).length,0);nodes.DailyBack.events.onactivate();assert(!nodes.DailyClaimPage.BHasClass("ArchiveHidden"));
const quantityCycle=fixture.cycle.map(day=>({...day,rewards:day.rewards.map(item=>({...item}))}));delete quantityCycle[0].rewards[0].count;send({today:25007,cycle:quantityCycle});let firstSlot=all(nodes.DailyCards).find(p=>p.BHasClass("DailyReward"));assert(!firstSlot.children.find(p=>p.BHasClass("DailyRewardQuantity")).visible,"missing server quantity is optional, never invented");firstSlot.events.onmouseover();assert(!nodes.DailyTooltipEffect.text.includes("数量："));quantityCycle[0].rewards[0].count=0;send({today:25008,cycle:quantityCycle});firstSlot=all(nodes.DailyCards).find(p=>p.BHasClass("DailyReward"));assert.equal(firstSlot.children.find(p=>p.BHasClass("DailyRewardQuantity")).text,"×0","explicit zero remains authoritative");
firstSlot.events.onmouseover();cfg.SurvivalDaily.Close();tick(.03);tick(.18);assert(nodes.DailyTooltip.BHasClass("ArchiveHidden"));assert.equal(cfg.SurvivalUILayers.Top(),null);cfg.SurvivalDaily.Open(false);nodes.DailyScrim.events.onactivate();assert.equal(cfg.SurvivalUILayers.Top(),null);cfg.SurvivalDaily.Open(false);all(nodes.DailyWindow).find(p=>p.BHasClass("PurpleClose")).events.onactivate();assert.equal(cfg.SurvivalUILayers.Top(),null);cfg.SurvivalDaily.Dispose();assert(![...subscriptions.values()].some(s=>s.n==="survival_daily_snapshot"));
const oldDaily=cfg.SurvivalDaily,oldClaimCount=count("survival_daily_claim"),oldPurchaseCount=count("survival_pass_purchase");root.RemoveAndDeleteChildren();assert.doesNotThrow(()=>{oldDaily.Close();oldDaily.Open(false);oldDaily.Inspect();oldDaily.Dispose();tick(.03);tick(.18);},"deleted native daily subtree tolerates cleanup and pending tooltips");
assembleIds();load("daily_remaining_5d5c1152eb.js");cfg.SurvivalDaily.Open(false);send({today:25009});assert.equal(nodes.DailyCards.GetChildCount(),7);assert.equal(count("survival_daily_claim"),oldClaimCount);assert.equal(count("survival_pass_purchase"),oldPurchaseCount);cfg.SurvivalDaily.Dispose();
console.log("DAILY_PURPLE_PASS: active controller/shared shell, real seven-day rewards/milestones, optional authoritative quantities, tooltip gap and opaque surfaces, rules auto-height/max-height with complete escaped long prose and scroll contract, native rules close/block/reopen with stale hover jobs, guarded claims/makeup/pass, deleted native subtree reload without transactions");
