'use strict';
// Preview-only density experiment. Production source and real catalog rows stay intact.
const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),{browser}=require('../shop_ui_12h/cdp.cjs');
const base='design_refs/purple_ui_10h/work',args=process.argv.slice(2),at=args.indexOf('--size'),size=(at>=0?args[at+1]:'1920x1080').split('x').map(Number);
const assembly=JSON.parse(fs.readFileSync(base+'/preview/assembly.json','utf8')),sourceDigest=crypto.createHash('sha256').update(JSON.stringify(assembly.sourceGraph)).digest('hex');
const variants=[{id:'production_4',columns:4,iconWidth:158,rowPitch:210,production:true},{id:'preview_5',columns:5,iconWidth:120,rowPitch:174},{id:'preview_6',columns:6,iconWidth:96,rowPitch:152}];
function comparison(){
 const records=['1920x1080','1280x720'].flatMap(viewport=>JSON.parse(fs.readFileSync(base+'/density/'+viewport+'_report.json','utf8')).records);
 const data=records.map(r=>({category:r.category,variant:r.variant,viewport:r.viewport,state:r.tips.length?'hover':'normal',full:r.fullyVisibleNames,short:r.shortenedNames.length,height:r.window.height,image:'../density_'+r.variant+'/'+r.viewport+'_shop_'+r.category+'_'+(r.tips.length?'hover':'normal')+'_crop.png'}));
 const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>商店密度 · 仅预览对比</title><style>body{margin:24px;background:#100c19;color:#e4d6f1;font:16px sans-serif}select{margin:12px;padding:8px;background:#261b36;color:#fff}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}article{background:#21172e;padding:12px;border:1px solid #654d7c}img{display:block;width:100%;height:auto}a{color:#ffdc87}h2{font-size:18px}</style><h1>生存商店密度对比（只在预览注入）</h1><p>保留当前生产 4 列。5/6 列是未采用实验；21 条为真实 CSV 完整挑战目录压力样例，实机通常只投影下一转等级。</p><p><a href="decision.json">取舍与数据限制</a> · <a href="1920x1080_report.json">1080 报告</a> · <a href="1280x720_report.json">720 报告</a></p><label>分类<select id="category"><option value="equipment">装备 4 件</option><option value="other">其他 6 件</option><option value="challenge">完整挑战目录 21 件</option></select></label><label>视口<select id="viewport"><option>1920x1080</option><option>1280x720</option></select></label><label>状态<select id="state"><option value="normal">普通</option><option value="hover">详情</option></select></label><div id="grid" class="grid"></div><script id="data" type="application/json">${JSON.stringify(data).replaceAll('<','\\u003c')}</script><script>
const D=JSON.parse(document.getElementById('data').textContent),names={production_4:'当前生产 · 4 列 / 158px实际图标',preview_5:'仅预览 · 5 列 / 120px图标',preview_6:'仅预览 · 6 列 / 96px图标'};
function render(){const grid=document.getElementById('grid');grid.replaceChildren();for(const r of D.filter(r=>r.category===document.getElementById('category').value&&r.viewport===document.getElementById('viewport').value&&r.state===document.getElementById('state').value)){const article=document.createElement('article'),heading=document.createElement('h2'),link=document.createElement('a'),img=document.createElement('img'),copy=document.createElement('p');heading.textContent=names[r.variant];link.href=r.image;link.target='_blank';link.rel='noopener';img.src=r.image;img.alt=names[r.variant];copy.textContent='窗高 '+Math.round(r.height)+'px · 完整名称 '+r.full+' · 需要 shrink '+r.short;link.append(img);article.append(heading,link,copy);grid.append(article);}}
document.querySelectorAll('select').forEach(e=>e.addEventListener('change',render));render();</script></html>`;
 fs.writeFileSync(base+'/density/Comparison.html',html);console.log('DENSITY_COMPARISON_BUILT images='+data.length);
}
async function inject(b,v){if(v.production)return;await b.run(`(()=>{
 const setting=${JSON.stringify(v)},columns=setting.columns,iconWidth=setting.iconWidth,rowPitch=setting.rowPitch;
 const cards=nodes.ShopItemList.Children().filter(p=>p.BHasClass('ShopShelfSlot')),rows=Math.ceil(cards.length/columns);
 const cellWidth=Math.floor((nodes.ShopItemList.el.clientWidth-12)/columns)-16,frameWidth=iconWidth+6,iconHeight=iconWidth*146/158,frameHeight=iconHeight+6;
 const height=Math.min(760,246+rows*rowPitch);nodes.CustomShopWindow.style.height=height+'px';nodes.ShopBody.style.height=Math.min(height-234,490)+'px';nodes.ShopFooter.style.position='36px '+(height-46)+'px 0px';
 for(const card of cards){card.style.width=cellWidth+'px';card.style.height=(rowPitch-18)+'px';const frame=card.FindChildrenWithClassTraverse('ShopItemFrame')[0],icon=card.FindChildrenWithClassTraverse('ShopItemIcon')[0],name=card.FindChildrenWithClassTraverse('ShopCardName')[0];if(frame){frame.style.position=((cellWidth-frameWidth)/2)+'px 0px 0px';frame.style.width=frameWidth+'px';frame.style.height=frameHeight+'px';}if(icon){icon.style.width=iconWidth+'px';icon.style.height=iconHeight+'px';}if(name){name.style.textOverflow='shrink';name.style.maxWidth=cellWidth+'px';name.style.position='0px '+(frameHeight+7)+'px 0px';}}
 previewState.densityExperiment={kind:'preview_only_injection',variables:{columns,iconWidth,rowPitch},derived:{cellWidth,frameWidth,frameHeight,height,rows},sourceUnmodified:true};syncLayout();return true;
})()`);}
async function metrics(b){return b.run(`(()=>{syncLayout();const list=nodes.ShopItemList.el,clip=list.getBoundingClientRect(),win=nodes.CustomShopWindow.el.getBoundingClientRect(),shown=e=>!!(e&&e.getBoundingClientRect().width&&getComputedStyle(e).display!=='none'&&!e.hidden),cards=[...list.querySelectorAll('.ShopShelfSlot')].map(e=>{const name=e.querySelector('.ShopCardName'),icon=e.querySelector('.ShopItemIcon'),r=e.getBoundingClientRect(),n=name.getBoundingClientRect();return {id:e.getAttribute('data-entry_id')||e.dataset.entry_id||e.id,name:name.textContent,bounds:r.toJSON(),icon:icon.getBoundingClientRect().toJSON(),label:n.toJSON(),font:getComputedStyle(name).fontSize,labelScrollWidth:name.scrollWidth,labelClientWidth:name.clientWidth,fullyVisible:r.top>=clip.top&&r.bottom<=clip.bottom,nameFullyVisible:n.top>=clip.top&&n.bottom<=clip.bottom};});const tips=[...document.querySelectorAll('#ShopEntryTooltip')].filter(shown);return {state:previewState,errors:previewErrors,calls:previewCalls,inspect:cfg.SurvivalShop.Inspect(),window:win.toJSON(),list:clip.toJSON(),cards,fullyVisibleCards:cards.filter(x=>x.fullyVisible).length,fullyVisibleNames:cards.filter(x=>x.nameFullyVisible).length,shortenedNames:cards.filter(x=>x.labelScrollWidth>x.labelClientWidth+1).map(x=>x.name),tips:tips.map(e=>({text:e.textContent,bounds:e.getBoundingClientRect().toJSON()})),footer:['ShopResourceSummary','ShopStatus'].map(id=>({id,text:nodes[id].text,bounds:nodes[id].el.getBoundingClientRect().toJSON()})),missing:[...document.images].filter(i=>shown(i)&&i.src&&(!i.complete||!i.naturalWidth)).map(i=>i.src)};})()`);}
(async()=>{if(args.includes('--review-only')){comparison();return;}const b=await browser(),records=[];try{
 if(args.includes('--verify-review')){await b.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await b.go(base+'/density/Comparison.html');const checks=[];for(const selected of [{category:'equipment',viewport:'1920x1080'},{category:'challenge',viewport:'1280x720'}]){await b.run(`document.getElementById('category').value='${selected.category}';document.getElementById('viewport').value='${selected.viewport}';render();true`);await b.run('new Promise(resolve=>setTimeout(resolve,180)).then(()=>true)');const images=await b.run("[...document.querySelectorAll('#grid img')].map(i=>({src:i.src,complete:i.complete,naturalWidth:i.naturalWidth,href:i.closest('a').href}))");assert.equal(images.length,3);assert(images.every(x=>x.complete&&x.naturalWidth>0&&x.href===x.src));checks.push({...selected,images});}await b.shot(base+'/density/Comparison_verified.png',{x:0,y:0,width:1440,height:1000});fs.writeFileSync(base+'/density/comparison_verification.json',JSON.stringify({at:new Date().toISOString(),status:'PASS_LOCAL_BROWSER',checks},null,2));console.log('DENSITY_COMPARISON_VERIFIED all3 images loaded and 720 challenge switched');return;}
 await b.call('Emulation.setDeviceMetricsOverride',{width:size[0],height:size[1],deviceScaleFactor:1,mobile:false});
 for(const category of ['equipment','other','challenge'])for(const v of variants)for(const state of ['normal','hover']){
  await b.go(base+'/preview/index.html','?page=shop&state=normal&category='+category);assert.equal(await b.run('previewReady'),true);await inject(b,v);
  if(state==='hover'){const source=await b.run("nodes.ShopItemList.el.querySelector('.ShopShelfSlot').getBoundingClientRect().toJSON()");await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:source.x+source.width/2,y:source.y+source.height/2});await b.run('new Promise(resolve=>setTimeout(resolve,100)).then(()=>true)');}
  const info=await metrics(b);assert.equal(info.errors.length,0);assert.equal(info.missing.length,0);assert.equal(info.cards.length,{equipment:4,other:6,challenge:21}[category],'True catalog count changed');info.actualColumns=info.cards.filter(x=>Math.abs(x.bounds.y-info.cards[0].bounds.y)<1).length;assert.equal(info.actualColumns,Math.min(v.columns,info.cards.length),'Nominal columns differ from rendered columns');assert(info.window.x>=-1&&info.window.y>=-1&&info.window.right<=size[0]+1&&info.window.bottom<=size[1]+1,'Density window exceeds viewport');
  if(state==='hover'){assert.equal(info.tips.length,1);const t=info.tips[0].bounds;assert(t.x>=-1&&t.y>=-1&&t.right<=size[0]+1&&t.bottom<=size[1]+1,'Density tooltip exceeds viewport');}
  assert(info.footer.every(x=>x.bounds.bottom<=info.window.bottom+1),'Density footer exceeds window');assert(!info.calls.some(x=>/purchase/.test(x.name||x.method||'')),'Density preview unexpectedly requested purchase');
  const prefix=base+'/density_'+v.id+'/'+size.join('x')+'_shop_'+category+'_'+state;await b.shot(prefix+'.png',{x:0,y:0,width:size[0],height:size[1]});const w=info.window;await b.shot(prefix+'_crop.png',{x:Math.max(0,w.x-6),y:Math.max(0,w.y-6),width:Math.min(size[0]-Math.max(0,w.x-6),w.width+12),height:Math.min(size[1]-Math.max(0,w.y-6),w.height+12)});
  const record={category,variant:v.id,variables:v.production?'Unmodified production':{columns:v.columns,iconWidth:v.iconWidth,rowPitch:v.rowPitch},viewport:size.join('x'),sourceDigest,...info};fs.writeFileSync(prefix+'_metrics.json',JSON.stringify(record,null,2));records.push(record);console.log('SHOP_DENSITY_CAPTURE '+prefix+'.png trueItems='+info.cards.length+' fullNames='+info.fullyVisibleNames+' shortened='+info.shortenedNames.length);
 }
 fs.mkdirSync(base+'/density',{recursive:true});fs.writeFileSync(base+'/density/'+size.join('x')+'_report.json',JSON.stringify({at:new Date().toISOString(),kind:'browser_preview_only_density_experiment',sourceDigest,sourceAssemblyAt:assembly.at,status:'PASS_LAYOUT_AND_TRUE_CATALOG_COUNTS',variables:'Three independent variables: columns, iconWidth and rowPitch; cell dimensions/window height are derived. Production labels, colors, controls, tooltip and business data retained.',records,limitations:['Candidate styles injected after production renders; no production file change.','Exact 4 equipment / 6 other / 21 challenge rows from current enabled CSV; no duplicated/fabricated items.','21 challenge/rebirth entries are the full CSV directory stress sample; the real server projects the next rebirth tier rather than always showing all 21 simultaneously.','Existing native text-overflow:shrink is explicitly approximated by clipped browser ellipsis for the two long captions; native shaping/readability remain separate.','No native console, game actions, purchase or reward grant.']},null,2));
 }finally{b.close();}})().catch(error=>{console.error(error);process.exitCode=1});
