"use strict";
// Run the active lottery presenters, cinematic and purple hooks. Requests stay in local recorders.
const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict"),{csv}=require("../shop_ui_12h/catalog.cjs");
const cfg={},jobs=new Map(),subscriptions=new Map(),netSubscriptions=new Map(),requests=[],ticketVisits=[],effectTooltips=[],movies=[],logs=[];let serial=0,clock=0;
const originalNoteCSS=fs.readFileSync('panorama/src/styles/custom_game/remaining_5d5c1152eb.css','utf8');assert(/#LotteryInfoDialog\.RHHistory #LotteryInfoNote \{visibility:visible/.test(originalNoteCSS),'original history contract exposes the local30/cross-game limitation note');assert(/\.LotteryUpdateAnnouncement #LotteryInfoDialog\.RHWindow #LotteryInfoNote \{ visibility: visible/.test(originalNoteCSS),'original update contract exposes the effective-date note');
class Panel{
 constructor(type,parent,id=""){this.type=type;this.paneltype=type;this.parent=parent;this.id=id;this.children=[];this.classes=new Set();this.style={};this.events={};this.visible=true;this.enabled=true;if(parent)parent.children.push(this);}
 valid(){assert(!this.deleted,"Underlying panel is deleted");}IsValid(){return !this.deleted;}
 AddClass(c){this.valid();String(c).split(/\s+/).filter(Boolean).forEach(c=>this.classes.add(c));}RemoveClass(c){this.valid();this.classes.delete(c);}BHasClass(c){this.valid();return this.classes.has(c);}SetHasClass(c,v){v?this.AddClass(c):this.RemoveClass(c);}ToggleClass(c){this.SetHasClass(c,!this.BHasClass(c));}
 GetParent(){this.valid();return this.parent;}Children(){this.valid();return this.children;}GetChildCount(){return this.Children().length;}GetChild(i){return this.Children()[i];}GetClasses(){this.valid();return [...this.classes];}
 FindChildTraverse(id){this.valid();if(this.id===id)return this;for(const child of this.children){const found=child.FindChildTraverse(id);if(found)return found;}return null;}
 SetPanelEvent(n,f){this.valid();this.events[n]=f;}SetImage(v){this.valid();this.image=v;}SetScaling(v){this.valid();this.scaling=v;}SetFocus(){}SetAcceptsFocus(){}
 MoveChildBefore(child,before){this.valid();this.children=this.children.filter(c=>c!==child);const index=this.children.indexOf(before);this.children.splice(index<0?this.children.length:index,0,child);}
 SetParent(parent){this.valid();if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);this.parent=parent;parent.children.push(this);}
 RemoveAndDeleteChildren(){this.valid();for(const child of [...this.children])child.DeleteAsync();this.children=[];}DeleteAsync(){this.valid();this.RemoveAndDeleteChildren();this.deleted=true;if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);}
 GetPositionWithinWindow(){this.valid();return {x:320,y:140};}get actuallayoutwidth(){this.valid();return this.parent?parseFloat(this.style.width)||1280:this.width||1920;}get actuallayoutheight(){this.valid();return this.parent?parseFloat(this.style.height)||800:this.height||1080;}get actualuiscale_x(){return 1;}get actualuiscale_y(){return 1;}
 SetControls(v){this.valid();this.controls=v;}SetRepeat(v){this.valid();this.repeat=v;}SetPlaybackVolume(v){this.valid();this.volume=v;}SetMovie(v){this.valid();this.movie=v;}Play(){this.valid();this.playing=true;movies.push(this);}Stop(){this.valid();this.playing=false;}
}
function decode(v){return String(v).replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&");}
function assemble(xml,root){const stack=[root];for(const match of xml.replace(/<!--[\s\S]*?-->/g,"").matchAll(/<(\/?)([A-Za-z][\w]*)\b([^>]*)>/g)){const [,end,type,body]=match;if(["root","styles","scripts","include"].includes(type))continue;if(end){stack.pop();continue;}const attrs=Object.fromEntries([...body.matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],decode(m[2])]));const p=new Panel(type,stack.at(-1),attrs.id||"");if(attrs.class)p.AddClass(attrs.class);if(attrs.text)p.text=attrs.text;if(attrs.visible)p.visible=attrs.visible!=="false";if(attrs.checked)p.checked=attrs.checked==="true";if(!/\/\s*$/.test(body))stack.push(p);}}
const root=new Panel("Panel",null,"hud_context");assemble(fs.readFileSync("panorama/src/layout/custom_game/survival_hud.xml","utf8"),root);
function dollar(owner){function $(id){return owner.FindChildTraverse(String(id).replace(/^#/,""));}$.GetContextPanel=()=>owner;$.CreatePanel=(t,p,id)=>new Panel(t,p,id);$.Msg=s=>logs.push(String(s));$.DispatchEvent=()=>{};$.RegisterEventHandler=()=>{};$.Schedule=(delay,fn)=>{const id=++serial;jobs.set(id,{at:clock+delay,fn});return id;};$.CancelScheduled=id=>jobs.delete(id);return $;}
class TestDate extends Date{static now(){return Math.floor(clock*1000);}}
const env={Date:TestDate,$:dollar(root),GameUI:{CustomUIConfig:()=>cfg},Game:{GetLocalPlayerID:()=>0,IsInToolsMode:()=>false},GameEvents:{Subscribe:(n,f)=>{const id=++serial;subscriptions.set(id,{n,f});return id;},Unsubscribe:id=>subscriptions.delete(id),SendCustomGameEventToServer:(n,p)=>requests.push({n,p})},CustomNetTables:{GetTableValue:()=>({resources:{gold:100,wood:200}}),SubscribeNetTableListener:(n,f)=>{const id=++serial;netSubscriptions.set(id,{n,f});return id;},UnsubscribeNetTableListener:id=>netSubscriptions.delete(id)}};
function load(name,target=env){vm.runInNewContext(fs.readFileSync("panorama/src/scripts/custom_game/"+name,"utf8"),target,{filename:name});}
function emit(name,payload){for(const sub of [...subscriptions.values()])if(sub.n===name)sub.f(payload);}
function advance(seconds){const end=clock+seconds;let turns=0;while(true){const next=[...jobs].filter(([,job])=>job.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;assert(++turns<5000,"unexpected runaway UI timer");jobs.delete(next[0]);clock=next[1].at;next[1].fn();}clock=end;}
function all(p=root){return [p,...p.Children().flatMap(child=>all(child))];}const node=id=>root.FindChildTraverse(id),draws=()=>requests.filter(r=>r.n==="ui_lottery_draw_request"),danger=()=>requests.filter(r=>r.n!=="ui_lottery_snapshot_request");
require("../load_shared_ui_test.cjs")(env,Panel,root);
cfg.SurvivalCommerceWallet={GetCatalog:()=>({balances:{u_coin:20,shop_points:320,shop_gold:2881}})};
cfg.SurvivalCommerceView={OpenTicketPurchase:pool=>{ticketVisits.push(pool);return true;}};
// The cross-context archive tooltip API is an external read-only dependency here.
cfg.ArchiveHandoff={ShowEffectOnly:(item,source)=>effectTooltips.push({item,source}),Hide:()=>{}};
const production=["ui_layers.js","common/purple_shell.js","reward_presentation.js","reference_windows.js","ui_snapshot_cache.js","remaining_5d5c1152eb.js","lottery_scene_transition.js","lottery_handoff_bb9968eef7.js","lottery_cinematic_v1.js","lottery_ui_remaining_5d5c1152eb.js","menu_purple.js"];
for(const source of production)load(source);
const ui=cfg.SurvivalLottery,pools=csv("data/csv/抽奖系统/lottery_pool_definitions.csv").filter(row=>row.enabled==="1"),pities=csv("data/csv/抽奖系统/lottery_pity_rules.csv").filter(row=>row.enabled==="1");
function snapshot(id="map",tickets=30,overrides={}){const row=pools.find(p=>p.pool_id===id),pity=pities.filter(p=>p.pool_id===id).map(p=>({quality:p.target_quality,batch_size:Number(p.threshold),label:"十连保底"+p.target_quality.toUpperCase()}));return {selected_pool_id:id,selected_pool:{id,display_name:row.display_name,description:row.description,ticket_content_id:row.ticket_content_id,ticket_name:row.ticket_content_id==="special_lottery_ticket"?"金色抽奖券":"普通抽奖券",tickets,single_cost:Number(row.single_cost),ten_cost:Number(row.ten_cost),pool_group:row.pool_group,pity,unlocked:true,...overrides},pools:pools.map(p=>({id:p.pool_id,display_name:p.display_name,pity:pities.filter(r=>r.pool_id===p.pool_id).map(r=>({quality:r.target_quality,batch_size:Number(r.threshold),label:"十连保底"+r.target_quality.toUpperCase()}))})),items:[{id:"reward_sr",name:"服务端奖励",description:"英雄攻击+10",quality:"sr",icon:"item_blink",owned_count:2,max_owned:3,duration_text:"7天",duplicate_points:30,count:3},{id:"reward_n",name:"服务端普通奖励",description:"护甲+2",quality:"n",icon:"item_chainmail",owned_count:0}],starjoy_points:10};}
let lastAwarded=null;
function awarded(count){return Array.from({length:count},(_,i)=>({id:"server_result_"+i,name:"结果"+i,description:"服务端效果"+i,quality:i===0?"ssr":"n",icon:"item_blink",count:i===0?3:1,duplicate:i===1,converted_points:20,...(i===0?{duration_text:"7天"}:{})}));}
function respond(req,count,remaining=20){lastAwarded=awarded(count);emit("ui_lottery_result",{ok:1,request_id:req.p.request_id,pool_id:req.p.pool_id,count,results:lastAwarded,snapshot:snapshot(req.p.pool_id,remaining)});}
ui.Open();assert.equal(cfg.SurvivalUILayers.Top(),"lottery");assert(node("LotteryMainCanvas").BHasClass("LotteryPurple"));assert.equal(node("LotteryMainCanvas").style.width,"1280px");assert.equal(node("LotteryMainCanvas").style.height,"800px");assert.equal(node("LotteryMainCanvas").style.transform,"scale3d(1,1,1)");ui.DrawSingle();ui.DrawTen();assert.equal(danger().length,0,"loading cannot issue a draw");assert.equal(ticketVisits.length,0);
const firstSnapshot=snapshot(),originalRewardData=JSON.stringify(firstSnapshot.items);emit("ui_lottery_snapshot",firstSnapshot);assert.equal(node("LotterySingleCost").text,"1");assert.equal(node("LotteryTenCost").text,"10");assert(node("LotteryDrawPityCaption").text.includes("SSR"),"pity follows actual configured map SSR");
const beforeStyle=draws().length;cfg.SurvivalPurpleLottery.Apply();cfg.SurvivalPurpleLottery.Compact(node("LotteryItemList"));cfg.LotteryHandoff.Ready();assert.equal(draws().length,beforeStyle);assert.equal(ticketVisits.length,0,"repeated styling never visits ticket checkout");
ui.Feature("details");assert.equal(cfg.SurvivalUILayers.Top(),"lottery_info");assert.equal(node("LotteryInfoDialog").style.width,"1280px");const detailCards=node("LotteryInfoList").Children();assert.equal(detailCards.length,2);assert.equal(detailCards[0].style.width,"130px");assert(detailCards[0].Children().some(p=>p.BHasClass("PurpleLotteryQuantity")&&p.text==="×2"));detailCards[0].events.onmouseover();detailCards[1].events.onactivate();
const metadataTip=effectTooltips.at(-1);assert.equal(metadataTip.source,detailCards[0]);assert.equal(metadataTip.item.name,firstSnapshot.items[0].name);
assert(metadataTip.item.description.startsWith(firstSnapshot.items[0].description+'\n'),"the complete server effect remains the first tooltip paragraph");
for(const line of ['品质：SR','已拥有：2 / 3','期限：7天','重复转化：30积分'])assert(metadataTip.item.description.split('\n').includes(line),'compact tooltip retains real '+line);
assert.equal(JSON.stringify(firstSnapshot.items),originalRewardData,"describing metadata never rewrites server rewards or their effect descriptions");
detailCards[1].events.onmouseover();const zeroTip=effectTooltips.at(-1).item.description;assert(zeroTip.startsWith('护甲+2\n'));assert(zeroTip.split('\n').includes('已拥有：0'),"explicit zero ownership is real information");assert(!/期限：|永久|重复转化：/.test(zeroTip),"an absent term/conversion field never implies permanence or a reward");assert(!detailCards[1].Children().some(p=>p.BHasClass('PurpleLotteryQuantity')),"zero owned count does not invent a positive compact badge");assert.equal(JSON.stringify(firstSnapshot.items),originalRewardData);
const unknownSnapshot=snapshot();delete unknownSnapshot.items[1].owned_count;const unknownRewardData=JSON.stringify(unknownSnapshot.items);emit('ui_lottery_snapshot',unknownSnapshot);const unknownCard=node('LotteryInfoList').GetChild(1);unknownCard.events.onmouseover();const unknownTip=effectTooltips.at(-1).item.description;assert(unknownTip.startsWith('护甲+2\n'));assert(!/已拥有：|期限：|永久|重复转化：/.test(unknownTip),"unknown ownership and missing metadata remain unknown in the tooltip");assert.equal(JSON.stringify(unknownSnapshot.items),unknownRewardData);emit('ui_lottery_snapshot',firstSnapshot);assert.equal(JSON.stringify(firstSnapshot.items),originalRewardData);
const detailDraws=draws().length;ui.DrawSingle();ui.DrawTen();ui.DrawAgain();assert.equal(draws().length,detailDraws,"nested details prevent underlying draws");assert.equal(ticketVisits.length,0);
// Switch the actual controller's two views on the same native info panel. Cached
// chrome must update its section label without replacing balances or duplicating art.
const sectionDialog=node("LotteryInfoDialog"),cachedInfoShell=sectionDialog.__purpleShell,infoChrome=cachedInfoShell.chrome;
const sectionCaption=all(infoChrome).find(p=>p.BHasClass("PurpleSectionCaption")),infoBalances=all(infoChrome).filter(p=>p.BHasClass("PurpleBalanceValue"));
const balanceValues=infoBalances.map(p=>p.text);assert.deepEqual(balanceValues,["20","320","2,881"]);
assert.equal(node("LotteryInfoTitle").text,"奖池详情");assert.equal(sectionCaption.text,"奖池详情");
for(const [feature,title]of [["history","抽奖记录"],["details","奖池详情"]]){
 ui.Feature(feature);assert.equal(cfg.SurvivalUILayers.Top(),"lottery_info");assert.equal(node("LotteryInfoDialog"),sectionDialog);
 assert.equal(node("LotteryInfoTitle").text,title);assert.equal(sectionCaption.text,title,"cached currency-row category follows the actual presenter title");assert.equal(node('LotteryInfoNote').style.visibility,feature==='history'?'visible':'collapse','original history note remains visible while pool detail uses its own rules');if(feature==='history')assert.equal(node('LotteryInfoNote').text,'仅本局最近30次抽取 · 跨局记录暂未接入');
 assert.equal(sectionDialog.__purpleShell,cachedInfoShell);assert.equal(sectionDialog.__purpleShell.chrome,infoChrome);assert(infoChrome.IsValid());
 assert.equal(sectionDialog.Children().filter(p=>p.BHasClass("PurpleChrome")).length,1);assert.equal(sectionDialog.Children().filter(p=>p.BHasClass("PurpleCorner")).length,4);
 assert.equal(cfg.SurvivalPurpleShell.Entries.filter(e=>e.panel===sectionDialog).length,1,"repeated view adoption keeps one live shell entry");
 assert.deepEqual(all(infoChrome).filter(p=>p.BHasClass("PurpleBalanceValue")),infoBalances,"cached adoption retains the original balance panels");
 assert.deepEqual(infoBalances.map(p=>p.text),balanceValues,"switching info views preserves authoritative wallet balances");
 assert.equal(draws().length,detailDraws);assert.equal(ticketVisits.length,0,"view titles and cached chrome never visit ticket checkout");
}
assert.equal(cfg.SurvivalUILayers.HandleEscape(),true);assert.equal(cfg.SurvivalUILayers.Top(),"lottery");assert(node("LotteryInfoOverlay").BHasClass("LotteryInfoHidden"));assert.equal(cfg.SurvivalUILayers.HandleEscape(),true);assert.equal(cfg.SurvivalUILayers.Top(),"lottery","duplicate ESC from the same press closes only the nested modal");advance(.1);assert.equal(cfg.SurvivalUILayers.HandleEscape(),true);assert.equal(cfg.SurvivalUILayers.Top(),null);assert(node("LotteryWindow").BHasClass("LotteryClosed"));
ui.Open();ui.DrawTen();const ten=draws().at(-1);assert.equal(ten.p.count,10);assert.deepEqual(Object.keys(ten.p).sort(),["count","pool_id","request_id"]);ui.DrawTen();ui.DrawSingle();ui.SelectPool("summer");cfg.SurvivalPurpleLottery.Apply();assert.equal(draws().at(-1),ten,"pending request blocks repeat draws and pool switching");assert.equal(ticketVisits.length,0);
emit("ui_lottery_result",{ok:1,request_id:"wrong-id",pool_id:"map",results:awarded(10)});assert(!node("LotteryAgain").enabled,"unrelated result never releases pending guard");respond(ten,10);assert.equal(node("LotteryItemList").GetChildCount(),10);assert(node("LotteryWindow").BHasClass("LotteryAnimating"));assert.equal(node("LotteryCinematicSurface").GetParent(),node("LotteryMainCanvas"));assert.equal(node("LotteryCinematicSurface").style.height,"672px");assert(movies.at(-1).movie.endsWith("/map.webm"));assert(parseFloat(movies.at(-1).style.width)<=1280&&parseFloat(movies.at(-1).style.height)<=672,"cinematic contains original film inside purple content bounds");
const resultCard=node("LotteryItemList").GetChild(0);assert.equal(resultCard.style.width,"184px");assert.equal(resultCard.Children().find(p=>p.BHasClass("LotteryRewardName")).text,"结果0");assert.equal(resultCard.Children().find(p=>p.BHasClass("LotteryRewardQuantity")).text,"×3");assert.equal(resultCard.Children().find(p=>p.BHasClass("LotteryRewardDescription")).style.visibility,"collapse");ui.DrawAgain();assert.equal(draws().at(-1),ten,"reveal animation blocks repeated request");node("LotteryCinematicSkip").events.onactivate();ui.SkipReveal();assert(!node("LotteryWindow").BHasClass("LotteryAnimating"));assert(movies.at(-1).deleted,"native movie skip disposes playback without redrawing");assert(node("LotteryAgain").enabled);advance(9);assert(!node("LotteryWindow").BHasClass("LotteryAnimating"));
// Activate actual revealed result cards; this opens rewardDetails, not pool selectReward.
const noteCases=[],noteRows=lastAwarded,noteRowsBefore=JSON.stringify(noteRows),noteActions={requests:requests.length,draws:draws().length,tickets:ticketVisits.length,exchanges:requests.filter(r=>r.n==='ui_lottery_exchange_request').length};
for(const [index,expected]of [[0,'SSR · 7天'],[1,'N']]){
 const actualCard=node('LotteryItemList').GetChild(index);assert(!actualCard.BHasClass('LotteryCardCovered'));actualCard.events.onactivate();assert.equal(cfg.SurvivalUILayers.Top(),'lottery_info');assert.equal(node('LotteryInfoTitle').text,noteRows[index].name);assert.equal(node('LotteryInfoNote').text,expected,'single-reward note includes only real quality and supplied term');assert(node('LotteryInfoNote').visible);assert.equal(node('LotteryInfoNote').style.visibility,'visible','actual reward presentation overrides legacy CSS collapse; Panel.visible alone is insufficient');assert(!/永久/.test(node('LotteryInfoNote').text));if(index===1)assert(!node('LotteryInfoNote').text.includes('·'),'an absent term adds neither a divider nor a guessed duration');ui.CloseInfo();assert.equal(cfg.SurvivalUILayers.Top(),'lottery');
 assert.equal(JSON.stringify(noteRows),noteRowsBefore,'card activation leaves authoritative award rows unchanged');assert.deepEqual({requests:requests.length,draws:draws().length,tickets:ticketVisits.length,exchanges:requests.filter(r=>r.n==='ui_lottery_exchange_request').length},noteActions,'opening and closing single-reward notes never requests, draws or purchases');noteCases.push({source:'actual result-card onactivate',index,suppliedDuration:noteRows[index].duration_text||null,note:node('LotteryInfoNote').text,inlineVisibility:node('LotteryInfoNote').style.visibility,immutableRows:true,unchangedActionCounts:true});
}
const notePresentationActions={danger:danger().length,draws:draws().length,tickets:ticketVisits.length},originalNoteCases=[];for(const feature of ['details','history']){ui.Feature(feature);assert.equal(node('LotteryInfoNote').style.visibility,feature==='history'?'visible':'collapse','returning from reward preserves each original view contract');if(feature==='history')assert.equal(node('LotteryInfoNote').text,'仅本局最近30次抽取 · 跨局记录暂未接入');originalNoteCases.push({feature,text:node('LotteryInfoNote').text,visibility:node('LotteryInfoNote').style.visibility,position:node('LotteryInfoNote').style.position});ui.CloseInfo();}assert.deepEqual({danger:danger().length,draws:draws().length,tickets:ticketVisits.length},notePresentationActions);assert.equal(JSON.stringify(noteRows),noteRowsBefore);
const announcedUpdate={title:'服务端更新公告',effective_date:'2026-10-10',summary:'服务端配置摘要：奖池奖励已更新'},updatePayload=snapshot('map',20,{update_notice:announcedUpdate}),updateNoticeBefore=JSON.stringify(announcedUpdate),updateRowsBefore=JSON.stringify(updatePayload.items);emit('ui_lottery_snapshot',updatePayload);const updateActions={danger:danger().length,draws:draws().length,tickets:ticketVisits.length};ui.Feature('update');assert.equal(node('LotteryInfoTitle').text,announcedUpdate.title);assert.equal(node('LotteryInfoNote').text,'更新生效日期：'+announcedUpdate.effective_date);assert.equal(node('LotteryInfoNote').style.visibility,'visible');assert.equal(node('LotteryInfoNote').style.position,'28px 773px 0px','alive purple update note stays in the footer, outside shared chrome');assert(node('LotteryInfoRules').text.includes(announcedUpdate.summary),'complete server update summary remains visible');originalNoteCases.push({feature:'update',text:node('LotteryInfoNote').text,summary:node('LotteryInfoRules').text,visibility:node('LotteryInfoNote').style.visibility,position:node('LotteryInfoNote').style.position});ui.CloseInfo();assert.deepEqual({danger:danger().length,draws:draws().length,tickets:ticketVisits.length},updateActions);assert.equal(JSON.stringify(announcedUpdate),updateNoticeBefore);assert.equal(JSON.stringify(updatePayload.items),updateRowsBefore);emit('ui_lottery_snapshot',snapshot('map',20));
ui.Feature("history");const historyRows=node("LotteryInfoList").GetChildCount();emit("ui_lottery_result",{ok:1,request_id:ten.p.request_id,results:awarded(10)});ui.Feature("history");assert.equal(node("LotteryInfoList").GetChildCount(),historyRows,"duplicate result does not append history");ui.CloseInfo();
emit("ui_lottery_snapshot",snapshot("map",26,{single_cost:3,ten_cost:27}));assert.equal(node("LotterySingleCost").text,"3");assert.equal(node("LotteryTenCost").text,"27");assert(node("LotterySingleButton").enabled&&!node("LotteryTenButton").enabled);const insufficient=draws().length;ui.DrawTen();assert.equal(draws().length,insufficient,"exact server ten cost guards insufficient balance");node("LotterySkipAnimation").checked=true;ui.SetSkipAnimation();ui.DrawSingle();const single=draws().at(-1);assert.equal(single.p.count,1);ui.DrawSingle();assert.equal(draws().at(-1),single);respond(single,1,25);assert(!node("LotteryWindow").BHasClass("LotteryAnimating"));assert.equal(node("LotteryItemList").GetChildCount(),1);ui.CloseResult();
emit("ui_lottery_snapshot",snapshot("map",0,{single_cost:0,ten_cost:10}));assert(node("LotterySingleButton").enabled&&!node("LotteryTenButton").enabled);assert.equal(node("LotterySingleCost").text,"");ui.DrawSingle();const free=draws().at(-1);assert.equal(free.p.count,1);emit("ui_lottery_result",{ok:0,request_id:free.p.request_id,error:"lottery_ticket_insufficient",snapshot:snapshot("map",0)});assert(!node("LotterySingleButton").enabled);assert(node("LotteryStatus").text.includes("不足"));
ui.CloseResult();ui.SelectPool("cultivation");emit("ui_lottery_snapshot",snapshot("cultivation",100,{unlocked:false,unlock_progress:99,unlock_required:100}));const lockedDraws=draws().length;ui.DrawSingle();ui.DrawTen();assert.equal(draws().length,lockedDraws);assert(node("LotteryStatus").text.includes("99 / 100"),"true map-draw unlock progress guards cultivation");ui.SelectPool("summer");assert(!node("LotterySingleButton").enabled);emit("ui_lottery_snapshot",snapshot("map",999));assert(!node("LotterySingleButton").enabled,"stale main pool snapshot cannot enable drawing");emit("ui_lottery_snapshot",snapshot("summer",20));assert(node("LotteryDrawPityCaption").text.includes("UR"));assert(node("LotteryWindow").BHasClass("LotteryGoldenTicket"));
ui.Feature("details");const mainTitle=node("LotteryTitle").text,mainBalance=node("LotteryTicketValue").text;ui.SelectPool("map");const detailReq=requests.at(-1).p;assert.equal(detailReq.snapshot_scope,"details");emit("ui_lottery_snapshot",{...snapshot("map",3),snapshot_scope:"details",snapshot_request_id:detailReq.snapshot_request_id});assert.equal(node("LotteryTitle").text,mainTitle);assert.equal(node("LotteryTicketValue").text,mainBalance);ui.CloseInfo();emit("ui_lottery_snapshot",{...snapshot("map",0),snapshot_scope:"details",snapshot_request_id:detailReq.snapshot_request_id});assert(node("LotteryInfoOverlay").BHasClass("LotteryInfoHidden"));
const explicitVisit=ticketVisits.length;cfg.SurvivalPurpleLottery.Apply();ui.Feature("history");ui.CloseInfo();assert.equal(ticketVisits.length,explicitVisit);ui.Feature("purchase");assert.equal(ticketVisits.length,explicitVisit+1);assert.equal(ticketVisits.at(-1).id,"summer","only explicit purchase visits the active true ticket pool");
node("LotterySkipAnimation").checked=false;ui.SetSkipAnimation();ui.DrawSingle();const closedReq=draws().at(-1);ui.Close();respond(closedReq,1,19);advance(9);assert(node("LotteryWindow").BHasClass("LotteryClosed"));assert(!node("LotteryWindow").BHasClass("LotteryAnimating"));assert.equal(cfg.SurvivalUILayers.Top(),null);
ui.Open();node("LotteryMainCanvas").__purpleShell.chrome.Children().flatMap(p=>all(p)).find(p=>p.BHasClass("PurpleClose")).events.onactivate();assert.equal(cfg.SurvivalUILayers.Top(),null,"shared close uses original lottery closure");
// Navigate executes the production layer/shell contracts. Only the cross-context archive
// entry API is adapted; the lottery origin and daily rules run their active controllers.
const navShell=cfg.SurvivalPurpleShell,U=cfg.SurvivalUI,layers=cfg.SurvivalUILayers;
const archivePanel=new Panel("Panel",root,"nav_archive_destination");
const archiveModal=U.ModalShell.Adopt({id:"archive",panel:archivePanel,root,width:1280,height:800});
let archiveOpens=0;const previousArchive=cfg.SurvivalArchive;
cfg.SurvivalArchive={Open(){archiveOpens++;archiveModal.Open();}};
ui.Open();ui.Feature("details");assert.equal(layers.Top(),"lottery_info");
const navDraws=draws().length,navPurchases=ticketVisits.length;
assert.equal(navShell.Navigate("archive"),true);assert.equal(layers.Top(),"archive");
assert(node("LotteryWindow").BHasClass("LotteryClosed"),"nested navigation must close the original lottery main as well as its info modal");
assert(node("LotteryInfoOverlay").BHasClass("LotteryInfoHidden"));
archiveModal.Close();assert.equal(layers.Top(),null,"closing the new page must not reveal the previous menu underneath");
ui.Open();ui.Feature("history");const samePageRequests=requests.length;
assert.equal(navShell.Navigate("lottery"),true);assert.equal(layers.Top(),"lottery");
assert(node("LotteryInfoOverlay").BHasClass("LotteryInfoHidden"));assert(!node("LotteryWindow").BHasClass("LotteryClosed"));
assert.equal(requests.length,samePageRequests,"returning from a child to its already-open parent must not reopen/refetch the parent");ui.Close();
// Both commerce child IDs are real checkout registrations. Their bodies are deliberately
// omitted here: the separate checkout suite verifies orders; this checks native stacking.
for(const childId of ["commerce_exchange","payment_shop"]){
 const parentPanel=new Panel("Panel",root,"nav_parent_"+childId),childPanel=new Panel("Panel",root,"nav_child_"+childId);
 const parentModal=U.ModalShell.Adopt({id:"commerce",panel:parentPanel,root,width:1280,height:800});
 const childModal=U.ModalShell.Adopt({id:childId,panel:childPanel,root,width:760,height:700});
 parentModal.Open();childModal.Open();assert.equal(navShell.Navigate("archive"),true);
 assert(!parentModal.IsOpen()&&!childModal.IsOpen(),childId+" navigation closes both registered menu layers");
 archiveModal.Close();assert.equal(layers.Top(),null);parentModal.Dispose();childModal.Dispose();
}
// A mandatory shell and an ordinary menu with a pending close refusal both retain
// their stack entries. Navigation may not force-remove them or open the destination.
for(const mandatory of [true,false]){
 const panel=new Panel("Panel",root,"nav_blocked_"+mandatory);let closeCalls=0;
 const blocked=U.ModalShell.Adopt({id:"commerce_exchange",panel,root,width:760,height:700,
  closePolicy:mandatory?"mandatory":undefined,onClose(){closeCalls++;}});
 blocked.Open();const opens=archiveOpens;
 assert.equal(navShell.Navigate("archive"),false);assert.equal(archiveOpens,opens);
 assert.equal(layers.Top(),"commerce_exchange");assert(blocked.IsOpen());assert.equal(closeCalls,mandatory?0:1);
 blocked.Dispose();assert.equal(layers.Top(),null);
}
// Gameplay choice layers are not navigation-owned menus. Even a dismissible choice
// must remain untouched; pending mandatory choices likewise stay authoritative.
for(const id of ["hero_skill_choice","rogue_choice","survival_difficulty"]){
 const panel=new Panel("Panel",root,"nav_gameplay_"+id);let closeCalls=0;
 layers.Open(id,panel,()=>{closeCalls++;if(id==="hero_skill_choice")layers.Close(id);});
 const opens=archiveOpens;assert.equal(navShell.Navigate("archive"),false);
 assert.equal(archiveOpens,opens);assert.equal(layers.Top(),id);assert.equal(closeCalls,0,"navigation cannot dismiss "+id);
 layers.Close(id);panel.DeleteAsync();
}
const dailyRoot=new Panel("Panel",null,"nav_daily_context");assemble(fs.readFileSync("panorama/src/layout/custom_game/archive.xml","utf8"),dailyRoot);
const dailyEnv={...env,$:dollar(dailyRoot)};load("daily_resources.js",dailyEnv);load("daily_remaining_5d5c1152eb.js",dailyEnv);
cfg.SurvivalDaily.Open(false);dailyRoot.FindChildTraverse("DailyRules").events.onactivate();
assert.equal(layers.Top(),"daily_rewards","actual daily rules is a child panel, not a fictitious daily_rules layer");
assert(!dailyRoot.FindChildTraverse("DailyRulesText").BHasClass("ArchiveHidden"));
assert.equal(navShell.Navigate("archive"),true);assert(dailyRoot.FindChildTraverse("DailyWindow").BHasClass("ArchiveHidden"));
assert(dailyRoot.FindChildTraverse("DailyRulesText").BHasClass("ArchiveHidden"),"real daily close hides its rules child before navigating");
archiveModal.Close();assert.equal(layers.Top(),null);cfg.SurvivalDaily.Dispose();dailyRoot.DeleteAsync();
assert.equal(requests.filter(r=>/^(survival_daily_claim|survival_pass_purchase|survival_commerce_request|survival_payment_request)$/.test(r.n)).length,0,"navigation never claims, buys passes, exchanges or creates orders");
assert.equal(draws().length,navDraws);assert.equal(ticketVisits.length,navPurchases);archiveModal.Dispose();
if(previousArchive===undefined)delete cfg.SurvivalArchive;else cfg.SurvivalArchive=previousArchive;
// Two native contexts share state while each script owns its subscriptions and generation.
const shellA=cfg.SurvivalPurpleShell,shopPanel=new Panel("Panel",root,"review_shop_a");shellA.Adopt({id:"shop",panel:shopPanel,width:1040,height:456});emit("ui_shop_snapshot",{resources:{gold:4321,wood:8765}});advance(0);assert.equal(all(shopPanel).find(p=>p.BHasClass("PurpleBalanceValue")).text,"4,321");
const otherRoot=new Panel("Panel",null,"archive_context"),otherEnv={...env,$:dollar(otherRoot)};load("common/purple_shell.js",otherEnv);const shellB=cfg.SurvivalPurpleShell;assert.notEqual(shellA,shellB);assert.equal([...subscriptions.values()].filter(s=>s.n==="ui_shop_snapshot").length,1,"last shared-shell context releases previous balance event subscriptions");assert.equal(netSubscriptions.size,1);assert.equal(shellB.Resources.gold,4321);assert(shellB.Entries.some(e=>e.panel===shopPanel),"new context inherits existing live window entries");emit("ui_shop_snapshot",{resources:{gold:9999,wood:10000}});advance(0);assert.equal(all(shopPanel).find(p=>p.BHasClass("PurpleBalanceValue")).text,"9,999","new context refreshes previous-context window balances");
const firstChrome=shopPanel.__purpleShell.chrome;shellB.Adopt({id:"shop",panel:shopPanel,width:1040,height:456});assert(!firstChrome.IsValid());assert.equal(shopPanel.Children().filter(p=>p.BHasClass("PurpleChrome")).length,1);assert.equal(shopPanel.Children().filter(p=>p.BHasClass("PurpleCorner")).length,4,"generation rebuild keeps exactly four corners");shopPanel.DeleteAsync();shellB.Refresh();assert(!shellB.Entries.some(e=>e.panel===shopPanel),"deleted context entries are pruned without native access");assert.equal(draws().length,4);assert.equal(ticketVisits.length,1);assert.equal(requests.filter(r=>r.n==="ui_lottery_exchange_request").length,0);
// Native layout reload deletes the complete owner, not merely a mock visibility flag.
const oldUI=cfg.SurvivalLottery,oldHook=cfg.SurvivalPurpleLottery,oldCallbacks=[...subscriptions.values()].filter(s=>/^ui_lottery_/.test(s.n));
oldUI.Open();const oldScheduled=[...jobs.values()].map(job=>job.fn),beforeDelete=requests.length;
root.DeleteAsync();assert.equal(oldUI.IsAlive(),false);assert.equal(oldHook.IsAlive(),false);
for(const fn of [()=>oldUI.Close(),()=>oldUI.Feature("details"),()=>oldUI.DrawSingle(),()=>oldUI.DrawTen(),()=>oldUI.SelectPool("summer"),()=>oldHook.Apply()])assert.doesNotThrow(fn);
for(const sub of oldCallbacks)assert.doesNotThrow(()=>sub.f(snapshot()));
for(const callback of oldScheduled)assert.doesNotThrow(callback);
assert.equal(requests.length,beforeDelete,"deleted old owner/callbacks cannot request or draw");
const reloadRoot=new Panel("Panel",null,"reload_context");assemble(fs.readFileSync("panorama/src/layout/custom_game/survival_hud.xml","utf8"),reloadRoot);env.$=dollar(reloadRoot);
require("../load_shared_ui_test.cjs")(env,Panel,reloadRoot);
for(let pass=0;pass<2;pass++){
 for(const source of production.filter(source=>source!=="menu_purple.js"))load(source);
 const R=cfg.RemainingHandoff,baseDialog=R.LotteryDialog,baseReward=R.RewardCard,baseFeature=cfg.SurvivalLottery.Feature;
 load("menu_purple.js");const firstHook=cfg.SurvivalPurpleLottery,firstWrapped=cfg.SurvivalLottery.Feature;load("menu_purple.js");
 assert.equal(firstHook.IsAlive(),false,"reload disposes previous style hook");assert.notEqual(cfg.SurvivalLottery.Feature,firstWrapped);
 for(const name of ["ui_lottery_snapshot","ui_lottery_result","ui_lottery_exchange_result"])assert.equal([...subscriptions.values()].filter(s=>s.n===name).length,2,"one presenter and one style subscription survive reload");
 cfg.SurvivalLottery.Open();emit("ui_lottery_snapshot",snapshot());cfg.SurvivalLottery.Feature("details");
 const card=reloadRoot.FindChildTraverse("LotteryInfoList").GetChild(0);assert.equal(all(card).filter(p=>p.BHasClass("PurpleLotteryQuantity")).length,1,"wrapper reload creates one quantity marker");
 cfg.SurvivalLottery.CloseInfo();cfg.SurvivalLottery.Close();cfg.SurvivalPurpleLottery.Dispose();
 assert.equal(R.LotteryDialog,baseDialog);assert.equal(R.RewardCard,baseReward);assert.equal(cfg.SurvivalLottery.Feature,baseFeature,"Dispose restores original Feature without nested wrappers");
}
assert.equal(draws().length,4);assert.equal(ticketVisits.length,1);
fs.mkdirSync('design_refs/purple_ui_10h/work/qa',{recursive:true});const noteReport={kind:'strict_native_mock',actual_game:false,at:new Date().toISOString(),cases:noteCases,originalNoteCases,L05:'semantic supplied/absent duration PASS',L06:'reward inline visibility PASS; history collapse was incorrect and superseded by L07',L07:'original CSS-backed history local30/cross-game limitation and update effective-date/summary visible at purple footer; detail collapse PASS',nativeResultFlow:'not tested; no actual lottery draw',source_sha256:require('node:crypto').createHash('sha256').update(fs.readFileSync('panorama/src/scripts/custom_game/lottery_ui_remaining_5d5c1152eb.js')).digest('hex'),allOriginalL04Regression:'PASS',finalLocalDrawRequests:draws().length,explicitLocalTicketVisits:ticketVisits.length,actual_transactions:0};fs.writeFileSync('design_refs/purple_ui_10h/work/qa/lottery_l05_note_report.json',JSON.stringify(noteReport,null,2));fs.writeFileSync('design_refs/purple_ui_10h/work/qa/lottery_l07_note_contract_report.json',JSON.stringify(noteReport,null,2));
console.log("LOTTERY_PURPLE_PASS: actual presenters/film/hooks, costs/pity/single/ten guards, immutable effect-first tooltip metadata and real result-card activation notes with supplied/missing-term guards, stale/close/ESC isolation, native nested menu navigation and real daily rules closure, mandatory/pending/gameplay guards, two-context balances, whole-owner deletion and two native reloads without duplicate wrappers/subscriptions, no actual transactions");
