'use strict';
// Read-only browser assembly of the active Panorama XML/script/style chain.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {csv,fixture:commerceFixture}=require('../shop_ui_12h/catalog.cjs');
const base='design_refs/purple_ui_10h/work',baseline=process.argv.includes('--baseline'),outputArg=process.argv.indexOf('--out'),out=outputArg>=0?process.argv[outputArg+1]:base+'/'+(baseline?'preview_before':'preview');
fs.mkdirSync(out,{recursive:true});
const uri=p=>pathToFileURL(path.resolve(p)).href;
function read(rel){const originals=[base+'/baseline/source/panorama/src/'+rel,base+'/baseline/source/'+rel],frozen=base+'/preview_before/sources/'+rel,original=originals.find(p=>fs.existsSync(p));return fs.readFileSync(baseline&&original?original:baseline&&fs.existsSync(frozen)?frozen:'panorama/src/'+rel,'utf8').replace(/^\uFEFF/,'');}
function save(file,text){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}
const manifest=read('layout/custom_game/custom_ui_manifest.xml');
const active=[...manifest.matchAll(/<CustomUIElement\b[^>]*type="Hud"[^>]*layoutfile="file:\/\/\{resources\}\/([^\"]+)"/g)].map(m=>m[1]);
const selected=['layout/custom_game/payment_test.xml','layout/custom_game/survival_hud.xml','layout/custom_game/archive.xml'];
for(const p of selected)if(!active.includes(p))throw Error('Not an active HUD layout: '+p);
const graph=new Map();
function visit(rel){if(graph.has(rel))return;const source=read(rel);graph.set(rel,source);if(rel.endsWith('.xml'))for(const m of source.matchAll(/(?:src|layoutfile)="file:\/\/\{resources\}\/([^\"]+\.(?:css|js|xml))"/g))visit(m[1]);}
visit('layout/custom_game/custom_ui_manifest.xml');
const layouts=selected.map(rel=>{const xml=read(rel),section=name=>(xml.match(new RegExp('<'+name+'>([\\s\\S]*?)</'+name+'>'))||[])[1]||'';return {rel,xml,styles:[...section('styles').matchAll(/<include\b[^>]*src="file:\/\/\{resources\}\/([^\"]+)"/g)].map(m=>m[1]),scripts:[...section('scripts').matchAll(/<include\b[^>]*src="file:\/\/\{resources\}\/([^\"]+)"/g)].map(m=>m[1])};});
function imageUri(value){const rel=value.replace(/^file:\/\/\{images\}\//,'');return nativeAliases['file://{images}/'+rel]||uri(fs.existsSync('art/ui/sources/'+rel)?'art/ui/sources/'+rel:'panorama/src/images/'+rel);}
function gradient(value){return value.replace(/gradient\(linear,\s*([\d.]+)% ([\d.]+)%,\s*([\d.]+)% ([\d.]+)%,\s*([\s\S]+)\)$/,(_,x1,y1,x2,y2,stops)=>{const angle=Math.atan2(Number(x2)-Number(x1),Number(y1)-Number(y2))*180/Math.PI;const colors=[...stops.matchAll(/(from|to|color-stop)\(([^()]*)\)/g)].map(m=>m[1]==='color-stop'?m[2].split(',').slice(1).join(',').trim()+' '+(parseFloat(m[2])*100)+'%':m[2].trim()+(m[1]==='from'?' 0%':' 100%'));return colors.length?'linear-gradient('+angle+'deg,'+colors.join(',')+')':'transparent';});}
function shadow(value,kind){if(value.trim()==='none')return value;const bits=value.trim().split(/\s+/);if(kind==='text'&&bits.length===5&&/^\d/.test(bits[3]))bits.splice(3,1);return bits.join(' ');}
function convertCss(source){let text=source,defs={};text=text.replace(/transition-property:\s*([^;]+)/g,(_,v)=>'transition-property:'+v.split(',').map(x=>x.trim()==='position'?'left,top':x.trim()).join(','));text=text.replace(/@define\s+(\w+)\s*:\s*([^;]+);/g,(_,k,v)=>{defs[k]=v;return '';});for(const[k,v]of Object.entries(defs))text=text.replace(new RegExp('(?<=[:\\s,])'+k+'(?=[;\\s,)])','g'),v);
 text=text.replace(/file:\/\/\{images\}\/([^"')\s]+)/g,(_,rel)=>imageUri('file://{images}/'+rel));
 text=text.replace(/\b(?:DOTAAbilityImage|DOTAItemImage|DOTAHeroImage|Image)\b/g,'img').replace(/\bLabel\b/g,'.label').replace(/\b(?:Button|RadioButton|ToggleButton)\b/g,'.button').replace(/\bTextEntry\b/g,'input');
 text=text.replaceAll(':selected','.Selected').replaceAll(':disabled','.UIDisabled').replace(/position:\s*(-?[\d.]+px)\s+(-?[\d.]+px)\s+0px/g,'position:absolute;left:$1;top:$2;--pano-position:explicit');
 text=text.replace(/flow-children:\s*(none|right-wrap|right|down)/g,(_,v)=>v==='none'?'display:block;--pano-flow:none':'display:flex;flex-direction:'+(v==='down'?'column':'row')+';flex-wrap:'+(v==='right-wrap'?'wrap':'nowrap')+';--pano-flow:'+v);
 text=text.replace(/(?:horizontal-align):\s*(left|center|right)/g,'--pano-halign:$1').replace(/vertical-align:\s*(top|center|bottom)/g,'--pano-valign:$1').replace(/align:\s*(left|center|right)\s+(top|center|bottom)/g,'--pano-halign:$1;--pano-valign:$2');
 text=text.replace(/ignore-parent-flow:\s*(true|false)/g,'--pano-ignore-flow:$1').replace(/visibility:\s*(collapse|visible)/g,'--pano-visibility:$1').replace(/overflow:\s*squish scroll/g,'overflow-x:hidden;overflow-y:auto').replace(/overflow:\s*scroll squish/g,'overflow-x:auto;overflow-y:hidden').replace(/overflow:\s*(clip|squish)/g,'overflow:hidden').replace(/overflow:\s*noclip/g,'overflow:visible').replace(/(width|height):\s*fit-children/g,'$1:max-content;--pano-fit-$1:1').replace(/(?:width|height):\s*fill-parent-flow\((\d+(?:\.\d+)?)\)/g,'flex:$1;min-width:0;min-height:0');
 text=text.replace(/(background-color|background):\s*(gradient\(linear,[^;]+\))/g,(_,key,v)=>'background:'+gradient(v)).replace(/brightness:\s*([\d.]+)/g,'--pano-brightness:$1').replace(/saturation:\s*([\d.]+)/g,'--pano-saturation:$1').replace(/text-shadow:\s*([^;]+)/g,(_,v)=>'text-shadow:'+shadow(v,'text')).replace(/box-shadow:\s*([^;]+)/g,(_,v)=>'box-shadow:'+shadow(v,'box')).replace(/font-weight:\s*medium/g,'font-weight:500').replace(/text-overflow:\s*shrink/g,'text-overflow:ellipsis;--pano-shrink:1').replace(/white-space:\s*normal/g,'white-space:pre-wrap');
 return text;
}
const content=csv('data/csv/物品系统/content_catalog.csv'),byContent=Object.fromEntries(content.map(x=>[x.content_id,x]));
const shop=csv('data/csv/商店系统/shop_entries.csv').filter(x=>x.enabled==='1').map((x,i)=>{const c=byContent[x.content_id]||{};return {entry_id:x.shop_entry_id,shop_entry_id:x.shop_entry_id,shop_id:x.category_id,category_id:x.category_id,content_id:x.content_id,name:x.display_name||c.name,description:c.description||x.notes,content_type:x.content_id==='service_early_final_boss'?'item':c.content_type||x.category_id,icon:c.icon||'item_broadsword',icon_type:(c.icon||'').startsWith('item_')?'item':'ability',wood_cost:Number(x.wood_cost)||0,gold_cost:Number(x.gold_cost)||0,purchase_limit:Number(x.purchase_limit)||0,stock_max:Number(x.stock_max)||0,sort_order:i,visible:1,purchasable:1,owned:0,owned_count:0,purchase_count:0,stock:Number(x.stock_max)||0};});
const archiveCats=csv('data/csv/存档系统/archive_categories.csv').filter(x=>x.enabled==='1').map(x=>({id:x.category_id||x.id,name:x.name||x.display_name,sort_order:Number(x.sort_order)||0}));
const archiveFiles=fs.readdirSync('data/csv/存档系统').filter(x=>/clear|achievement/.test(x));
const archiveSource=archiveFiles.find(x=>x==='archive_achievements.csv')||archiveFiles.find(x=>/clear/.test(x));
const archive=archiveSource?csv('data/csv/存档系统/'+archiveSource):[];
const archiveData={fragment:csv('data/csv/存档系统/archive_fragment_definitions.csv').filter(x=>x.enabled==='1'),fragmentLevels:csv('data/csv/存档系统/archive_fragment_levels.csv').filter(x=>x.enabled==='1'),work:csv('data/csv/存档系统/archive_work_items.csv').filter(x=>x.enabled==='1'),titles:csv('data/csv/存档系统/archive_titles.csv').filter(x=>x.enabled==='1')};
archiveData.social=csv('data/csv/存档系统/archive_social_items.csv').filter(x=>x.enabled==='1');archiveData.socialRules=csv('data/csv/存档系统/archive_social_rules.csv').filter(x=>x.enabled==='1');
const dailyData={items:csv('data/csv/存档系统/archive_daily_items.csv').filter(x=>x.enabled==='1'),schedule:csv('data/csv/存档系统/archive_daily_schedule.csv').filter(x=>x.enabled==='1'),rules:csv('data/csv/存档系统/archive_daily_rules.csv')[0]};
const treasureData=csv('data/csv/肉鸽奖励系统/rogue_reward_cards.csv').filter(x=>x.enabled==='1');
const fixture={shop,commerce:commerceFixture(),archive,archiveCats,content,lottery:{updates:csv('data/csv/抽奖系统/lottery_pool_updates.csv'),pools:csv('data/csv/抽奖系统/lottery_pool_definitions.csv').filter(x=>x.enabled==='1'),items:csv('data/csv/抽奖系统/lottery_item_definitions.csv').filter(x=>x.enabled==='1'),members:csv('data/csv/抽奖系统/lottery_pool_items.csv').filter(x=>x.enabled==='1'),pity:csv('data/csv/抽奖系统/lottery_pity_rules.csv').filter(x=>x.enabled==='1')},archiveIcons:csv('data/csv/存档系统/archive_item_icons.csv'),nativeBitmaps:fs.readdirSync('art/ui/sources/spellicons/survival/native').filter(x=>x.endsWith('.png')),source:{shop:'CSV shop_entries + content_catalog; availability/resources/ownership are explicit browser samples',archive:archiveSource||'synthetic layout stress rows',commerce:'Enabled paid/wallet CSV products with sample ownership/balances'}};
save(out+'/fixture.json',JSON.stringify(fixture));
fixture.archiveData=archiveData;fixture.dailyData=dailyData;fixture.treasureData=treasureData;save(out+'/fixture.json',JSON.stringify(fixture));
const nativeManifest=base+'/native_preview/manifest.json';const nativeAliases=fs.existsSync(nativeManifest)?JSON.parse(fs.readFileSync(nativeManifest,'utf8')).aliases:{};const assetPaths={...nativeAliases},resourceFallbacks=[];function assetWalk(assetRoot,dir=assetRoot){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())assetWalk(assetRoot,full);else if(entry.name.endsWith('.vtex')){const input=fs.readFileSync(full,'utf8').match(/"m_fileName"\s*"string"\s*"panorama\/images\/([^\"]+)"/);if(input){const rel=path.relative(assetRoot,full).replaceAll('\\','/').replace(/\.vtex$/,'');let original=input[1];if(!fs.existsSync('art/ui/sources/'+original)&&!fs.existsSync('panorama/src/images/'+original)&&/archive_gpu_(small|regular)/.test(rel)){const id=rel.split('/').pop(),configured=fixture.archiveIcons.find(x=>x.item_id===id);if(configured&&configured.icon_path){resourceFallbacks.push({texture:'s2r://panorama/images/'+rel+'.vtex',unavailableRecipePng:original,configuredCsvIcon:configured.icon_path,kind:'configured_icon_mapping_preview_only'});original=configured.icon_path;}}assetPaths['s2r://panorama/images/'+rel+'.vtex']=imageUri('file://{images}/'+original);}}}}assetWalk('art/ui/sources');assetWalk('panorama/src/images');
for(const[source]of graph){if(source.endsWith('.xml'))for(const m of read(source).matchAll(/file:\/\/\{images\}\/([^"']+)/g))assetPaths[m[1]]=imageUri('file://{images}/'+m[1]);}
if(baseline)for(const[rel,source]of graph)save(out+'/sources/'+rel,source);
let css=layouts.map(l=>l.styles.map(rel=>'/* '+rel+' */\n'+convertCss(graph.get(rel)||read(rel))).join('\n')).join('\n');
save(out+'/style.css',css);
// Build-time source snapshot keeps JS and CSS mutually consistent while agents edit.
const snapshotSources=Object.fromEntries([...graph]);
const background='design_refs/ui_20h/work/baseline/battle_no_queue.png';
save(out+'/index.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>紫色弹窗 · 真实组件浏览器预览</title><link rel="stylesheet" href="style.css"><style>
@property --pano-visibility{syntax:"*";inherits:false;initial-value:visible}@property --pano-fit-width{syntax:"*";inherits:false;initial-value:0}@property --pano-fit-height{syntax:"*";inherits:false;initial-value:0}@property --pano-halign{syntax:"*";inherits:false;initial-value:left}@property --pano-valign{syntax:"*";inherits:false;initial-value:top}@property --pano-flow{syntax:"*";inherits:false;initial-value:none}@property --pano-ignore-flow{syntax:"*";inherits:false;initial-value:false}@property --pano-position{syntax:"*";inherits:false;initial-value:normal}@property --pano-brightness{syntax:"*";inherits:false;initial-value:1}@property --pano-saturation{syntax:"*";inherits:false;initial-value:1}
@font-face{font-family:"Source Han Sans SC";src:url("${uri('panorama/fonts/Radiance-Survival-SourceHanSansSC-Regular.otf')}")}@font-face{font-family:"Source Han Serif SC";src:url("${uri('panorama/fonts/Radiance-Survival-SourceHanSerifSC-Bold.otf')}")}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:"Source Han Sans SC",sans-serif}body{background:#151127 url("${uri(background)}") center/cover}.panel{position:absolute;flex-shrink:0;transform-origin:0% 0%;align-content:flex-start;align-items:flex-start}.panel[hidden]{display:none!important}.label{display:block;pointer-events:none;line-height:1.25;white-space:nowrap}.button{cursor:pointer}img{object-fit:contain}#PreviewRoot{left:0;top:0;overflow:visible}.PreviewContext{left:0;top:0;width:100%;height:100%;pointer-events:none}.PreviewContext>.panel{pointer-events:none}.PreviewContext .button{pointer-events:auto}#PreviewCaption{position:fixed;bottom:5px;left:8px;color:#ded2fb;background:#181124cf;font:11px "Source Han Sans SC";padding:4px 8px;z-index:2000000;pointer-events:none}.PreviewNativeStandin{background-color:#161322}.UIClosed,.ArchiveHidden,.Hidden,.VipWindowHidden,.LotteryInfoHidden,.LotteryTooltipHidden{display:none!important}.UINineSlice{display:flex;flex-direction:column}.UINineSlice>.UINineRow{display:flex;flex-direction:row;position:relative;width:100%;flex-shrink:0}.UINineRow>.UINineTile{position:relative;flex-shrink:0;height:100%}.panel::-webkit-scrollbar{width:6px;height:6px}.panel::-webkit-scrollbar-thumb{background:#665082;border-radius:4px}.panel::-webkit-scrollbar-track{background:#100b1c}
</style><div id="PreviewRoot"></div><div id="PreviewCaption">${baseline?'迭代前':'当前实现'} · 生产 XML / JS / CSS · 显式浏览器样例 · 未连接游戏、账号或支付</div>
<script>window.PREVIEW_LAYOUTS=${JSON.stringify(layouts).replaceAll('</script','<\\/script')};window.PREVIEW_SOURCES=${JSON.stringify(snapshotSources).replaceAll('</script','<\\/script')};window.PREVIEW_FIXTURE=${JSON.stringify(fixture).replaceAll('</script','<\\/script')};window.PREVIEW_SOURCE_ROOT=${JSON.stringify(uri('panorama/src')+'/')};window.IMAGE_ROOT=${JSON.stringify(uri('art/ui/sources')+'/')};window.IMAGE_FALLBACK_ROOT=${JSON.stringify(uri('panorama/src/images')+'/')};window.PREVIEW_ASSET_PATHS=${JSON.stringify(assetPaths)};window.PREVIEW_BASELINE=${baseline};</script><script src="${uri('tools/purple_ui_10h/adapter.js')}"></script><script src="${uri('tools/purple_ui_10h/state.js')}"></script></html>`);
const records=[...graph].map(([rel,s])=>({path:rel,sha256:crypto.createHash('sha256').update(s).digest('hex')}));
save(out+'/assembly.json',JSON.stringify({at:new Date().toISOString(),kind:'production_component_browser_preview',baseline,layouts:layouts.map(({rel,styles,scripts})=>({rel,styles,scripts})),sourceGraph:records,resourceFallbacks,limitations:['Browser emulates Panorama layout and APIs; native rendering remains separate.','Missing GPU recipe PNGs use the configured CSV icon when available; resourceFallbacks records each preview-only mapping.','DOTA ability/item/scene widgets use existing bitmap assets or empty stand-ins.','Styles follow active XML include order; shared browser CSS cascade is an approximation of layout contexts.','Progress, unlocks, stock, currency balances and ownership are labeled fixture states.','No account, checkout, game commands, server connection or reward claims.'],fixtureSource:fixture.source},null,2));
console.log('PURPLE_PREVIEW_BUILT '+out+' sources='+records.length+' scripts='+layouts.reduce((n,x)=>n+x.scripts.length,0));
module.exports={convertCss,gradient};
