'use strict';
const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),{browser}=require('../shop_ui_12h/cdp.cjs');
let qaReportWritten=false;
process.on('beforeExit',()=>{if(!qaReportWritten){console.error('PURPLE_QA_INCOMPLETE: no new report was written');process.exitCode=1;}});
const base='design_refs/purple_ui_10h/work',out=base+'/qa';
const sourceAssembly=JSON.parse(fs.readFileSync(base+'/preview/assembly.json','utf8')),sourceDigest=crypto.createHash('sha256').update(JSON.stringify(sourceAssembly.sourceGraph)).digest('hex');
const args=process.argv.slice(2),arg=(name,fallback)=>{const n=args.indexOf(name);return n>=0?args[n+1]:fallback;};
const pages=arg('--pages')?arg('--pages').split(','):arg('--page')?[arg('--page')]:['archive','shop','commerce'];
const category=arg('--category'),categoryQuery=category?'&category='+encodeURIComponent(category):'';
const states=arg('--state')?[arg('--state')]:arg('--states')?arg('--states').split(','):['normal','long','unknown','locked','stock','hover','empty','scroll'];
const windowIds={archive:'ArchiveWindow',shop:'CustomShopWindow',daily:'DailyWindow',treasure:'TreasureWindow',lottery:'LotteryMainCanvas',vip:'VIPWindow',paid_checkout:'PaymentDialog'};
const cardSelectors={archive:'.ArchiveCard',shop:'.ShopShelfSlot',commerce:'.CJProduct',daily:'.DailyNormalCard,.DailyWeekCard,.DailySpecial',treasure:'.TreasureCard',lottery:'.LotteryDetailRow',vip:'.VIPRewardCard',wallet_checkout:'.CommerceConfirmBuy',paid_checkout:'#PaymentProductArt'};
const tooltipSelectors={archive:'#ArchiveTooltip',shop:'#ShopEntryTooltip',commerce:'.RCPurpleDetail',daily:'#DailyTooltip',treasure:'#TreasureTooltip',lottery:'#LotteryItemTooltip,#ArchiveTooltip',vip:'#VIPTooltip',wallet_checkout:'.__unusedCheckoutTooltip',paid_checkout:'.__unusedCheckoutTooltip'};
const sizes=arg('--size')?[arg('--size').split('x').map(Number)]:[[1280,720],[1920,1080],[2560,1440],[2560,1080]];
const wait=b=>b.run('new Promise(resolve=>setTimeout(resolve,70)).then(()=>true)');
async function metrics(b,page){return b.run(`(()=>{
 const e=${page==='wallet_checkout'?"document.querySelector('.CommerceConfirm')":page==='lottery'?"(nodes.LotteryInfoDialog&&!nodes.LotteryInfoOverlay.BHasClass('LotteryInfoHidden')?nodes.LotteryInfoDialog:nodes.LotteryMainCanvas).el":windowIds[page]?'nodes.'+windowIds[page]+'.el':"document.querySelector('.CommercePurple')"},r=e.getBoundingClientRect();
 const shown=e=>!!(e&&e.getBoundingClientRect().width&&getComputedStyle(e).display!=='none'&&!e.hidden);
 const tips=[...document.querySelectorAll('${tooltipSelectors[page]}')].filter(shown),rule=nodes.DailyRulesText&&nodes.DailyRulesText.el,body=nodes.DailyRulesBody&&nodes.DailyRulesBody.el;
 return {window:r.toJSON(),errors:previewErrors,scripts:previewScriptResults,visible:shown(e),cards:[...document.querySelectorAll('${cardSelectors[page]}')].filter(shown).length,
 balances:[...e.querySelectorAll('.PurpleBalance')].filter(shown).map(x=>x.textContent).join(' '),shellResources:cfg.SurvivalPurpleShell&&cfg.SurvivalPurpleShell.Resources,shellEntries:cfg.SurvivalPurpleShell&&cfg.SurvivalPurpleShell.Entries.map(x=>({id:x.id,valid:x.panel.IsValid(),values:x.balances.map(y=>y.value.text)})),footer:page==='shop'?['ShopResourceSummary','ShopStatus'].map(id=>({id,bounds:nodes[id].el.getBoundingClientRect().toJSON()})):[],
 rules:page==='daily'&&shown(rule)?{bounds:rule.getBoundingClientRect().toJSON(),body:body.getBoundingClientRect().toJSON(),scrollWidth:body.scrollWidth,clientWidth:body.clientWidth,scrollHeight:rule.scrollHeight,clientHeight:rule.clientHeight,text:body.textContent}:null,dailyFooter:page==='daily'?['DailyRules','DailyMakeup','DailyClaim','DailyNotice'].map(id=>nodes[id]&&nodes[id].el).filter(shown).map(el=>({id:el.id,bounds:el.getBoundingClientRect().toJSON()})):[],shopHeader:page==='shop'?{background:getComputedStyle(nodes.ShopHeader.el).backgroundColor,inline:nodes.ShopHeader.el.style.cssText}:null,
 tipCandidates:[...document.querySelectorAll('${tooltipSelectors[page]}')].map(e=>({id:e.id,classes:e.className,hidden:e.hidden,inline:e.style.cssText,bounds:e.getBoundingClientRect().toJSON(),display:getComputedStyle(e).display})),tips:tips.map(e=>({bounds:e.getBoundingClientRect().toJSON(),text:e.textContent})),checkoutVisible:shown(nodes.PaymentDialog&&nodes.PaymentDialog.el),walletCheckoutVisible:shown(document.querySelector('.CommerceConfirm')),checkoutFields:page.endsWith('_checkout')?[...e.querySelectorAll(page==='paid_checkout'?'#PaymentTitle,#PaymentPrice,#PaymentDescription,#PaymentValues,.PaymentRewardCopy,#PaymentQR,.PaymentFooter .PaymentAction,#PaymentStatus,#PaymentHint':'.CommerceConfirmCopy,.CommerceConfirmStatus,.CommerceConfirmBuy,.CommerceConfirmBack')].filter(shown).map(x=>({id:x.id,classes:x.className,text:x.textContent,bounds:x.getBoundingClientRect().toJSON(),scrollWidth:x.scrollWidth,clientWidth:x.clientWidth})):[],
 commerceFields:page==='commerce'?[...e.querySelectorAll('.CJProduct')].map(card=>{const name=card.querySelector('.RCProductName'),icon=card.querySelector('.RCProductArt');return {card:card.getBoundingClientRect().toJSON(),title:name.textContent,name:name.getBoundingClientRect().toJSON(),image:icon.src,decoded:icon.complete&&icon.naturalWidth>0,naturalWidth:icon.naturalWidth,captionFont:getComputedStyle(name).fontSize};}):[],commerceInspect:page==='commerce'?cfg.SurvivalCommerceView.Inspect():null,pager:page==='commerce'?(e.querySelector('.CJPageLabel')||{}).textContent:null,
 fixtureState:previewState,lotteryMeta:page==='lottery'&&shown(nodes.ArchiveTooltip.el)?{name:nodes.ArchiveTooltipName.text,effect:nodes.ArchiveTooltipEffect.text,source:PREVIEW_FIXTURE.lottery.items.find(x=>x.display_name===nodes.ArchiveTooltipName.text)}:null,
 lotteryPopup:page==='lottery'&&['history','update'].includes(previewState.state)?{title:nodes.LotteryInfoTitle.text,note:nodes.LotteryInfoNote.text,noteVisible:shown(nodes.LotteryInfoNote.el),noteBounds:nodes.LotteryInfoNote.el.getBoundingClientRect().toJSON(),rules:nodes.LotteryInfoRules.text,rulesBounds:nodes.LotteryInfoRules.el.getBoundingClientRect().toJSON(),sample:previewState.updateNoticeSample||null,unchangedNotice:previewState.updateNoticeUnchanged}:null,
 lotteryRewardDetails:page==='lottery'&&previewState.rewardDetailsSample?{title:nodes.LotteryInfoTitle.text,note:nodes.LotteryInfoNote.text,noteBounds:nodes.LotteryInfoNote.el.getBoundingClientRect().toJSON(),body:nodes.LotteryInfoList.el.textContent,sample:previewState.rewardDetailsSample}:null,
 missing:[...document.images].filter(i=>shown(i)&&i.src&&(!i.complete||!i.naturalWidth)).map(i=>i.src),vipState:page==='vip'?{action:nodes.VIPActionText.text,enabled:nodes.VIPAction.enabled,wallet:nodes.VIPWallet.text,status:nodes.VIPStatus.text}:null,calls:previewCalls};
})()`);}
async function pointer(b,page,width,height,locked){
 await b.go(base+'/preview/index.html','?page='+page+'&state='+(locked?'locked':'normal')+categoryQuery);await b.run('previewReady');
 const cardSelector=page==='shop'?'.ShopShelfSlot':'.CJProduct';
 const source=await b.run(`document.querySelector('${cardSelector}').getBoundingClientRect().toJSON()`);
 await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:source.x+source.width/2,y:source.y+source.height/2});await wait(b);
 const setup=await b.run(`(()=>{syncLayout();const tip=${page==='shop'?'nodes.ShopEntryTooltip.el':"document.querySelector('.RCPurpleDetail.Visible')"};if(!tip)return null;const buy=${page==='shop'?'nodes.ShopTooltipPurchase.el':"tip.querySelector('.RCProductBuy,.RCBundleBuy')"};return {tip:tip.getBoundingClientRect().toJSON(),buy:buy.getBoundingClientRect().toJSON()};})()`);
 assert(setup&&setup.tip.width>20&&setup.tip.height>40,'Pointer did not open '+page+' tooltip');
 const tip=setup.tip,y=Math.max(source.y+8,tip.y+8),gap=tip.x>source.x?(source.right+tip.x)/2:(source.x+tip.right)/2;
 await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:gap,y});await b.run('new Promise(resolve=>setTimeout(resolve,40)).then(()=>true)');
 await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:tip.x+8,y:Math.min(tip.bottom-8,y)});await b.run('new Promise(resolve=>setTimeout(resolve,230)).then(()=>true)');
 const survived=await metrics(b,page);assert.equal(survived.tips.length,1,'Tooltip closed crossing gap '+page);
 const point={x:setup.buy.x+setup.buy.width/2,y:setup.buy.y+setup.buy.height/2};
 const hit=await b.run(`(()=>{const e=document.elementFromPoint(${point.x},${point.y});return e&&!!e.closest('${page==='shop'?'.ShopTooltipPurchase':'.RCProductBuy,.RCBundleBuy'}');})()`);
 assert(hit,'Purchase pointer target obstructed '+page+' '+JSON.stringify({locked,source,setup,point,visibleTips:survived.tips}));
 const before=await b.run('previewCalls.length');await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});
 await b.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});
 const calls=await b.run('previewCalls.slice('+before+')');
 if(locked)assert.equal(calls.filter(x=>/purchase|checkout/.test(x.name||x.method||'')).length,0,'Locked item requested purchase');
 else assert(calls.some(x=>/purchase|wallet|paid/.test(x.name||x.method||'')),'Enabled purchase did not reach local mock '+page);
 return {page,width,height,locked,source,tip,button:setup.buy,gapCrossed:true,hoverSurvived:true,buttonHit:true,calls,kind:'browser_pointer_to_local_mock_only'};
}
async function vipNavigation(b,width,height){
 await b.go(base+'/preview/index.html','?page=vip&state=normal');assert.equal(await b.run('previewReady'),true);
 await b.run('shop();commerce();daily();treasure();lottery();closeWindows();sampleResources();syncLayout();true');
 const transitions=[],shownExpression="e=>!!(e&&e.getBoundingClientRect().width>0&&getComputedStyle(e).display!=='none'&&!e.hidden)";
 const inspect=()=>b.run(`(()=>{const shown=${shownExpression};return {top:cfg.SurvivalUILayers.Top(),windows:Object.entries({vip:nodes.VIPWindow.el,archive:nodes.ArchiveWindow.el,shop:nodes.CustomShopWindow.el,commerce:document.querySelector('.CommercePurple'),daily:nodes.DailyWindow.el,treasure:nodes.TreasureWindow.el,lottery:nodes.LotteryMainCanvas.el}).filter(([id,e])=>shown(e)).map(([id])=>id),tipVisible:shown(nodes.VIPTooltip.el),errors:previewErrors,calls:previewCalls};})()`);
 async function click(bounds){const point={x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2};await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await b.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});await wait(b);await b.run('syncLayout();true');return point;}
 for(const [page,caption]of [['treasure','宝物'],['archive','存档'],['lottery','抽奖'],['commerce','商城'],['escape','']]){
  await b.run('closeWindows();if(nodes.HandoffTopNavigation)nodes.HandoffTopNavigation.visible=true;syncLayout();true');await b.run('new Promise(resolve=>setTimeout(resolve,180)).then(()=>true)');
  const entry=await b.run('nodes.HandoffNav_vip.el.getBoundingClientRect().toJSON()');assert(entry.width>10,'VIP HUD entry missing');const point=await click(entry);let active=await inspect();assert.deepEqual(active.windows,['vip'],'HUD VIP entry failed '+JSON.stringify(active));assert.equal(active.top,'vip');
  const card=await b.run("document.querySelector('.VIPRewardCard').getBoundingClientRect().toJSON()");await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:card.x+card.width/2,y:card.y+card.height/2});await wait(b);active=await inspect();assert(active.tipVisible,'VIP hover missing before close');
  if(page==='escape'){assert.equal(await b.run("cfg.SurvivalUILayers.HandleEscape('vip')"),true);await wait(b);active=await inspect();assert.deepEqual(active.windows,[]);assert.equal(active.top,null);assert(!active.tipVisible,'VIP tooltip survives Escape');}
  else{const button=await b.run(`(()=>{const e=[...nodes.VIPWindow.el.querySelectorAll('.PurpleTab')].find(x=>x.querySelector('.PurpleTabName').textContent==='${caption}');return e&&e.getBoundingClientRect().toJSON();})()`);assert(button,'VIP shared tab missing '+caption);await click(button);active=await inspect();assert.deepEqual(active.windows,[page],'VIP navigation leaves wrong window '+JSON.stringify(active));assert.equal(active.top,page);assert(!active.tipVisible,'VIP tooltip survives navigation');}
  assert.equal(active.errors.length,0);assert(!active.calls.some(x=>x.name==='survival_vip_request'&&x.payload.action!=='view'||/ui_lottery_draw|ui_shop_purchase|survival_commerce_checkout|survival_archive_promote|survival_archive_title_equip|survival_daily_claim/.test(x.name||x.method||'')),'VIP navigation triggered reward action');
  await b.shot(out+'/'+width+'x'+height+'_vip_navigation_'+page+'.png',{x:0,y:0,width,height});transitions.push({from:'vip',page,width,height,entry,point,...active,kind:page==='escape'?'browser_local_escape_api':'browser_pointer_hud_entry_and_shared_navigation'});
 }
 return transitions;
}
async function navigation(b,width,height){
 await b.go(base+'/preview/index.html','?page=archive&state=normal');assert.equal(await b.run('previewReady'),true);
 await b.run('shop();commerce();daily();treasure();lottery();closeWindows();cfg.SurvivalArchive.Open();sampleResources();syncLayout();true');await wait(b);
 const transitions=[];
 for(const [page,caption,layer]of [['shop','生存商店','shop'],['commerce','商城','commerce'],['daily','每日奖励','daily_rewards'],['treasure','宝物','treasure'],['lottery','抽奖','lottery'],['archive','存档','archive']]){
  const button=await b.run(`(()=>{const e=[...document.querySelectorAll('.PurpleTab')].find(x=>x.getBoundingClientRect().width&&x.querySelector('.PurpleTabName').textContent==='${caption}');return e&&e.getBoundingClientRect().toJSON();})()`);
  assert(button,'Navigation tab missing '+caption);const point={x:button.x+button.width/2,y:button.y+button.height/2};
  await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await b.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});await wait(b);await b.run('syncLayout();true');
  const info=await metrics(b,page),active=await b.run(`(()=>{const shown=e=>e&&e.getBoundingClientRect().width>0&&getComputedStyle(e).display!=='none'&&!e.hidden;return {top:cfg.SurvivalUILayers.Top(),windows:Object.entries({archive:nodes.ArchiveWindow.el,shop:nodes.CustomShopWindow.el,commerce:document.querySelector('.CommercePurple'),daily:nodes.DailyWindow.el,treasure:nodes.TreasureWindow.el,lottery:nodes.LotteryMainCanvas.el}).filter(([id,e])=>shown(e)).map(([id])=>id)};})()`);
  assert.deepEqual(active.windows,[page],'Navigation leaves wrong windows visible '+JSON.stringify(active));assert.equal(active.top,layer,'Navigation layer mismatch');assert.equal(info.errors.length,0);assert.equal(info.missing.length,0);assert(info.window.x>=-2&&info.window.y>=-2&&info.window.right<=width+2&&info.window.bottom<=height+2,'Navigation window outside viewport');
  assert(!info.calls.some(x=>/ui_lottery_draw|ui_shop_purchase|survival_commerce_checkout|survival_archive_promote|survival_archive_title_equip|survival_daily_claim/.test(x.name||x.method||'')),'Navigation triggered a transaction');
  await b.shot(out+'/'+width+'x'+height+'_navigation_'+page+'.png',{x:0,y:0,width,height});transitions.push({page,width,height,active,point,...info,kind:'browser_pointer_navigation_to_local_fixtures_only'});
 }
 return transitions;
}
async function dailyMutualExclusion(b,width,height){
 await b.go(base+'/preview/index.html','?page=daily&state=normal');assert.equal(await b.run('previewReady'),true);
 const shown="e=>!!(e&&e.getBoundingClientRect().width&&getComputedStyle(e).display!=='none'&&!e.hidden)";
 const inspect=()=>b.run(`(()=>{syncLayout();const shown=${shown};return {tip:shown(nodes.DailyTooltip.el),rules:shown(nodes.DailyRulesText.el),tipBounds:nodes.DailyTooltip.el.getBoundingClientRect().toJSON(),ruleBounds:nodes.DailyRulesText.el.getBoundingClientRect().toJSON(),tipBackground:getComputedStyle(nodes.DailyTooltip.el).backgroundImage,rulesBackground:getComputedStyle(nodes.DailyRulesText.el).backgroundImage,errors:previewErrors,calls:previewCalls};})()`);
 const sources=await b.run("[...document.querySelectorAll('.DailyReward')].filter(e=>e.getBoundingClientRect().width).map(e=>e.getBoundingClientRect().toJSON())");assert(sources.length>1,'Daily rewards missing');
 const move=async r=>{await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:r.x+r.width/2,y:r.y+r.height/2});await b.run('new Promise(resolve=>setTimeout(resolve,110)).then(()=>true)');};
 await move(sources[0]);let first=await inspect();assert(first.tip,'Physical daily hover did not open detail');
 const oldTip=first.tipBounds,button=await b.run('nodes.DailyRules.el.getBoundingClientRect().toJSON()'),point={x:button.x+button.width/2,y:button.y+button.height/2};
 async function toggle(){await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await b.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});await b.run('new Promise(resolve=>setTimeout(resolve,110)).then(()=>true)');}
 await toggle();const open=await inspect();assert(open.rules&&!open.tip,'Rules and old hover detail overlap');
 const blocked=[];for(const r of [sources[0],sources[1],oldTip]){await move(r);const info=await inspect();assert(info.rules&&!info.tip,'Reward/old tooltip mouse movement reopened detail above rules');blocked.push(info);}
 await b.shot(out+'/'+width+'x'+height+'_daily_pointer_rules.png',{x:0,y:0,width,height});
 await toggle();const closed=await inspect();assert(!closed.rules,'Rules did not close');await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:2,y:2});await move(sources[0]);const restored=await inspect();assert(restored.tip&&!restored.rules,'Fresh hover failed after closing rules');assert.equal(restored.errors.length,0);assert(!restored.calls.some(x=>/claim|purchase|checkout|draw/.test(x.name||x.method||'')&&!/catalog/.test(x.payload&&x.payload.action||'')),'Daily pointer test requested reward/transaction');
 await b.shot(out+'/'+width+'x'+height+'_daily_pointer_restored.png',{x:0,y:0,width,height});
 return {page:'daily',width,height,kind:'browser_physical_mouse_rules_tooltip_mutual_exclusion',first,open,blocked,closed,restored,pass:true};
}
async function commerceLifecycle(b,width,height){
 await b.go(base+'/preview/index.html','?page=commerce&state=normal&category=technology25');assert.equal(await b.run('previewReady'),true);
 const inspect=()=>b.run(`(()=>{syncLayout();function walk(p){return p.Children().flatMap(c=>[c,...walk(c)]);}const all=walk(root),cards=all.filter(p=>p.BHasClass('CJProduct')),layers=all.filter(p=>p.BHasClass('CommercePurpleDetailLayer')),tips=all.filter(p=>p.BHasClass('RCPurpleDetail')),shown=e=>!!(e&&e.getBoundingClientRect().width&&getComputedStyle(e).display!=='none'&&!e.hidden);return {cards:cards.length,layers:layers.length,tips:tips.length,shownTips:tips.filter(p=>shown(p.el)).length,orphanTips:tips.filter(p=>!p.__purpleSource||!p.__purpleSource.IsValid()||p.__purpleSource.__purpleDetail!==p||!p.GetParent().BHasClass('CommercePurpleDetailLayer')).length,allLayerChildren:layers.map(p=>p.Children().length),sameSourceCards:window.__qaCommerceSaved?cards.length===window.__qaCommerceSaved.cards.length&&cards.every((p,i)=>p===window.__qaCommerceSaved.cards[i]):null,oldTipsDeleted:window.__qaCommerceSaved?window.__qaCommerceSaved.tips.every(p=>!p.IsValid()):null,oldSourcesDeleted:window.__qaCommerceSaved?window.__qaCommerceSaved.cards.every(p=>!p.IsValid()):null,visibleWindow:shown(document.querySelector('.CommercePurple')),errors:previewErrors,calls:previewCalls};})()`);
 async function save(){await b.run(`(()=>{function walk(p){return p.Children().flatMap(c=>[c,...walk(c)]);}const all=walk(root);window.__qaCommerceSaved={cards:all.filter(p=>p.BHasClass('CJProduct')),tips:all.filter(p=>p.BHasClass('RCPurpleDetail'))};return true;})()`);}
 async function hoverFirst(){await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:2,y:2});const source=await b.run("document.querySelector('.CJProduct').getBoundingClientRect().toJSON()");await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:source.x+source.width/2,y:source.y+source.height/2});await wait(b);const info=await inspect();assert.equal(info.shownTips,1,'Floating detail physical hover failed');assert.equal(info.orphanTips,0);return info;}
 async function click(selector,text){const rect=await b.run(`(()=>{const e=[...document.querySelectorAll('${selector}')].find(e=>e.getBoundingClientRect().width&&e.textContent.includes('${text}'));return e&&e.getBoundingClientRect().toJSON();})()`);assert(rect,'Actual commerce control missing '+text);const point={x:rect.x+rect.width/2,y:rect.y+rect.height/2};await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await b.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await b.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});await wait(b);return point;}
 const initial=await hoverFirst();assert.equal(initial.cards,15);assert.equal(initial.tips,15);await save();await b.run('cfg.SurvivalCommerceView.Close();syncLayout();true');const closed=await inspect();assert(!closed.visibleWindow);assert.equal(closed.tips,0);assert(closed.oldTipsDeleted&&closed.sameSourceCards,'Close must delete only details and preserve product identities');
 await b.run('cfg.SurvivalCommerceView.Open();syncLayout();true');await wait(b);const reopened=await hoverFirst();assert(reopened.sameSourceCards&&reopened.oldTipsDeleted,'Reopen altered original source cards or revived old tooltip');assert.equal(reopened.tips,15);
 await save();const categoryPoint=await click('.RCTab','武器');const categoryChanged=await inspect();assert.equal(categoryChanged.orphanTips,0);assert(categoryChanged.oldSourcesDeleted&&categoryChanged.oldTipsDeleted,'Category change leaves old tree alive');assert.equal(categoryChanged.cards,categoryChanged.tips);
 await click('.RCTab','科技');await hoverFirst();await save();const pagePoint=await click('.CJPageAction','下一页');const pageChanged=await inspect();assert.equal(pageChanged.cards,10);assert.equal(pageChanged.tips,10);assert.equal(pageChanged.orphanTips,0);assert(pageChanged.oldSourcesDeleted&&pageChanged.oldTipsDeleted,'Page change leaves old tree alive');const finalHover=await hoverFirst();assert.equal(finalHover.errors.length,0);assert(!finalHover.calls.some(x=>/purchase|wallet|paid/.test(x.method||'')||x.name==='survival_commerce_request'&&x.payload.action==='purchase'||x.name==='survival_payment_request'&&x.payload.action==='create'),'Lifecycle navigation requested checkout/purchase');
 await b.shot(out+'/'+width+'x'+height+'_commerce_lifecycle_page2.png',{x:0,y:0,width,height});await b.run('cfg.SurvivalCommerceView.Dispose();syncLayout();true');const disposed=await inspect();assert.equal(disposed.cards,0);assert.equal(disposed.tips,0);assert.equal(disposed.layers,0);
 return {width,height,kind:'browser_actual_production_floating_detail_lifecycle',initial,closed,reopened,categoryPoint,categoryChanged,pagePoint,pageChanged,finalHover,disposed,pass:true};
}
async function commerceEdges(b,width,height){
 const checks=[];for(const variant of ['first','rightmost','bottom_right','long_scroll']){
  await b.go(base+'/preview/index.html','?page=commerce&category=technology25&state='+(variant==='long_scroll'?'scroll_detail':'normal'));assert.equal(await b.run('previewReady'),true);
  const source=await b.run(`(()=>{const cards=[...document.querySelectorAll('.CJProduct')];let e=cards[${variant==='first'||variant==='long_scroll'?0:'cards.length-1'}];if(${variant==='rightmost'}){const top=cards[0].getBoundingClientRect().y;e=cards.filter(c=>Math.abs(c.getBoundingClientRect().y-top)<2).sort((a,b)=>b.getBoundingClientRect().right-a.getBoundingClientRect().right)[0];}return e.getBoundingClientRect().toJSON();})()`);await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:2,y:2});await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:source.x+source.width/2,y:source.y+source.height/2});await wait(b);
  let info=await metrics(b,'commerce');assert.equal(info.tips.length,1);const tip=info.tips[0].bounds,clip={left:Math.max(0,info.window.x),top:Math.max(0,info.window.y),right:Math.min(width,info.window.right),bottom:Math.min(height,info.window.bottom)};assert(tip.x>=clip.left-1&&tip.y>=clip.top-1&&tip.right<=clip.right+1&&tip.bottom<=clip.bottom+1,'Detail exceeds native window/screen clip model '+JSON.stringify({variant,tip,clip}));
  await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:tip.x+8,y:tip.y+8});await wait(b);const detail=await b.run(`(()=>{function walk(p){return p.Children().flatMap(c=>[c,...walk(c)]);}const p=walk(root).find(p=>p.BHasClass('RCPurpleDetail')&&p.BHasClass('Visible'));const body=p.FindChildrenWithClassTraverse('RCProductEffect')[0];if(${variant==='long_scroll'})body.ScrollToBottom();syncLayout();const buy=p.el.querySelector('.RCProductBuy'),r=buy.getBoundingClientRect();let row50;const node=body.el.firstChild,offset=node&&node.textContent.indexOf('第50行');if(offset>=0){const range=document.createRange();range.setStart(node,offset);range.setEnd(node,offset+4);row50=range.getBoundingClientRect().toJSON();}return {scrollTop:body.el.scrollTop,scrollHeight:body.el.scrollHeight,clientHeight:body.el.clientHeight,body:body.el.getBoundingClientRect().toJSON(),row50,panel:p.el.getBoundingClientRect().toJSON(),button:r.toJSON(),buttonHit:!!document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('.RCProductBuy'),text:p.el.textContent};})()`);
  if(variant==='long_scroll')assert(detail.scrollHeight>detail.clientHeight&&detail.scrollTop>0,'Long description did not scroll '+JSON.stringify(detail));if(variant==='long_scroll')assert(detail.row50&&detail.row50.y>=detail.body.y-1&&detail.row50.bottom<=detail.body.bottom+1,'Last description row is not readable');assert(detail.button.y>=detail.panel.y-1&&detail.button.bottom<=detail.panel.bottom+1,'Final action unreadable after detail scrolling');assert(detail.buttonHit,'Visible detail action covered after scroll');assert.equal(info.errors.length,0);assert(!info.calls.some(x=>/purchase|wallet|paid/.test(x.method||'')),'Edge/scroll fixture performed checkout');
  await b.shot(out+'/'+width+'x'+height+'_commerce_'+variant+'.png',{x:0,y:0,width,height});checks.push({variant,source,detail,clip,clipModel:'preview-only CommercePurple clip-path inset(0) based on native C16 observation',...info});
 }
 return {width,height,kind:'browser_window_clip_model_physical_edge_hover_and_production_Panel_ScrollToBottom_API',checks,pass:true};
}
async function commerceWheel(b,width,height){
 const checks=[];
 for(const variant of ['actual_effect','long_effect']){
  await b.go(base+'/preview/index.html','?page=commerce&category=technology25&state='+(variant==='long_effect'?'scroll_detail':'normal'));assert.equal(await b.run('previewReady'),true);
  const source=await b.run("document.querySelector('.CJProduct').getBoundingClientRect().toJSON()");await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:2,y:2});await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:source.x+source.width/2,y:source.y+source.height/2});await wait(b);
  const inspect=()=>b.run(`(()=>{const tip=document.querySelector('.RCPurpleDetail.Visible');const body=tip&&tip.querySelector('.RCProductEffect');if(!body)return null;const bounds=body.getBoundingClientRect(),buy=tip.querySelector('.RCProductBuy'),br=buy.getBoundingClientRect(),node=body.firstChild;const lastLine=body.textContent.trim().split('\\n').pop();let lastLineBounds=null;if(node&&node.nodeType===3){const start=node.textContent.lastIndexOf(lastLine);if(start>=0){const range=document.createRange();range.setStart(node,start);range.setEnd(node,start+lastLine.length);lastLineBounds=range.getBoundingClientRect().toJSON();}}const point={x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2},hit=document.elementFromPoint(point.x,point.y);return {scrollTop:body.scrollTop,scrollHeight:body.scrollHeight,clientHeight:body.clientHeight,body:bounds.toJSON(),pointerEvents:getComputedStyle(body).pointerEvents,point,hitClass:hit&&hit.className,bodyHit:hit===body||body.contains(hit),lastLine,lastLineBounds,panel:tip.getBoundingClientRect().toJSON(),button:br.toJSON(),buttonHit:buy===document.elementFromPoint(br.x+br.width/2,br.y+br.height/2)||buy.contains(document.elementFromPoint(br.x+br.width/2,br.y+br.height/2)),text:tip.textContent};})()`);
  const before=await inspect();assert(before&&before.scrollHeight>before.clientHeight,'Actual effect fixture does not need scrolling');await b.call('Input.dispatchMouseEvent',{type:'mouseMoved',...before.point});await wait(b);await b.shot(out+'/'+width+'x'+height+'_commerce_'+variant+'_wheel_before.png',{x:0,y:0,width,height});
  for(let i=0;i<3;i++){await b.call('Input.dispatchMouseEvent',{type:'mouseWheel',...before.point,deltaX:0,deltaY:Math.max(600,before.scrollHeight)});await b.run('new Promise(resolve=>setTimeout(resolve,120)).then(()=>true)');}
  const after=await inspect();await b.shot(out+'/'+width+'x'+height+'_commerce_'+variant+'_wheel_after.png',{x:0,y:0,width,height});assert(after&&after.scrollTop>before.scrollTop,'Physical wheel did not scroll actual effect '+JSON.stringify({variant,before,after}));assert.equal(after.pointerEvents,'auto','Production effect rejects input');assert(after.lastLineBounds&&after.lastLineBounds.y>=after.body.y-1&&after.lastLineBounds.bottom<=after.body.bottom+1,'Physical wheel final line not readable');assert(after.buttonHit,'Physical wheel leaves action obstructed');const info=await metrics(b,'commerce'),clip={left:Math.max(0,info.window.x),top:Math.max(0,info.window.y),right:Math.min(width,info.window.right),bottom:Math.min(height,info.window.bottom)};assert(after.panel.x>=clip.left-1&&after.panel.y>=clip.top-1&&after.panel.right<=clip.right+1&&after.panel.bottom<=clip.bottom+1,'Physical wheel detail exceeds window/screen intersection');assert(after.button.y>=after.panel.y-1&&after.button.bottom<=after.panel.bottom+1,'Physical wheel final action exceeds detail');assert.equal(info.errors.length,0);assert(!info.calls.some(x=>/purchase|wallet|paid/.test(x.method||'')),'Physical wheel opened checkout');checks.push({variant,source,before,after,clip,...info});
 }
 return {width,height,kind:'browser_actual_CDP_mouseWheel_no_ScrollToBottom_API',checks,pass:true};
}
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await browser(),cases=[],pointers=[],navigations=[],dailyPointers=[],commerceLifecycles=[],commerceEdgesCases=[],commerceWheels=[];try{
 for(const [width,height]of sizes){await b.call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});
  if(args.includes('--daily-pointer-only')){dailyPointers.push(await dailyMutualExclusion(b,width,height));continue;}
  if(args.includes('--commerce-lifecycle-only')){commerceLifecycles.push(await commerceLifecycle(b,width,height));continue;}
  if(args.includes('--commerce-edge-only')){commerceEdgesCases.push(await commerceEdges(b,width,height));continue;}
  if(args.includes('--commerce-wheel-only')){commerceWheels.push(await commerceWheel(b,width,height));continue;}
  if(args.includes('--vip-navigation-only')){navigations.push(...await vipNavigation(b,width,height));continue;}
  if(args.includes('--navigation-only')){navigations.push(...await navigation(b,width,height));continue;}
  if(!args.includes('--pointer-only'))for(const page of pages)for(const state of states){
   await b.go(base+'/preview/index.html','?page='+page+'&state='+state+categoryQuery);assert.equal(await b.run('previewReady'),true,'Preview state failed '+page+'/'+state);await b.run('syncLayout();true');const info=await metrics(b,page);
   assert(info.visible,'Window missing');assert(info.window.x>=-2&&info.window.y>=-2&&info.window.right<=width+2&&info.window.bottom<=height+2,'Window outside viewport '+JSON.stringify({page,state,width,height,bounds:info.window}));
   assert.equal(info.errors.length,0,'Production browser script error '+JSON.stringify(info.errors));if(page!=='paid_checkout')assert(!info.checkoutVisible,'Inactive checkout remains visible');else assert(!info.walletCheckoutVisible,'Inactive wallet checkout remains visible');assert.equal(info.missing.length,0,'Visible icon missing '+JSON.stringify(info.missing));
   if(state==='empty')assert.equal(info.cards,0);else if(!page.endsWith('_checkout')&&!(page==='lottery'&&['normal','history','locked','reward_known','reward_unknown'].includes(state)))assert(info.cards>0,'No rendered cards '+page);assert(info.tips.length<=1,'Multiple detail panels visible');
   if(!page.endsWith('_checkout'))assert(info.balances&&!info.balances.includes('—'),'Shared sample balances failed to refresh '+JSON.stringify({page,balances:info.balances,resources:info.shellResources,entries:info.shellEntries}));
   if(page.endsWith('_checkout')){for(const f of info.checkoutFields){assert(f.bounds.x>=info.window.x-1&&f.bounds.y>=info.window.y-1&&f.bounds.right<=info.window.right+1&&f.bounds.bottom<=info.window.bottom+1,'Checkout content exceeds window '+JSON.stringify(f));}const purchaseCalls=info.calls.filter(x=>x.name==='survival_commerce_request'&&x.payload.action==='purchase'||x.name==='survival_payment_request'&&x.payload.action==='create');assert.equal(purchaseCalls.length,page==='wallet_checkout'&&['receipt','delivered'].includes(state)?1:0,'Checkout must use only explicit local fixture action');if(page==='paid_checkout'&&state==='pending')assert(info.checkoutFields.some(x=>x.id==='PaymentQR'&&x.bounds.width>40),'Local QR renderer missing');} for(const {id,bounds:f}of info.footer)assert(f.y>=info.window.y&&f.bottom<=info.window.bottom+1,'Footer content outside shop '+id);
   if(page==='shop')assert.equal(info.shopHeader.background,'rgb(16, 11, 33)','Old teal header remains');
   if(['rules','rules_long'].includes(state)&&page==='daily'){assert(info.rules,'Rules panel missing');const scale=info.window.width/1280;assert(info.rules.body.right<=info.rules.bounds.right-16*scale,'Rules body exceeds panel');assert(info.rules.scrollWidth<=info.rules.clientWidth+2,'Rules text overflows horizontal');assert(info.rules.bounds.height<=516*scale+1,'Rules exceeds max height');if(state==='rules'){assert(info.rules.bounds.height<515*scale,'Short rules retained fixed height');assert(info.rules.body.bottom<=info.rules.bounds.bottom+1,'Short rule body clipped');}else{assert(info.rules.text.includes('第50行'),'Long rule fixture lost row 50');await b.run('nodes.DailyRulesText.ScrollToBottom();syncLayout();true');await wait(b);info.rulesScroll=await b.run(`(()=>{const p=nodes.DailyRulesText.el,body=nodes.DailyRulesBody.el,walker=document.createTreeWalker(body,NodeFilter.SHOW_TEXT);let n,row;while(n=walker.nextNode())if(n.textContent.includes('第50行')){const r=document.createRange();r.selectNodeContents(n);row=r.getBoundingClientRect().toJSON();break;}return {scrollTop:p.scrollTop,scrollHeight:p.scrollHeight,clientHeight:p.clientHeight,row50:row,panel:p.getBoundingClientRect().toJSON()};})()`);assert(info.rulesScroll.scrollTop>0,'Long rules did not scroll');assert(info.rulesScroll.row50.y>=info.rulesScroll.panel.y-1&&info.rulesScroll.row50.bottom<=info.rulesScroll.panel.bottom+1,'Row50 unreadable after scrolling');}for(const f of info.dailyFooter)assert(f.bounds.y>=info.window.y&&f.bounds.bottom<=info.window.bottom+1,'Daily footer exceeds window '+f.id);assert(!info.calls.some(x=>/claim|purchase|checkout|draw/.test(x.name||x.method||'')),'Rules fixture requested reward/transaction');}
   if(page==='vip'&&['pending_select','insufficient','unsynced'].includes(state)){assert.equal(info.vipState.action,{pending_select:'正在保存…',insufficient:'付费币不足',unsynced:'等待会员数据'}[state]);assert.equal(info.vipState.enabled,false);assert(!info.calls.some(x=>x.name==='survival_vip_request'&&x.payload.action!=='view'),'VIP fixture requested reward');}
   if(['hover','long','unknown','stock','max_hover','selected_hover','little_jacket','page2_hover'].includes(state)&&state!=='empty')assert.equal(info.tips.length,1,'Hover detail missing '+page+'/'+state+' '+JSON.stringify(info.tipCandidates));
   if(page==='lottery'&&['hover','stock','unknown'].includes(state)){const m=info.lotteryMeta;assert(m&&m.source,'Real CSV metadata source missing');const effect=m.effect.replace(/\s/g,''),description=m.source.description.replace(/\s/g,'');assert(effect.indexOf(description)===0,'Description is not first '+JSON.stringify(m));assert(m.effect.includes('品质：'),'Reward quality omitted');if(state==='unknown'){for(const key of ['已拥有：','期限：','重复转化：'])assert(!m.effect.includes(key),'Missing metadata fabricated '+key);}else{assert(effect.includes('已拥有：'+(state==='stock'?1:0)+'/'+m.source.max_owned),'Ownership/max count omitted '+JSON.stringify(m));assert(m.effect.includes('期限：'+m.source.duration_text),'Actual CSV duration omitted');assert(effect.includes('重复转化：'+m.source.duplicate_points+'积分'),'Duplicate conversion omitted '+JSON.stringify(m));}assert(!info.calls.some(x=>/draw|purchase|checkout/.test(x.name||x.method||'')),'Lottery tooltip requested transaction');}
   if(page==='lottery'&&['history','update'].includes(state)){const m=info.lotteryPopup;assert(m&&m.noteVisible,'Original history/update note hidden');for(const f of [m.noteBounds,m.rulesBounds])assert(f.x>=info.window.x-1&&f.right<=info.window.right+1&&f.y>=info.window.y-1&&f.bottom<=info.window.bottom+1,'Original popup text exceeds dialog');if(state==='history')assert.equal(m.note,'仅本局最近30次抽取 · 跨局记录暂未接入');else {assert(m.sample&&m.unchangedNotice,'Actual CSV update notice missing or mutated');const n=m.sample.notice;assert.equal(m.title,n.title);assert.equal(m.note,n.effective_date?'更新生效日期：'+n.effective_date:'奖池配置已更新');assert(m.rules.includes(n.summary),'Actual CSV notice summary missing');}assert(!info.calls.some(x=>/draw|purchase|checkout/.test(x.name||x.method||'')),'Original popup requested a draw/transaction');}
   if(page==='lottery'&&['reward_known','reward_unknown'].includes(state)){const m=info.lotteryRewardDetails;assert(m&&m.sample,'Actual production single-result detail is missing');assert.equal(m.title,m.sample.name);assert(m.note.toUpperCase().includes(m.sample.quality.toUpperCase()),'Actual quality missing');if(state==='reward_known')assert(m.sample.duration&&m.note.includes(m.sample.duration),'Actual CSV duration missing');else assert(!m.note.includes('永久')&&!m.note.includes(' · '),'Missing duration invented in visible note');assert(m.body.replace(/\s/g,'').includes(m.sample.description.replace(/\s/g,'')),'Actual item description missing');assert(m.noteBounds.x>=info.window.x-1&&m.noteBounds.right<=info.window.right+1&&m.noteBounds.y>=info.window.y-1&&m.noteBounds.bottom<=info.window.bottom+1,'Visible reward note exceeds dialog');assert(!info.calls.some(x=>/draw|purchase|checkout/.test(x.name||x.method||'')),'Local single-result detail requested a draw/transaction');}
   if(page==='commerce'&&category==='technology25'&&state!=='empty'){assert.equal(info.pager,(['page2','page2_hover'].includes(state)?'2':'1')+' / 2 · 25件');assert.equal(info.commerceFields.length,['page2','page2_hover'].includes(state)?10:15);for(const f of info.commerceFields){assert(f.decoded,'Canonical technology icon missing '+f.title);assert(!f.image.includes('lottery_attribute_crystal'),'Old placeholder remains '+f.title);assert(f.name.x>=f.card.x-1&&f.name.right<=f.card.right+1,'Caption exceeds card '+f.title);assert(Math.abs((f.name.x+f.name.right)-(f.card.x+f.card.right))<3,'Caption is not centered '+f.title);}}
   for(const {bounds:t}of info.tips)assert(t.x>=-2&&t.y>=-2&&t.right<=width+2&&t.bottom<=height+2,'Tooltip outside viewport '+JSON.stringify({page,state,width,height,bounds:t}));
   await b.shot(out+'/'+width+'x'+height+'_'+page+'_'+state+'.png',{x:0,y:0,width,height});cases.push({page,state,width,height,...info});
  }
  if(!args.includes('--no-pointer'))for(const page of pages.filter(x=>x==='shop'||x==='commerce'))for(const locked of [false,true])pointers.push(await pointer(b,page,width,height,locked));
 }
 const result={at:new Date().toISOString(),status:'PASS_BROWSER_COMPONENTS',kind:'production_component_browser_preview',sourceDigest,sourceAssemblyAt:sourceAssembly.at,checks:['Active production XML include order','No browser script errors','Visible windows and available hover bounds','Visible icon decoding','Inactive checkout hidden',...(cases.some(x=>!x.page.endsWith('_checkout'))?['Visible shared sample balances']:[]),...(cases.some(x=>x.state==='empty')?['Empty and populated grids']:[]),...(cases.some(x=>x.state==='long')?['Long names and descriptions']:[]),...(cases.some(x=>x.state==='unknown')?['Unknown progress']:[]),...(cases.some(x=>x.state==='locked')?['Unavailable entries']:[]),...(cases.some(x=>x.state==='stock')?['Ownership and stock fixtures']:[]),...(cases.some(x=>x.page==='daily'&&x.state==='rules')?['Rules body and text horizontal bounds']:[]),...(cases.some(x=>x.page==='shop')?['Shop footer inside window']:[]),...(cases.some(x=>x.page.endsWith('_checkout'))?['Checkout title, price, description, rewards, QR, status and action bounds','Checkout APIs record only expected local fixture actions']:[]),...(pointers.length?['Physical mouse crossing tooltip gap and purchase hit target','Unavailable items send no backend purchase request; frontend reward view may open']:[])],limitations:['Panorama rendering and DOTA native widgets need separate in-game acceptance','Checkout/draw/claim APIs are local recording mocks','Browser ellipsis approximates Panorama shrink'],cases,pointers,dailyPointers,commerceLifecycles,commerceEdgesCases,commerceWheels,category};
 if(commerceWheels.length)result.checks.push('Actual CDP mouseWheel scrolls real first effect and explicit50line stress to readable last line','Physical wheel keeps price/action inside window/screen intersection and sends no checkout');if(commerceEdgesCases.length)result.checks.push('Physical first/rightmost/bottomright detail stays inside modal-window and screen intersection clip model','Explicit long-text fixture scrolls to a visible, unobstructed final action without checkout');if(commerceLifecycles.length)result.checks.push('Physical commerce floating-detail hover and category/page transitions','Close/reopen deletes details but preserves original source card identity','Actual __purpleSource/__purpleDetail links; no orphan panels or checkout requests','Dispose deletes details and modal layer');if(dailyPointers.length)result.checks.push('Physical daily hover → rules → behind-card movement keeps tooltip hidden → close and fresh hover restores detail');if(category==='technology25')result.checks.push('Exact 25 wallet technology CSV products across 15/10 pages','Canonical official icons decoded, no old placeholder','Product captions centered within cards');result.navigations=navigations;if(navigations.length)result.checks.push(args.includes('--vip-navigation-only')?'Physical mouse opens VIP from actual HUD entry and switches four shared targets':'Physical mouse switches all shared navigation tabs','Only destination window stays visible','Destination modal layer is active','Navigation sends no transaction request');if(args.includes('--vip-navigation-only'))result.checks.push('VIP tooltip closes with navigation and local Escape API');if(cases.some(x=>x.page==='vip'&&['pending_select','insufficient','unsynced'].includes(x.state)))result.checks.push('VIP pending, insufficient balance and unsynced action labels are disabled');
 const reportName=arg('--report',args.includes('--navigation-only')?'navigation_report':args.includes('--pointer-only')?'pointer_report':args.includes('--page')?'report_'+arg('--page')+'_'+arg('--state','matrix'):'matrix_report').replace(/\.json$/,'');fs.writeFileSync(out+'/'+reportName+'.json',JSON.stringify(result,null,2));qaReportWritten=true;console.log('PURPLE_QA_PASS cases='+cases.length+' pointers='+pointers.length+' navigations='+navigations.length);
 }finally{b.close();}})().catch(error=>{console.error(error);process.exitCode=1});
