'use strict';
// Scoped final gallery verification: no production UI test, native console or transaction.
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
require('./review.cjs');
const {browser}=require('../shop_ui_12h/cdp.cjs'),root='design_refs/purple_ui_10h',work=root+'/work',read=p=>JSON.parse(fs.readFileSync(p,'utf8')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const metadataOnly=process.argv.includes('--metadata-only');
let completed=false;process.on('beforeExit',()=>{if(!completed){console.error('C25_REVIEW_CHECK_INCOMPLETE');process.exitCode=1;}});
(async()=>{
 const best=read(root+'/BEST_VERSION.json'),proof=read(work+'/shop_reference_drawer/sourceproof.json'),acceptance=read(work+'/native_shop_standalone_acceptance.json'),previous=read(work+'/review/verification.json');
 assert.equal(proof.sourceCount,143);assert.equal(proof.matchingSources,143);assert(/^PASS/.test(proof.status));assert.equal(best.preview_source_digest,proof.sourceDigest);assert.equal(acceptance.sourceDigest,proof.sourceDigest);assert.equal(previous.status,'PASS');
 const b=await browser();
 try{
  await b.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1080,deviceScaleFactor:1,mobile:false});await b.go(root+'/Review.html');
  const data=await b.run('D');assert.deepEqual(data.best,best);assert.deepEqual(data.nativeShopAcceptance,acceptance);assert(data.standaloneShop);assert.equal(data.primary.length,6);assert.equal(Object.keys(data.best.components).length,8);assert.equal(data.latestShopOverride.candidate,'C25');assert.equal(data.latestShopOverride.sourceDigest,proof.sourceDigest);
  const shop=data.current.filter(r=>r.page==='shop');assert.equal(shop.length,48);assert(shop.every(r=>r.folder==='shop_reference_drawer/current'&&r.sourceScope.captureGraphDigest===proof.sourceDigest),'Old shared shop leaked into current gallery');
  const primary=[];for(const record of data.primary){const result=await b.run(`(async()=>{choose(${JSON.stringify(record)});const imgs=[...document.querySelectorAll('#viewer img')];await Promise.all(imgs.map(i=>i.decode()));return {page:$('page').value,category:$('category').value,comparison:!!$('compare-range'),image:document.querySelector('#viewer .stage>img').getAttribute('src'),decoded:imgs.every(i=>i.complete&&i.naturalWidth>0)};})()`);assert.equal(result.page,record.page);assert(result.comparison&&result.decoded);assert.equal(result.image,record.image);primary.push(result);}
  const selections=[];for(const record of shop){const result=await b.run(`(async()=>{const r=${JSON.stringify(record)};choose(r);const imgs=[...document.querySelectorAll('#viewer img')];await Promise.all(imgs.map(i=>i.decode()));return {page:$('page').value,category:$('category').value,state:$('state').value,viewport:$('viewport').value,image:document.querySelector('#viewer .stage>img').getAttribute('src'),comparison:!!$('compare-range'),before:document.querySelector('#before-layer img')&&document.querySelector('#before-layer img').getAttribute('src'),decoded:imgs.every(i=>i.complete&&i.naturalWidth>0),caption:$('viewer').textContent,defaultRange:$('compare-range')&&$('compare-range').value};})()`);assert.equal(result.image,record.image);assert.equal(result.page,'shop');assert.equal(result.category,record.category);assert.equal(result.state,record.state);assert.equal(result.viewport,record.viewport);assert(result.decoded);const paired=['normal','hover'].includes(record.state);assert.equal(result.comparison,paired);if(paired){assert(result.before.startsWith('work/shop_reference_drawer/rejected_previous/'));assert.equal(result.defaultRange,'0');assert(result.caption.includes('用户明确拒绝的旧统一窗'));const clip=await b.run(`$('compare-range').value=65;$('compare-range').dispatchEvent(new Event('input'));$('before-layer').style.clipPath`);assert(clip.includes('35%'));}else assert(result.caption.includes('没有匹配的改前图'));selections.push(result);}
  const paths=[...new Set([...data.current,...data.before,...data.native,...data.experiments].map(r=>r.image))];assert(paths.every(p=>fs.existsSync(path.join(root,p))));
  const priorImages=metadataOnly?read(work+'/review/verification_shop_c25_images.json'):previous;assert.equal(priorImages.status,'PASS');if(metadataOnly)assert.deepEqual([...paths].sort(),priorImages.allImageDecode.records.map(r=>r.path).sort(),'Gallery images changed; metadata-only check cannot reuse them');
  const old=new Map(priorImages.allImageDecode.records.map(r=>[r.path,r]));const reused=paths.filter(p=>old.has(p)&&(metadataOnly||!p.startsWith('work/shop_reference_drawer/')&&!/work\/native\/c2[0-5]_/.test(p))).map(p=>old.get(p));const targets=paths.filter(p=>!reused.some(r=>r.path===p));
  const decoded=await b.run(`(async()=>{const paths=${JSON.stringify(targets)},rows=[];let next=0;await Promise.all(Array.from({length:4},async()=>{while(next<paths.length){const path=paths[next++],i=new Image();i.src=url(path);try{await i.decode();rows.push({path,complete:i.complete,naturalWidth:i.naturalWidth,naturalHeight:i.naturalHeight});}catch(error){rows.push({path,complete:false,error:String(error)});}}}));return rows;})()`);assert(decoded.every(r=>r.complete&&r.naturalWidth>0));assert.equal(reused.length+decoded.length,paths.length);
  const evidence=new Set(Object.values(best.components).flatMap(c=>c.evidence||[]));if(best.common_navigation&&best.common_navigation.evidence)evidence.add(best.common_navigation.evidence);assert.deepEqual(data.native.filter(r=>r.selected).map(r=>r.image).sort(),[...evidence].sort());
  const accepted=new Set(acceptance.captures.map(r=>r.path));assert.deepEqual(data.native.filter(r=>r.standaloneAccepted).map(r=>r.image).sort(),[...accepted].sort());for(const cap of acceptance.captures){assert.equal(hash(root+'/'+cap.path),cap.sha256);assert(fs.existsSync(root+'/'+cap.provenance));}
  for(const name of ['c25_native_esc_closed.png','c25_native_hud_entry_reopen.png','c25_native_other_final.png','c25_native_final_restored.png']){const r=data.native.find(r=>r.image==='work/native/'+name);assert(r&&!r.selected&&!r.standaloneAccepted,'Historical misnamed capture became accepted '+name);}
  assert(data.native.find(r=>r.image.endsWith('/c25_native_esc_closed.png')).note.includes('不能证明商店'));assert(data.native.find(r=>r.image.endsWith('/c25_native_other_final.png')).note.includes('画面仍是挑战'));
  assert(data.native.find(r=>r.image.endsWith('/c25_native_second_esc.png')).standaloneAccepted);assert(data.native.find(r=>r.image.endsWith('/c25_native_entry_reopen_verified.png')).selected);assert(data.native.find(r=>r.image.endsWith('/c25_native_other_verified.png')).selected);
  assert(data.docs.every(p=>fs.existsSync(root+'/'+p)));assert(data.docs.includes('StandaloneShop.md'));assert(data.docs.includes('work/native_shop_standalone_acceptance.json'));assert(data.experiments.some(r=>r.kind==='user_rejected_previous_unified_shop'));
  const links=await b.run(`[...document.querySelectorAll('a')].map(a=>a.getAttribute('href')).filter(Boolean)`);assert(links.every(p=>fs.existsSync(path.resolve(root,decodeURIComponent(p)))),'Broken actual local gallery link');
  await b.run(`switchSection('browser');choose(D.primary.find(r=>r.page==='shop'));window.scrollTo(0,0);Promise.all([...document.querySelectorAll('#viewer img')].map(i=>i.decode())).then(()=>true)`);await b.shot(work+'/review/1440x1080_review_shop_c25.png',{x:0,y:0,width:1440,height:1080});
  await b.run(`switchSection('native');$('native-page').value='shop';renderNative();window.scrollTo(0,0);true`);await b.shot(work+'/review/1440x1080_review_native_shop_c25.png',{x:0,y:0,width:1440,height:1080});
  await b.run(`switchSection('qa');$('shop-validation').scrollIntoView({block:'start'});true`);await b.shot(work+'/review/1440x1080_review_shop_qa_c25.png',{x:0,y:0,width:1440,height:1080});
  const result={at:new Date().toISOString(),kind:'local_review_gallery_scoped_shop_c25',status:'PASS',gallerySha256:hash(root+'/Review.html'),bestSourceDigest:proof.sourceDigest,current:data.current.length,before:data.before.length,native:data.native.length,experiments:data.experiments.length,primary,shopSelections:selections,metadataOnly,latestShopOverride:data.latestShopOverride,allImageDecode:{count:paths.length,newlyDecodedCount:decoded.length,reusedCount:reused.length,reuseFrom:metadataOnly?'verification_shop_c25_images.json; identical877-image path set, Root metadata-only update with unchanged PNGs. That report decoded308 new images in Chrome and reused569 original unchanged captures.':'C19 verification.json; unchanged pre-existing PNG families retained without recapture. New standalone shop, its histories and C20–C25 native files decoded in actual Chrome.',failures:[],records:[...reused,...decoded]},winnerLabels:{components:Object.keys(best.components),selectedNative:[...evidence],standaloneNativeAccepted:[...accepted]},nativeCaptureHashChecks:acceptance.captures.length,localLinks:links,docs:data.docs,scope:'Gallery checks only. Only48Shop state selectors and six primary pairs inspected anew; unchanged component gallery/image evidence reused. No production retest, game console, account action or transaction.'};
  fs.writeFileSync(work+'/review/verification_shop_c25.json',JSON.stringify(result,null,2));completed=true;console.log('C25_REVIEW_PASS shop48 primary6 newDecode'+decoded.length+' reused'+reused.length+' sha'+result.gallerySha256);
 }finally{b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
