'use strict';
const fs=require('fs'),path=require('path');
const base='design_refs/purple_ui_10h/work/shop_reference_drawer';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const previous=read(base+'/rejected_previous/report.json'),current=read(base+'/current/report.json');
const records=current.cases.flatMap(c=>['normal','hover','slide_partial','slide_settled'].map(state=>({width:c.width,height:c.height,category:c.category,state,image:'current/'+c.width+'x'+c.height+'_shop_'+c.category+'_'+state+'.png',before:['normal','hover'].includes(state)?'rejected_previous/'+c.width+'x'+c.height+'_shop_'+c.category+'_'+state+'.png':null})));
for(const r of records)for(const f of [r.image,r.before].filter(Boolean))if(!fs.existsSync(base+'/'+f))throw Error('Missing paired image '+f);
const data={kind:'production_component_browser_preview',at:new Date().toISOString(),previousDigest:previous.sourceDigest,currentDigest:current.sourceDigest,currentStatus:current.status,reference:read(base+'/reference_geometry.json'),records};
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>生存商店 · 独立参考图抽屉</title><style>
*{box-sizing:border-box}body{margin:0;background:#100a1c;color:#e9deef;font:15px/1.65 'Microsoft YaHei','Segoe UI',sans-serif}main{max-width:1440px;margin:auto;padding:28px 24px}h1{color:#edce88;margin:0;font-size:28px}p{margin:8px 0}.dim{color:#b7a2c8}a{color:#efd28d}select{font:inherit;background:#281a38;border:1px solid #74558e;border-radius:5px;padding:7px;color:#f1e6f7}.controls{display:flex;gap:18px;flex-wrap:wrap;margin:22px 0}.controls label{display:flex;gap:8px;align-items:center}.box{border:1px solid #604774;border-radius:8px;background:#1b112b;padding:16px;margin:18px 0}.stage{width:100%;position:relative;overflow:hidden;background:#050406}.stage img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}.layer{position:absolute;inset:0;clip-path:inset(0 50% 0 0)}.line{position:absolute;left:50%;top:0;bottom:0;width:2px;background:#efd18a}.caption{display:flex;justify-content:space-between;margin:8px 0}.slider{display:flex;align-items:center;gap:14px;margin-top:14px}.slider input{width:100%;accent-color:#af81d7}.links{display:flex;flex-wrap:wrap;gap:18px}code{overflow-wrap:anywhere;color:#ceb7e1}table{border-collapse:collapse;width:100%;font-size:14px}td{border-bottom:1px solid #453252;padding:8px;vertical-align:top}td:first-child{width:160px;color:#efd18a}@media(max-width:640px){main{padding:18px 12px}.controls{gap:10px}.controls label{flex:1;min-width:140px}.controls select{flex:1}h1{font-size:24px}}
</style><main><h1>生存商店 · 左侧滑出参考图版</h1><p>真实生产 XML / JS / CSS 与本地 CSV 样例；实际游戏验收单独记录。</p><p class="dim">旧 1040 统一弹窗已被用户明确拒绝，只作同状态前后比较。中间帧暂停实际运行中的生产 CSS 过渡；没有写入伪造位移。</p><div class="controls"><label>视口<select id="viewport"></select></label><label>分类<select id="category"></select></label><label>状态<select id="state"></select></label></div><div class="box"><div id="caption" class="caption"></div><div id="stage" class="stage"></div><div id="slider" class="slider"></div><p id="scope" class="dim"></p><div id="images" class="links"></div></div><div class="box"><h2>参考合同与样例范围</h2><table><tbody id="contract"></tbody></table><p class="dim">原图来自用户会话附件；观察坐标是近似值，此页面不伪造附件原图。挑战样例采用实际 server 下一转投影规则：11 项挑战＋0 转角色的下一转 1 项；不是通常同屏显示全 21 转生目录。</p><div class="links"><a href="current/report.json">新抽屉检查</a><a href="rejected_previous/report.json">被拒绝上版</a><a href="reference_geometry.json">附件几何观察</a></div><p>当前源：<code id="current-digest"></code></p><p>旧源：<code id="before-digest"></code></p></div></main><script type="application/json" id="data">${JSON.stringify(data).replace(/</g,()=>String.fromCharCode(92)+'u003c')}</script><script>
const D=JSON.parse(document.getElementById('data').textContent),byId=id=>document.getElementById(id),labels={equipment:'装备',challenge:'挑战',other:'其他',normal:'展开完成',hover:'右侧详情',slide_partial:'实际滑入中间帧',slide_settled:'滑入完成'};
function options(id,values,title){const e=byId(id);for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=title(value);e.append(o);}return e;}
options('viewport',[...new Set(D.records.map(x=>x.width+'x'+x.height))],s=>s.replace('x',' × ')).value='1920x1080';options('category',['equipment','challenge','other'],s=>labels[s]);options('state',['normal','hover','slide_partial','slide_settled'],s=>labels[s]);
function image(src,parent){const i=document.createElement('img');i.src=src;i.alt='实际生产组件浏览器样例';parent.append(i);return i;}
function anchor(src,text){const a=document.createElement('a');a.href=src;a.textContent=text;a.target='_blank';a.rel='noopener';byId('images').append(a);}
function render(){const r=D.records.find(x=>x.width+'x'+x.height===byId('viewport').value&&x.category===byId('category').value&&x.state===byId('state').value),stage=byId('stage');stage.replaceChildren();byId('slider').replaceChildren();byId('images').replaceChildren();stage.style.aspectRatio=r.width+'/'+r.height;image(r.image,stage);byId('caption').textContent=labels[r.category]+' · '+labels[r.state]+' · '+r.width+' × '+r.height;if(r.before){const layer=document.createElement('div');layer.className='layer';image(r.before,layer);stage.append(layer);const line=document.createElement('div');line.className='line';stage.append(line);const a=document.createElement('span');a.textContent='被拒绝旧版';const input=document.createElement('input');input.type='range';input.min=0;input.max=100;input.value=0;layer.style.clipPath='inset(0 100% 0 0)';line.style.left='0%';input.setAttribute('aria-label','同状态前后对比位置');const z=document.createElement('span');z.textContent='新抽屉';byId('slider').append(a,input,z);input.oninput=()=>{layer.style.clipPath='inset(0 '+(100-input.value)+'% 0 0)';line.style.left=input.value+'%';};anchor(r.before,'打开被拒绝旧图');byId('scope').textContent='默认完整新图；拖动金线显示被拒绝旧图。同一视口／分类／状态，使用相同真实 CSV 条目和明确本地角色样例。';}else byId('scope').textContent='旧版没有真实滑入过渡；本状态仅展示新抽屉，不拿旧普通帧冒充对应动画帧。';anchor(r.image,'打开新图');}
for(const id of ['viewport','category','state'])byId(id).onchange=render;byId('current-digest').textContent=D.currentDigest;byId('before-digest').textContent=D.previousDigest;
const contract=[['主窗','1920参考下 680 × 600，左侧16；固定三行图标区。'],['图标格','四列、纯图标；只保留服务端真实动态数量。'],['顶部','生存商店标题、三个分类、关闭；独立于统一导航框架。'],['右侧详情','348宽、窗口右边22间距，左尖角；图标／名称／类型／真实价格、效果、红色操作。'],['业务样例','装备4、其他6、实际投影挑战12；无抽奖、购买、领取或支付。']];for(const row of contract){const tr=document.createElement('tr');for(const text of row){const td=document.createElement('td');td.textContent=text;tr.append(td);}byId('contract').append(tr);}render();
</script></html>`;
fs.writeFileSync(base+'/Comparison.html',html);
console.log('SHOP_DRAWER_COMPARISON '+base+'/Comparison.html states='+records.length);
