"use strict";
// Production-controller model verifies timing/input/business; screenshots verify paint.
const fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"),assert=require("node:assert/strict"),crypto=require("node:crypto");
const sourcePaths={xml:"panorama/src/layout/custom_game/survival_hud.xml",controller:"panorama/src/scripts/custom_game/shop_remaining_5d5c1152eb.js",tooltip:"panorama/src/scripts/custom_game/shop_tooltip_remaining_5d5c1152eb.js",css:"panorama/src/styles/custom_game/shop_purple.css",shell:"panorama/src/scripts/custom_game/common/purple_shell.js"};
const sources=Object.fromEntries(Object.entries(sourcePaths).map(([k,p])=>[k,fs.readFileSync(p,"utf8")]));
const report={version:"shop_standalone_d04_c25",scope:"production controller/XML with deterministic native-panel/input/timer model; no engine paint or real transactions",sourceHashes:Object.fromEntries(Object.entries(sourcePaths).map(([k,p])=>[p,crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex")])),checks:[],actualTransactions:0};
const nodes={},events={},tableEvents={},requests=[],timers=new Map(),handlers=new Map();let timerId=0,subscriptionId=0,now=0,autoState={},tooltipDefinition={};
class Panel{
 constructor(type,parent,id){this.type=type;this.paneltype=type;this.parent=parent;this.id=id||"";this.children=[];this.classes=new Set();this.style={};this.events={};this.attrs={};this.visible=true;this.enabled=true;this.hittest=true;this.hittestchildren=true;this.actuallayoutwidth=144;this.actuallayoutheight=144;this.actualuiscale_x=1;this.actualuiscale_y=1;if(parent)parent.children.push(this);if(id)nodes[id]=this;}
 AddClass(c){this.classes.add(c);}RemoveClass(c){this.classes.delete(c);}SetHasClass(c,v){v?this.AddClass(c):this.RemoveClass(c);}BHasClass(c){return this.classes.has(c);}
 SetPanelEvent(n,fn){this.events[n]=fn;}GetParent(){return this.parent;}GetChildCount(){return this.Children().length;}GetChild(i){return this.Children()[i];}Children(){return this.children.filter(p=>p.IsValid());}
 IsValid(){return !this.deleted&&(!this.parent||this.parent.IsValid());}FindChildTraverse(id){if(this.id===id)return this;for(const p of this.Children()){const found=p.FindChildTraverse(id);if(found)return found;}return null;}
 RemoveAndDeleteChildren(){this.Children().forEach(p=>p.DeleteAsync(0));this.children=[];}DeleteAsync(){this.deleted=true;for(const p of this.children)p.DeleteAsync(0);if(this.id&&nodes[this.id]===this)delete nodes[this.id];if(this.parent)this.parent.children=this.parent.children.filter(p=>p!==this);}
 SetAttributeString(k,v){this.attrs[k]=v;}GetAttributeString(k,f){return Object.hasOwn(this.attrs,k)?this.attrs[k]:f;}SetImage(v){this.image=v;}SetScaling(v){this.scaling=v;}SetAcceptsFocus(v){this.acceptsFocus=v;}SetFocus(){this.focused=true;}
 GetPositionWithinWindow(){return this.position||{x:0,y:0};}
}
const root=new Panel("Panel",null,"root");root.actuallayoutwidth=1920;root.actuallayoutheight=1080;root.position={x:0,y:0};
// Preserve actual XML parents, rather than generating disconnected fixture IDs.
const body=sources.xml.match(/<Panel\b[\s\S]*<\/root>/)?.[0]||sources.xml;
const stack=[root];for(const match of body.matchAll(/<\/?([A-Za-z][\w]*)\b([^>]*)>/g)){
 const tag=match[0],type=match[1];if(tag.startsWith("</")){if(stack.length>1&&stack.at(-1).type===type)stack.pop();continue;}
 if(["root","scripts","styles","include"].includes(type))continue;
 const attrs=Object.fromEntries([...match[2].matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));const p=new Panel(type,stack.at(-1),attrs.id);
 for(const c of (attrs.class||"").split(/\s+/))if(c)p.AddClass(c);
 for(const k of ["hittest","hittestchildren","visible","enabled"])if(k in attrs)p[k]=attrs[k]!=="false";
 if("text" in attrs)p.text=attrs.text;if("src" in attrs)p.SetImage(attrs.src);if(!tag.endsWith("/>"))stack.push(p);
}
assert(nodes.CustomShopWindow&&nodes.ShopEntryTooltip,"actual HUD XML must provide both original shop roots");
nodes.ShopEntryTooltip.actuallayoutwidth=370;nodes.ShopEntryTooltip.actuallayoutheight=320;nodes.CustomShopWindow.actuallayoutwidth=680;nodes.CustomShopWindow.actuallayoutheight=600;nodes.CustomShopWindow.position={x:16,y:240};
for(const p of new Set([nodes.ShopEntryTooltip.GetParent(),nodes.CustomShopWindow.GetParent()])){p.actuallayoutwidth=1920;p.actuallayoutheight=1080;p.position={x:0,y:0};}
function $(id){const p=nodes[String(id).replace(/^#/,"")];return p&&p.IsValid()?p:null;}
$.GetContextPanel=()=>root;$.CreatePanel=(t,p,id)=>new Panel(t,p,id);$.DispatchEvent=()=>{};$.Msg=()=>{};$.RegisterForUnhandledEvent=()=>{};$.RegisterEventHandler=(name,p,fn)=>{p.events[name]=fn;};
$.Schedule=(delay,fn)=>{timers.set(++timerId,{delay:Number(delay),due:now+Number(delay),fn});return timerId;};$.CancelScheduled=id=>timers.delete(id);
function advance(seconds){const end=now+seconds;let guard=0;for(;;){const next=[...timers].filter(([,t])=>t.due<=end+1e-9).sort((a,b)=>a[1].due-b[1].due||a[0]-b[0])[0];if(!next)break;assert(++guard<100000,"timer loop must converge");timers.delete(next[0]);now=Math.max(now,next[1].due);next[1].fn();}now=end;}
class ClockDate extends Date{constructor(...args){super(...(args.length?args:[1700000000000+Math.floor(now*1000)]));}static now(){return 1700000000000+Math.floor(now*1000);}}
const remainingCalls=[];
const cfg={SurvivalInputDispatcher:{RegisterKeyHandler:(name,fn,priority)=>handlers.set(name,{fn,priority})},RemainingHandoff:{SurvivalShopWindow(p){remainingCalls.push(p);},UpdateShopPrices(){},SurvivalShopCard(){},ShopStock:e=>Number(e.stock_max)>0?{count:Number(e.stock||0),max:Number(e.stock_max)}:Number(e.purchase_limit)>1?{count:Math.max(0,Number(e.purchase_limit)-Number(e.owned_count||0)),max:Number(e.purchase_limit)}:null}};
const env={$,Date:ClockDate,GameUI:{CustomUIConfig:()=>cfg},Game:{GetGameTime:()=>now,GetLocalPlayerID:()=>0,IsInToolsMode:()=>false},CustomNetTables:{GetTableValue:(table,key)=>table==="survival_tooltips"?tooltipDefinition:table==="survival_shop_config"?autoState:{},SubscribeNetTableListener:(name,fn)=>{tableEvents[name]=fn;return ++subscriptionId;},UnsubscribeNetTableListener:()=>{}},GameEvents:{Subscribe:(name,fn)=>{(events[name]??=[]).push(fn);return ++subscriptionId;},Unsubscribe:()=>{},SendCustomGameEventToServer:(name,payload)=>requests.push({n:name,p:payload})}};
function load(file){vm.runInNewContext(fs.readFileSync(file,"utf8"),env,{filename:file});}
function emit(name,payload){for(const fn of events[name]||[])fn(payload);}
require("../load_shared_ui_test.cjs")(env,Panel,root);load("panorama/src/scripts/custom_game/ui_layers.js");load(sourcePaths.shell);
const shell=cfg.SurvivalPurpleShell,adoptions=[],realAdopt=shell.Adopt;shell.Adopt=function(props){adoptions.push(props.id);return realAdopt(props);};
load(sourcePaths.tooltip);load(sourcePaths.controller);
const shop=cfg.SurvivalShop,tip=cfg.SurvivalShopTooltip;
const cards=()=>nodes.ShopItemList.Children().filter(p=>p.BHasClass("ShopShelfSlot"));
const purchaseCount=()=>requests.filter(r=>r.n==="ui_shop_purchase_request").length;
const count=name=>requests.filter(r=>r.n===name).length;
const descendants=p=>p.Children().flatMap(c=>[c,...descendants(c)]);
const contains=(parent,child)=>{for(let p=child;p;p=p.GetParent())if(p===parent)return true;return false;};
// Resolve final scoped shop CSS for contracts only; full-chain paint is independent.
const cssRules=[...sources.css.replace(/\/\*[\s\S]*?\*\//g,"").matchAll(/([^{}]+)\{([^{}]*)\}/g)].flatMap((m,index)=>m[1].split(",").map(selector=>({selector:selector.trim(),index,declarations:Object.fromEntries(m[2].split(";").filter(x=>x.includes(":")).map(x=>{const i=x.indexOf(":");return [x.slice(0,i).trim(),x.slice(i+1).trim()];}))})));
function matchPart(p,s){if(!p||/:/.test(s))return false;const id=s.match(/#([\w-]+)/);if(id&&p.id!==id[1])return false;for(const m of s.matchAll(/\.([\w-]+)/g))if(!p.BHasClass(m[1]))return false;const type=s.match(/^[A-Za-z][\w]*/);return !type||p.type===type[0];}
function matches(p,selector){const parts=selector.split(/\s+/).filter(x=>x!==">");if(!matchPart(p,parts.pop()))return false;while(parts.length){const part=parts.pop();p=p.GetParent();while(p&&!matchPart(p,part))p=p.GetParent();if(!p)return false;}return true;}
function style(p,key){if(p.style[key]!==undefined&&p.style[key]!=="")return p.style[key];const name=key.replace(/[A-Z]/g,m=>"-"+m.toLowerCase());let found=null;for(const r of cssRules){if(!(name in r.declarations)||!matches(p,r.selector))continue;const specificity=(r.selector.match(/#/g)||[]).length*1000+(r.selector.match(/\./g)||[]).length*10;if(!found||specificity>found.specificity||specificity===found.specificity&&r.index>=found.index)found={specificity,index:r.index,value:r.declarations[name]};}return found?.value;}
function shown(p){if(!p)return false;for(;p;p=p.GetParent())if(!p.IsValid()||p.visible===false||p.BHasClass("Hidden")||style(p,"visibility")==="collapse")return false;return true;}
function dispatchInput(p,event){if(!shown(p)||p.enabled===false||p.hittest===false)return false;for(let parent=p.GetParent();parent;parent=parent.GetParent())if(parent.hittestchildren===false)return false;if(p.events[event]){p.events[event]();return true;}return false;}
function check(name,fn){fn();report.checks.push({name,pass:true});}
let sequence=0;function snapshot(entries,mode="shop",extra={}){emit("ui_shop_snapshot",{sequence:++sequence,full:1,ui_mode:mode,entries,categories:[],resources:{gold:300,wood:500},...extra});}
const weapon={entry_id:"real_sword",shop_id:"weapon",content_id:"weapon_growth_sword_01",content_type:"weapon",name:"成长之剑",description:"测试用装备效果",icon:"item_broadsword",visible:1,purchasable:1,gold_cost:100,wood_cost:0,purchase_limit:5,owned_count:2};
const locked={...weapon,entry_id:"locked_sword",name:"加速手套",purchasable:0,disabled_reason:"金币不足"};
const book={...weapon,entry_id:"shop_item_knowledge_book",shop_id:"item",content_id:"item_knowledge_book",content_type:"item",name:"知识之书",gold_cost:50000,stock_max:99,stock:2};
const originalRows=JSON.stringify([weapon,locked,book]);
try{
check("locked open preserves unlock authority",()=>{shop.Open();assert.equal(requests.length,0);shop.SetUnlocks({shop:true});shop.Open();assert.equal(requests.at(-1).n,"ui_shop_open_request");assert.equal(cfg.SurvivalUILayers.Top(),"shop");});
check("standalone shell and three actual tabs",()=>{
 assert.equal(style(nodes.CustomShopWindow,"width"),"680px");assert.equal(style(nodes.CustomShopWindow,"height"),"600px");assert.equal(style(nodes.CustomShopWindow,"horizontalAlign"),"left");assert.equal(style(nodes.CustomShopWindow,"verticalAlign"),"top");assert.equal(parseFloat(style(nodes.CustomShopWindow,"position")),16);
 assert.equal(style(nodes.CustomShopWindow,"margin"),"0px");assert.equal(style(nodes.CustomShopWindow,"backgroundColor"),"gradient(linear,0% 0%,100% 100%,from(#2e243d),to(#21182f))");assert.equal(remainingCalls.length,0,"old Reference window cannot override independent geometry");assert(!nodes.CustomShopWindow.BHasClass("PurpleShell"));assert.equal(adoptions.length,0);assert(!descendants(nodes.CustomShopWindow).some(p=>p.BHasClass("PurpleChrome")));assert(!shell.Entries.some(e=>e.id==="shop"));
 assert(shown(nodes.ShopTitle));assert.equal(nodes.ShopTitle.text,"生存商店");assert(shown(nodes.ShopCloseButton));assert(nodes.ShopModeOther);
 assert.equal(style(nodes.ShopHeader,"height"),"138px");assert(parseFloat(style(nodes.ShopModeToggles,"position").split(" ")[1])+parseFloat(style(nodes.ShopModeToggles,"height"))<=parseFloat(style(nodes.ShopHeader,"height")),"header owns complete tab bounds");assert(nodes.ShopTitleDivider&&nodes.ShopTitleDivider.GetParent()===nodes.ShopHeader);assert.equal(style(nodes.ShopTitleDivider,"position"),"0px 74px 0px");assert.equal(style(nodes.ShopTitleDivider,"height"),"1px");assert.equal(nodes.ShopHeader.style.borderBottom,"0px");
 const foreign=new Panel("Panel",root,"ShopTestCommerceShell");const adoption=realAdopt({id:"commerce",panel:foreign,width:1280,height:800});assert(!descendants(foreign).some(p=>p.BHasClass("PurpleTabName")&&p.text==="生存商店"),"shared navigation no longer offers survival shop");adoption.Dispose();foreign.DeleteAsync(0);assert.equal(requests.filter(r=>r.n!=="ui_shop_open_request").length,0);
});
snapshot([weapon,locked,book]);
check("fixed viewport and real category/count without captions or filler",()=>{
 assert.equal(cards().length,2);assert.equal(cards()[0].__survivalStockLabel.text,"3/5");assert.equal(cards()[0].__survivalStockLabel.visible,false,"native visible property must not override stylesheet collapse");assert(!cards().some(c=>descendants(c).some(p=>p.BHasClass("ShopCardName")&&shown(p))),"reference cells show only item icons");assert.equal(style(nodes.CustomShopWindow,"height"),"600px");
 const initialBody=style(nodes.ShopBody,"height");const realRows=Array.from({length:21},(_,i)=>({...weapon,entry_id:"pressure_"+i}));snapshot(realRows);assert.equal(cards().length,21,"no filler");assert.equal(style(nodes.CustomShopWindow,"height"),"600px");assert.equal(style(nodes.ShopBody,"height"),initialBody,"records cannot resize the fixed viewport");assert.equal(style(nodes.ShopItemList,"flowChildren"),"right-wrap");assert.equal(style(nodes.ShopItemList,"overflow"),"squish scroll");
 const cell=cards()[0],bodyWidth=parseFloat(style(nodes.ShopBody,"width")),bodyHeight=parseFloat(initialBody),cellWidth=parseFloat(style(cell,"width")),cellHeight=parseFloat(style(cell,"height")),margin=String(style(cell,"margin")).split(" ").map(parseFloat);assert.equal(Math.floor(bodyWidth/(cellWidth+margin[1])),4);assert.equal(Math.floor(bodyHeight/(cellHeight+margin[2])),3);assert.equal(style(cell,"padding"),"0px");assert.equal(style(cell,"border"),"0px");assert(cards().every(c=>!descendants(c).some(p=>(p.BHasClass("ShopCardName")||p.BHasClass("ShopStockLabel")||p.BHasClass("AutoBookButton"))&&shown(p))));report.fixedViewport={width:680,height:600,bodyWidth,bodyHeight,cellWidth,cellHeight,margin,columns:4,rows:3,stressRows:21};snapshot([weapon,locked,book]);
});
let tile=cards()[0];tile.position={x:400,y:300};
check("reference tooltip type/nonzero cost/effect use actual XML hierarchy",()=>{
 const before=purchaseCount();dispatchInput(tile,"onmouseover");advance(.04);assert(shown(nodes.ShopEntryTooltip));assert.equal(nodes.ShopTooltipTitle.text,weapon.name);assert(shown(nodes.ShopTooltipType));assert.equal(nodes.ShopTooltipType.text,"装备");assert.equal(nodes.ShopTooltipGoldCost.text,"100");assert(nodes.ShopTooltipGoldCost.GetParent().visible);assert.equal(nodes.ShopTooltipWoodCost.GetParent().visible,false);
 assert(contains(nodes.ShopTooltipTitleBlock,nodes.ShopTooltipCostRow),"cost belongs to title/type header");assert(contains(nodes.ShopTooltipTitleBlock,nodes.ShopTooltipType));assert(nodes.ShopTooltipArrow&&shown(nodes.ShopTooltipArrow));assert(nodes.ShopTooltipEffectHeading&&shown(nodes.ShopTooltipEffectHeading));assert.equal(style(nodes.ShopEntryTooltip,"width"),"370px");assert.equal(purchaseCount(),before,"hover never purchases");
 const button=nodes.ShopTooltipPurchase;assert(shown(button));assert.equal(button.GetChild(0).text,"购买");const fill=String(style(button,"backgroundColor"));assert(/#(?:8|9|a|b|c)[0-9a-f]{5}/i.test(fill),"purchase retains red surface");
 const cornerPositions={TL:"22px 0px 0px",TR:"-2px 0px 0px",BL:"22px -2px 0px",BR:"-2px -2px 0px"};const tooltipCorners=nodes.ShopEntryTooltip.Children().filter(p=>p.BHasClass("ShopFrameCorner"));assert.equal(tooltipCorners.length,4);for(const [key,value]of Object.entries(cornerPositions))assert.equal(style(tooltipCorners.find(p=>p.BHasClass("ShopFrameCorner"+key)),"position"),value);const windowCorner=nodes.CustomShopWindow.Children().find(p=>p.BHasClass("ShopFrameCornerTL"));assert.equal(style(windowCorner,"position"),"-5px -5px 0px","tooltip gutter cannot alter window corners");
});
check("transparent root owns gutter/arrow/corners and inset frame owns actual content/actions",()=>{
 const outer=nodes.ShopEntryTooltip,frame=nodes.ShopTooltipFrame;assert(frame&&frame.GetParent()===outer);assert.equal(style(outer,"width"),"370px");assert.equal(style(outer,"padding"),"0px");assert.equal(style(outer,"backgroundColor"),"transparent");assert.equal(style(outer,"border"),"0px");assert.equal(style(frame,"width"),"348px");assert.equal(style(frame,"margin"),"0px 0px 0px 22px");assert.equal(style(frame,"padding"),"20px");assert.equal(style(frame,"height"),"fit-children");assert(String(style(frame,"backgroundColor")).includes("from(#282036)"));
 for(const id of ["ShopTooltipHeader","ShopTooltipIconHost","ShopTooltipTitle","ShopTooltipType","ShopTooltipCostRow","ShopTooltipEffectHeading","ShopTooltipDescription","ShopTooltipCondition","ShopTooltipOwned","ShopTooltipFields","ShopTooltipStatus","ShopTooltipPurchase","ShopTooltipAutoPurchase"])assert(contains(frame,nodes[id]),id+" belongs to the inner frame");assert.equal(nodes.ShopTooltipPurchase.GetParent(),frame);assert.equal(nodes.ShopTooltipAutoPurchase.GetParent(),frame);assert.equal(nodes.ShopTooltipArrow.GetParent(),outer);assert(!contains(frame,nodes.ShopTooltipArrow));assert.equal(parseFloat(nodes.ShopTooltipArrow.style.position),6);
 const [left]=outer.style.position.split(" ").map(parseFloat);assert.equal(left,16+680,"root starts at the shop edge; the 22px frame inset supplies the only gap");assert.equal(parseFloat(style(frame,"width"))+22,parseFloat(style(outer,"width")));assert.equal(outer.Children().filter(p=>p.BHasClass("ShopFrameCorner")).length,4);assert.equal(frame.Children().filter(p=>p.BHasClass("ShopFrameCorner")).length,0);assert.equal(nodes.ShopTooltipDescription.hittest,true,"real description can receive scroll input");report.tooltipStructure={rootWidth:370,rootPadding:0,frameWidth:348,frameInset:22,framePadding:20,rootLeft:left,frameLeft:left+22,arrowX:6,contentAndActionsInFrame:true,arrowAndCornersInRoot:true,paintVerified:false};
});
check("hover gap, pin and latest authoritative purchase guard",()=>{
 dispatchInput(tile,"onmouseout");dispatchInput(nodes.ShopEntryTooltip,"onmouseover");advance(.2);assert(shown(nodes.ShopEntryTooltip));assert(dispatchInput(nodes.ShopTooltipPurchase,"onactivate"));assert.equal(purchaseCount(),1);assert.equal(requests.at(-1).p.entry_id,weapon.entry_id);
 dispatchInput(nodes.ShopEntryTooltip,"onmouseout");advance(.2);assert(!shown(nodes.ShopEntryTooltip));dispatchInput(tile,"onactivate");dispatchInput(tile,"onmouseout");advance(.2);assert(tip.Inspect().pinned);assert(shown(nodes.ShopEntryTooltip));assert.equal(purchaseCount(),1);
 snapshot([{...weapon,purchasable:0,disabled_reason:"已购买至上限"},locked,book]);assert.equal(nodes.ShopTooltipPurchase.enabled,false);nodes.ShopTooltipPurchase.events.onactivate();assert.equal(purchaseCount(),1);tile.events.oncontextmenu();assert.equal(purchaseCount(),1,"right click preserves authoritative guard");
});
check("tooltip positions are bounded at viewport edges",()=>{
 const restored={...weapon,purchasable:1,description:"对目标造成冰霜伤害并降低其移动速度"};snapshot([restored,locked,book]);tile=cards()[0];tile.position={x:1780,y:1020};tile.actuallayoutwidth=144;tile.actuallayoutheight=144;dispatchInput(tile,"onmouseover");advance(.04);const [x,y]=nodes.ShopEntryTooltip.style.position.split(" ").map(parseFloat);assert(x>=12&&x+370<=1920-12);assert(y>=12&&y+320<=1080-12);assert.equal(nodes.ShopTooltipDescription.text,restored.description);report.tooltipEdge={x,y,width:370,height:320};
});
check("auto-book real event, canonical IDs and live net-table state",()=>{
 shop.SelectOther();assert.equal(nodes.ShopTitle.text,"生存商店","Other changes actual category while preserving reference shop title");assert.equal(cards().length,1);assert.equal(cards()[0].GetAttributeString("entry_id"),book.entry_id);assert(nodes.ShopModeOther.BHasClass("Selected"));dispatchInput(cards()[0],"onmouseover");assert(nodes.ShopTooltipAutoPurchase.visible);dispatchInput(nodes.ShopTooltipAutoPurchase,"onactivate");assert.equal(requests.at(-1).n,"ui_shop_auto_purchase_toggle_request");assert.equal(requests.at(-1).p.entry_id,book.entry_id);
 autoState={[book.entry_id]:1};tableEvents.survival_shop_config?.("", "auto_purchase_0",autoState);tip.UpdateAutoPurchaseState();assert(nodes.ShopTooltipAutoPurchase.BHasClass("AutoBookEnabled"));const before=requests.length;shop.ToggleAutoPurchaseEntry("forged_book");assert.equal(requests.length,before);
 const moreBooks=Array.from({length:6},(_,i)=>({...book,entry_id:i?"other_"+i:book.entry_id}));snapshot([weapon,...moreBooks]);assert.equal(cards().length,6);assert.equal(style(nodes.CustomShopWindow,"height"),"600px");
});
check("stale snapshots/delta retain identity and update purchased stock",()=>{
 shop.SelectShop();snapshot([{...weapon,purchase_limit:1,owned_count:0}]);const original=cards()[0],seq=sequence;emit("ui_shop_snapshot",{sequence:seq,full:1,ui_mode:"shop",entries:[],resources:{gold:999}});assert.strictEqual(cards()[0],original);
 emit("ui_shop_snapshot",{sequence:++sequence,base_sequence:seq,full:0,ui_mode:"shop",categories:[],changed_entries:[{...weapon,purchase_limit:1,owned_count:1,purchasable:0,disabled_reason_code:"purchase_limit_reached"}]});assert.strictEqual(cards()[0],original);assert(original.BHasClass("StockEmpty"));assert(!original.__survivalStockLabel,"single-use item has no redundant stock count");
});
check("stock empty differs from resource shortage/unlimited items",()=>{
 const cases=[[{...weapon,stock:0,stock_max:5,purchasable:0},true,"0/5"],[{...weapon,stock:1,stock_max:5,purchasable:0,disabled_reason_code:"insufficient_gold"},false,"1/5"],[{...weapon,stock:0,stock_max:0,purchase_limit:5,owned_count:5,purchasable:0},true,"0/5"],[{...weapon,stock:0,stock_max:0,purchase_limit:0},false,null]];
 for(const [row,empty,text] of cases){snapshot([row]);assert.equal(cards()[0].BHasClass("StockEmpty"),empty);if(text){assert.equal(cards()[0].__survivalStockLabel.text,text);assert.equal(cards()[0].__survivalStockLabel.visible,false,"each authoritative update keeps stock label hidden while text stays correct");}else assert(!cards()[0].__survivalStockLabel);}
 const repeat={...weapon,stock:0,stock_max:0,purchase_limit:5,owned_count:2};snapshot([repeat]);const sameCard=cards()[0],sameLabel=sameCard.__survivalStockLabel;assert.equal(sameLabel.text,"3/5");snapshot([{...repeat,owned_count:3}]);assert.strictEqual(cards()[0],sameCard,"owned-count-only refresh retains the actual production card");assert.strictEqual(cards()[0].__survivalStockLabel,sameLabel);assert.equal(sameLabel.text,"2/5");assert.equal(sameLabel.visible,false,"in-place authoritative update does not revive the same stock label");
 for(const content_id of ["weapon_growth_sword_01","item_death_mask","item_small_polar_crystal"]){snapshot([{...weapon,content_id,purchase_limit:1,owned_count:0}]);assert(!cards()[0].BHasClass("StockEmpty"));snapshot([{...weapon,content_id,purchase_limit:1,owned_count:1,purchasable:0,disabled_reason_code:"purchase_limit_reached"}]);assert(cards()[0].BHasClass("StockEmpty"));snapshot([{...weapon,content_id,purchase_limit:1,owned_count:0,purchasable:0,disabled_reason_code:"insufficient_gold"}]);assert(!cards()[0].BHasClass("StockEmpty"));}
});
check("early-final radial cooldown blocks purchase and refreshes once",()=>{
 const start=now,early={...weapon,entry_id:"early",content_id:"service_early_final_boss",early_final_cooldown_remaining:.6,early_final_cooldown_total:.6,early_final_cooldown_until:start+.6};shop.SelectOther();snapshot([early]);const card=cards()[0],mask=card.__survivalCooldownMask;assert(mask.visible);assert(mask.style.clip.includes("360.00deg"));assert.equal(mask.hittestchildren,false);const before=purchaseCount();card.events.oncontextmenu();assert.equal(purchaseCount(),before);advance(.3);assert(mask.style.clip.includes("180.00deg"));const opens=count("ui_shop_open_request");advance(.31);assert.equal(mask.visible,false);assert.equal(count("ui_shop_open_request"),opens+1);advance(.1);assert.equal(count("ui_shop_open_request"),opens+1);card.events.oncontextmenu();assert.equal(purchaseCount(),before+1);
});
check("research aliases/prerequisites/in-flight guards and remembered tab",()=>{
 shop.OpenResearch(123);assert.equal(nodes.ShopTitle.text,"科技","normal research keeps its original title");const technology={...weapon,entry_id:"tech_attack",content_id:"technology_attack",content_type:"technology",prerequisite_met:1,purchasable:0,disabled_reason_code:"insufficient_gold",purchase_entry_id:"tech_attack_next"};snapshot([technology],"research");assert.equal(nodes.ShopTitle.text,"科技");const before=purchaseCount();cards()[0].events.onactivate();assert.equal(purchaseCount(),before+1);assert.equal(requests.at(-1).p.source_entindex,123);assert.equal(requests.at(-1).p.entry_id,"tech_attack_next");cards()[0].events.onactivate();assert.equal(purchaseCount(),before+1);
 emit("ui_operation_result",{operation:"shop_purchase",success:0,error:"fixture"});snapshot([{...technology,prerequisite_met:0,purchasable:1}],"research");cards()[0].events.onactivate();assert.equal(purchaseCount(),before+1);assert(cards()[0].BHasClass("PrerequisiteLocked"));snapshot([{...technology,completed:1}],"research");assert.equal(cards().length,0);
 const auto={...technology,entry_id:"advanced_auto",auto_research_available:1,technology_group:"attack",prerequisite_met:1};snapshot([auto],"research",{research_scope:"advanced"});assert.equal(nodes.ShopTitle.text,"高级研究","advanced research keeps its original title");cards()[0].events.oncontextmenu();assert.equal(requests.at(-1).n,"ui_shop_auto_research_toggle_request");assert.equal(requests.at(-1).p.source_entindex,123);assert.equal(requests.at(-1).p.technology_group,"attack");
 shop.OpenChallenge();assert.equal(nodes.ShopTitle.text,"生存商店","challenge keeps reference title while request mode is challenge");assert(nodes.ShopModeChallenge.BHasClass("Selected"));shop.Close();shop.ToggleShop();assert.equal(nodes.ShopTitle.text,"生存商店","reopening remembered challenge keeps title");assert.equal(requests.at(-1).p.mode,"challenge");shop.SelectShop();assert.equal(nodes.ShopTitle.text,"生存商店");assert.equal(requests.at(-1).p.mode,"shop");shop.OpenResearch(123);shop.Close();shop.Open();assert.equal(nodes.ShopTitle.text,"生存商店");assert.equal(requests.at(-1).p.mode,"shop","research cannot replace remembered shop tab");report.titleContract={equipment:"生存商店",other:"生存商店",challenge:"生存商店",rememberedChallenge:"生存商店",research:"科技",advancedResearch:"高级研究",businessModesUnchanged:true};
});
check("left position slide persists and stale exit cannot hide reopen",()=>{
 shop.SelectShop();snapshot([weapon]);tile=cards()[0];dispatchInput(tile,"onmouseover");advance(.04);const previousAction=nodes.ShopTooltipPurchase.events.onactivate,before=purchaseCount();assert.equal(parseFloat(style(nodes.CustomShopWindow,"position")),16);shop.Close();const exitPosition=parseFloat(style(nodes.CustomShopWindow,"position"));assert(exitPosition<0);assert(!shown(nodes.ShopEntryTooltip));assert.equal(nodes.ShopEntryTooltip.hittest,false);assert.equal(nodes.ShopEntryTooltip.hittestchildren,false);assert.equal(nodes.CustomShopWindow.hittest,false);assert.equal(nodes.CustomShopWindow.hittestchildren,false);assert.equal(cfg.SurvivalUILayers.Top(),null);
 assert.equal(nodes.CustomShopWindow.visible,true,"visible while sliding out");assert.equal(dispatchInput(tile,"oncontextmenu"),false);assert.equal(dispatchInput(nodes.ShopTooltipPurchase,"onactivate"),false);previousAction();assert.equal(purchaseCount(),before,"old detail action after close cannot trade");advance(.25);assert.equal(nodes.CustomShopWindow.visible,true,".25s is inside .28s exit");snapshot([weapon]);assert.equal(parseFloat(style(nodes.CustomShopWindow,"position")),exitPosition,"authoritative data during exit cannot reset position");advance(.03);assert.equal(nodes.CustomShopWindow.visible,true,"the .28s transition completes before the .29s hide");
 const staleClose=[...timers.values()].filter(t=>t.delay===.29).map(t=>t.fn);assert(staleClose.length>0,"exercise a real scheduled exit, rather than an empty callback list");shop.Open();const openPosition=style(nodes.CustomShopWindow,"position");for(const fn of staleClose)fn();advance(.35);assert.equal(nodes.CustomShopWindow.visible,true);assert.equal(style(nodes.CustomShopWindow,"position"),openPosition);assert.strictEqual(cards()[0],tile,"reopen preserves source-card identity when authoritative structure is unchanged");assert.equal(nodes.CustomShopWindow.hittestchildren,true);assert.equal(cfg.SurvivalUILayers.Top(),"shop");assert.equal(purchaseCount(),before);
 shop.Close();advance(.3);assert.equal(nodes.CustomShopWindow.visible,false);assert.equal(nodes.CustomShopWindow.hittestchildren,false);assert(parseFloat(style(nodes.CustomShopWindow,"position"))<0);const pending=timers.size;shop.Close();assert.equal(nodes.CustomShopWindow.visible,false,"idempotent close cannot revive an already-hidden panel");assert.equal(timers.size,pending,"idempotent close cannot schedule a new visual exit");advance(.3);assert.equal(nodes.CustomShopWindow.visible,false);
 report.animation={transitionDuration:style(nodes.CustomShopWindow,"transitionDuration"),exitPosition,visibleAtSeconds:.25,hiddenAfterSeconds:.3,staleCallbacksExecuted:staleClose.length};assert(/(?:^|\s|,)\.?28s(?:$|\s|,)/.test(String(style(nodes.CustomShopWindow,"transitionDuration"))),"position transition is .28s");assert(String(style(nodes.CustomShopWindow,"transitionProperty")).includes("position"));
});
check("ESC/Cancelled consume one close and immediately cancel input",()=>{
 shop.Open();snapshot([weapon]);dispatchInput(cards()[0],"onmouseover");advance(.04);const closes=count("ui_shop_close_request"),before=purchaseCount();assert(handlers.get("modal_escape"));assert.equal(handlers.get("modal_escape").fn("ESC",true),true);assert.equal(count("ui_shop_close_request"),closes+1);assert.equal(nodes.CustomShopWindow.hittestchildren,false);assert(!shown(nodes.ShopEntryTooltip));nodes.CustomShopWindow.events.Cancelled?.();assert.equal(count("ui_shop_close_request"),closes+1,"duplicate Cancelled does not close twice");handlers.get("modal_escape").fn("ESC",false);advance(.3);assert.equal(nodes.CustomShopWindow.visible,false);assert.equal(purchaseCount(),before);
 shop.Open();assert.equal(nodes.CustomShopWindow.events.Cancelled(),true);assert.equal(nodes.CustomShopWindow.hittestchildren,false);advance(.3);assert.equal(nodes.CustomShopWindow.visible,false);assert.equal(cfg.SurvivalUILayers.Top(),null);
});
check("Fit scale and full left exit work across four viewport aspect ratios",()=>{
 const rows=[];for(const [w,h]of [[1280,720],[1920,1080],[2560,1440],[2560,1080]]){root.actuallayoutwidth=w;root.actuallayoutheight=h;const scale=Math.min(w/1920,h/1080);shop.Open();assert.equal(style(nodes.CustomShopWindow,"width"),"680px");assert.equal(style(nodes.CustomShopWindow,"height"),"600px");assert.equal(parseFloat(style(nodes.CustomShopWindow,"position")),16);assert(String(style(nodes.CustomShopWindow,"transform")).includes("scale3d"));shop.Close();const x=parseFloat(style(nodes.CustomShopWindow,"position"));assert(x+680*scale<=-12,"entire scaled drawer exits the screen, including rounded coordinates");advance(.25);assert(nodes.CustomShopWindow.visible);assert.equal(nodes.CustomShopWindow.hittestchildren,false);advance(.05);assert.equal(nodes.CustomShopWindow.visible,false);rows.push({viewport:[w,h],scale,exitX:x,right:x+680*scale});}root.actuallayoutwidth=1920;root.actuallayoutheight=1080;report.scaledExitModel=rows;
});
check("zero/dual costs and effect fallback reset without buying or mutating rows",()=>{
 shop.Open();const before=purchaseCount();tooltipDefinition={name:"配置名",desc:"配置中的商品效果",needgold:10,needwood:25};tip.Show({entry_id:"fallback",name:"fallback"});assert.equal(nodes.ShopTooltipGoldCost.text,"10");assert.equal(nodes.ShopTooltipWoodCost.text,"25");assert.equal(nodes.ShopTooltipDescription.text,"配置中的商品效果");assert(nodes.ShopEntryTooltip.BHasClass("ShopTooltipDualCost"));assert.equal(style(nodes.ShopTooltipHeader,"height"),"140px");assert.equal(style(nodes.ShopTooltipCostRow,"height"),"64px");assert.equal(style(nodes.ShopTooltipCostRow,"flowChildren"),"down");
 for(const [content_type,type]of [["weapon","装备"],["equipment","装备"],["item","道具"],["challenge","挑战"],["rebirth","转职"],["technology","科技"],["service","其他"]]){const row={entry_id:"typed_"+content_type,name:"真实类别测试",content_type,description:"测试效果",gold_cost:100,wood_cost:0,purchasable:1},saved=JSON.stringify(row);tip.Show(row);assert.equal(nodes.ShopTooltipType.text,type);assert(shown(nodes.ShopTooltipType));assert.equal(JSON.stringify(row),saved);}
 tooltipDefinition={};tip.Show({entry_id:"free",name:"免费",content_type:"item",gold_cost:0,wood_cost:0,purchasable:1});assert(!nodes.ShopTooltipGoldCost.GetParent().visible&&!nodes.ShopTooltipWoodCost.GetParent().visible);assert(!nodes.ShopEntryTooltip.BHasClass("ShopTooltipDualCost"));assert.equal(style(nodes.ShopTooltipHeader,"height"),"108px");assert.equal(style(nodes.ShopTooltipCostRow,"height"),"32px");assert.equal(nodes.ShopTooltipDescription.text,"");assert.equal(nodes.ShopTooltipDescription.visible,false);assert.equal(nodes.ShopTooltipEffectHeading.visible,false);tip.Hide();assert.equal(purchaseCount(),before);assert.equal(JSON.stringify([weapon,locked,book]),originalRows);shop.Close();advance(.3);
});
check("deleted panel cannot receive delayed placement or exit input",()=>{
 shop.Open();snapshot([weapon]);const source=cards()[0];dispatchInput(source,"onmouseover");const before=purchaseCount();shop.Close();source.DeleteAsync(0);nodes.CustomShopWindow.DeleteAsync(0);advance(.35);assert.equal(purchaseCount(),before);assert.equal(dispatchInput(source,"oncontextmenu"),false);assert.equal(cfg.SurvivalUILayers.Top(),null);
});
assert.equal(remainingCalls.length,0);assert.equal(adoptions.length,0);assert(!shell.Entries.some(e=>e.id==="shop"));report.mockPurchases=purchaseCount();report.pass=true;
console.log("SHOP_STANDALONE_PASS: 680x600 left drawer, no shared navigation/adoption, fixed icon-only viewport, type/header costs/red purchase, .28s slide/.25s persistence, reopen/ESC/input cancellation, stock/cooldown/research/auto-book guards");
}catch(error){report.pass=false;report.failure=String(error.stack||error);throw error;}finally{const target="design_refs/purple_ui_10h/work/qa/shop_standalone_d04_report.json";fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,JSON.stringify(report,null,2)+"\n");}
