/* Browser-only Panorama adapter. Original production panels, scripts and events are used. */
'use strict';
window.previewErrors=[];window.previewCalls=[];window.previewMessages=[];window.previewCommands={};window.previewScriptResults=[];
window.addEventListener('error',event=>previewErrors.push({scope:'browser',message:event.message,stack:event.error&&event.error.stack}));
window.addEventListener('unhandledrejection',event=>previewErrors.push({scope:'promise',message:String(event.reason)}));
window.previewScale=innerHeight/1080;
const cfg={},nodes={},subscribers=new Map(),netSubscribers=[],netData={};
let currentContext=null,serial=0,scheduleCount=0;
function cssValue(value){return typeof value==='string'?value.replace(/file:\/\/\{images\}\/([^"')\s]+)/g,(_,rel)=>PREVIEW_ASSET_PATHS[rel]||IMAGE_ROOT+rel):value;}
function gradient(value){return String(value).replace(/gradient\(linear,\s*([\d.]+)% ([\d.]+)%,\s*([\d.]+)% ([\d.]+)%,\s*([\s\S]+)\)$/,(_,x1,y1,x2,y2,stops)=>{const angle=Math.atan2(+x2-x1,+y1-y2)*180/Math.PI;const colors=[...stops.matchAll(/(from|to|color-stop)\(([^()]*)\)/g)].map(m=>m[1]==='color-stop'?m[2].split(',').slice(1).join(',').trim()+' '+(parseFloat(m[2])*100)+'%':m[2].trim()+(m[1]==='from'?' 0%':' 100%'));return colors.length?'linear-gradient('+angle+'deg,'+colors.join(',')+')':'transparent';});}
class Panel{
 constructor(type,parent,id,element){this.type=type;this.id=id||'';this.parent=parent;this.children=[];this.events={};this.attrs={};this.deleted=false;this.html=false;this.el=element||document.createElement(/^(Image|DOTAAbilityImage|DOTAItemImage|DOTAHeroImage)$/.test(type)?'img':type==='Label'?'label':type==='TextEntry'?'input':'div');this.el.classList.add('panel');this.el.dataset.type=type;if(type==='Label')this.el.classList.add('label');if(/Button/.test(type))this.el.classList.add('button');if(parent){parent.children.push(this);parent.el.append(this.el);}if(id){nodes[id]=this;this.el.id=id;}this.enabled=true;this._style={};
  this.style=new Proxy(this._style,{set:(target,key,value)=>{target[key]=value;const s=this.el.style,v=cssValue(value);if(key==='transitionProperty'){s.transitionProperty=String(value).split(',').map(x=>x.trim()==='position'?'left,top':x.trim()).join(',');}else if(key==='position'){const xy=String(value).split(' ');s.position='absolute';s.left=xy[0];s.top=xy[1];s.setProperty('--pano-position','explicit');}else if(['horizontalAlign','verticalAlign','align'].includes(key)){if(key==='align'){const a=String(value).split(' ');s.setProperty('--pano-halign',a[0]);s.setProperty('--pano-valign',a[1]);}else s.setProperty(key==='horizontalAlign'?'--pano-halign':'--pano-valign',value);}else if(key==='flowChildren'){s.setProperty('--pano-flow',value);s.display=value==='none'?'block':'flex';s.flexDirection=value==='down'?'column':'row';s.flexWrap=value==='right-wrap'?'wrap':'nowrap';}else if(key==='ignoreParentFlow')s.setProperty('--pano-ignore-flow',String(value));else if(key==='visibility'){s.setProperty('--pano-visibility',value);s.display=value==='collapse'?'none':target.flowChildren&&target.flowChildren!=='none'?'flex':'block';}else if(key==='brightness'||key==='saturation'){s.setProperty('--pano-'+key,value);}else if((key==='width'||key==='height')&&value==='fit-children'){s[key]='max-content';s.setProperty('--pano-fit-'+key,'1');}else if(/^fill-parent-flow\([\d.]+\)$/.test(value)){s.flex=String(value).match(/[\d.]+/)[0];s.minWidth='0';s.minHeight='0';}else if(key==='backgroundColor'&&String(value).includes('gradient('))s.backgroundImage=gradient(value);else if(key==='textShadow')s.textShadow=String(value).replace(/(\d+px\s+\d+px\s+\d+px)\s+[\d.]+\s+/,'$1 ');else if(key==='textOverflow'&&value==='shrink'){s.textOverflow='ellipsis';s.overflow='hidden';}else if(key==='overflow'){s.overflow=value==='clip'?'hidden':value==='noclip'?'visible':value;s.overflowX=value==='squish scroll'?'hidden':s.overflowX;s.overflowY=value==='squish scroll'?'auto':s.overflowY;}else s[key]=v;return true;}});
 }
 AddClass(c){for(const n of String(c).split(' ').filter(Boolean))this.el.classList.add(n);}RemoveClass(c){this.el.classList.remove(c);}ToggleClass(c){this.el.classList.toggle(c);}SetHasClass(c,v){this.el.classList.toggle(c,!!v);}BHasClass(c){return this.el.classList.contains(c);}GetClasses(){return [...this.el.classList];}
 SetPanelEvent(name,fn){const event={onactivate:'click',onmouseover:'mouseenter',onmouseout:'mouseleave',oncontextmenu:'contextmenu'}[name]||name.replace(/^on/,'');if(this.events[name])this.el.removeEventListener(event,this.events[name]);const wrapped=e=>{if(name==='oncontextmenu'&&e)e.preventDefault();try{const result=fn(e);if(result===true&&e&&e.stopPropagation)e.stopPropagation();if(window.syncLayout)window.syncLayout();return result;}catch(error){previewErrors.push({scope:'event '+name,id:this.id,message:String(error),stack:error.stack});}};this.events[name]=wrapped;this.el.addEventListener(event,wrapped);}ClearPanelEvent(name){delete this.events[name];}
 SetImage(value){let rel=String(value),source=rel;const match=rel.match(/^s2r:\/\/panorama\/images\/(.+)\.vtex(?:_c)?$/);if(PREVIEW_ASSET_PATHS[rel])source=PREVIEW_ASSET_PATHS[rel];else if(match){let asset=match[1];const nativeUri='file://{images}/'+asset.replace(/_png$/,'')+'.png';if(PREVIEW_ASSET_PATHS[nativeUri]){this.el.src=PREVIEW_ASSET_PATHS[nativeUri];return;}if(/archive_gpu_(small|regular)\//.test(asset)){const key=asset.split('/').pop();const row=PREVIEW_FIXTURE.archiveIcons&&PREVIEW_FIXTURE.archiveIcons.find(x=>x.item_id===key);asset=row&&row.icon_path?row.icon_path:asset;}source=IMAGE_ROOT+asset+(asset.endsWith('.png')?'':'.png');}else if(rel.startsWith('file://{images}/')){rel=rel.slice(16);const native=rel.startsWith('items/')?rel.split('/').pop():null;if(native&&PREVIEW_FIXTURE.nativeBitmaps.includes(native))source=IMAGE_ROOT+'spellicons/survival/native/'+native;else source=PREVIEW_ASSET_PATHS[rel]||IMAGE_ROOT+rel;}this.el.src=source;this.el.onerror=()=>{if(this.el.dataset.fallback)return;this.el.dataset.fallback='1';if(source.startsWith(IMAGE_ROOT))this.el.src=IMAGE_FALLBACK_ROOT+source.slice(IMAGE_ROOT.length);};}
 SetScaling(v){this.el.style.objectFit=v==='stretch-to-fit'?'fill':'contain';}SetAcceptsFocus(){}SetFocus(){}SetInputFocus(){}SetDialogVariable(key,value){this.attrs[key]=value;}SetDialogVariableInt(key,value){this.attrs[key]=value;}SetDialogVariableFloat(key,value){this.attrs[key]=value;}
 SetAttributeString(k,v){this.attrs[k]=String(v);}GetAttributeString(k,f){return this.attrs[k]===undefined?f:this.attrs[k];}SetAttributeInt(k,v){this.attrs[k]=Number(v);}GetAttributeInt(k,f){return this.attrs[k]===undefined?f:Number(this.attrs[k]);}
 FindChildTraverse(id){if(this.id===id)return this;for(const child of this.children){const result=child.FindChildTraverse(id);if(result)return result;}return null;}FindChild(id){return this.children.find(p=>p.id===id)||null;}FindChildrenWithClassTraverse(cls){return this.children.flatMap(x=>(x.BHasClass(cls)?[x]:[]).concat(x.FindChildrenWithClassTraverse(cls)));}GetParent(){return this.parent;}GetChildCount(){return this.children.length;}GetChild(i){return this.children[i];}Children(){return this.children.filter(p=>!p.deleted);}IsValid(){return !this.deleted;}
 RemoveAndDeleteChildren(){for(const child of this.children)child.DeleteAsync(0);this.children=[];this.el.replaceChildren();}DeleteAsync(){this.deleted=true;for(const child of [...this.children])child.DeleteAsync(0);if(this.id&&nodes[this.id]===this)delete nodes[this.id];if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);this.el.remove();}SetParent(parent){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=parent;parent.children.push(this);parent.el.append(this.el);}MoveChildBefore(child,before){this.children=this.children.filter(p=>p!==child);this.children.splice(Math.max(0,this.children.indexOf(before)),0,child);this.el.insertBefore(child.el,before&&before.el);}MoveChildAfter(child,after){this.children=this.children.filter(p=>p!==child);this.children.splice(this.children.indexOf(after)+1,0,child);this.el.insertBefore(child.el,after&&after.el.nextSibling);}
 GetPositionWithinWindow(){const r=this.el.getBoundingClientRect();return {x:r.x,y:r.y};}ScrollToFit(){this.el.scrollIntoView({block:'nearest'});}ScrollToTop(){this.el.scrollTop=0;}ScrollToBottom(){this.el.scrollTop=this.el.scrollHeight;}
 get actuallayoutwidth(){return this.el.offsetWidth*previewScale;}get actuallayoutheight(){return this.el.offsetHeight*previewScale;}get actualuiscale_x(){return nativeScale(this.el,'x');}get actualuiscale_y(){return nativeScale(this.el,'y');}get actualxoffset(){return this.el.getBoundingClientRect().x;}get actualyoffset(){return this.el.getBoundingClientRect().y;}get paneltype(){return this.type;}get layoutfile(){return this.attrs.layoutfile||'';}
 get paneltype(){return this.type;}set text(v){if(this.type==='TextEntry')this.el.value=String(v);else if(this.html)this.el.innerHTML=String(v).replace(/<font color="([^\"]+)"/g,'<span style="color:$1"').replaceAll('</font>','</span>');else this.el.textContent=String(v===undefined?'':v);}get text(){return this.el.textContent;}set visible(v){this.el.hidden=!v;}get visible(){return !this.el.hidden;}set enabled(v){this._enabled=v;this.SetHasClass('UIDisabled',v===false);}get enabled(){return this._enabled;}set checked(v){this.SetHasClass('Selected',!!v);}get checked(){return this.BHasClass('Selected');}set hittest(v){this._hit=v;if(this.type==='Label'||/Image/.test(this.type))this.el.style.pointerEvents=v?'auto':'none';else this.el.style.pointerEvents=v?'auto':'none';}get hittest(){return this._hit!==false;}set hittestchildren(v){this.attrs.hittestchildren=v;this.el.classList.toggle('PreviewNoHitChildren',v===false);}get hittestchildren(){return this.attrs.hittestchildren!==false;}
 set abilityname(v){this._ability=v;const name=String(v).replace(/^ability_/,'');this.SetImage(PREVIEW_FIXTURE.nativeBitmaps.includes(name+'.png')?'file://{images}/spellicons/survival/native/'+name+'.png':'file://{images}/spellicons/'+name+'.png');}get abilityname(){return this._ability;}set itemname(v){this._item=v;this.SetImage('file://{images}/spellicons/survival/native/'+String(v).replace(/^item_/,'')+'.png');}get itemname(){return this._item;}set heroname(v){this.SetImage('file://{images}/spellicons/survival/native/portrait_'+String(v).replace(/^npc_dota_hero_/,'')+'.png');}
 BLoadLayout(source){const rel=String(source).replace(/^file:\/\/\{resources\}\//,'');const xml=PREVIEW_SOURCES&&PREVIEW_SOURCES[rel];if(xml){parseXml(xml,this);return true;}this.AddClass('PreviewNativeStandin');return false;}BLoadLayoutSnippet(){return false;}SetScenePanelToLocalHero(){}SetCamera(){}SetUnit(){}SetAttribute(){return this;}
}
function nativeScale(element,axis){let scale=previewScale;for(let node=element;node&&node.id!=='PreviewRoot';node=node.parentElement){const transform=getComputedStyle(node).transform;if(transform&&transform!=='none'){const matrix=new DOMMatrix(transform);scale*=axis==='x'?Math.hypot(matrix.a,matrix.b):Math.hypot(matrix.c,matrix.d);}}return scale;}
const root=new Panel('Panel',null,'PreviewRoot',document.getElementById('PreviewRoot'));root.style.width=(innerWidth/previewScale)+'px';root.style.height='1080px';root.style.transform='scale3d('+previewScale+','+previewScale+',1)';
function $(selector){return selector&&selector[0]==='#'?nodes[selector.slice(1)]||null:currentContext?currentContext.FindChildTraverse(String(selector)):nodes[selector]||null;}
$.GetContextPanel=()=>currentContext||root;$.CreatePanel=(type,parent,id)=>new Panel(type,parent||currentContext||root,id);$.Schedule=(seconds,fn)=>{const context=currentContext;if(++scheduleCount>30000)return 0;return setTimeout(()=>{const previous=currentContext;currentContext=context;try{fn();}catch(error){previewErrors.push({scope:'scheduled',message:String(error),stack:error.stack});}finally{currentContext=previous;}},Math.max(0,seconds*1000));};$.CancelScheduled=id=>clearTimeout(id);$.Msg=(...args)=>previewMessages.push(args.map(String).join(' '));$.Localize=s=>s;$.RegisterEventHandler=()=>1;$.RegisterForUnhandledEvent=()=>1;$.UnregisterEventHandler=()=>{};$.DispatchEvent=(name,node,...args)=>{if(name==='Activated'&&node&&node.events.onactivate)return node.events.onactivate();if(name==='DOTAShowTextTooltip')window.previewNativeTooltip=args[0];return true;};$.GetKeybindForCommand=()=>'';
function stub(values={}){return new Proxy(values,{get:(t,k)=>k in t?t[k]:(()=>0)});}
const GameUI=stub({CustomUIConfig:()=>cfg,GetCursorPosition:()=>[0,0],GetScreenWidth:()=>innerWidth,GetScreenHeight:()=>innerHeight,GetCameraLookAtPosition:()=>[0,0,0],GetCameraPosition:()=>[0,0,0],WorldToScreenX:()=>-10000,WorldToScreenY:()=>-10000});
const Game=stub({GetLocalPlayerID:()=>0,GetGameTime:()=>100,GetDOTATime:()=>100,GetState:()=>10,IsInToolsMode:()=>false,AddCommand:(name,fn)=>{previewCommands[name]=fn;},GetPlayerInfo:()=>({player_name:'预览玩家',player_steamid:'PREVIEW'}),GetMapInfo:()=>({map_display_name:'浏览器组件预览'})});
const Players=stub({GetLocalPlayer:()=>0,GetPlayerHeroEntityIndex:()=>42,GetLocalPlayerPortraitUnit:()=>42,GetSelectedEntities:()=>[42],GetPlayerName:()=> '预览玩家',GetSteamAccountID:()=>0});
const Entities=stub({IsValidEntity:()=>false,GetUnitName:()=>'',GetAbsOrigin:()=>[0,0,0],GetHealth:()=>100,GetMaxHealth:()=>100,GetMana:()=>0,GetMaxMana:()=>0,GetOwner:()=>42,GetPlayerOwnerID:()=>0,GetAllEntities:()=>[]});
const Abilities=stub(),Items=stub(),Buffs=stub();
const GameEvents={Subscribe:(name,fn)=>{const id=++serial;subscribers.set(id,{name,fn,context:currentContext});return id;},Unsubscribe:id=>subscribers.delete(id),SendCustomGameEventToServer:(name,payload)=>previewCalls.push({name,payload})};
const CustomNetTables={GetTableValue:(table,key)=>netData[table]&&netData[table][key]||null,GetAllTableValues:table=>Object.entries(netData[table]||{}).map(([key,value])=>({key,value})),SubscribeNetTableListener:(table,fn)=>{netSubscribers.push({table,fn,context:currentContext});return netSubscribers.length;}};
const DotaDefaultUIElement_t=stub(),DOTA_GameState=stub(),DOTA_GameMode=stub(),DOTATeam_t=stub(),DOTA_UIMode=stub();
window.emit=(name,payload)=>{for(const sub of subscribers.values())if(sub.name===name){const previous=currentContext;currentContext=sub.context;try{sub.fn(payload);}catch(error){previewErrors.push({scope:'event '+name,message:String(error),stack:error.stack});}finally{currentContext=previous;}}};
window.emitNet=(table,key,payload)=>{(netData[table]||={})[key]=payload;for(const sub of netSubscribers)if(sub.table===table){const previous=currentContext;currentContext=sub.context;try{sub.fn(table,key,payload);}catch(error){previewErrors.push({scope:'net '+table,message:String(error),stack:error.stack});}finally{currentContext=previous;}}};
function parseXml(source,parent){const xml=new DOMParser().parseFromString(source,'application/xml');if(xml.querySelector('parsererror'))throw Error(xml.querySelector('parsererror').textContent);function create(el,target){if(['styles','scripts','snippets','include'].includes(el.tagName))return;const node=new Panel(el.tagName,target,el.getAttribute('id'));for(const a of el.attributes){const {name,value}=a;if(name==='class')node.AddClass(value);else if(name==='visible')node.visible=value!=='false';else if(name==='hittest'||name==='hittestchildren')node[name]=value!=='false';else if(name==='text')node.text=value;else if(name==='src')node.SetImage(value);else if(name==='style'){const converted=window.convertInline(value);node.el.style.cssText+=';'+converted;}else if(name.startsWith('on'))node.SetPanelEvent(name,()=>window.eval(value));else node.attrs[name]=value;}for(const child of el.children)create(child,node);return node;}for(const child of xml.documentElement.children)if(!['styles','scripts','snippets'].includes(child.tagName))create(child,parent);}
window.convertInline=value=>String(value).replace(/visibility:\s*(collapse|visible)/g,'--pano-visibility:$1').replace(/position:\s*(-?[\d.]+px)\s+(-?[\d.]+px)\s+0px/g,'position:absolute;left:$1;top:$2').replace(/flow-children:\s*none/g,'display:block;--pano-flow:none').replace(/flow-children:\s*(right-wrap|right|down)/g,(_,v)=>'display:flex;flex-direction:'+(v==='down'?'column':'row')+';flex-wrap:'+(v==='right-wrap'?'wrap':'nowrap')+';--pano-flow:'+v).replace(/horizontal-align:\s*(left|center|right)/g,'--pano-halign:$1').replace(/vertical-align:\s*(top|center|bottom)/g,'--pano-valign:$1');
const previewHitStyle=document.createElement('style');previewHitStyle.textContent='.PreviewNoHitChildren * {pointer-events:none!important}';document.head.append(previewHitStyle);
window.previewGeometryModels=['CommercePurple rectangle clip observed in native C16; browser-only clip-path simulation, not complete Panorama renderer','hittestchildren=false suppresses descendant DOM pointer targets; parent remains eligible only when hittest=true','Native transition-property:position maps to equivalent CSS left/top transitions; actual timing and values remain production-owned','VoidShadowCount text-overflow:shrink is approximated by local canvas text measurement inside the authored label width; native font rasterization remains separate'];
window.syncLayout=()=>{
 // Native C16 clips this surface even when the authored CSS says noclip.
 // Keep this explicit preview model separate from the production cascade.
 for(const surface of document.querySelectorAll('.CommercePurple'))surface.style.clipPath='inset(0px)';
 const elements=[...document.querySelectorAll('.panel')];
 for(const element of elements){
  if(element.hidden)continue;
  const computed=getComputedStyle(element),ownFlow=computed.getPropertyValue('--pano-flow').trim();
  const collapsed=computed.getPropertyValue('--pano-visibility').trim()==='collapse';
  if(collapsed){element.style.display='none';continue;}
  if(element.dataset.panoCollapsed==='1'||element.style.display==='none')element.style.display=ownFlow&&ownFlow!=='none'?'flex':'block';
  element.dataset.panoCollapsed=collapsed?'1':'0';
  const parent=element.parentElement,parentStyle=parent&&getComputedStyle(parent),flow=parentStyle&&parentStyle.getPropertyValue('--pano-flow').trim();
  const ignore=computed.getPropertyValue('--pano-ignore-flow').trim()==='true',relative=flow&&flow!=='none'&&!ignore;
  if(relative){element.style.position='relative';element.style.left='auto';element.style.top='auto';element.style.translate='none';const axis=flow==='down'?'--pano-halign':'--pano-valign',alignment=computed.getPropertyValue(axis).trim();element.style.alignSelf=alignment==='center'?'center':alignment==='right'||alignment==='bottom'?'flex-end':'flex-start';}
  else if(!element.classList.contains('UINineRow')&&!element.classList.contains('UINineTile')){
   element.style.position='absolute';
   const h=computed.getPropertyValue('--pano-halign').trim(),v=computed.getPropertyValue('--pano-valign').trim();
   if(h==='center')element.style.left='50%';else if(h==='right'){element.style.left='auto';element.style.right='0px';}
   if(v==='center')element.style.top='50%';else if(v==='bottom'){element.style.top='auto';element.style.bottom='0px';}
   element.style.translate=(h==='center'?'-50%':'0%')+' '+(v==='center'?'-50%':'0%');
  }
  const bright=computed.getPropertyValue('--pano-brightness').trim(),sat=computed.getPropertyValue('--pano-saturation').trim();
  if(bright||sat)element.style.filter='brightness('+(bright||1)+') saturate('+(sat||1)+')';
 }
 // Panorama fit-children includes positioned descendants; CSS max-content does not.
 // Only containers with absolute children need this measured emulation.
 for(const element of elements.reverse()){
  if(element.hidden||getComputedStyle(element).display==='none')continue;
  const computed=getComputedStyle(element),children=[...element.children].filter(child=>!child.hidden&&getComputedStyle(child).display!=='none');
  if(!children.length||!children.some(child=>getComputedStyle(child).position==='absolute'))continue;
  const paddingBottom=parseFloat(computed.paddingBottom)||0,paddingRight=parseFloat(computed.paddingRight)||0;
  if(computed.getPropertyValue('--pano-fit-height').trim()==='1'){
   const height=Math.max(0,...children.map(child=>child.offsetTop+child.offsetHeight+(parseFloat(getComputedStyle(child).marginBottom)||0)))+paddingBottom;
   element.style.height=height+'px';
  }
  if(computed.getPropertyValue('--pano-fit-width').trim()==='1'){
   const width=Math.max(0,...children.map(child=>child.offsetLeft+child.offsetWidth+(parseFloat(getComputedStyle(child).marginRight)||0)))+paddingRight;
   element.style.width=width+'px';
  }
 }
 // Panorama shrinks quantity labels to fit. CSS text-overflow alone cannot.
 // Keep this browser-only model scoped to the production quantity component.
 const measureCanvas=window.voidQuantityMeasureCanvas||(window.voidQuantityMeasureCanvas=document.createElement('canvas'));
 const measure=measureCanvas.getContext('2d');
 for(const element of document.querySelectorAll('.VoidShadowCount')){
  const computed=getComputedStyle(element);if(element.hidden||computed.display==='none'||computed.getPropertyValue('--pano-shrink').trim()!=='1')continue;
  const nominal=Number(element.dataset.voidNominalFontSize)||(parseFloat(computed.fontSize)||19);element.dataset.voidNominalFontSize=String(nominal);
  measure.font=computed.fontStyle+' '+computed.fontWeight+' '+nominal+'px '+computed.fontFamily;
  const textWidth=measure.measureText(element.textContent||'').width,available=Math.max(1,element.clientWidth-12);
  element.style.fontSize=Math.min(nominal,textWidth>0?nominal*available/textWidth:nominal)+'px';
 }
};
window.previewLoad=async()=>{for(const layout of PREVIEW_LAYOUTS){const context=new Panel('Panel',root,'PreviewContext_'+layout.rel.split('/').pop().replace('.xml',''));context.AddClass('PreviewContext');context.attrs.layoutfile=layout.rel;currentContext=context;parseXml(layout.xml,context);for(const rel of layout.scripts){try{if(PREVIEW_SOURCES){window.eval(PREVIEW_SOURCES[rel]+'\n//# sourceURL='+rel);previewScriptResults.push({rel,ok:true});}else{await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=PREVIEW_SOURCE_ROOT+rel;script.onload=resolve;script.onerror=()=>reject(Error('Script load failed '+rel));document.head.append(script);});previewScriptResults.push({rel,ok:true});}}catch(error){previewScriptResults.push({rel,ok:false,message:String(error)});previewErrors.push({scope:'script '+rel,message:String(error),stack:error.stack});}}}currentContext=root;syncLayout();return true;};
