'use strict';
// Reproducible presentation catalog. This never imports sample counts or writes a save.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {csv}=require('../shop_ui_12h/catalog.cjs');
const pack='design_refs/void_shadow_v1/package',work='design_refs/void_shadow_v1/work';
const layout=JSON.parse(fs.readFileSync(pack+'/layout.json','utf8'));
const catalog=csv('data/csv/存档系统/archive_shadow_items.csv').filter(x=>x.enabled==='1').map(x=>({id:x.item_id,name:x.display_name,description:x.description,quality:x.quality,icon_style:x.icon_style,max_owned:Number(x.max_owned)||undefined}));
const categories=csv('data/csv/存档系统/archive_categories.csv').map(x=>({id:x.category_id,name:x.display_name,disabled:x.enabled==='1'?0:1,sort_order:Number(x.sort_order)}));
const sha=data=>crypto.createHash('sha256').update(data).digest('hex');
const records=[];const assets={};
for(const [key,entry] of Object.entries(layout.assets)){
 if(key==='scene_reference')continue;
 const relative='images/custom_game/void_shadow_v1/'+entry.file.replace(/^assets\//,'');
 const source=pack+'/'+entry.file,bytes=fs.readFileSync(source);
 if(sha(bytes)!==entry.sha256)throw Error('Unexpected asset bytes: '+key);
 const dest='panorama/src/'+relative;fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,bytes);
 assets[key]={...entry,file:'file://{images}/'+relative.slice(7)};
 records.push({key,source,destination:dest,sha256:sha(bytes),relative});
}
const data={canvas:layout.canvas,assets,layers:layout.layers.filter(x=>x.kind==='image'?x.asset!=='scene_reference':!/^virtual_/.test(x.id)).map(x=>x.kind==='text'?{...x,text:/^(sidebar_|gold_text|purple_gem_text|ticket_text)/.test(x.id)?undefined:x.text}:x),items:layout.items.map((x,i)=>({id:catalog[i]?catalog[i].id:x.id,icon_asset:x.icon_asset,icon_bbox:x.icon_bbox,quantity_bbox:x.quantity_bbox,name_bbox:x.name_bbox})),catalog,categories};
const generated='panorama/src/scripts/custom_game/archive_void_v1_data.js';
fs.writeFileSync(generated,'// Generated by tools/void_shadow_v1/import.cjs from package geometry and project CSV. No preview counts.\n(function(){GameUI.CustomUIConfig().ArchiveVoidV1Data='+JSON.stringify(data)+';})();\n');
const assetLayout='panorama/src/layout/custom_game/archive_void_v1_assets.xml';
fs.writeFileSync(assetLayout,'<root><Panel hittest="false" hittestchildren="false">\n'+Object.values(assets).map(x=>'  <Image src="'+x.file+'" visible="false" style="visibility:collapse; width:0px; height:0px;" />').join('\n')+'\n</Panel></root>\n');
fs.mkdirSync(work,{recursive:true});
fs.writeFileSync(work+'/import.json',JSON.stringify({at:new Date().toISOString(),records,catalogSource:'data/csv/存档系统/archive_shadow_items.csv',categoriesSource:'data/csv/存档系统/archive_categories.csv',mapping:'Ordered shadow_NN ↔ virtual_NN; geometry only, no preview names/counts/caps',font:'Reuses already registered byte-identical Radiance-Survival-SourceHanSansSC-Regular.otf',excluded:['reference/**','assets/backgrounds/scene_exterior_reference.png','data_preview.json']},null,2));
fs.writeFileSync(work+'/compile_scope.json',JSON.stringify(records.map(x=>x.relative).concat(['scripts/custom_game/archive_void_v1_data.js','scripts/custom_game/archive_void_v1.js','styles/custom_game/archive_void_v1.css','scripts/custom_game/archive_180de7e38b_titles_compact_v6.js','layout/custom_game/archive_void_v1_assets.xml','layout/custom_game/archive.xml']),null,2));
console.log('VOID_IMPORT '+records.length+' assets; '+catalog.length+' configured items.');
