import csv,json
from pathlib import Path
r=Path.cwd(); out=r/'art/ui/development/archive_polish_v1'
rows=[x for x in csv.DictReader((r/'data/csv/存档系统/archive_work_items.csv').open(encoding='utf-8-sig')) if not x['item_id'].startswith('#')]
concepts=[('老板凝视','an ornate vigilant golden eye above a small jade office seal'),('996','an elegant jade and ivory clock with three small gilded gears'),('继续努力','a rising teal banner and golden laurel with a small upward arrow'),('不要猝死','a warm glowing protective heart cradled by an ivory shield'),('老板买车','a miniature elegant jade and gold automobile'),('带薪拉屎','a whimsical immaculate ivory toilet with gold trim and a small gold coin, no waste'),('今晚加班','an antique jade desk lamp glowing beside a crescent moon'),('拼好饭','an ivory lunch box with rice and colorful vegetables, gold clasps'),('脂肪肝','a stylized non-gory amber liver-shaped charm with a jade protective mount'),('胃结石','a smooth jade stomach-shaped amulet holding one pale polished stone, non-gory'),('高血压','a crimson heart-shaped jewel surrounded by a golden pressure gauge, no numbers'),('鸡汤','an elegant ivory soup bowl with warm golden broth and a little feather emblem'),('画饼','a golden pie floating above an artists jade palette and brush'),('摸鱼','a playful small jade fish curled around an ivory cushion'),('咖啡','an ornate ivory coffee cup with teal saucer and gold steam'),('健身房','a pair of compact jade dumbbells held in a gold laurel'),('内卷','an ornate tightly spiraling ivory scroll wrapped with teal ribbon')]
base='Create one original fantasy RPG inventory icon. Square 1024x1024, real transparent alpha background. Refined painterly 3D item illustration in deep teal jade, ivory, champagne gold, with restrained relevant accent colors. Clear large centered silhouette within central 80 percent, readable at 93x74 design pixels. Match an elegant gold framed pearl ivory archive UI. No card border, no rectangular backdrop, no floor, no letters, no numbers, no watermarks, no checkerboard. '
p=[dict(id='achievement_shared',name='通关与无尽共用成就徽章',prompt=base+'A single elegant gold laurel victory medallion holding a teal banner and ivory ascending tower, subtly incorporating an infinity loop, emblematic of completed challenges and enduring achievement.')]
for i,(name,subject) in enumerate(concepts,1):p.append(dict(id='work_theme_%02d'%i,name=name,prompt=base+'Subject: '+subject+'. Tasteful light workplace humor, polished collectible object rather than a flat navigation symbol.'))
(out/'prompts.json').write_text(json.dumps(p,ensure_ascii=False,indent=2),encoding='utf-8')
(out/'work_themes.json').write_text(json.dumps({x['item_id']:'work_theme_%02d'%((i%17)+1) for i,x in enumerate(rows)},indent=2),encoding='utf-8')
print('Prepared',len(p),'distinct images for',len(rows),'work entries plus shared achievement art')
