// Additive art study on the CURRENT saved map; no gameplay or navigation edits.
// node tools/map_c6/valley-decor.cjs [converted-current-map.vmap]
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),L=require('./lib.cjs');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'output/valley_decor_v1');
fs.mkdirSync(out,{recursive:true});
const source=fs.readFileSync(process.argv[2]||path.join(out,'before.vmap'),'utf8');
if(source.includes('valley_decor_v1_'))throw Error('Already decorated; use the saved baseline.');
const placements=[];
let seed=316461;
const rnd=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
const rot=(x,y,k)=>[[x,y],[y,-x],[-x,-y],[-y,x]][k];
function add(model,x,y,z,scale,yaw,color='255 255 255',role='border'){
 placements.push({name:'valley_decor_v1_'+placements.length,model:'models/props_nature/'+model+'.vmdl',origin:[+x.toFixed(2),+y.toFixed(2),z],scale:+scale.toFixed(3),yaw:+yaw.toFixed(2),color,role});
}
// Small asymmetrical islands of foliage, with broad empty gaps between them.
// Courtyard middle, stairs and the centre of all four lanes remain clear.
for(let k=0;k<4;k++){
 const toWorld=(x,y)=>{const p=rot(x,y,k);return [p[0]-1024,p[1]+4096];};
 for(const [ax,ay] of [[690,1230],[690,1730],[720,2200],[1130,2420],[1620,2220],[2060,1880],[1730,640],[1260,640]]){
  for(let n=0;n<6;n++){
   const a=rnd()*Math.PI*2,r=20+rnd()*95,[x,y]=toWorld(ax+Math.cos(a)*r,ay+Math.sin(a)*r);
   const m=n===0?'river_rocks002':n===1?'bush_00':n===2?'fern001':n===3?'flowers001':'grass_clump_00a';
   const s=n===0?.6+rnd()*.2:n===1?1.0+rnd()*.3:n===2?.9+rnd()*.3:n===3?.38:1.3+rnd()*.5;
   add(m,x,y,384,s,rnd()*360,n===0?'202 209 182':'255 255 255');
  }
 }
 // Low verge only: leave at least 280 units of readable lane centre.
 for(let n=0;n<9;n++){
  const [x,y]=toWorld(1360+n*66,((n%2)?1:-1)*(184+rnd()*12));
  add(n%3===0?'flowers002':'grass_clump_00b',x,y,128,.35+rnd()*.2,rnd()*360,'255 255 255','verge');
 }
}
// Four existing ordinary-wave markers retain their exact coordinates.
const markers=L.blocks(source,'CMapEntity').filter(e=>/^monsterborn_player[1-4]$/.test(L.value(e.text,'targetname')||''));
if(markers.length!==4)throw Error('Expected four authoritative wave markers.');
const portals=markers.map(e=>({marker:L.value(e.text,'targetname'),origin:L.value(e.text,'origin').split(/\s+/).map(Number)}));
for(const p of portals){
 p.origin[2]=128;
 for(let n=0;n<7;n++){
  const a=(n/7)*Math.PI*2;
  add('river_rocks001',p.origin[0]+Math.cos(a)*114,p.origin[1]+Math.sin(a)*114,124,.42+rnd()*.08,n*51,'195 208 184','spawn_ring');
 }
}
const particle='particles/survival_environment/valley_spawn.vpcf';
// Verify every dependency against the installed Valve assets, not another addon.
const vpk=new L.Vpk(path.resolve(root,'../../dota/pak01_dir.vpk'));
for(const r of [...new Set(placements.map(p=>p.model))])if(!vpk.entries.has(r+'_c'))throw Error('Missing Valve resource '+r);
fs.writeFileSync(path.join(out,'placements.json'),JSON.stringify({placements,portals,particle},null,2));
// Tools-only preview supports repeated refresh and explicit removal.
const lua=`-- Generated by tools/map_c6/valley-decor.cjs. Art preview only.
if not IsInToolsMode() or GetMapName() ~= "template_map" then return end
local old = VALLEY_DECOR_PREVIEW
VALLEY_DECOR_PREVIEW = nil
if old then
 for _,id in ipairs(old.particles or {}) do ParticleManager:DestroyParticle(id,true); ParticleManager:ReleaseParticleIndex(id) end
 for _,e in ipairs(old.entities or {}) do if IsValidEntity(e) then UTIL_Remove(e) end end
end
if VALLEY_DECOR_REMOVE then VALLEY_DECOR_REMOVE=nil; print("VALLEY_DECOR_REMOVED"); return end
local state={entities={},particles={}}
VALLEY_DECOR_PREVIEW=state
local props={
${placements.map(p=>` {${JSON.stringify(p.model)},${p.origin[0]},${p.origin[1]},${p.scale},${p.yaw},${JSON.stringify(p.color)},${JSON.stringify(p.name)}},`).join('\n')}
}
for _,p in ipairs(props) do
 local pos=Vector(p[2],p[3],0)
 local z=GetGroundHeight(pos,nil)
 local e=SpawnEntityFromTableSynchronous("prop_dynamic",{model=p[1],origin=Vector(p[2],p[3],z-2),angles=Vector(0,p[5],0),modelscale=p[4],solid=0,rendercolor=p[6],targetname=p[7]})
 if e then state.entities[#state.entities+1]=e end
 print("VALLEY_PLACEMENT",p[7],z-2,GridNav:IsTraversable(pos),GridNav:IsBlocked(pos))
end
for _,name in ipairs({${portals.map(p=>JSON.stringify(p.marker)).join(',')}}) do
 local e=Entities:FindByName(nil,name)
 local pos=e:GetAbsOrigin(); pos.z=GetGroundHeight(pos,nil)+4
 local id=ParticleManager:CreateParticle(${JSON.stringify(particle)},PATTACH_WORLDORIGIN,nil)
 ParticleManager:SetParticleControl(id,0,pos)
 ParticleManager:SetParticleControl(id,1,Vector(130,0,0))
 state.particles[#state.particles+1]=id
end
print("VALLEY_DECOR_READY",#state.entities,#state.particles)
`;
fs.writeFileSync(path.join(root,'scripts/vscripts/tests/valley_decor_preview.lua'),lua);
fs.writeFileSync(path.join(out,'preview.json'),JSON.stringify([{name:'console_send',arguments:{commands:'host_timescale 1\nscript_reload_code tests/valley_decor_preview\ndota_camera_distance 2200\ndota_camera_set_lookatpos 340 4920\nr_drawpanorama 0\nhideconsole'}}],null,2));
console.log(JSON.stringify({props:placements.length,portals:portals.length,out}));
