const drawer=document.querySelector('#drawer'),content=document.querySelector('#content'),tooltip=document.querySelector('#tooltip');
const shop=[['武器装备',[
 ['成长之剑',0,100,0,null,'swords'],['加速手套 LV1',1,200,0,'5/5'],['灼热之刃 LV1',2,200,0,'5/5'],['铁甲 LV1',3,200,0,'5/5']]],
 ['道具材料', [['死亡面罩',4,300,10000],['锻造之锤',5,1000,5000,'5/5'],['小极地晶石',6,1000,0],['知识之书',7,50000,0,'99/99'],['超级知识之书',8,500000,500000,'99/99']]],
 ['提前通关', [['提前通关',9,50000,0,'1/1']]]];
const challenges=[['练功房', [['木材练功房',0,0,2000],['金币练功房',1,50,10000],['属性练功房',4,500,10000],['大属性练功房',5,2000,10000]]],['进阶挑战', [['挑战合成宝石',5,0,5000],['进入冰霜之地',3,0,5000],['熔火核心 LV1–3',2,0,20000],['熔火核心 LV4',7,0,40000],['挑战冰烬挽歌',9,0,50000],['进入七宗罪',8,0,100000],['进入罪渊',10,0,100000]]],['转生挑战', Array.from({length:10},(_,i)=>['挑战'+(i+1)+'转',11+i,[0,0,100,500,1000,4000,8000,10000,15000,20000][i],(i+1)*10000])]];
function icon(index,atlas='shop'){const n=atlas==='shop'?4:5;const el=document.createElement('div');el.className='icon';el.style.backgroundImage=`url(assets/${atlas}.png)`;el.style.backgroundSize=`${n*100}% ${n*100}%`;el.style.backgroundPosition=`${(index%n)/(n-1)*100}% ${Math.floor(index/n)/(n-1)*100}%`;return el;}
function costs(gold,wood){const el=document.createElement('div');el.className='costs';for(const [type,value]of[['gold',gold],['wood',wood]]){if(value>0){const row=document.createElement('span');row.className='cost';row.innerHTML=`<i class="${type}" aria-label="${type==='gold'?'金币':'木材'}"></i><span>${value}</span>`;el.append(row)}}return el;}
function tip(item,target,atlas){tooltip.replaceChildren();const head=document.createElement('div');head.className='tiphead';head.append(icon(item[1],atlas));const name=document.createElement('strong');name.textContent=item[0];head.append(name);tooltip.append(head,costs(item[2],item[3]));tooltip.hidden=false;const r=target.getBoundingClientRect();tooltip.style.left=Math.min(r.right+15,innerWidth-260)+'px';tooltip.style.top=Math.max(8,Math.min(r.top,innerHeight-tooltip.offsetHeight-10))+'px';}
function selectTab(tab){tooltip.hidden=true;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));content.replaceChildren();content.scrollTop=0;for(const [title,items]of tab==='shop'?shop:challenges){const section=document.createElement('section');section.className='group';const heading=document.createElement('h3');heading.textContent=title;const grid=document.createElement('div');grid.className='grid';for(const item of items){const atlas=item[5]||(tab==='shop'?'shop':'challenges');const card=document.createElement('div');card.className='item';const button=document.createElement('button');button.setAttribute('aria-label',item[0]);button.append(icon(item[1],atlas));button.onmouseenter=()=>tip(item,button,atlas);button.onmouseleave=()=>tooltip.hidden=true;button.onfocus=()=>tip(item,button,atlas);button.onblur=()=>tooltip.hidden=true;button.oncontextmenu=e=>{e.preventDefault();document.querySelector('#notice').textContent='预览：右键购买 '+item[0]+'（不产生实际购买）';};card.append(button);if(item[4]){const stock=document.createElement('span');stock.className='stock';stock.textContent=item[4];card.append(stock)}card.append(costs(item[2],item[3]));grid.append(card)}section.append(heading,grid);content.append(section)}}
function openShop(){drawer.classList.add('open')}function closeShop(){drawer.classList.remove('open');tooltip.hidden=true}function replay(){closeShop();setTimeout(openShop,420)}function showGallery(){tooltip.hidden=true;document.querySelector('#gallery').hidden=false}function hideGallery(){document.querySelector('#gallery').hidden=true}document.addEventListener('keydown',e=>{if(e.key==='Escape'){hideGallery();closeShop()}});
['成长之剑','霜之剑刃','极寒之刃','冰火裁决','深渊审判'].forEach((name,row)=>{const el=document.createElement('div');el.className='sword-row';const h=document.createElement('h3');h.textContent=name;el.append(h);for(let i=0;i<5;i++){const cell=document.createElement('div');cell.className='sword-cell';cell.append(icon(row*5+i,'swords'),document.createTextNode('外观 '+(i+1)));el.append(cell)}document.querySelector('#swords').append(el)});
selectTab('shop');requestAnimationFrame(()=>requestAnimationFrame(openShop));window.previewReady=true;
