'use strict';
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const base='design_refs/ui_20h',before=process.argv.includes('--baseline'),out=base+'/work/'+(before?'preview_before':'preview');fs.mkdirSync(out,{recursive:true});
const uri=p=>pathToFileURL(path.resolve(p)).href;
function source(p){const saved=base+'/work/checkpoints/baseline/'+p;return before&&fs.existsSync(saved)?saved:p;}
function css(p){let s=fs.readFileSync(p,'utf8');return s.replaceAll('file://{images}/',uri('art/ui/sources')+'/').replace(/\bLabel\b/g,'.label').replace(/\bImage\b/g,'img').replace(/\bRadioButton\b/g,'.radio').replace(/\bButton\b/g,'.button').replaceAll(':selected','.Selected').replaceAll(':disabled','.UIDisabled').replace(/position:\s*(-?[\d.]+px)\s+(-?[\d.]+px)\s+0px/g,'position:absolute;left:$1;top:$2').replace(/flow-children:\s*(none|right-wrap|right|down)/g,(_,v)=>v==='none'?'display:block':`display:flex;flex-direction:${v==='down'?'column':'row'};${v==='right-wrap'?'flex-wrap:wrap':''}`).replace(/overflow:\s*squish scroll/g,'overflow-x:hidden;overflow-y:auto').replace(/overflow:\s*scroll squish/g,'overflow-x:auto;overflow-y:hidden').replace(/overflow:\s*clip/g,'overflow:hidden').replace(/overflow:\s*noclip/g,'overflow:visible').replace(/visibility:\s*collapse/g,'display:none').replace(/(width|height):\s*fit-children/g,'$1:max-content').replace(/align:\s*center center/g,'left:50%;top:50%;transform:translate(-50%,-50%)').replace(/align:\s*left top/g,'transform:none').replace(/horizontal-align:\s*center/g,'left:50%;transform:translateX(-50%)').replace(/horizontal-align:\s*right/g,'left:auto;right:0').replace(/vertical-align:\s*center/g,'top:50%;transform:translateY(-50%)').replace(/vertical-align:\s*bottom/g,'top:auto;bottom:0').replace(/text-overflow:\s*shrink/g,'text-overflow:ellipsis;overflow:hidden;white-space:nowrap').replace(/brightness:\s*([\d.]+)/g,'filter:brightness($1)').replace(/text-shadow:[^;]+/g,'text-shadow:none').replace(/background-color:\s*gradient\(linear,\s*0% 0%,\s*0% 100%,\s*from\(([^)]+)\),\s*to\(([^)]+)\)\)/g,'background:linear-gradient($1,$2)').replace(/box-shadow:[^;]+/g,'box-shadow:none');}
const archiveStyles=[...fs.readFileSync(source('panorama/src/layout/custom_game/archive.xml'),'utf8').matchAll(/<include src="file:\/\/\{resources\}\/styles\/custom_game\/([^\"]+\.css)"/g)].map(m=>m[1]);
const styleFiles=[...new Set(['production_progress.css','remaining_5d5c1152eb.css','handoff_v1.css',...archiveStyles])];
let styles=styleFiles.map(f=>css(source('panorama/src/styles/custom_game/'+f))).join('\n').replace(/ignore-parent-flow:\s*true/g,'--pano-ignore-flow:true');
if(!before&&fs.existsSync('panorama/src/styles/custom_game/common/jade_ui.css'))styles+='\n'+css('panorama/src/styles/custom_game/common/jade_ui.css');
fs.writeFileSync(out+'/style.css',styles);
const fixture=Array.from({length:8},(_,i)=>({training_id:'train_lumberjack_0'+(i+1),name:'伐木工LV'+(i+1),level:i+1,cost_wood:[10,100,500,1000,5000,30000,150000,400000][i],cost_gold:i>3?100*(i-3):0,count:0,max_count:i?3:5,queued_count:0,population:i<3?1:2,train_duration:1,available:i<3?1:0,reason:i<3?'':'training_city_level_required',requires_city_level:i<3?1:2}));
const scripts=['common/ui_registry.js','ui_layers.js','common/ui_components.js','ui_snapshot_cache.js','geometry_remaining_5d5c1152eb.js','archive_theme_tokens.js','archive_theme.js','reference_windows.js','archive_handoff_assets.js','archive_handoff_180de7e38b.js','remaining_5d5c1152eb.js','navigation_remaining_5d5c1152eb.js',...(!before?['common/jade_components.js','archive_jade.js']:[]),'archive_180de7e38b_titles_compact_v6.js','production_progress.js'];
fs.writeFileSync(out+'/index.html',`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="style.css"><style>
@font-face{font-family:Han;src:url('${uri('design_refs/shop_ui_12h/fonts/SourceHanSansSC-Regular.otf')}')}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:Han;background:#24464d}.panel{position:absolute;flex-shrink:0}.panel[hidden],.ArchiveHidden{display:none!important}.label{display:block;font-family:Han!important}.radio{cursor:pointer}.label,.button{line-height:1.25}.button{cursor:pointer}.panel img{object-fit:contain}#PreviewRoot{inset:0;width:100%;height:100%}.caption{position:fixed;left:10px;bottom:8px;background:#224b50;color:#faf5e7;font:12px Han;padding:4px 9px;z-index:999999}#BattleBackdrop{position:absolute;inset:0;background-image:url('${uri('design_refs/ui_20h/work/baseline/battle_no_queue.png')}');background-size:cover;background-position:center;pointer-events:none}#TrainingBaselineMask{position:absolute;background-image:inherit;background-size:1920px 1080px;display:none}#ArchiveTabs>.panel,#ArchiveGrid>.panel{position:relative;left:auto;top:auto}.ProductionProgressFill{background:#ceb674}.ProductionQueueHost{scrollbar-width:thin}#ArchiveWindow{isolation:isolate}.ArchiveTab label{line-height:31px}.ArchiveCard{isolation:isolate}#ArchiveTooltipBody>.panel{position:relative;left:auto;top:auto}.ArchiveHidden{display:none}.ArchiveNameHost label{line-height:23px}
</style><div id="BattleBackdrop"></div><div id="PreviewRoot"></div><div class="caption">${before?'迭代前':'最佳版'}真实组件预览 · 显式样例数据 · 未连接账号或支付</div>
<script>window.IMAGE_ROOT=${JSON.stringify(uri('art/ui/sources')+'/')};window.CATALOG_FIXTURE={paid:{categories:[]},wallet:{}};window.TRAINING_FIXTURE=${JSON.stringify(fixture)};window.ARCHIVE_XML=${JSON.stringify(fs.readFileSync(source('panorama/src/layout/custom_game/archive.xml'),'utf8'))};</script><script src="${uri('tools/shop_ui_12h/adapter.js')}"></script><script src="${uri('tools/ui_20h/preview-adapter.js')}"></script>${scripts.map(s=>'<script src="'+uri(source('panorama/src/scripts/custom_game/'+s))+'"></script>').join('')}<script src="${uri('tools/ui_20h/preview-state.js')}"></script>`);
let page=fs.readFileSync(out+'/index.html','utf8');
const hudSources=['tools/ui_20h/hud-adapter.js','panorama/src/scripts/custom_game/handoff_assets.js','panorama/src/scripts/custom_game/geometry_remaining_5d5c1152eb.js','panorama/src/scripts/custom_game/topnav_remaining_5d5c1152eb.js'];
page+='<script>if(new URLSearchParams(location.search).get("page")==="hud"){'+hudSources.map(p=>'eval('+JSON.stringify(fs.readFileSync(source(p),'utf8'))+');').join('')+'}</script>';
page=page.replace('.label{display:block;font-family:Han!important}', '.label{display:block}');
page+='<style>@font-face{font-family:"Source Han Sans SC";src:url("'+uri('design_refs/shop_ui_12h/fonts/SourceHanSansSC-Regular.otf')+'")}@font-face{font-family:"Source Han Serif SC";src:url("'+uri('design_refs/shop_ui_12h/fonts/SourceHanSerifSC-SemiBold.otf')+'")}</style>';
fs.writeFileSync(out+'/index.html',page);
fs.appendFileSync(out+'/index.html','<style>.UINineSlice{display:flex;flex-direction:column}.UINineSlice>.UINineRow{position:relative;display:flex;flex-direction:row;left:auto;top:auto;width:100%;flex-shrink:0}.UINineRow>.UINineTile{position:relative;left:auto;top:auto;flex-shrink:0;height:100%}</style>');
fs.appendFileSync(out+'/index.html','<style>#ArchiveTooltipBody{position:relative;left:0;top:0;}#ArchiveTooltipBody>.panel{position:relative;left:auto;top:auto;}#ArchiveTooltipEffect{line-height:1.6;}</style>');
fs.appendFileSync(out+'/index.html','<style>.VipWindowHidden{display:none!important;}</style>');
console.log('UI20H_PRODUCTION_COMPONENT_PREVIEW_BUILT');
module.exports={css};
