'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve('design_refs/shop_ui_12h'),dest=root+'/Delivery',dev=path.resolve('art/ui/development/commerce_jade_v1');
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
fs.mkdirSync(dest,{recursive:true});fs.mkdirSync(dev+'/source',{recursive:true});
const raw=JSON.parse(fs.readFileSync(root+'/work/assets_manifest.json','utf8'));
const recipes=JSON.parse(fs.readFileSync(root+'/source/component_recipes.json','utf8'));
const resources={version:'B17 + L21 + T23',generatedAt:new Date().toISOString(),materials:[],originalArtwork:[]};
for(const [id,record] of Object.entries(raw.assets)){
 const master=path.resolve('art/ui/sources/custom_game/commerce_jade_v1/'+id+'.png'),buf=fs.readFileSync(master);
 const options=[path.resolve(record.source).replace(/\.png$/,'.svg'),root+'/source/materials/'+id+'.svg',root+'/source/'+id+'.svg'];
 if(id==='nav_selected')options.unshift(root+'/source/nav_selected_material.svg');
 const source=options.find(f=>fs.existsSync(f)),recipe=recipes.find(r=>r.id===id);
 let editable;
 if(source){fs.copyFileSync(source,dev+'/source/'+id+'.svg');editable='art/ui/development/commerce_jade_v1/source/'+id+'.svg';}
 else if(recipe&&recipe.css){editable='art/ui/development/commerce_jade_v1/component_recipes.json#'+id;}
 else {editable=path.relative(process.cwd(),master).replaceAll('\\','/');} // Original raster icon is its source; do not invent a vector master.
 resources.materials.push({id,width:buf.readUInt32BE(16),height:buf.readUInt32BE(20),master:path.relative(process.cwd(),master).replaceAll('\\','/'),runtime:'panorama/images/custom_game/commerce_jade_v1/'+id+'_png.vtex_c',editable,sha256:hash(master)});
}
fs.writeFileSync(dev+'/component_recipes.json',JSON.stringify(recipes.filter(r=>raw.assets[r.id]&&!resources.materials.find(a=>a.id===r.id).editable.endsWith('.svg')),null,2));
fs.copyFileSync(root+'/assets/scenery.png',dev+'/scenery.png');
for(const [icon,value]of Object.entries(raw.items))resources.originalArtwork.push({source:'panorama/src/images/'+icon,sha256:hash(path.resolve('panorama/src/images',icon)),sourceSize:value.sourceSize,alphaBounds:value.alphaBounds,shadow:'art/ui/sources/'+value.shadow,shadowSha256:hash(path.resolve('art/ui/sources',value.shadow))});
fs.writeFileSync(dest+'/resources.json',JSON.stringify(resources,null,2));
const entries=[];
for(const group of fs.readdirSync(root+'/work/checkpoints')){
 const f=root+'/work/checkpoints/'+group+'/decision.json';if(!fs.existsSync(f))continue;
 const d=JSON.parse(fs.readFileSync(f));for(const e of d.entries)entries.push({...e,keep:e.result==='保留'});
}
const final=JSON.parse(fs.readFileSync(root+'/work/checkpoints/production_best/manifest.json'));for(const d of final.decisions)entries.push({...d,result:d.keep?'保留':'淘汰'});
entries.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
if(entries.length!==24)throw Error('Expected all 24 candidate decisions, got '+entries.length);
const img=(f,alt,cls='')=>`<img class="${cls}" src="../work/${f}" alt="${esc(alt)}" loading="lazy">`;
const candidateHTML=entries.map(e=>{const config=JSON.parse(fs.readFileSync(root+'/work/candidates/'+e.id+'/config.json','utf8'));return `<article><div class="candidate-title"><strong>${e.id}</strong><span class="${e.keep?'keep':'reject'}">${e.result}</span></div><p>${esc(e.improvement)}</p><div class="pair">${img('candidates/'+e.id+'/card_normal.png',e.id+' 默认')}${img('candidates/'+e.id+'/card_hover.png',e.id+' 悬停')}</div><small>代价 / 选择依据：${esc(e.cost)}</small><details><summary>变量与整页截图</summary><pre>${esc(JSON.stringify(config.changes||config,null,2))}</pre><a href="../work/candidates/${e.id}/normal.png">默认全图</a> · <a href="../work/candidates/${e.id}/hover.png">悬停全图</a></details></article>`;}).join('');
const categories=[['technology','科技与服务（本地 30）'],['item','道具与材料（本地 84）'],['weapon','武器装备（本地空）'],['challenge','挑战（本地空）'],['rebirth','转职（本地空）'],['bundles','礼包（本地空）']];
fs.writeFileSync(dest+'/index.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>商城最佳版 · 云海青玉</title><style>
*{box-sizing:border-box}body{margin:0;color:#244554;background:#f7f7ef;font:16px/1.65 system-ui,"Microsoft Yahei",sans-serif}main{max-width:1480px;margin:auto;padding:40px 30px}h1,h2{font-family:Georgia,"SimSun",serif;line-height:1.3}h1{font-size:38px;margin:0 0 14px}h2{font-size:26px;margin:42px 0 14px}p{margin:8px 0 18px}.muted,small{color:#627e82}.tag{display:inline-block;padding:3px 10px;background:#e4ece1;border-radius:4px;margin-right:8px}nav{display:flex;gap:16px;flex-wrap:wrap}a{color:#3d777e}button,select{border:1px solid #b1beb7;background:#f5f6ed;color:#244554;border-radius:4px;padding:8px 16px;font:inherit;cursor:pointer}button.active{background:#477d82;color:#fff9e7}img{display:block;max-width:100%;height:auto;border-radius:4px}.compare{position:relative;width:100%;aspect-ratio:8/5;overflow:hidden;background:#173944;border-radius:6px}.compare img{position:absolute;width:100%;height:100%;object-fit:contain;border-radius:0}.compare .after{clip-path:inset(0 0 0 var(--reveal,50%))}.divider{position:absolute;left:var(--reveal,50%);height:100%;width:2px;background:#faf8ec;pointer-events:none}.labels{position:absolute;inset:15px 16px auto;display:flex;justify-content:space-between;pointer-events:none}.labels span{background:#173d46de;color:#fff9e7;padding:3px 9px;border-radius:3px}input[type=range]{width:100%;accent-color:#477d82}.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:15px 0}.native-row,.category-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.sheet{background:#ebf0e5;padding:10px;border-radius:6px}.sheet p{margin:6px 4px}.experiments{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}article{padding:16px;border:1px solid #d1dbcd;border-radius:6px;background:#fbfaf5}article p{font-size:14px;min-height:65px}.candidate-title{display:flex;justify-content:space-between}.keep{color:#3f7769}.reject{color:#8a7160}.pair{display:flex;gap:8px;margin-bottom:12px}.pair img{width:calc(50% - 4px)}pre{white-space:pre-wrap;font-size:12px}.crop-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.crop-grid img{background:#eaf0e6}.inline-links{display:flex;gap:20px;flex-wrap:wrap}.browser-view{border:1px solid #ccd8cb;padding:8px;background:#eaf0e6}.caption{font-size:14px;color:#627e82;margin:10px 0 20px}@media(max-width:900px){main{padding:24px 16px}.experiments{grid-template-columns:repeat(2,minmax(0,1fr))}.native-row,.category-grid{grid-template-columns:1fr}.crop-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style><main><h1>商城最佳版 · 云海青玉</h1><p><span class="tag">B17 + L21 + T23</span><span class="tag">24 个候选</span><span class="tag">真实组件组装</span></p><p>云海背景接象牙浅底，商品保留原图与独立投影，名称、价格、描述和购买按钮各自绑定。最佳版来自逐组比较；最新的 T24 已淘汰。</p><nav><a href="#native">真实游戏</a><a href="#preview">分辨率预览</a><a href="#reuse">复用组件</a><a href="#experiments">候选比较</a><a href="../Integration.md">接入与恢复说明</a><a href="../Decisions.md">完整决策</a></nav>
<h2 id="native">真实游戏前后对比</h2><p class="muted">Dota 2 Tools，1280×800，同一测试局、同一科技首屏、服务端真实目录。原版和最终版依次截图；世界和倒计时会随游戏推进。未发起购买或订单。</p><div class="compare" id="compare"><img src="../work/production/native_before.png" alt="本次修改前真实商城"><img class="after" src="../work/production/native_final_normal.png" alt="最佳版真实商城"><div class="divider"></div><div class="labels"><span>修改前</span><span>最佳版</span></div></div><input aria-label="拖动比较原版和最佳版" id="reveal" type="range" min="0" max="100" value="50"><p class="caption">拖动分界查看完整默认态。独立对比图：<a href="native_before_after.png">前后并排</a> · <a href="../work/production/native_final_normal.png">最终默认原图</a></p>
<div class="native-row"><div class="sheet">${img('production/native_final_hover.png','真实游戏悬停')}<p>悬停：名称持续可见，效果说明软边遮罩，购买区域独立。为便于重复验收使用 Tools 强制悬停，未触发购买。</p></div><div class="sheet">${img('production/native_final_item.png','真实游戏道具分类')}<p>道具：原抽奖券缩略图 96px 内嵌，积分与 U 币各自显示；其余商品原图映射保持。</p></div></div>
<details><summary>关闭商城后的原有 HUD</summary>${img('production/native_final_hud_closed.png','关闭商城后的底部HUD')}</details><h2>关键局部 · 原生像素</h2><div class="crop-grid">${['native_header','native_sidebar','native_card_normal','native_card_hover'].map(n=>`<div>${img('production/'+n+'.png',n)}<small>${{native_header:'顶部雾化衔接',native_sidebar:'侧栏接缝 / 导航底线',native_card_normal:'默认物品 / 名称价格',native_card_hover:'悬停 / 描述 / 购买'}[n]}</small></div>`).join('')}</div>
<h2 id="preview">分辨率和字段适配 · 浏览器组件预览</h2><p class="muted">以下通过生产 JS 组件、控制器和 CSS 的浏览器适配器组装。1280×720、1920×1080、2560×1440、2560×1080 均检查几何和交互；这些尺寸尚未逐一在 Panorama 游戏内验证。</p><div class="toolbar"><select id="resolution" aria-label="预览分辨率">${['1920x1080','1280x720','2560x1440','2560x1080'].map(r=>`<option>${r}</option>`).join('')}</select><button class="active" data-state="normal">默认</button><button data-state="hover">悬停</button><button data-state="long">长名称 / 12 位价格 / 长描述</button></div><div class="browser-view"><img id="resolutionImage" src="../work/production/qa_1920x1080_normal.png" alt="1920×1080 浏览器生产组件预览"></div>
<h2>已有类别 · 本地 CSV 预览</h2><p class="muted">本地启用 114 条（108 兑换 + 6 付费配置），当前服务器只返回 108 条兑换：科技 25，道具 83，导航也只显示它返回的两类。没有为截图新增商品。四个空类别保持空态。</p><div class="category-grid">${categories.map(([id,title])=>`<div class="sheet">${img('production/category_'+id+'.png',title)}<p>${title}</p></div>`).join('')}</div>
<h2 id="reuse">复用组件和状态</h2><p class="muted">原项目弓、盾、长杆、球形物品、皮肤图和旧券图共用同一卡片壳。皮肤是兼容样例，礼包使用已有未启用的 7 奖励配置做 2×2 可滚动组件验收；均不是新上架商品。</p><div class="sheet">${img('production/component_reuse.png','原商品与皮肤图复用组件')}</div><div class="native-row"><div class="sheet">${img('production/component_states.png','购买与导航状态')}<p>商品默认 / 悬停，导航默认 / 悬停 / 选中，按钮默认 / 悬停 / 按下。</p></div><div class="sheet">${img('production/bundle_component.png','礼包2乘2组件')}<p>奖励数超过四项时内容区滚动，名称、价格和购买区保持独立。</p></div></div>
<h2 id="experiments">24 个实质候选</h2><p class="muted">每轮改变 1–3 个变量；从当时最佳版本生成。每张候选都有默认、悬停、局部和可恢复记录。前 20 个为参考组件组装比较，L21–T24 在生产组件和真实 CSV 预览中比较。</p><div class="experiments">${candidateHTML}</div>
<h2>源文件与交付</h2><div class="inline-links"><a href="../Integration.md">尺寸 / 层级 / 接入 / 恢复</a><a href="resources.json">37 材质和 75 物品投影索引</a><a href="../Plan.md">完成计划</a><a href="../Progress.md">进度和验证范围</a><a href="../work/checkpoints/production_best/manifest.json">最佳版检查点</a><a href="../work/production/verification.json">几何交互报告</a><a href="../work/production/extended_qa.json">字段和复用报告</a></div><p class="caption">底部 HUD 和业务代码沿用现有项目；未接真实支付。原商品图没有重绘或改写。低清旧券图仍有原图自带背景，是资源本身的限制。</p></main><script>
const compare=document.querySelector('#compare');document.querySelector('#reveal').oninput=e=>compare.style.setProperty('--reveal',e.target.value+'%');let state='normal';function show(){const res=document.querySelector('#resolution').value;const i=document.querySelector('#resolutionImage');i.src='../work/production/qa_'+res+'_'+state+'.png';i.alt=res+' '+state+' 浏览器组件预览';}document.querySelector('#resolution').onchange=show;document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{state=b.dataset.state;document.querySelectorAll('[data-state]').forEach(x=>x.classList.toggle('active',x===b));show();});
</script></html>`);
console.log('DELIVERY_BUILT: gallery, editable source inventory, '+resources.materials.length+' materials / '+resources.originalArtwork.length+' original items / '+entries.length+' candidates');
