'use strict';
const fs=require('fs'),assert=require('node:assert/strict'),{browser,sleep}=require('./cdp.cjs');
const base='design_refs/shop_ui_12h/work/production';
(async()=>{const b=await browser(),report={kind:'browser_component_checks',longFields:[],components:[],states:[]};try{
 for(const[w,h]of [[1280,720],[1920,1080],[2560,1440],[2560,1080]]){
  await b.call('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:false});await b.go(base+'/after.html','?category=technology');
  await b.run(`const p=CATALOG_FIXTURE.wallet.products.filter(p=>p.category_id==='technology')[1];p.title='极寒之刃·银白烈风限定永久纪念版本名称压力样例';p.price=999999999999;p.reward_lines=[];p.description=Array(24).fill('全属性增加，攻击和护甲说明保持动态文本。').join('\\n');cfg.SurvivalCommerceView.UpdateWalletCatalog(CATALOG_FIXTURE.wallet);selectCategory('technology');syncFlows();document.querySelectorAll('.CJProduct')[1].classList.add('CJVisualHover');`);
  const ok=await b.run(`(()=>{const c=document.querySelectorAll('.CJProduct')[1],n=c.querySelector('.RCProductName'),d=c.querySelector('.RCProductEffect'),a=c.querySelector('.RCProductBuy'),p=c.querySelector('.CJPrice'),r=c.getBoundingClientRect(),nr=n.getBoundingClientRect(),dr=d.getBoundingClientRect(),ar=a.getBoundingClientRect(),pr=p.getBoundingClientRect();return nr.left>=r.left&&nr.right<=r.right&&pr.right<=r.right&&dr.bottom<=ar.top+2&&d.scrollHeight>d.clientHeight&&getComputedStyle(n).overflow==='hidden'&&p.dataset.type==='Panel';})()`);assert(ok,'long fields stay within their own card');
  await b.shot(base+`/qa_${w}x${h}_long.png`);report.longFields.push({w,h,status:'PASS',scope:'labelled pressure fixture, no live catalog modification'});
 }
 await b.call('Emulation.setDeviceMetricsOverride',{width:1920,height:1080,deviceScaleFactor:1,mobile:false});await b.go(base+'/after.html','?category=item');
 await b.run(`const g=document.querySelector('.RCGrid');g.panel=undefined;const pg=panoRoot.children.find(p=>p.BHasClass('CommerceJade')).children.find(p=>p.BHasClass('RCGrid'));pg.RemoveAndDeleteChildren();window.boardCards=[];
 const data=CATALOG_FIXTURE.wallet.products;const picks=['lottery_gale_bow.png','lottery_titan_shield.png','lottery_supreme_fishing_rod.png','lottery_time_orb.png'].map(n=>data.find(p=>p.icon.endsWith(n)));picks.push({...data[0],title:'皮肤图适配样例',icon:'custom_game/archive_items_v2/lottery_magical_girl_juggernaut.png',price:0});picks.push(data.find(p=>p.icon.includes('ticket_illustrated')));
 picks.forEach((p,i)=>{if(!p)throw Error('Component source not found');const c=cfg.SurvivalCommerceComponents.Product(pg,p,{effect:'原项目图 · 组件复用检查',purchaseLabel:'预览状态',action:()=>{}});cfg.SurvivalCommerceComponents.Box(c,(i%4)*312,Math.floor(i/4)*366,296,348);boardCards.push(c);});syncFlows();document.querySelector('.PreviewCaption').textContent='组件适配样例 · 原项目装备/英雄图/券图 · 非新上架商品 / 无支付';`);
 await b.run(`Promise.all([...document.images].map(i=>i.decode().catch(()=>false))).then(()=>true)`);
 const art=await b.run(`[...document.querySelectorAll('.RCProductArt')].map(i=>({src:i.src.split('/').at(-1),loaded:i.complete&&i.naturalWidth>0,fit:getComputedStyle(i).objectFit,box:i.getBoundingClientRect().toJSON()}))`);assert(art.every(i=>i.loaded&&i.fit==='contain'),JSON.stringify(art));report.components=art;await b.shot(base+'/component_reuse.png');
 await b.run(`boardCards[0].AddClass('CJVisualHover');boardCards[1].AddClass('CJVisualHover');boardCards[1].children.flatMap(p=>p.children).find(p=>p.BHasClass('RCProductHover')).children.find(p=>p.BHasClass('CJBuy')).AddClass('PreviewHover');boardCards[2].AddClass('CJVisualHover');boardCards[2].children.flatMap(p=>p.children).find(p=>p.BHasClass('RCProductHover')).children.find(p=>p.BHasClass('CJBuy')).AddClass('PreviewPressed');document.querySelectorAll('.CJNav')[0].classList.add('PreviewHover');syncFlows();`);await sleep(230);await b.shot(base+'/component_states.png');report.states.push({state:'card default/hover; nav default/hover/selected; buy default/hover/pressed',status:'CAPTURED',scope:'same production classes and factory'});
 await b.go(base+'/after.html','?category=technology');assert(await b.run('cfg.SurvivalCommerceView.IsOpen()'));await b.run(`document.querySelector('.RCClose').click()`);assert(!await b.run('cfg.SurvivalCommerceView.IsOpen()'));await b.run('cfg.SurvivalCommerceView.Open()');await b.run(`document.querySelector('.RCBackdrop').click()`);assert(!await b.run('cfg.SurvivalCommerceView.IsOpen()'));report.states.push({state:'independent close X / outside scrim',status:'PASS'});
 fs.writeFileSync(base+'/extended_qa.json',JSON.stringify(report,null,2));console.log('EXTENDED_QA_PASS: 4 long-field viewports, original art variants, component states, close input');
 }finally{b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
