'use strict';
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url'),{fixture}=require('./catalog.cjs');
const repo=process.cwd(),base=path.resolve('design_refs/shop_ui_12h'),dir=base+'/work/production';fs.mkdirSync(dir,{recursive:true});
const uri=f=>pathToFileURL(path.resolve(f)).href;
function css(src){
 let text=fs.readFileSync(src,'utf8'),defines={};text=text.replace(/@define\s+(\w+):\s*([^;]+);/g,(_,k,v)=>{defines[k]=v;return '';});for(const[k,v]of Object.entries(defines))text=text.replaceAll(': '+k+';',': '+v+';').replaceAll(':'+k+';',':'+v+';');
 text=text.replaceAll('file://{images}/',uri('panorama/src/images')+'/').replace(/\bLabel\b/g,'.label').replace(/\bImage\b/g,'img').replace(/\bButton\b/g,'.button').replaceAll(':disabled','.UIDisabled').replaceAll('visibility:collapse','display:none').replaceAll('overflow:squish scroll','overflow-x:hidden;overflow-y:auto').replaceAll('overflow:scroll squish','overflow-x:auto;overflow-y:hidden').replaceAll('overflow:noclip','overflow:visible').replaceAll('overflow:clip','overflow:hidden').replaceAll('text-overflow:shrink','text-overflow:ellipsis').replaceAll('text-overflow:clip','text-overflow:clip').replaceAll('width:fit-children','width:max-content').replaceAll('height:fit-children','height:max-content').replaceAll('font-weight:normal','font-weight:400').replaceAll('font-weight:medium','font-weight:500');
 text=text.replace(/position:\s*(-?[\d.]+px)\s+(-?[\d.]+px)\s+0px/g,'position:absolute;left:$1;top:$2');
 text=text.replace(/flow-children:\s*(none|right-wrap|right|down)/g,(_,v)=>v==='none'?'display:block':`display:flex;flex-direction:${v==='down'?'column':'row'};${v==='right-wrap'?'flex-wrap:wrap':''}`);
 text=text.replace(/align:\s*center center/g,'left:50%;top:50%;transform:translate(-50%,-50%)').replace(/align:\s*left top/g,'left:0;top:0').replace(/horizontal-align:\s*center/g,'left:50%;transform:translateX(-50%)').replace(/vertical-align:\s*center/g,'top:50%;transform:translateY(-50%)').replace(/horizontal-align:\s*right/g,'right:0;left:auto').replace(/vertical-align:\s*bottom/g,'bottom:0;top:auto').replace(/brightness:\s*([\d.]+)/g,'filter:brightness($1)').replace(/white-space:\s*normal/g,'white-space:pre-wrap').replace(/text-shadow:[^;]+/g,'text-shadow:none');
 text=text.replace(/horizontal-align:\s*left/g,'transform:none').replace(/vertical-align:\s*top/g,'transform:none');
 text=text.replaceAll('translateY(-2px)','translateY(-2px)').replace(/scaleX\(-1\)/g,'scaleX(-1)');
 text+='\n'+text.split(/(?<=})/).filter(r=>/:hover|:active/.test(r)).map(r=>r.replaceAll(':hover','.PreviewHover').replaceAll(':active','.PreviewPressed')).join('\n');return text;
}
for(const mode of ['before','after']){
 const baseline=base+'/work/checkpoints/baseline',styles=[css('panorama/src/styles/custom_game/common/ui_components.css'),css('panorama/src/styles/custom_game/lottery_handoff_bb9968eef7.css'),css(mode==='before'?baseline+'/remaining_5d5c1152eb.css':'panorama/src/styles/custom_game/remaining_5d5c1152eb.css')];
 if(mode==='after')styles.push(css('panorama/src/styles/custom_game/common/commerce_jade.css'));
 fs.writeFileSync(dir+'/'+mode+'.css',styles.join('\n'));
 let extra=`*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{background:#203a46 url('${uri(base+'/work/baseline/game_postgame.png')}') center/cover;font-family:HanSans}.panel{position:absolute;flex-shrink:0}.panel[hidden]{display:none!important}.label{display:block;font-weight:400;pointer-events:none}.button{cursor:pointer}img{object-fit:contain}.panel .panel{max-width:initial}.panel[style*="flex"]>.panel,.CJPriceRow>.panel,.CJPager>.panel,.RCBundleContents>.panel{position:relative;left:auto;top:auto;transform:none}#PreviewRoot{width:100%;height:100%;inset:0}.PreviewCaption{position:fixed;left:8px;bottom:4px;color:#fdfbe8;font:12px HanSans;z-index:200000;background:#173e4c;padding:3px 8px}.UIModal{transform-origin:center;isolation:isolate}.UIModalInputShield{pointer-events:none}.UIFontTitle,.CJBuy .label,.RCProductName,.RCTabText,.RCTitle{font-family:HanSerif!important}.UIIconImage{position:absolute}.CJPriceRow{white-space:nowrap;width:max-content;max-width:264px}.CJPriceRow>.panel{align-self:center}.CJPriceValue{max-width:230px!important}.CJYuanIcon{height:28px}.CJNav .RCTabText{margin:0;padding:0}.CJPageAction>.label{width:100%;text-align:center}.CJProduct{isolation:isolate}.CJProduct .CJPriceRow{left:50%;top:50%;transform:translate(-50%,-50%)}.CJPriceRow>.label{height:30px;line-height:30px}.RCProductName{line-height:34px}.RCTitle{line-height:72px}.RCTabText{line-height:42px}.CJBuy>.label{height:30px;line-height:30px;white-space:nowrap}.CJCloseArt{pointer-events:none}.RCProductEffect:not(.CJLongEffect){line-height:40px}.CJLongEffect{line-height:24px}.CJFrame,.CJHeaderMist,.CJSidebarSeam{pointer-events:none}.RCBundleName{line-height:23px}.RCBundleContents{align-content:flex-start}.CJPageLabel{line-height:28px}.CJNavGlow{pointer-events:none}.CJProduct:hover .RCProductHover,.CJProduct.PreviewHover .RCProductHover,.CJProduct.CJVisualHover .RCProductHover{display:block}.RCProductArt{object-fit:contain}.CJPriceValue{text-overflow:ellipsis;overflow:hidden}`;
 extra+=`@font-face{font-family:HanSans;src:url('${uri(base+'/fonts/SourceHanSansSC-Regular.otf')}')}@font-face{font-family:HanSerif;src:url('${uri(base+'/fonts/SourceHanSerifSC-SemiBold.otf')}')}`;
 const scripts=['common/ui_registry.js','ui_layers.js','common/ui_components.js','remaining_5d5c1152eb.js'];if(mode==='after')scripts.push('common/commerce_art_manifest.js','common/commerce_components.js');
 let scriptTags=scripts.map(s=>`<script src="${uri('panorama/src/scripts/custom_game/'+s)}"></script>`).join('');scriptTags+=`<script src="${uri(mode==='before'?baseline+'/commerce_remaining_5d5c1152eb.js':'panorama/src/scripts/custom_game/commerce_remaining_5d5c1152eb.js')}"></script>`;
 fs.writeFileSync(dir+'/'+mode+'.html',`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="${mode}.css"><style>${extra}</style><div id="PreviewRoot"></div><div class="PreviewCaption">组件预览 · ${mode==='before'?'原商城':'最佳材质 B17'} · 本地CSV商品，未连接账号/支付</div><script>window.IMAGE_ROOT=${JSON.stringify(uri('panorama/src/images')+'/')};window.CATALOG_FIXTURE=${JSON.stringify(fixture())};</script><script src="${uri('tools/shop_ui_12h/adapter.js')}"></script>${scriptTags}<script>cfg.SurvivalCommerceView.Open();selectCategory(new URLSearchParams(location.search).get('category')||'technology');syncFlows();</script>`);
}
console.log('PRODUCTION_PREVIEW_BUILT: same controllers/components, read-only CSV fixture');
