const events={},requests=[];
// Browser-only adapter, not shipped to Dota. Runs the production component factories.
const config={},nodes={};
class Panel{
 constructor(type,parent,id,element){this.type=type;this.parent=parent;this.children=[];this.id=id;this.events={};this.el=element||document.createElement(type==='Image'?'img':type==='Label'?'label':'div');this.el.classList.add('panel');if(type==='Label')this.el.classList.add('label');if(parent){parent.children.push(this);parent.el.append(this.el)}if(id){this.el.id=id;nodes[id]=this}this.style=new Proxy({}, {set:(o,k,v)=>{o[k]=v;const e=this.el.style;if(k==='position'){const xy=String(v).split(' ');e.position='absolute';e.left=this.el.classList.contains('UIModal')?'50%':xy[0];e.top=this.el.classList.contains('UIModal')?'50%':xy[1]}else if(k==='transform'&&this.el.classList.contains('UIModal'))e.transform='translate(-50%,-50%) '+v;else if(k==='backgroundImage')e.backgroundImage=String(v).replace('file://{images}/','../../../panorama/src/images/');else if(!['horizontalAlign','verticalAlign','align','flowChildren','brightness'].includes(k))e[k]=v;return true}});this.enabled=true;}
 set text(s){this.el.textContent=s}get text(){return this.el.textContent}set visible(v){this.el.style.display=v?'':'none'}get visible(){return this.el.style.display!=='none'}set checked(v){this.el.classList.toggle('checked',!!v)}get checked(){return this.el.classList.contains('checked')}set enabled(v){this._enabled=v;this.el.classList.toggle('UIDisabled',v===false)}get enabled(){return this._enabled}set hittest(v){this._hit=v;}set hittestchildren(v){}
 SetScaling(v){this.el.style.objectFit=v==='stretch-to-fit'?'fill':'contain'}ToggleClass(c){this.el.classList.toggle(c)}RemoveAndDeleteChildren(){this.children=[];this.el.replaceChildren()}FindChildTraverse(id){if(this.id===id)return this;for(const c of this.children){const p=c.FindChildTraverse(id);if(p)return p;}return null}AddClass(c){this.el.classList.add(c)}RemoveClass(c){this.el.classList.remove(c)}BHasClass(c){return this.el.classList.contains(c)}SetHasClass(c,v){this.el.classList.toggle(c,!!v)}GetParent(){return this.parent}GetChildCount(){return this.children.length}GetChild(i){return this.children[i]}IsValid(){return true}SetImage(uri){this.el.src=uri.replace('file://{images}/','../../../panorama/src/images/')}SetPanelEvent(n,fn){if(this.events[n])this.el.removeEventListener(n==='onactivate'?'click':n.slice(2),this.events[n]);const wrapped=e=>{if(n==='onactivate')e.stopPropagation();fn(e)};this.events[n]=wrapped;this.el.addEventListener(n==='onactivate'?'click':n.slice(2),wrapped)}
 get actuallayoutwidth(){return innerWidth}get actuallayoutheight(){return innerHeight}get actualuiscale_x(){return 1}get actualuiscale_y(){return 1}
}
const root=new Panel('Panel',null,'PreviewRoot',document.body);
function $(id){return nodes[id.slice(1)]}$.GetContextPanel=()=>root;$.CreatePanel=(t,p,id)=>new Panel(t,p,id);$.Schedule=(d,fn)=>setTimeout(fn,d*1000);$.CancelScheduled=id=>clearTimeout(id);$.DispatchEvent=()=>{};
const GameUI={CustomUIConfig:()=>config},GameEvents={Subscribe(n,f){events[n]=f;return n},Unsubscribe(n){delete events[n]},SendCustomGameEventToServer(n,p){requests.push({n,p})}};
function host(id){return new Panel('Panel',null,id,document.getElementById(id))}
