"""Opt-in real HTTP/Lua lottery acceptance on the existing loopback test service.

Write mode requires runtime environment plus a separately configured libpq
fixture service. It creates two random synthetic accounts, seeds only those
accounts with map tickets and a sentinel permanent item, then uses real HTTP
requests. There are no special-ticket grants, payments, configuration syncs,
table deletions or service interruptions. Test rows remain for inspection.

After an operator restarts the backend, verify mode needs only the private
token and prior report. It reads the exact saved profiles and lottery snapshots
without new commands or fixture administration. A matching report proves state
retention; the operator must separately record the actual process restart.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import hmac
import json
import os
from pathlib import Path
import re
import secrets
import stat
import sys

from http_acceptance import (AcceptanceFailure, HttpClient, PROFILE_READ_EFFECTS,
    load_private_report, loopback_target, profile_summary, read_token, require,
    same_saved_state, write_report)

FORMAT = 1
GENERATOR = "goufayu.lottery_upgrade_acceptance.v1"
SENTINEL = "acceptance_permanent_item"
CHECKS = {
    "authenticated_lottery_endpoint", "two_new_synthetic_accounts_seeded",
    "real_lua_map_ten_draw", "lottery_replay_same_request_exactly_once",
    "lottery_account_isolation", "permanent_content_preserved",
    "raw_save_cannot_replace_lottery_inventory",
}
NOT_TESTED = ["actual_process_restart_requires_operator_evidence", "real_database_outage",
              "real_game_client", "payment", "offsite_restore"]


def digest(value):
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, allow_nan=False,
        sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()


def snapshot(client, account, config_hash):
    value = client.success("POST", "/v1/lottery/snapshot",
        {"account_id": account, "config_hash": config_hash}, "lottery_snapshot_failed")
    require(value.get("ok") is True and value.get("config_hash") == config_hash
            and isinstance(value.get("snapshots"), list), "lottery_snapshot_invalid")
    maps = [row for row in value["snapshots"]
            if isinstance(row, dict) and row.get("selected_pool_id") == "map"]
    require(len(maps) == 1, "lottery_map_pool_missing")
    row = maps[0]
    require(row.get("ticket_content_id") == "lottery_ticket"
            and type(row.get("tickets")) is int and row["tickets"] >= 0
            and type(row.get("draws")) is int and row["draws"] >= 0
            and type(row.get("ten_cost")) is int and 1 <= row["ten_cost"] <= 20,
            "lottery_map_contract_invalid")
    return value, row


def database_identity(connection):
    # libpq can otherwise resolve a service to a remote or non-test database.
    require(connection.info.host in {"127.0.0.1", "::1"}
            and connection.info.port == 5432 and connection.info.dbname == "goufayu_test"
            and connection.info.server_version // 10000 == 17, "lottery_test_database_required")
    return connection.info.host, connection.info.port, connection.info.dbname


def private_fixture_passfile(path):
    """Validate metadata only; libpq reads it without exposing any credentials."""
    require(path is not None, "fixture_passfile_required")
    path = Path(path)
    require(path.is_absolute() and not path.is_symlink(), "fixture_passfile_path_invalid")
    try:
        descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
        with os.fdopen(descriptor, "rb") as stream:
            info = os.fstat(stream.fileno())
            require(stat.S_ISREG(info.st_mode), "fixture_passfile_not_regular")
            if os.name == "posix":
                require(info.st_uid in {0, os.geteuid()} and not info.st_mode & 0o077,
                        "fixture_passfile_permissions_invalid")
            else:
                from http_acceptance import _windows_private_file
                _windows_private_file(path)
        return str(path)
    except OSError:
        raise AcceptanceFailure("fixture_passfile_unreadable") from None


class Fixture:
    """Admin writes are bound to fresh identities generated by this invocation."""
    def __init__(self, app, settings, service, passfile=None):
        import psycopg
        require(isinstance(service, str) and re.fullmatch(r"[A-Za-z0-9_-]{1,64}", service),
                "fixture_service_required")
        self.app, self.service, self.psycopg = app, service, psycopg
        self.passfile = private_fixture_passfile(passfile)
        self.created = set()
        with psycopg.connect(settings.postgres_dsn) as runtime:
            self.identity = database_identity(runtime)
            runtime_user = runtime.info.user
        with self.connect() as fixture:
            require(fixture.info.user != runtime_user, "separate_fixture_identity_required")

    def connect(self):
        options = {"service": self.service, "connect_timeout": 5}
        if self.passfile:
            options["passfile"] = self.passfile
        connection = self.psycopg.connect(**options)
        try:
            require(database_identity(connection) == self.identity, "fixture_database_mismatch")
            connection.execute("SET statement_timeout='10s'")
            connection.execute("SET lock_timeout='3s'")
            return connection
        except Exception:
            connection.close()
            raise

    def reserve_account(self):
        for _ in range(5):
            account = "900" + f"{secrets.randbelow(10**16):016d}"
            database_id = self.app._database_account_id(account)
            with self.connect() as admin:
                exists = admin.execute("SELECT 1 FROM public.survival_players WHERE account_id=%s",
                                       (database_id,)).fetchone()
            if not exists and account not in self.created:
                self.created.add(account)
                return account
        raise AcceptanceFailure("synthetic_account_allocation_failed")

    def seed(self, account, before):
        require(account in self.created and before.get("account_id") == account
                and before["save"].get("content_inventory", {}) == {}
                and before["save"].get("archive", {}) == {}, "synthetic_account_not_fresh")
        database_id = self.app._database_account_id(account)
        with self.connect() as admin:
            # Match the production RPC lock order and guard against a concurrent
            # write. Fixtures never reset an inventory or reuse an old account.
            admin.execute("SELECT 1 FROM public.player_gameplay_stats WHERE player_id=%s FOR UPDATE",
                          (database_id,))
            revision = admin.execute("SELECT profile_revision FROM public.survival_players WHERE account_id=%s FOR UPDATE",
                                     (database_id,)).fetchone()
            require(revision is not None and revision[0] == before["revision"], "fixture_revision_changed")
            inventory = admin.execute("SELECT content_inventory FROM public.player_archive_state WHERE account_id=%s FOR UPDATE",
                                      (database_id,)).fetchone()
            require(inventory is None or inventory[0] == {}, "fixture_inventory_already_present")
            admin.execute("INSERT INTO public.player_archive_state(account_id,content_inventory) VALUES(%s,%s::jsonb) "
                          "ON CONFLICT(account_id) DO UPDATE SET content_inventory=EXCLUDED.content_inventory",
                          (database_id, json.dumps({"lottery_ticket": 20, SENTINEL: 1})))
            admin.execute("UPDATE public.survival_players SET profile_revision=profile_revision+1 WHERE account_id=%s",
                          (database_id,))


def run_write(client, app, fixture, report):
    checks, config_hash = report["checks"], app.archive.bundle.hash
    status, value = client.request("POST", "/v1/lottery/snapshot", {}, authenticated=False)
    require(status == 401 and value.get("ok") is False, "lottery_authentication_failed")
    checks["authenticated_lottery_endpoint"] = True
    accounts = [fixture.reserve_account(), fixture.reserve_account()]
    report["synthetic_accounts"] = accounts
    for account in accounts:
        fixture.seed(account, client.profile(account))
    first, other = accounts
    before, other_before = client.profile(first), client.profile(other)
    _, initial = snapshot(client, first, config_hash)
    require(initial["tickets"] == 20 and initial["draws"] == 0, "lottery_fixture_not_visible")
    checks["two_new_synthetic_accounts_seeded"] = True

    request_id = "lottery-acceptance:" + secrets.token_hex(16)
    operation = {"id": "lottery-acceptance:" + secrets.token_hex(16), "kind": "lottery_draw",
                 "pool_id": "map", "count": 10, "request_id": request_id}
    payload = {"account_id": first, "config_hash": config_hash, "command": operation}
    drawn = client.success("POST", "/v1/archive/command", payload, "lottery_draw_failed")
    response = drawn.get("response", {})
    require(drawn.get("ok") is True and drawn.get("done") is True
            and isinstance(response, dict) and response.get("ok") is True
            and response.get("request_id") == request_id and response.get("count") == 10
            and response.get("state_persisted") is True
            and isinstance(response.get("results"), list) and len(response["results"]) == 10,
            "lottery_draw_receipt_invalid")
    after = client.profile(first)
    _, current = snapshot(client, first, config_hash)
    require(current["tickets"] == 20 - initial["ten_cost"] and current["draws"] == 10
            and after["revision"] > before["revision"], "lottery_draw_not_persisted")
    checks["real_lua_map_ten_draw"] = True
    for _ in range(2):
        replay = client.success("POST", "/v1/archive/command", payload, "lottery_replay_failed")
        require(replay.get("ok") is True and replay.get("done") is True
                and replay.get("response") == response
                and same_saved_state(after, client.profile(first)), "lottery_replay_changed_saved_state")
    checks["lottery_replay_same_request_exactly_once"] = True
    require(same_saved_state(other_before, client.profile(other)), "lottery_player_isolation_failed")
    other_drawn = client.success("POST", "/v1/archive/command", {**payload, "account_id": other},
                                "second_player_lottery_failed")
    other_after = client.profile(other)
    _, other_current = snapshot(client, other, config_hash)
    require(other_drawn.get("ok") is True and other_drawn.get("done") is True
            and other_current["tickets"] == 20 - initial["ten_cost"] and other_current["draws"] == 10
            and same_saved_state(after, client.profile(first)), "lottery_operation_player_scope_failed")
    checks["lottery_account_isolation"] = True
    for profile in (after, other_after):
        require(profile["save"].get("content_inventory", {}).get(SENTINEL) == 1,
                "lottery_permanent_content_lost")
    checks["permanent_content_preserved"] = True
    for route in ("/v1/archive/save", "/v1/profile/save", "/v1/save"):
        status, value = client.request("POST", route,
            {"account_id": first, "revision": before["revision"], "save": before["save"]})
        require(status in {404, 405} and value.get("ok") is False, "stale_raw_save_accepted")
    require(same_saved_state(after, client.profile(first)), "stale_raw_save_changed_inventory")
    checks["raw_save_cannot_replace_lottery_inventory"] = True
    report["verification"] = {"config_hash": config_hash,
        "players": [profile_summary(after), profile_summary(other_after)],
        "snapshot_sha256": [digest(snapshot(client, account, config_hash)[0]) for account in accounts]}
    report.update(status="PASS", code="lottery_upgrade_acceptance_passed")


def validate_report(value):
    fields = {"format", "generator", "mode", "status", "code", "started_at", "finished_at",
              "synthetic_accounts", "checks", "not_tested", "test_records_retained",
              "profile_read_side_effects", "verification"}
    require(isinstance(value, dict) and set(value) == fields, "lottery_report_fields_invalid")
    require(type(value["format"]) is int and value["format"] == FORMAT and value["generator"] == GENERATOR
            and value["mode"] == "write_test" and value["status"] == "PASS"
            and value["code"] == "lottery_upgrade_acceptance_passed"
            and value["test_records_retained"] is True and value["not_tested"] == NOT_TESTED
            and value["profile_read_side_effects"] == PROFILE_READ_EFFECTS,
            "lottery_report_source_invalid")
    accounts = value["synthetic_accounts"]
    require(isinstance(accounts, list) and len(accounts) == 2 and len(set(accounts)) == 2
            and all(isinstance(a, str) and re.fullmatch(r"900[0-9]{16}", a) for a in accounts),
            "lottery_report_accounts_invalid")
    require(isinstance(value["checks"], dict) and set(value["checks"]) == CHECKS
            and all(v is True for v in value["checks"].values()), "lottery_report_checks_invalid")
    for key in ("started_at", "finished_at"):
        require(isinstance(value[key], str) and len(value[key]) < 64, "lottery_report_time_invalid")
        require(datetime.fromisoformat(value[key]).tzinfo is not None, "lottery_report_time_invalid")
    evidence = value["verification"]
    require(isinstance(evidence, dict) and set(evidence) == {"config_hash", "players", "snapshot_sha256"},
            "lottery_report_evidence_invalid")
    require(isinstance(evidence["players"], list) and len(evidence["players"]) == 2
            and isinstance(evidence["snapshot_sha256"], list) and len(evidence["snapshot_sha256"]) == 2,
            "lottery_report_evidence_invalid")
    for hash_value in [evidence["config_hash"], *evidence["snapshot_sha256"]]:
        require(isinstance(hash_value, str) and re.fullmatch(r"[0-9a-f]{64}", hash_value),
                "lottery_report_digest_invalid")
    for account, player in zip(accounts, evidence["players"]):
        require(isinstance(player, dict) and set(player) == {"account_id", "revision", "boss_kills",
            "online_seconds_total", "archive_online_actual_seconds", "save_sha256"}
            and player["account_id"] == account, "lottery_report_player_invalid")
        require(type(player["revision"]) is int and 1 <= player["revision"] < 2**63
                and all(type(player[k]) is int and player[k] == 0 for k in
                    ("boss_kills", "online_seconds_total", "archive_online_actual_seconds"))
                and isinstance(player["save_sha256"], str)
                and re.fullmatch(r"[0-9a-f]{64}", player["save_sha256"]), "lottery_report_player_invalid")
    return value


def verify_previous(client, source, report):
    validate_report(source)
    ready = client.success("GET", "/ready", None, "database_readiness_failed")
    require(ready.get("ok") is True and ready.get("database") == "ready", "database_readiness_failed")
    evidence = source["verification"]
    config = client.success("POST", "/v1/archive/config", {}, "archive_config_failed")
    require(config.get("config_hash") == evidence["config_hash"], "lottery_reentry_config_changed")
    report["synthetic_accounts"] = list(source["synthetic_accounts"])
    for expected, expected_snapshot in zip(evidence["players"], evidence["snapshot_sha256"]):
        account = expected["account_id"]
        require(profile_summary(client.profile(account)) == expected, "lottery_reentry_saved_state_changed")
        require(digest(snapshot(client, account, evidence["config_hash"])[0]) == expected_snapshot,
                "lottery_reentry_snapshot_changed")
    report["checks"].update(prior_written_saved_state_retained=True, lottery_snapshots_retained=True,
                            no_new_business_commands_or_fixtures=True)
    report.update(status="PASS", code="lottery_prior_report_verified")


def main(argv=None):
    class Parser(argparse.ArgumentParser):
        def error(self, message):
            self.exit(2, '{"status":"FAIL","code":"cli_arguments_invalid"}\n')
    parser = Parser(description=__doc__)
    parser.add_argument("--base-url", default="http://127.0.0.1:8765")
    parser.add_argument("--token-file", type=Path, default=Path("/etc/goufayu/api-token"))
    parser.add_argument("--fixture-service")
    parser.add_argument("--fixture-passfile", type=Path,
                        help="Separate private libpq password FILE for fixture administration; never a password")
    parser.add_argument("--report", type=Path, required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--confirm-test-writes", action="store_true")
    mode.add_argument("--verify-report", type=Path)
    args = parser.parse_args(argv)
    report = {"format": FORMAT, "generator": GENERATOR,
        "mode": "verify_prior_report" if args.verify_report else "write_test",
        "status": "FAIL", "code": "not_started", "started_at": datetime.now(timezone.utc).isoformat(),
        "synthetic_accounts": [], "checks": {}, "not_tested": NOT_TESTED,
        "test_records_retained": True, "profile_read_side_effects": PROFILE_READ_EFFECTS}
    try:
        require(not args.report.exists() and not args.report.is_symlink(), "report_path_already_exists")
        target = loopback_target(args.base_url)
        if args.verify_report:
            require(not args.fixture_service and not args.fixture_passfile, "verify_fixture_service_refused")
            source = load_private_report(args.verify_report, validate_report)
            verify_previous(HttpClient(target, read_token(args.token_file)), source, report)
        else:
            require(os.environ.get("GOUFAYU_ACCEPTANCE") == "local-test", "explicit_test_environment_required")
            require(args.fixture_service, "fixture_service_required")
            private_fixture_passfile(args.fixture_passfile)
            sys.path.insert(0, os.environ["FISHING_BACKEND_ROOT"])
            from fishing_api.config import Settings
            from test_postgres_acceptance import build_current_test_application
            settings = Settings.from_env()
            require(settings.database_backend == "postgres" and settings.archive_http,
                    "postgres_archive_backend_required")
            require(target == (settings.host, settings.port), "live_target_settings_mismatch")
            token = read_token(args.token_file)
            require(hmac.compare_digest(token, settings.api_token), "live_token_settings_mismatch")
            app = build_current_test_application(settings)  # No configuration sync.
            fixture = Fixture(app, settings, args.fixture_service, args.fixture_passfile)
            run_write(HttpClient(target, token), app, fixture, report)
    except AcceptanceFailure as exc:
        report["code"] = str(exc)
    except Exception:
        # Driver and config exceptions can contain secrets. Never print their text.
        report["code"] = "lottery_acceptance_internal_failure"
    report["finished_at"] = datetime.now(timezone.utc).isoformat()
    if report["code"] != "report_path_already_exists":
        try:
            write_report(args.report, report)
        except AcceptanceFailure:
            report.update(status="FAIL", code="report_write_failed")
    print(json.dumps(report, ensure_ascii=False, separators=(",", ":")))
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
