-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_rogue_reward_effects")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_rogue_lumberjack_attack_speed") or _G.modifier_rogue_lumberjack_attack_speed, "Missing modifier class: modifier_rogue_lumberjack_attack_speed")
assert(type(definition) == "table", "Invalid modifier class: modifier_rogue_lumberjack_attack_speed")
modifier_rogue_lumberjack_attack_speed = definition
return definition
