-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_survival_hero_mana_standard")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_survival_hero_mana_standard") or _G.modifier_survival_hero_mana_standard, "Missing modifier class: modifier_survival_hero_mana_standard")
assert(type(definition) == "table", "Invalid modifier class: modifier_survival_hero_mana_standard")
modifier_survival_hero_mana_standard = definition
return definition
