-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_building_blink_move")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_building_blink_move") or _G.modifier_building_blink_move, "Missing modifier class: modifier_building_blink_move")
assert(type(definition) == "table", "Invalid modifier class: modifier_building_blink_move")
modifier_building_blink_move = definition
return definition
