-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_rogue_reward_effects")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_rogue_sharp_volley_growth, "Missing modifier class: modifier_rogue_sharp_volley_growth")
assert(type(definition) == "table", "Invalid modifier class: modifier_rogue_sharp_volley_growth")
rawset(getfenv(1), "modifier_rogue_sharp_volley_growth", definition)
