-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
if DoIncludeScript then DoIncludeScript("modifiers/modifier_equipment_effects", getfenv(1)) else require("modifiers/modifier_equipment_effects") end
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_equipment_effects") or _G.modifier_equipment_effects, "Missing modifier class: modifier_equipment_effects")
assert(type(definition) == "table", "Invalid modifier class: modifier_equipment_effects")
modifier_equipment_effects = definition
return definition
