-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_practice_monster_ai")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_practice_monster_ai, "Missing modifier class: modifier_practice_monster_ai")
assert(type(definition) == "table", "Invalid modifier class: modifier_practice_monster_ai")
rawset(getfenv(1), "modifier_practice_monster_ai", definition)
