-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_grid_building_preview")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_grid_building_preview, "Missing modifier class: modifier_grid_building_preview")
assert(type(definition) == "table", "Invalid modifier class: modifier_grid_building_preview")
rawset(getfenv(1), "modifier_grid_building_preview", definition)
