-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_blademaster_clone")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_blademaster_clone") or _G.modifier_blademaster_clone, "Missing modifier class: modifier_blademaster_clone")
assert(type(definition) == "table", "Invalid modifier class: modifier_blademaster_clone")
modifier_blademaster_clone = definition
return definition
