-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_single_health_bar")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_single_health_bar, "Missing modifier class: modifier_single_health_bar")
assert(type(definition) == "table", "Invalid modifier class: modifier_single_health_bar")
rawset(getfenv(1), "modifier_single_health_bar", definition)
