-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
if DoIncludeScript then DoIncludeScript("modifiers/modifier_survival_hero_base_health", getfenv(1)) else require("modifiers/modifier_survival_hero_base_health") end
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_survival_hero_base_health") or _G.modifier_survival_hero_base_health, "Missing modifier class: modifier_survival_hero_base_health")
assert(type(definition) == "table", "Invalid modifier class: modifier_survival_hero_base_health")
modifier_survival_hero_base_health = definition
return definition
