-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_rogue_combat_effects")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_rogue_training_attack") or _G.modifier_rogue_training_attack, "Missing modifier class: modifier_rogue_training_attack")
assert(type(definition) == "table", "Invalid modifier class: modifier_rogue_training_attack")
modifier_rogue_training_attack = definition
return definition
