-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_equipment_effects")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_equipment_effects, "Missing modifier class: modifier_equipment_effects")
assert(type(definition) == "table", "Invalid modifier class: modifier_equipment_effects")
rawset(getfenv(1), "modifier_equipment_effects", definition)
