-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
if DoIncludeScript then DoIncludeScript("modifiers/modifier_research_technology", getfenv(1)) else require("modifiers/modifier_research_technology") end
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_research_technology") or _G.modifier_research_technology, "Missing modifier class: modifier_research_technology")
assert(type(definition) == "table", "Invalid modifier class: modifier_research_technology")
modifier_research_technology = definition
return definition
