-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_survival_hero_projectile_speed")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_survival_hero_projectile_speed, "Missing modifier class: modifier_survival_hero_projectile_speed")
assert(type(definition) == "table", "Invalid modifier class: modifier_survival_hero_projectile_speed")
rawset(getfenv(1), "modifier_survival_hero_projectile_speed", definition)
