-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_lumberjack_cheer")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_lumberjack_cheer") or _G.modifier_lumberjack_cheer, "Missing modifier class: modifier_lumberjack_cheer")
assert(type(definition) == "table", "Invalid modifier class: modifier_lumberjack_cheer")
modifier_lumberjack_cheer = definition
return definition
