-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_weapon_attack_tracker")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_weapon_attack_tracker") or _G.modifier_weapon_attack_tracker, "Missing modifier class: modifier_weapon_attack_tracker")
assert(type(definition) == "table", "Invalid modifier class: modifier_weapon_attack_tracker")
modifier_weapon_attack_tracker = definition
return definition
