-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_hero_passive_skill_effects")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_hero_passive_skill_effect") or _G.modifier_hero_passive_skill_effect, "Missing modifier class: modifier_hero_passive_skill_effect")
assert(type(definition) == "table", "Invalid modifier class: modifier_hero_passive_skill_effect")
modifier_hero_passive_skill_effect = definition
return definition
