-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_research_technology")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_research_armor_reduction, "Missing modifier class: modifier_research_armor_reduction")
assert(type(definition) == "table", "Invalid modifier class: modifier_research_armor_reduction")
rawset(getfenv(1), "modifier_research_armor_reduction", definition)
