-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_wall_collision_barrier")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_wall_collision_barrier, "Missing modifier class: modifier_wall_collision_barrier")
assert(type(definition) == "table", "Invalid modifier class: modifier_wall_collision_barrier")
rawset(getfenv(1), "modifier_wall_collision_barrier", definition)
