-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_endless_training_target")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_endless_training_target, "Missing modifier class: modifier_endless_training_target")
assert(type(definition) == "table", "Invalid modifier class: modifier_endless_training_target")
rawset(getfenv(1), "modifier_endless_training_target", definition)
