-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
if DoIncludeScript then DoIncludeScript("modifiers/modifier_weapon_stat_projection", getfenv(1)) else require("modifiers/modifier_weapon_stat_projection") end
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_weapon_stat_projection") or _G.modifier_weapon_stat_projection, "Missing modifier class: modifier_weapon_stat_projection")
assert(type(definition) == "table", "Invalid modifier class: modifier_weapon_stat_projection")
modifier_weapon_stat_projection = definition
return definition
