-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_tower_auto_attack")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_tower_auto_attack") or _G.modifier_tower_auto_attack, "Missing modifier class: modifier_tower_auto_attack")
assert(type(definition) == "table", "Invalid modifier class: modifier_tower_auto_attack")
modifier_tower_auto_attack = definition
return definition
