-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_survival_managed_buff")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_survival_managed_aura") or _G.modifier_survival_managed_aura, "Missing modifier class: modifier_survival_managed_aura")
assert(type(definition) == "table", "Invalid modifier class: modifier_survival_managed_aura")
modifier_survival_managed_aura = definition
return definition
