-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_lumberjack_personality")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_lumberjack_personality, "Missing modifier class: modifier_lumberjack_personality")
assert(type(definition) == "table", "Invalid modifier class: modifier_lumberjack_personality")
rawset(getfenv(1), "modifier_lumberjack_personality", definition)
