-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_building_under_construction")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_building_under_construction") or _G.modifier_building_under_construction, "Missing modifier class: modifier_building_under_construction")
assert(type(definition) == "table", "Invalid modifier class: modifier_building_under_construction")
modifier_building_under_construction = definition
return definition
