-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_enemy_wall_ai")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_enemy_wall_ai, "Missing modifier class: modifier_enemy_wall_ai")
assert(type(definition) == "table", "Invalid modifier class: modifier_enemy_wall_ai")
rawset(getfenv(1), "modifier_enemy_wall_ai", definition)
