-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_hero_poison_cloud_armor")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_hero_poison_cloud_armor") or _G.modifier_hero_poison_cloud_armor, "Missing modifier class: modifier_hero_poison_cloud_armor")
assert(type(definition) == "table", "Invalid modifier class: modifier_hero_poison_cloud_armor")
modifier_hero_poison_cloud_armor = definition
return definition
