-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_rogue_reward_effects")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_rogue_tower_attack_projection") or _G.modifier_rogue_tower_attack_projection, "Missing modifier class: modifier_rogue_tower_attack_projection")
assert(type(definition) == "table", "Invalid modifier class: modifier_rogue_tower_attack_projection")
modifier_rogue_tower_attack_projection = definition
return definition
