-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_tower_attack_effects")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_tower_attack_effects") or _G.modifier_tower_attack_effects, "Missing modifier class: modifier_tower_attack_effects")
assert(type(definition) == "table", "Invalid modifier class: modifier_tower_attack_effects")
modifier_tower_attack_effects = definition
return definition
