-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_wall_collision_barrier")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_wall_collision_barrier") or _G.modifier_wall_collision_barrier, "Missing modifier class: modifier_wall_collision_barrier")
assert(type(definition) == "table", "Invalid modifier class: modifier_wall_collision_barrier")
modifier_wall_collision_barrier = definition
return definition
