-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_hero_ice_cone_freeze")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(rawget(getfenv(1), "modifier_hero_ice_cone_freeze") or _G.modifier_hero_ice_cone_freeze, "Missing modifier class: modifier_hero_ice_cone_freeze")
assert(type(definition) == "table", "Invalid modifier class: modifier_hero_ice_cone_freeze")
modifier_hero_ice_cone_freeze = definition
return definition
