-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_debug_fixed_attack_rate")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_debug_fixed_attack_rate, "Missing modifier class: modifier_debug_fixed_attack_rate")
assert(type(definition) == "table", "Invalid modifier class: modifier_debug_fixed_attack_rate")
rawset(getfenv(1), "modifier_debug_fixed_attack_rate", definition)
