-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_debug_move_speed_cap")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_debug_move_speed_cap, "Missing modifier class: modifier_debug_move_speed_cap")
assert(type(definition) == "table", "Invalid modifier class: modifier_debug_move_speed_cap")
rawset(getfenv(1), "modifier_debug_move_speed_cap", definition)
