-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_debug_combat_bonus")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_debug_attack_bonus, "Missing modifier class: modifier_debug_attack_bonus")
assert(type(definition) == "table", "Invalid modifier class: modifier_debug_attack_bonus")
rawset(getfenv(1), "modifier_debug_attack_bonus", definition)
