-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_tree_progression")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_tree_progression, "Missing modifier class: modifier_tree_progression")
assert(type(definition) == "table", "Invalid modifier class: modifier_tree_progression")
rawset(getfenv(1), "modifier_tree_progression", definition)
