-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.
require("modifiers/modifier_monkey_king_clone")
-- require may be cached and populate _G rather than this engine script scope.
local definition = assert(_G.modifier_monkey_king_clone, "Missing modifier class: modifier_monkey_king_clone")
assert(type(definition) == "table", "Invalid modifier class: modifier_monkey_king_clone")
rawset(getfenv(1), "modifier_monkey_king_clone", definition)
