$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$registry = Get-Content (Join-Path $repo 'scripts/vscripts/core/modifier_registry.lua') -Raw
$entries = [regex]::Matches($registry, 'name\s*=\s*"([^"]+)"\s*,\s*path\s*=\s*"([^"]+)"')
$output = Join-Path $repo 'scripts/vscripts/modifier_bindings'
New-Item -ItemType Directory -Path $output -Force | Out-Null
foreach ($entry in $entries) {
    $name = $entry.Groups[1].Value
    $module = $entry.Groups[2].Value
    $load = 'require("' + $module + '")'
    if ($name -in @('modifier_survival_hero_base_health','modifier_weapon_stat_projection','modifier_equipment_effects','modifier_research_technology')) {
        $load = 'if DoIncludeScript then DoIncludeScript("' + $module + '", getfenv(1)) else require("' + $module + '") end'
    }
    $lines = @(
        '-- Generated by tools/build_modifier_bindings.ps1. Engine script entry; do not require this file.'
        $load
        '-- require may be cached and populate _G rather than this engine script scope.'
        ('local definition = assert(rawget(getfenv(1), "' + $name + '") or _G.' + $name + ', "Missing modifier class: ' + $name + '")')
        ('assert(type(definition) == "table", "Invalid modifier class: ' + $name + '")')
        ($name + ' = definition')
        'return definition'
    )
    [IO.File]::WriteAllText((Join-Path $output ($name + '.lua')), ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
}
Write-Output ('MODIFIER_BINDINGS_BUILT: ' + $entries.Count)
