const fs=require('fs'),path=require('path');const out='art/ui/development/daily_rewards_import/preview';fs.mkdirSync(out,{recursive:true});
let adapter=fs.readFileSync('art/ui/development/ui_reuse_import/preview/adapter.js','utf8');
adapter=adapter.replace("set hittest(v){}set hittestchildren(v){}","set hittest(v){this._hit=v;}set hittestchildren(v){}");
adapter=adapter.replace('AddClass(c){',"SetScaling(v){this.el.style.objectFit=v==='stretch-to-fit'?'fill':'contain'}ToggleClass(c){this.el.classList.toggle(c)}RemoveAndDeleteChildren(){this.children=[];this.el.replaceChildren()}FindChildTraverse(id){if(this.id===id)return this;for(const c of this.children){const p=c.FindChildTraverse(id);if(p)return p;}return null}AddClass(c){");
adapter=adapter.replace('GameEvents={Subscribe(){},Unsubscribe(){}}','GameEvents={Subscribe(n,f){events[n]=f;return n},Unsubscribe(n){delete events[n]},SendCustomGameEventToServer(n,p){requests.push({n,p})}}');
adapter='const events={},requests=[];\n'+adapter;
adapter=adapter.replace("this.events[n]=fn;this.el.addEventListener(n==='onactivate'?'click':n.slice(2),fn)","const wrapped=e=>{if(n==='onactivate')e.stopPropagation();fn(e)};this.events[n]=wrapped;this.el.addEventListener(n==='onactivate'?'click':n.slice(2),wrapped)");
fs.writeFileSync(out+'/adapter.js',adapter);
let css=fs.readFileSync('panorama/src/styles/custom_game/daily_rewards.css','utf8')+fs.readFileSync('panorama/src/styles/custom_game/daily_assets.css','utf8');
css=css.replaceAll('file://{images}/','../../../panorama/src/images/').replaceAll('UIFontHeading','"Source Han Serif SC"').replace(/\bLabel\b/g,'.label').replace(/\bButton\b/g,'.button').replace(/font-weight:medium/g,'font-weight:500').replace(/position:\s*([\d.-]+)px\s+([\d.-]+)px\s+0px/g,'position:absolute;left:$1px;top:$2px').replace(/flow-children:down/g,'display:flex;flex-direction:column').replace(/flow-children:right/g,'display:flex;flex-direction:row').replace(/flow-children:none/g,'display:block').replace(/align:center center/g,'left:50%;top:50%;transform:translate(-50%,-50%)').replace(/horizontal-align:center/g,'left:50%;transform:translateX(-50%)').replace(/overflow:squish scroll/g,'overflow:auto').replace(/@keyframes '([^']+)'/g,'@keyframes $1');
css+='\n*{box-sizing:border-box}.panel{position:absolute}.label{display:block;position:absolute;line-height:1.45;font-family:"Source Han Sans SC";pointer-events:none}.ArchiveHidden,.UIClosed{display:none!important}.UIModalScrim{position:fixed;inset:0;width:100%;height:100%}.DailyText{position:relative}.DailyItems .DailyReward{position:relative;flex-shrink:0}.DailyNormalCard,.DailyWeekCard{background-size:100% 100%}#DailyClaimPage,#DailyFrame,#DailyHeader{pointer-events:none}#DailyClaimPage>.panel,#DailyHeader>.panel{pointer-events:auto}#DailyCards{pointer-events:none}#DailyCards>.panel{pointer-events:auto}#DailyHeading{pointer-events:none!important}#DailyWindow .DailyDay{left:0;top:23px}#DailyWindow .DailyRewardName{left:0}.DailyItemArt{top:0}.DailySpecial .label{position:relative}#DailyPassPage>.label{position:relative}#DailyPassPage #DailySpecials,#DailyPassPage .button{position:relative}#DailyClaim .label,#DailyMakeup .label{top:50%;transform:translateY(-50%);left:0}#DailyPassStatusText{top:13px}#DailyHeader{z-index:10}#DailyClose .DailyIconArt{left:-8px;top:-8px;transform:none}.DailyBaseReward .DailyItemArt{left:0;transform:none}#DailyRules .label{top:12px}#DailyWindow .DailySection{font-size:28px}body{margin:0;background:#263b42;width:100vw;height:100vh;position:relative;overflow:hidden}#DailyHeading{font-family:"Source Han Serif SC"!important;font-weight:700!important}';
for(const [face,family,weight] of [['SansSC-Regular','Sans',400],['SansSC-Medium','Sans',500],['SerifSC-Bold','Serif',700]])css+=`\n@font-face{font-family:"Source Han ${family} SC";font-weight:${weight};src:url('../../../panorama/fonts/Radiance-Survival-SourceHan${face}.otf')}`;
fs.writeFileSync(out+'/style.css',css);
const xml=fs.readFileSync('panorama/src/layout/custom_game/archive.xml','utf8');
const boot=`const xml=${JSON.stringify(xml)};const tree=new DOMParser().parseFromString(xml,'text/xml');function mount(node,parent){const p=new Panel(node.tagName,parent,node.getAttribute('id')||'');if(node.tagName==='Button')p.el.classList.add('button');(node.getAttribute('class')||'').split(' ').filter(Boolean).forEach(c=>p.AddClass(c));if(node.hasAttribute('text'))p.text=node.getAttribute('text');for(const c of node.children)mount(c,p);return p;}for(const id of ['DailyEntry','PassEntry','DailyScrim','DailyWindow'])mount(tree.querySelector('[id="'+id+'"]'),root);`;
const scripts=['common/ui_registry','daily_resources','ui_layers','common/ui_components','daily_rewards'].map(n=>`<script src="../../../panorama/src/scripts/custom_game/${n}.js"></script>`);
fs.writeFileSync(out+'/index.html',`<!doctype html><meta charset="utf-8"><title>每日奖励 · 代码运行预览（非游戏截图）</title><link rel="stylesheet" href="style.css"><body><script src="adapter.js"></script><script>${boot}</script>${scripts.join('')}<script src="fixture.js"></script></body>`);
// Parse actual project CSV rewards for the preview; never copy kit mock economy.
function csv(file){return fs.readFileSync(file,'utf8').trim().split(/\r?\n/).filter(s=>!s.startsWith('#')).map(s=>(s.match(/("[^"]*"|[^,]+)(,|$)/g)||[]).map(v=>v.replace(/,$/,'').replace(/^"|"$/g,'')));}
function rows(file){const a=csv(file),h=a.shift();return a.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])));}
const items=Object.fromEntries(rows('data/csv/存档系统/archive_daily_items.csv').map(i=>[i.item_id,i]));
const cycle=rows('data/csv/存档系统/archive_daily_schedule.csv').map(r=>({day:Number(r.day_id),is_today:r.day_id==='7'?1:0,status:r.day_id==='7'?'claimable':'claimed',rewards:r.item_ids.split('|').map((id,i)=>({id,name:items[id].display_name,description:items[id].description,count:Number(r.item_counts.split('|')[i])}))}));
const fixture={ok:true,sequence:1,today:25000,count:6,claimed:0,ordinary_status:'claimable',cycle_mode:'claim_count',period_id:'0',has_pass:1,cycle,specials:[],pending:0,missed:[24999],purchase_enabled:0,price:'价格待配置',duration_days:30,subtitle:'每日领取 · 七次循环',rule_text:'每日零点刷新；断签不重置累计进度。通行证奖励按累计签到次数发放。',premium:{status:'unconfigured',name:'周末高级装备',description:'周周期与装备候选池尚未配置。'}};
fs.writeFileSync(out+'/fixture.js','const fixture='+JSON.stringify(fixture)+';config.SurvivalDaily.Open(false);events.survival_daily_snapshot(fixture);window.previewReady=true;');
console.log('DAILY_PREVIEW_BUILT: actual UI/controller/components + project reward fixtures, not native game capture');
