const fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'../output/terrain_reference_review');fs.mkdirSync(out,{recursive:true});
const groups=[
 {id:'A',name:'大圣的新游记',note:'重点看东方园林的整体搭配：石路、岸边构件、松树与草地的比例。作为修仙风格的起点候选。',source:'https://www.dota2.com/700/monkeyking',images:['https://cdn.steamstatic.com/apps/dota2/images/700/hero/terrain_06.jpg','https://cdn.steamstatic.com/apps/dota2/images/700/hero/terrain_07.jpg']},
 {id:'B',name:'不朽庭院',note:'重点比较石材铺装的细节与地面、植被之间的边界处理。留意规整庭院是否符合你想要的感觉。',source:'https://www.dota2.com/international2016/battlepass?l=english',images:['https://cdn.steamstatic.com/apps/dota2/images/international2016/battle_pass/colosseum_images/4.jpg','https://cdn.steamstatic.com/apps/dota2/images/international2016/battle_pass/colosseum_images/7.jpg']},
 {id:'C',name:'官方天辉河岸 · Wandering Waters',note:'重点看自然岸坡、石块、树丛与水面如何组合。适合判断你更喜欢自然山水还是人工庭院。',source:'https://www.dota2.com/wanderingwaters',images:['https://cdn.akamai.steamstatic.com/apps/dota2/images/dota_react/patch738/comparison/radiant/new/T2Approach_R.jpg','https://cdn.steamstatic.com/apps/dota2/images/dota_react/patch738/comparison/radiant/new/BaseCorner_R.jpg']}
];
(async()=>{
 await Promise.all(groups.flatMap(g=>g.images.map(async(url,i)=>{const file=g.id+'_'+(i+1)+'.jpg';const r=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(url+' '+r.status);const b=Buffer.from(await r.arrayBuffer());if(b[0]!==255||b[1]!==216)throw Error('Not JPEG '+url);fs.writeFileSync(path.join(out,file),b);} )));
 fs.writeFileSync(path.join(out,'sources.json'),JSON.stringify(groups,null,2));
 const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>地形方向选择 · 官方实景</title><style>*{box-sizing:border-box}body{margin:0;background:#e5e8e4;color:#263931;font:17px/1.7 system-ui}main{max-width:1500px;margin:auto;padding:28px}h1{font-size:28px}p{max-width:1050px}nav{position:sticky;top:0;background:#e5e8e4f5;padding:14px;z-index:2}a{color:#265f69}nav a{margin-right:28px}section{scroll-margin-top:80px;margin-top:45px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;background:#f6f6f0;padding:10px}img{width:100%;display:block;cursor:zoom-in}figcaption{padding:8px 0}dialog{max-width:96vw;border:0;padding:8px;background:#263931}dialog img{max-width:92vw;max-height:88vh;width:auto}button{padding:10px;cursor:pointer}small{display:block} @media(max-width:850px){.grid{grid-template-columns:1fr}}</style><main><h1>先选场景方向，再做局部样板</h1><p>下面是 Valve 官方页面中的地形实景展示，保留原图。它们用于选视觉方向，不代表已确认整套资源可以直接移植到当前项目。</p><p>先选一组作为主要参考，也可以明确指出另一组中只想借鉴的部分，例如“以 A 为主，水边参考 C”。重点比较地形轮廓、材质尺度、颜色与明暗、植被分布。暂不修改整张地图。</p><nav>${groups.map(g=>`<a href="#${g.id}">${g.id} · ${g.name}</a>`).join('')}</nav>${groups.map(g=>`<section id="${g.id}"><h2>${g.id} · ${g.name}</h2><p>${g.note} <a href="${g.source}" target="_blank">官方出处</a></p><div class="grid">${g.images.map((u,i)=>`<figure><img src="${g.id}_${i+1}.jpg" alt="${g.name} 官方截图 ${i+1}" onclick="document.querySelector('#large').src=this.src;document.querySelector('dialog').showModal()"><figcaption>${g.id}${i+1} · 点击放大 <a href="${u}" target="_blank">原图</a></figcaption></figure>`).join('')}</div></section>`).join('')}<section><h2>选定后的执行范围</h2><p>先核对本地材质、法线、混合遮罩、模型和着色器。只做一块约一至两屏大小的实机样板：一座岛的岸边、草地、石路、台阶和相邻水面。固定正常游戏视角与近景，对照参考逐项调整；样板认可后再扩展到其他房间与全图。</p><p>现有格局保留为工作底稿；本轮圆形岛的外观尚未获认可，不作为最终美术基准。不要把概念图或这些整张截图直接当作材质。</p></section></main><dialog><button onclick="document.querySelector('dialog').close()">关闭</button><img id="large"></dialog></html>`;
 fs.writeFileSync(path.join(out,'index.html'),html);console.log('Reference review: '+out+'; '+groups.length+' groups / 6 official screenshots');
})().catch(e=>{console.error(e);process.exitCode=1;});
