const fs=require('fs'),path=require('path');
const dir='art/ui/development/ui_reuse_import/preview';fs.mkdirSync(dir,{recursive:true});const registry=JSON.parse(fs.readFileSync('art/ui/development/ui_reuse_import/runtime_registry.json'));
let css=fs.readFileSync('panorama/src/styles/custom_game/common/ui_components.css','utf8').replace(/ui-resource:\/\/([\w.-]+)/g,(_,id)=>'../../../panorama/src/images/'+registry.assets[id].runtime).replace(/:selected/g,'.checked').replace(/visibility:collapse/g,'visibility:hidden').replace(/flow-children:right-wrap/g,'display:flex;flex-wrap:wrap').replace(/flow-children:right/g,'display:flex;flex-direction:row').replace(/flow-children:down/g,'display:flex;flex-direction:column');
// Add forced pseudo states for visual comparison; source artwork and components stay identical.
css+='\n'+css.split(/(?<=})/).filter(r=>/:hover|:active|:disabled/.test(r)).map(r=>r.replaceAll(':hover','.PreviewHover').replaceAll(':active','.PreviewPressed').replaceAll(':disabled','.UIDisabled')).join('\n');css=css.replace(/brightness:([.\d]+);/g,'filter:brightness($1);');fs.writeFileSync(dir+'/shared.css',css);
fs.writeFileSync(dir+'/index.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>共用 UI 组件状态页</title><link rel="stylesheet" href="shared.css"><style>
*{box-sizing:border-box}body{margin:0;background:#142b35;color:#d0d6d5;font-family:'Source Han Sans SC','Microsoft YaHei',sans-serif}#page{width:1510px;margin:24px auto;padding:24px}h1{font-family:'Source Han Serif SC',SimSun,serif;font-size:30px;margin:0 0 8px}.note{color:#a7bbbf;font-size:15px;margin-bottom:24px}.row{display:grid;grid-template-columns:120px repeat(6,1fr);align-items:center;gap:8px;margin-bottom:18px}.row>label{font-size:17px}.demo{height:76px;display:flex;align-items:center;justify-content:center;position:relative}.columns{height:26px;text-align:center;font-size:15px;color:#c7b88f}.panel{position:relative;flex-shrink:0}.label{display:block;white-space:pre-wrap;pointer-events:none}.UIIconButton,.UIActionButton,.UITab,.UINavToggle,.UICheckbox{cursor:pointer}.UIActionButton{width:208px;height:52px}.UIButtonLabel,.UITabLabel{position:absolute;width:100%;top:50%;transform:translateY(-50%);text-align:center}.UIIcon{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%)}.UIIconButton .UIIcon{top:6px;transform:translateX(-50%)}.UIIconImage{position:absolute;max-width:none}.UIIconLabel{position:absolute;bottom:0}.UITab{width:207px;height:52px;background-repeat:no-repeat}.UINavToggle{width:207px;height:64px}.UINavLabel{position:absolute;left:0;top:50%;transform:translateY(-50%)}.UINavToggle .UIIcon{left:10px;transform:translateY(-50%);margin-left:8px}.UICheckOff,.UICheckOn{position:absolute;left:10px;top:50%;transform:translateY(-50%)}.UICheckboxLabel{position:absolute;top:50%;transform:translateY(-50%)}.UIDisabled{cursor:default}.UICardTitle{position:absolute;bottom:10px}.UIProgressBadge{position:absolute;right:3px;top:3px}.UICardSquare{height:157px;background-repeat:no-repeat}.UICardArt{position:absolute;left:50%;transform:translateX(-50%);object-fit:contain}.bottom{display:flex;gap:24px;margin-top:28px}.gallery{width:740px;padding:20px;background:#24404a;border:1px solid #50646b}.gallery h2{margin:0 0 18px;font-size:20px;font-weight:500}.cards{display:flex;gap:20px}.caption{margin-top:12px;color:#aabec2;font-size:14px;line-height:1.6}.UIModal{position:fixed!important;left:50%;top:50%;transform-origin:center;box-shadow:0 10px 40px #0006;overflow:hidden}.UIModalHeader{height:76px;padding:18px 24px;border-bottom:1px solid #c7b88f}.UIModalHeader>.label{font-family:SimSun,serif;font-size:28px}.UICloseButton{position:absolute;right:16px;top:16px;cursor:pointer}.UIModalScrim{position:fixed;inset:0}.UIModalHitArea{position:absolute;inset:0}.UIClosed{display:none}.sampleBody{padding:26px;color:#203e4a;font-size:20px;line-height:1.8}.sampleBody small{display:block;font-size:16px}.UIBundleItem{gap:4px}.UIPriceLabel{margin-top:12px}.sampleCard{width:280px;height:240px;padding:12px}.sampleCard>.UICardTitle{position:static}.sampleCard>.UIActionButton{position:absolute;bottom:12px}.UICaption{font-size:15px}.modalButtons{display:flex;gap:14px;margin-top:20px}
</style><div id="page"><h1>苟发育 · 共用 UI 状态样例</h1><div class="note">浏览器组件预览，不是游戏实机截图。使用游戏同一份注册表、组件脚本和状态素材；样例文案及数字仅用于组件测试。</div><div id="matrix"></div><div class="bottom"><section class="gallery"><h2>卡片／数据标记／透明边缘</h2><div id="cards" class="cards"></div><div class="caption">玉白卡体与进度标记按独立资源绘制。未提供上限时隐藏分母；选中不改变单元尺寸。物品图仅此样例使用登记的展示素材。</div></section><section class="gallery"><h2>共用弹窗与商品内容变体</h2><div id="product"></div><div class="modalButtons" id="modalButtons"></div><div class="caption">窗口框暂用共用细线底板；干净透明九宫格在素材包中尚未提供。五分栏商品业务数据没有接入时不造数据。</div></section></div></div><script src="adapter.js"></script><script src="../../../panorama/src/scripts/custom_game/common/ui_registry.js"></script><script src="../../../panorama/src/scripts/custom_game/ui_layers.js"></script><script src="../../../panorama/src/scripts/custom_game/common/ui_components.js"></script><script src="demo.js"></script></html>`);
console.log('SHARED_PREVIEW_BUILD_PASS');
// The browser adapter uses the same role sheet; only this preview gets @font-face.
let typography=fs.readFileSync('panorama/src/styles/custom_game/common/ui_typography.css','utf8');
const definitions={};typography=typography.replace(/@define\s+(\w+):\s*([^;]+);/g,(_,key,value)=>{definitions[key]=value;return '';});
for(const [key,value]of Object.entries(definitions))typography=typography.replaceAll(': '+key+';',': '+value+';');
typography=typography.replace(/font-weight:\s*medium/g,'font-weight:500').replace(/\bLabel\b/g,'.label').replace(/\bTextEntry\b/g,'input').replace(/\b(?:Button|RadioButton|ToggleButton)\b/g,'.button');
for(const [file,family,weight]of [['SourceHanSansSC-Regular','Source Han Sans SC',400],['SourceHanSansSC-Medium','Source Han Sans SC',500],['SourceHanSerifSC-Bold','Source Han Serif SC',700]])typography+='\n@font-face{font-family:"'+family+'";font-weight:'+weight+';src:url("../../../panorama/fonts/Radiance-Survival-'+file+'.otf") format("opentype");}';
fs.writeFileSync(dir+'/typography.css',typography);
let html=fs.readFileSync(dir+'/index.html','utf8').replace('</style>','</style><link rel="stylesheet" href="typography.css">');
html=html.replace('.UIModalHeader>.label{font-family:SimSun,serif;','.UIModalHeader>.label{');
fs.writeFileSync(dir+'/index.html',html);
