"""Generate archive color consumers from one editable palette."""
import json,re
from pathlib import Path
root=Path(__file__).resolve().parent.parent
colors=json.loads((root/'data/ui/archive_theme.json').read_text(encoding='utf-8'))
# The ability tooltip is the visual reference approved by the user. Derive the
# entire surface from its real style, including alpha, rather than a similar RGB.
ability_css=(root/'panorama/src/styles/custom_game/ability_tooltip.css').read_text(encoding='utf-8')
ability_surface=re.search(r'#CustomAbilityTooltip\s*\{([^}]+)\}',ability_css).group(1)
def tooltip_property(name):
    return re.search(r'(?:^|;)\s*'+re.escape(name)+r'\s*:\s*([^;]+);',ability_surface).group(1).strip()
# The user now chooses the saturated lumberjack training panel for backgrounds.
# Keep the approved ability typography below; remove alpha so scenery cannot tint it.
production_css=(root/'panorama/src/styles/custom_game/production_progress.css').read_text(encoding='utf-8')
production_surface=re.search(r'#SurvivalProductionPanel\s*\{([^}]+)\}',production_css).group(1)
production_background=re.search(r'background-color\s*:\s*([^;]+);',production_surface).group(1).strip()
colors['surface_52']=re.sub(r'#([0-9a-fA-F]{6})[0-9a-fA-F]{2}\b',r'#\1',production_background)
colors['surface_53']=tooltip_property('border').split()[-1]
colors['tooltip_shadow']=tooltip_property('box-shadow')
# Text roles share the reference's actual colors too: white body, grey labels,
# gold values. Keep this in the generator so CSS and runtime cannot drift.
def reference_color(selector):
    block=re.search(re.escape(selector)+r'\s*\{([^}]+)\}',ability_css).group(1)
    return re.search(r'(?:^|;)\s*color\s*:\s*([^;]+);',block).group(1).strip()
colors['body']=colors['name']=reference_color('#CustomAbilityDescription')
colors['heading']=reference_color('#CustomAbilityTitle')
colors['number']=colors['progress']=colors['selected']=reference_color('.AbilityFieldValue')
colors['muted']=colors['detail_heading']=reference_color('.AbilityFieldLabel')
def reference_property(selector, name):
    block=re.search(re.escape(selector)+r'\s*\{([^}]+)\}',ability_css).group(1)
    return re.search(r'(?:^|;)\s*'+re.escape(name)+r'\s*:\s*([^;]+);',block).group(1).strip()
colors['tooltip_font']=reference_property('#CustomAbilityTooltip Label','font-family')
colors['tooltip_title_size']=reference_property('#CustomAbilityTitle','font-size')
colors['tooltip_body_size']=reference_property('#CustomAbilityDescription','font-size')
colors['tooltip_field_size']=reference_property('.AbilityFieldLabel','font-size')
colors['tooltip_meta_size']=reference_property('#CustomAbilityLevel','font-size')
# Match the actual rendered training instruction (33px at its minimum HUD scale).
job_style=re.search(r'\.ProductionJobName\s*\{([^}]+)\}',production_css).group(1)
job_size=float(re.search(r'font-size\s*:\s*([\d.]+)px',job_style).group(1))
colors['archive_text_size']=str(round(job_size*0.5*1.15))+'px'
for role in ['tooltip_title_size','tooltip_body_size','tooltip_field_size','tooltip_meta_size']:
    colors[role]=colors['archive_text_size']
colors['tooltip_padding']=tooltip_property('padding')
colors['tooltip_width']=tooltip_property('width')
# Every surface directly behind archive text/art uses the reference's opaque base.
for role in ['surface_16','surface_17','surface_32','surface_33','surface_35','surface_37','icon_surface']:
    colors[role]=colors['surface_52']
colors['tab']=colors['body']




template=(root/'data/ui/archive_comfort.template.css').read_text(encoding='utf-8')
css=re.sub(r'\{\{(\w+)\}\}',lambda m: colors[m.group(1)],template)
(root/'panorama/src/styles/custom_game/archive_comfort.css').write_text('/* Generated by tools/build_archive_theme.py; edit data/ui/archive_theme.json; background follows production_progress.css; typography follows ability_tooltip.css. */\n'+css,encoding='utf-8')
(root/'panorama/src/scripts/custom_game/archive_theme_tokens.js').write_text('// Generated from data/ui/archive_theme.json and ability_tooltip.css.\nGameUI.CustomUIConfig().SurvivalArchiveColors = '+json.dumps(colors,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
