$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$engine=(Resolve-Path (Join-Path $repo '../../..')).Path
$content=Join-Path $engine 'content/dota_addons/survival/panorama'
$compiler=Join-Path $engine 'game/bin/win64/resourcecompiler.exe'
$files=@('scripts/custom_game/commerce_remaining_5d5c1152eb.js','scripts/custom_game/payment_test.js','styles/custom_game/payment_test.css','layout/custom_game/payment_test.xml','layout/custom_game/custom_ui_manifest.xml')
$catalogFile=Join-Path $repo 'output/payment_catalog.json'
if(Test-Path -LiteralPath $catalogFile){
 $catalog=Get-Content -LiteralPath $catalogFile -Raw -Encoding UTF8 | ConvertFrom-Json
 $images=@()
 foreach($icon in @($catalog.catalog.products.icon | Sort-Object -Unique)){
  if($icon -notmatch '^custom_game/[A-Za-z0-9_/-]+\.png$' -or $icon.Contains('..')){throw 'Invalid payment icon path.'}
  $files+=('images/'+$icon)
  $images+=('    <Image src="file://{images}/'+$icon+'" />')
 }
 # PNGs are Panorama layout dependencies, not direct resourcecompiler inputs.
 # Compile a generated dependency layout so dynamically configured icons exist.
 $assetRelative='layout/custom_game/payment_catalog_assets.xml'
 $assetSource=Join-Path $repo ('panorama/src/'+$assetRelative)
 $assetXml="<!-- Generated by tools/build_payment_ui.ps1 from the validated shop catalog. -->`n<root>`n  <Panel hittest=`"false`">`n"+($images -join "`n")+"`n  </Panel>`n</root>`n"
 [IO.File]::WriteAllText($assetSource,$assetXml,[Text.UTF8Encoding]::new($false))
 $files+=$assetRelative
}
$backup=Join-Path $repo ('output/payment_ui_backup/'+(Get-Date -Format 'yyyyMMdd_HHmmss'))
foreach($relative in $files){
 $from=Join-Path $repo ('panorama/src/'+$relative)
 $to=Join-Path $content $relative
 if(Test-Path -LiteralPath $to){$old=Join-Path $backup $relative;New-Item -ItemType Directory -Force (Split-Path $old)|Out-Null;Copy-Item -LiteralPath $to -Destination $old}
 New-Item -ItemType Directory -Force (Split-Path $to)|Out-Null
 Copy-Item -LiteralPath $from -Destination $to -Force
 if($relative.StartsWith('images/')){continue}
 $result=@(& $compiler -i $to -game (Join-Path $engine 'game/dota') -nop4)
 $result|Where-Object{$_ -match 'ERROR:|FAIL|WARNING|OK:|Failed to'}|Write-Output
 if($LASTEXITCODE -ne 0){throw "Payment UI compilation failed: $relative"}
}
Write-Output 'PAYMENT_UI_BUILD_PASS'
