// Use the same resolver as the live shop; emit engine KV and server mappings.
const fs=require('fs'),vm=require('vm'),path=require('path');
const config={};vm.runInNewContext(fs.readFileSync('panorama/src/scripts/custom_game/item_art_remaining_5d5c1152eb.js','utf8'),{GameUI:{CustomUIConfig:()=>config}});
const resolve=config.SurvivalItemArt.ResolveOriginal;
const texture=(v,id)=>/^(?:weapon_|item_survival_)ice_blade_/.test(id)?'survival_unified/extreme_cold_blade_v2':'survival_shop_v2/'+v[0]+'_'+String(v[1]).padStart(2,'0');
const mappings={};
for(const file of ['weapon_definitions','item_definitions'])for(const line of fs.readFileSync('data/csv/物品系统/'+file+'.csv','utf8').split(/\r?\n/)){
 const id=line.split(',')[0],v=resolve(id);if(v)mappings[id]=texture(v,id);
}
const file='scripts/npc/npc_items_custom.txt';let count=0;
const kv=fs.readFileSync(file,'utf8').replace(/("(item_[^"]+)"\s*\{)([^{}]*)(\})/g,(all,start,id,body,end)=>{
 const v=resolve(id);if(!v)return all;
 mappings[id]=texture(v,id);count++;
 return start+body.replace(/("AbilityTextureName"\s*)"[^"]*"/,'$1"'+texture(v,id)+'"')+end;
});
fs.writeFileSync(file,kv);
fs.writeFileSync('scripts/vscripts/config/inventory_original_icons.lua','-- Generated by tools/build_inventory_icon_manifest.cjs from the live shop resolver.\nreturn {\n'+Object.keys(mappings).sort().map(id=>'    ["'+id+'"] = "'+mappings[id]+'",').join('\n')+'\n}\n');
const manifest=[];for(const[atlas,n]of[['shop',4],['swords',5],['challenges',5]])for(let i=0;i<n*n;i++)manifest.push({atlas,grid:n,index:i,file:atlas+'_'+String(i).padStart(2,'0')+'.png'});
fs.writeFileSync('panorama/src/images/custom_game/shop_v2/inventory_manifest.json',JSON.stringify({nativeItems:count,mappings,images:manifest},null,2));
fs.writeFileSync('panorama/src/layout/custom_game/inventory_original_assets.xml','<root><Panel>'+manifest.map(m=>'<Image src="file://{images}/items/survival_shop_v2/'+m.file+'" />').join('')+'</Panel></root>');
console.log('Mapped '+count+' native items; '+Object.keys(mappings).length+' total identities.');
