const fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'../output/terrain_reference_review/open_ground');fs.mkdirSync(out,{recursive:true});
const refs=[
{id:'D1',name:'开阔草坪 · Anemo 场景资源演示',kind:'Unity 资源包演示图，仅作外观参考',note:'看大面积草地的冷暖变化、不同密度的草、少量裸露地面。建筑和树木退到边缘，中央仍然开阔。',source:'https://www.gameassetdeals.com/asset/208171/anemo-open-world-stylized-island-environment',url:'https://assetstorev1-prd-cdn.unity3d.com/package-screenshot/e7197e6f-3e8b-4cb6-b9c9-83926d860c86_scaled.jpg'},
{id:'D2',name:'起伏草甸 · 原神蒙德原野',kind:'HoYoLAB 玩家实机截图；第三人称视角',note:'看连续的大块草色、稀疏花草与远近层次。只参考色彩和疏密，高草密度与地势不能直接照搬到俯视战斗场地。',source:'https://www.hoyolab.com/article/271831',url:'https://upload-os-bbs.hoyolab.com/upload/2021/03/29/104988318/642ad371086cdc4497a13d2dc4ceb223_2327693248005770345.png'},
{id:'E1',name:'中央留白 · TFT 灵魂莲华场地',kind:'游戏场地展示图，来自 Mobalytics',note:'看中央连续的开阔地面如何通过大尺度纹样和材质变化获得细节；桃花、建筑与水景集中在场地外围。适合讨论主城或大挑战房的留白。',source:'https://mobalytics.gg/blog/tft/tft-positioning-guide-how-to-get-the-most-from-your-units/',url:'https://cdnportal.mobalytics.gg/production/2025/07/TFT-Set-15-Spirit-Blossom-Arena-2000x1125.jpg'},
{id:'E2',name:'旧石与苔草 · LoL Arena',kind:'Riot 官方场地展示图',note:'看低对比石纹、裂缝和苔草如何共同组成大片地面。此图中央有障碍，借鉴地面处理即可，不照搬障碍布局。',source:'https://www.leagueoflegends.com/en-gb/news/dev/dev-leveling-up-arena/',url:'https://cmsassets.rgpub.io/sanity/images/dsfx7636/news_live/0db09579a157f5f7e6d793bdf8ee3d41503a7c99-1416x1080.jpg'},
{id:'F1',name:'开阔旧石平台 · LoL Arena',kind:'游戏场地展示图，来自 AltChar',note:'看大块旧石地面、环形纹理和少量苔草形成的变化。重点观察三个开阔平台内部，布局和外围构筑物仅作背景。',source:'https://www.altchar.com/game-news/league-of-legends-arena-2v2v2v2-game-mode-will-return-during-the-msi-event-aIyWU9z6BCyU',url:'https://media.altchar.com/prod/images/gm_article_promo_image/62531f0a5263-desert-oasis.png'},
{id:'F2',name:'冰雪战斗空地 · LoL Arena',kind:'竞技场展示图转载，来自 Wallpaper Abyss',note:'看浅色空地里的冰裂纹、深浅冰色、积雪和边缘岩石。适合讨论冰雪练功房，中央仍保留大面积活动空间。',source:'https://wall.alphacoders.com/big.php?i=1320097',url:'https://images6.alphacoders.com/132/thumb-1920-1320097.jpeg'}
];
(async()=>{
 const results=await Promise.allSettled(refs.map(async r=>{const res=await fetch(r.url,{signal:AbortSignal.timeout(25000)});if(!res.ok)throw Error(res.status+' '+r.id);const b=Buffer.from(await res.arrayBuffer());const ext=b[0]===255&&b[1]===216?'jpg':b[0]===137?'png':b.toString('ascii',8,12)==='WEBP'?'webp':null;if(!ext)throw Error('Not image '+r.id);r.file=r.id+'.'+ext;fs.writeFileSync(path.join(out,r.file),b);return r.id;}));
 results.forEach((r,i)=>{if(r.status==='rejected'){refs[i].error=String(r.reason);console.error(refs[i].id,refs[i].error);}});
 fs.writeFileSync(path.join(out,'sources.json'),JSON.stringify(refs,null,2));const ok=refs.filter(r=>r.file);
 fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>大面积空地参考</title><style>*{box-sizing:border-box}body{margin:0;background:#e7e9e2;color:#2c3c32;font:17px/1.75 system-ui}main{max-width:1500px;margin:auto;padding:28px}h1{font-size:30px}p{max-width:1150px}a{color:#276874}nav{position:sticky;top:0;background:#e7e9e2f5;padding:14px 0;z-index:2}nav a{margin-right:24px}section{margin:40px 0;scroll-margin-top:80px}img{display:block;max-width:100%;max-height:730px;margin:auto;cursor:zoom-in}figure{margin:0;padding:12px;background:#f8f8f1}figcaption{padding:10px}small{color:#5d6d61}dialog{padding:10px;border:0;background:#263731;max-width:97vw}dialog img{max-width:92vw;max-height:87vh}button{padding:10px;cursor:pointer}</style><main><h1>大面积空地：开阔，但地面有层次</h1><p>这一页专门选草坪、草土空地与大片战斗地面。请按正常游戏视角关注地面变化，暂时忽略场地边缘的建筑装饰。图片保留原貌，来源与类型分别标明。</p><p><b>这些是外观参考，尚未核对其原始材质能否在项目中使用。</b>其他游戏与 Unity 的截图用于选择方向；选定后优先用现有 Dota 资源实现所需效果，缺失部分再制作独立资源。</p><nav>${ok.map(r=>`<a href="#${r.id}">${r.id} · ${r.name.split(' · ')[0]}</a>`).join('')}</nav>${ok.map(r=>`<section id="${r.id}"><h2>${r.id} · ${r.name}</h2><small>${r.kind} · <a href="${r.source}" target="_blank">来源</a></small><p>${r.note}</p><figure><img src="${r.file}" onclick="document.querySelector('#big').src=this.src;document.querySelector('dialog').showModal()" alt="${r.name}"><figcaption>${r.id} · 点击放大 · <a href="${r.url}" target="_blank">原图</a></figcaption></figure></section>`).join('')}<section><h2>选择时看这四点</h2><p>① 大面积地面有没有连续的深浅变化；② 草、土、石是否相互穿插；③ 细节有没有疏密，而非均匀撒满；④ 去掉周围建筑后，地面本身是否仍然好看。主岛样板优先验证这四点，树木、花丛和小建筑随后再加。</p><a href="../index.html">返回上一组地形参考</a></section></main><dialog><button onclick="document.querySelector('dialog').close()">关闭</button><img id="big"></dialog></html>`);
 console.log(ok.length+' references saved to '+out);
})();
