const fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'../output/gold_training_room');
const assets=JSON.parse(fs.readFileSync(path.join(out,'asset_manifest.json')));
const layout=JSON.parse(fs.readFileSync(path.join(out,'room_layout.json')));
const triangles=layout.placements.reduce((s,p)=>s+(assets.find(a=>a.name===p.name)?.triangles||0),0);
const cards=assets.map(a=>`<article><a href="previews/components/${a.name}.png"><img loading="lazy" src="previews/components/${a.name}.png" alt="${a.label}"></a><h3>${a.label}</h3><code>${a.name}</code><p>${a.triangles.toLocaleString()} 三角面 · ${a.collision_hulls?'实体碰撞':'装饰 / 配套地面支撑'}</p><a href="source/models/gold_training_room/${a.name}.fbx">FBX</a></article>`).join('');
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>金币练功房 · 模块化样板房</title><style>*{box-sizing:border-box}body{margin:0;background:#eeeae1;color:#313c39;font:16px/1.7 system-ui,"Microsoft YaHei",sans-serif}header,main{max-width:1220px;margin:auto;padding:36px 28px}header{padding-bottom:10px}h1{font-size:36px;margin:0}h2{margin:38px 0 16px}p{margin:8px 0}.tag{font-size:13px;color:#4c756d;letter-spacing:2px}.links{display:flex;gap:14px;flex-wrap:wrap;margin:20px 0}a{color:#295f56}.links a{background:#fff9;border:1px solid #cabd99;border-radius:6px;padding:9px 15px;text-decoration:none}.hero{width:100%;display:block;border-radius:8px}.details{display:grid;grid-template-columns:1fr 1fr;gap:16px}.details img{width:100%;border-radius:6px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}article{background:#fff8;border:1px solid #d5cebf;border-radius:8px;padding:12px}article img{width:100%;border-radius:4px}article h3{font-size:16px;margin:5px 0}article code{font-size:12px}article p{font-size:12px;color:#6e746a}.note{border-left:3px solid #b79853;padding:8px 18px;background:#ffffff55}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}.details{grid-template-columns:1fr}h1{font-size:28px}}</style><header><div class="tag">GOLD PRACTICE ROOM · B01—B16</div><h1>金币练功房</h1><p>后侧传送台 · 中央刷怪地纹 · 封闭低墙 · 外围石景与植被</p><div class="links"><a href="gold_training_room.blend">打开 Blender 场景</a><a href="source/maps/gold_training_room_review.vmap">独立地图源文件</a><a href="source/maps/prefabs/gold_training_room.vmap">房间预制件</a><a href="room_layout.json">组件坐标清单</a></div><p>${assets.length} 个自制组件 / ${layout.placements.length} 个实例 / 约 ${(triangles/10000).toFixed(1)} 万自制三角面 / 原生松树复用</p></header><main><img class="hero" src="previews/room_overview.png" alt="金币练功房 Blender 全景"><p class="note">以上为实际 Blender 场景渲染。石材、青铜、布料包含颜色、法线与反射贴图；传送台和地纹使用实体嵌件，未制作发光、火焰或粒子。玩法入口与刷怪位置以命名标记预留，正式地图中的放置与玩法联调可在后续进行。</p><h2>近景与布局</h2><div class="details"><img src="previews/entry_detail.png" alt="传送台与弧墙"><img src="previews/stone_coin_detail.png" alt="金币碑与石材细节"><img src="previews/room_top.png" alt="俯视布局"><img src="previews/component_library.png" alt="可复用组件总览"></div><h2>可复用组件</h2><div class="grid">${cards}</div><h2>使用说明</h2><p>Blender 文件包含组装房间与 B01—B16 组件库两个场景，贴图已打包。标准地板为 256×256；直墙长 256 / 128，高 176；三片 60° 弧墙可拼成后侧半圆。B15 松树使用 Dota 原生 <code>models/props_foliage/tree_pine01.vmdl</code>，Blender 内保留其预览副本。</p><p>Hammer 资源目录为 <code>models/gold_training_room/</code>。房间净尺寸 2048×2304，Blender 地板 Z=0，地图实例整体抬高 128；各组件保留独立对象。正式主地图未替换。</p></main></html>`);
const gallery=path.join(out,'index.html');
if(fs.existsSync(path.join(out,'material_review/index.html'))){
 const html=fs.readFileSync(gallery,'utf8').replace('<div class="links">','<div class="links"><a href="material_review/index.html">本轮材质修改前后对比</a>');
 fs.writeFileSync(gallery,html);
}
if(fs.existsSync(path.join(out,'previews/runtime_complete.png'))){
 const html=fs.readFileSync(gallery,'utf8').replace('<h2>使用说明</h2>','<h2>游戏内检查</h2><a href="previews/runtime_complete.png"><img class="hero" src="previews/runtime_complete.png" alt="Workshop 独立地图实际游戏截图"></a><p>房间已编译并在 Workshop 加载，中央与入口采样点可行走，建造者完成室内步行；截图保留游戏 HUD。完整挑战玩法尚未联调。</p><h2>使用说明</h2>');
 fs.writeFileSync(gallery,html);
}
console.log('GOLD_ROOM_GALLERY',assets.length,'components',triangles,'triangles');
