const fs=require('fs'),path=require('path'),base=path.resolve(__dirname,'../panorama/src');
function change(name,fn){const file=path.join(base,'scripts/custom_game',name);let s=fs.readFileSync(file,'utf8');if(s.includes('// UI_REUSE_V1'))return;s=fn(s);fs.writeFileSync(file,s.replace('"use strict";','"use strict";\n    // UI_REUSE_V1\n    var U=GameUI.CustomUIConfig().SurvivalUI;'));}
function replace(s,from,to){if(!s.includes(from))throw Error('Missing migration anchor: '+from.slice(0,90));return s.replace(from,to);}
function replaceFunction(s,name,next,body){const a=s.indexOf('    function '+name+'('),b=s.indexOf('    function '+next+'(',a);if(a<0||b<0)throw Error(name);return s.slice(0,a)+body+'\n'+s.slice(b);}
change('archive.js',s=>{
 s=replaceFunction(s,'cardFrame','render','    function cardFrame(card) { U.CardShell.Adopt(card,{bodyVariant:"square"}); }');
 s=replace(s,'toggle.AddClass("ArchiveTab");','toggle.AddClass("ArchiveTab"); U.NavToggle.Adopt(toggle);');
 s=replace(s,'var glyph=$.CreatePanel("Panel",toggle,"");glyph.AddClass("ArchiveKitIcon");glyph.AddClass("KitIcon_"+(navIcons[category.id] || "book"));glyph.hittest=false;','U.Icon(toggle,category.id==="clear"||!navIcons[category.id]?"icon.nav.archive":"icon.archive."+navIcons[category.id],28);');
 s=replace(s,'label(parent,Math.max(0,count)+"/"+target,"ArchiveCount");','U.ProgressBadge(parent,{current:Math.max(0,count),required:target}).AddClass("ArchiveCount");');
 s=replace(s,'var layers=GameUI.CustomUIConfig().SurvivalUILayers;if(layers)layers.Close("archive");','archiveShell.Close();');
 s=replace(s,'var layers=GameUI.CustomUIConfig().SurvivalUILayers;if(layers)layers.Open("archive",panel("ArchiveWindow"),close);\n            watchFit();','archiveShell.Open();');
 s=replace(s,'    GameUI.CustomUIConfig().SurvivalArchive = {','    var archiveShell=U.ModalShell.Adopt({id:"archive",panel:panel("ArchiveWindow"),root:$.GetContextPanel(),scrim:panel("ArchiveScrim"),header:panel("ArchiveHeader"),titlePanel:panel("ArchiveTitle"),closeButton:panel("ArchiveClose"),width:1002,height:758,fit:{reference:[1672,941]},onClose:close});\n    U.ActionButton.Adopt(panel("ArchiveDraw"),{variant:"gold"}); U.Tooltip.Adopt(panel("ArchiveTooltip"));\n    GameUI.CustomUIConfig().SurvivalArchive = {');return s;
});
change('shop_ui.js',s=>{
 s=replace(s,'    function setOpenState(opened) {','    function setOpenState(opened) {\n        if(shopShell){if(opened)shopShell.Open();else shopShell.Close();}');
 s=replace(s,'card.AddClass("ShopShelfSlot");','card.AddClass("ShopShelfSlot"); U.CardShell.Adopt(card,{bodyVariant:"product"});');
 s=replace(s,'    setUnlocks(GameUI.CustomUIConfig().SurvivalShopUnlocks || unlocks);','    var shopShell=U.ModalShell.Adopt({id:"shop",panel:byId("CustomShopWindow"),root:$.GetContextPanel(),header:byId("ShopHeader"),titlePanel:byId("ShopTitle"),scrim:byId("ShopBackdrop"),scrimButton:byId("ShopBackdropClick"),closeButton:byId("ShopCloseButton"),width:1208,height:806,onClose:close});\n    ["ShopModeShop","ShopModeChallenge","ShopModeLottery"].forEach(function(id){if(byId(id))U.TabBar.Adopt(byId(id));});\n    U.ActionButton.Adopt(byId("ShopRefreshButton")); U.Tooltip.Adopt(byId("ShopEntryTooltip"));\n    setUnlocks(GameUI.CustomUIConfig().SurvivalShopUnlocks || unlocks);');return s;
});
change('lottery_ui.js',s=>{
 s=replace(s,'function cancelAnimation() { animationSerial++; animationTimers.forEach(function (timer) { if ($.CancelScheduled) $.CancelScheduled(timer); }); animationTimers = []; }','function cancelAnimation() { animationSerial++; drawSequence.Cancel(); animationTimers = []; }');
 const a=s.indexOf('        function later(ms, action)'),b=s.indexOf('\n    }',a);if(a<0||b<0)throw Error('lottery sequence');s=s.slice(0,a)+`        drawSequence.Play(visibleResults,{timing:timing,flipHalf:motion.flipHalf,onCharged:function(){rootClass("LotteryCharging",false);},onEnter:function(i){cardState(resultCards[i],"LotteryCardEntering",false);},onFlip:function(i){cardState(resultCards[i],"LotteryCardNarrow",true);},onReveal:function(i){cardState(resultCards[i],"LotteryCardCovered",false);cardState(resultCards[i],"LotteryCardNarrow",false);},onReady:finishReveal});`+s.slice(b);
 s=replace(s,'var layers = GameUI.CustomUIConfig().SurvivalUILayers; if (layers) layers.Close("lottery_info");','infoShell.Close();');
 s=replace(s,'        ensureDetailSlices();\n        watchDetailsSize();','        // Shared shell owns frame and the only modal scale.');
 s=replace(s,'var layers = GameUI.CustomUIConfig().SurvivalUILayers; if (layers) layers.Open("lottery_info", overlay, closeInfo);','infoShell.Open();');
 s=replace(s,'button.AddClass("LotteryPoolTab");','button.AddClass("LotteryPoolTab"); U.TabBar.Adopt(button);');
 s=replaceFunction(s,'createV3CardBorder','setHeaderIcon','    function createV3CardBorder(parent) { U.CardShell.Adopt(parent,{bodyVariant:"square"}); }');
 s=replace(s,'"file://{images}/custom_game/lottery_handoff/icons/" + ({details:"pool",history:"history",announcement:"announcement",purchase:"plus",firstgift:"gift",privilege:"gift"}[name] || "info") + ".svg"','U.Asset(({details:"icon.pool_details",history:"icon.history",purchase:"icon.add",announcement:"icon.nav.social",firstgift:"icon.nav.benefit",privilege:"icon.nav.benefit"}[name]||"icon.pool_details"))');
 s=replace(s,'    var state = null;','    var drawSequence=U.DrawResultSequence();\n    var infoShell=U.ModalShell.Adopt({id:"lottery_info",panel:$("#LotteryInfoDialog"),root:$.GetContextPanel(),scrim:$("#LotteryInfoOverlay"),header:$("#LotteryInfoHeader"),titlePanel:$("#LotteryInfoTitle"),closeButton:$("#LotteryInfoClose"),width:1045,height:760,onClose:closeInfo});\n    U.FullscreenShell.Adopt({panel:$("#LotteryWindow"),sceneId:"scene.treasure"});\n    ["LotterySingleButton","LotteryTenButton","LotteryAgain","LotteryConfirm","LotteryInfoConfirm"].forEach(function(id){U.ActionButton.Adopt($("#"+id),{variant:id==="LotteryTenButton"||id==="LotteryAgain"?"gold":"ivory"});});\n    U.Checkbox.Adopt($("#LotterySkipAnimation")); U.CloseButton($("#LotteryCloseButton"),close);\n    var state = null;');return s;
});
change('rogue_reward_ui.js',s=>{
 s=replaceFunction(s,'later','active','    var augment=U.AugmentChoiceGroup();\n    function later(time,fn){augment.Later(time,fn);}\n    function cancel(){generation++;augment.Cancel();}');
 const a=s.indexOf('        if(!reduced){later(.01+index*.11'),b=s.indexOf('\n        return c;',a);if(a<0||b<0)throw Error('augment timing');s=s.slice(0,a)+'        if(!reduced)augment.Animate(c,index);'+s.slice(b);
 s=replace(s,'    render(CustomNetTables.GetTableValue','    U.FullscreenShell.Adopt({panel:panel("RogueRewardBackdrop"),liveGame:true});\n    U.ActionButton.Adopt(panel("RogueRewardReroll")); U.Checkbox.Adopt(panel("RogueReducedMotion"));\n    render(CustomNetTables.GetTableValue');return s;
});
change('main_hud_skin.js',s=>{
 s=replace(s,'i.SetImage("file://{images}/custom_game/main_hud_v1/"+file);','i.SetImage(U.ProjectAsset("custom_game/main_hud_v1/"+file));');
 const a=s.indexOf('    assets.icons.forEach(function(a)'),b=s.indexOf('\n    [["SharedUnitsButton"',a);if(a<0||b<0)throw Error('HUD nav');s=s.slice(0,a)+`    U.HUDShell.Adopt(skin);
    assets.icons.forEach(function(a){var b=U.IconButton(p("MainHudTop"),{id:"MainHudEntry_"+a.id,iconId:"icon.nav."+a.id,label:a.label,action:function(){activate(a.id);}});b.AddClass("MainHudIconButton");tip(b,function(){return available(a.id)?a.label:a.label+"：功能待接入";});topButtons[a.id]=b;});`+s.slice(b);
 s=replace(s,'topButtons[id].SetHasClass("Unavailable",!available(id));','topButtons[id].SetHasClass("Unavailable",!available(id)); U.State.Set(topButtons[id],{enabled:!!available(id)});');return s;
});
for(const name of ['archive.xml','survival_hud.xml','lottery_window.xml','rogue_reward_ui.xml']){const file=path.join(base,'layout/custom_game',name);if(!fs.existsSync(file))continue;let s=fs.readFileSync(file,'utf8');if(!s.includes('common/ui_components.js'))s=s.replace('<scripts>','<scripts><include src="file://{resources}/scripts/custom_game/common/ui_registry.js"/><include src="file://{resources}/scripts/custom_game/common/ui_components.js"/>');if(!s.includes('common/ui_components.css'))s=s.replace('</styles>','<include src="file://{resources}/styles/custom_game/common/ui_assets.css"/><include src="file://{resources}/styles/custom_game/common/ui_components.css"/></styles>');if(s.includes('id="LotteryInfoHeader"')&&!s.includes('id="LotteryInfoClose"'))s=s.replace('<Button onactivate="GameUI.CustomUIConfig().SurvivalLottery.CloseInfo()">','<Button id="LotteryInfoClose" onactivate="GameUI.CustomUIConfig().SurvivalLottery.CloseInfo()">');fs.writeFileSync(file,s);}
console.log('UI_REUSE_MIGRATION_PASS: archive, shop, pool/history, fullscreen lottery, augment motion, HUD icon buttons');
