// Original ten-biome approval artwork. Gameplay and existing models stay separate.
const fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'../output/ten_realm_arena_concepts_v1');
fs.mkdirSync(out,{recursive:true});
const themes=[
 ['黄沙古垒','沙漠',['风积黄沙','风化砂岩','湿沙浅滩'],
  'A sun-bleached DESERT dueling enclosure. Broad packed ochre sand battle floor, fine wind ripples near the sides and a few exposed worn sandstone paving fragments. Low continuous weathered sandstone walls form a completely closed perimeter, square eroded corner buttresses, no gate opening. Sand drifts and sparse dry scrub only outside the walls. The sandy island apron is irregular and slopes gradually from dry pale sand through a narrow darker damp-sand margin into transparent aquamarine shallows. Partly submerged sandstone shelves and a few tiny foam traces give way to deeper blue water; no sheer square slab touching ocean.',
  '干沙 → 暗色湿沙 → 水下砂岩浅滩 → 青蓝深水'],
 ['林间古环','林地',['落叶泥土','苔石与树根','溪岸卵石'],
  'A temperate WOODLAND dueling enclosure, green and earthy. A broad flat firm forest-earth combat clearing with a restrained worn irregular stone border and scattered leaves. Continuous low moss-covered fieldstone walls interlocked with sturdy root buttresses close every side. Mature broadleaf trees, small ferns and gnarled roots are concentrated outside the fence, their canopies do not cover the central fight floor. An irregular forest island shore changes from leaf litter and grass to exposed root mats, rounded cobbles, darker damp soil and submerged pebbles in clear green-blue water. No timber stage and no perfect square island edge.',
  '林土与落叶 → 根系卵石 → 湿岸碎石 → 清水'],
 ['沼泽沉垣','沼泽',['压实泥炭','腐木与苔墙','芦苇淤泥'],
  'A readable atmospheric MARSH dueling enclosure, olive, muted teal and earthy brown. The central battle floor is continuous firm compacted peat with a little flat worn paving, dry enough to fight on, no impassable pool in its center. Entire perimeter closed by low age-sunken mossy stone walls reinforced with short waterlogged timber piles. Reeds, cypress knees, a few crooked swamp trees and shallow muddy pools live outside the walls. Shore transition is a wide irregular marsh shelf: damp peat to muddy rivulets, reeds rooted in sediment, waterlogged driftwood and shallow murky green water gradually deepening to surrounding blue-green water. No giant fog bank or luminous poison.',
  '泥炭 → 湿泥水沟 → 芦苇浅水 → 深绿水域'],
 ['赤岩断谷','红岩峡谷',['红砂岩层理','赭色碎砾','浸水岩阶'],
  'A RED ROCK CANYON dueling enclosure, visually unlike the pale sandy desert: broad flat layered reddish sandstone bedrock floor with thin dry fissures and darker smooth worn areas. Closed low wall assembled from natural horizontal red-rock ledges with a few stout carved sandstone pillars, all sides unbroken. Outside stand compact asymmetrical stepped canyon outcrops, not high mountains. The island rim exposes red sedimentary strata descending in broken terraces, talus chips and rounded water-worn boulders toward calm water. Rust-red dry stone turns burgundy near the wet line, submerged ledges remain visible under turquoise shallows that merge into deep teal. No sand dunes.',
  '红岩台阶 → 崩落砾石 → 暗红湿岩 → 碧水'],
 ['霜雪寒垒','雪原冻岸',['积雪与冻土','霜白石墙','冰缘冷水'],
  'A SNOWFIELD AND FROZEN SHORE dueling enclosure. Broad flat pale packed snow and blue-grey frozen stone floor, subtle swept paths with safe readable texture. Closed continuous low frost-covered stone walls and thick short ice-crusted corner posts; no openings. Only a few snow-laden conifers and low snowy boulders outside. The irregular coast descends through wind-packed snow to dark wet rock, thin fractured rim ice, a few small ice floes and translucent pale blue shallow water, then deep cold steel-blue surrounding water. Shore ice is irregular and thin; do not put the entire arena on a giant ice cube, no blizzard, no luminous ice.',
  '积雪 → 冰霜湿岩 → 碎冰浅水 → 冷蓝深水'],
 ['潮礁碧湾','海岸珊瑚礁',['浅色珊瑚石','贝砂与海草','碧蓝礁湖'],
  'A TROPICAL CORAL-LIMESTONE COAST dueling enclosure, luminous natural daylight, cream, turquoise and fresh green. Broad solid pale coral-limestone flagstone combat floor with embedded fossil and shell grain, extremely little loose sand. Continuous low rounded shell-limestone walls and stout coral-stone posts close the complete perimeter. A few palms, coastal succulents and sea grass outside only. The natural island apron is porous eroded limestone meeting shell-sand pockets, tidal pools and sea-grass shallows; visible submerged reef shelves create a gradual cream-to-turquoise-to-deep-blue shoreline. Reefs are outside the dry combat floor. No desert dunes, no modern beach furniture.',
  '珊瑚石 → 贝砂潮池 → 海草礁盘 → 碧蓝海水'],
 ['熔岩黑岸','火山岩地',['冷却玄武岩','暗铜与焦岩','湿黑礁石'],
  'A VOLCANIC BASALT coastal dueling enclosure. Broad flat charcoal-grey basalt and cooled cracked lava-rock battle floor, occasional rusty mineral seams, solid safe continuous ground. Unbroken low basalt defensive walls with restrained weathered copper clamps close all sides. Several squat jagged black volcanic outcrops at exterior corners and sparse ash outside, not on the combat surface. All lava is cooled and non-emissive. Irregular shore made of stepped basalt columns, tumbled black boulders, dark wet reflective rock at the waterline and pale small surf marks; submerged black reef shelves visible through blue-green shallows before deep blue water. No live lava river pouring into water, no fire, no smoke curtain.',
  '冷却熔岩 → 黑礁碎石 → 湿润岩岸 → 深蓝海水'],
 ['紫晶岩庭','晶矿岩地',['紫灰矿岩','不发光石英','水下晶砾'],
  'A CRYSTALLINE MINERAL ROCK dueling enclosure, lilac grey, muted purple and cool silver-blue, lit by daylight rather than glow. Broad flat violet-grey schist combat ground with restrained pale quartz veins, tactile natural rock. Completely continuous low schist walls with compact smoky amethyst crystal clusters embedded at outer corners; no crystal spires or obstacle in the middle. Asymmetrical mineral outcrops decorate outside. Shoreline transitions through fractured grey-purple bedrock into loose quartz gravel, rounded wet mineral stones, submerged pebble shelves and clear steel-turquoise shallows joining deeper blue water. Crystals reflect daylight but never emit light; no magical void or floating island.',
  '矿岩 → 石英碎砾 → 湿润矿石 → 清澈水域'],
 ['天辉圣庭','天辉出生地风格',['浅白石铺地','青金嵌饰','花草苔岸'],
  'A RADIANT BASE-SPAWN inspired enclosed dueling courtyard from the Dota 2 world, original architectural arrangement. Broad open ivory limestone paving with restrained green jade and gold leaf inlays, light cheerful natural materials. Continuous low pale stone walls and short gold-capped pillars enclose all four sides. Radiant teal banners, a small crescent-shaped unlit fountain basin at the far perimeter, living broadleaf trees, pink blossom clusters and flowers arranged outside or in the wall border. No giant Ancient or hero statue occupying the center. The pale stone edge breaks naturally into mossy limestone shelves, grass tufts, scattered rounded boulders and clear emerald-turquoise shallows with submerged stone and plant roots, then calm blue water. Fountain style expressed through architecture; no glowing portals or particle beams.',
  '白石花庭 → 苔岩草岸 → 清澈浅滩 → 蓝绿水域'],
 ['夜魇荒庭','夜魇出生地风格',['暗灰石板','骨白棘饰','枯根黑泥岸'],
  'A DIRE BASE-SPAWN inspired enclosed dueling courtyard from the Dota 2 world, original architectural arrangement, clearly distinct from the volcanic arena. Broad flat worn ash-grey cracked flagstones with subdued dark crimson mineral accents, readable midtone ground. Unbroken low severe dark-stone walls strengthened by bone-pale thorn-shaped exterior braces and short Dire red-black banner posts. A low unlit angular fountain ruin at far perimeter, twisted dead branches and desiccated grey-brown root masses outside; no high citadel, giant Ancient, or central statue. Shore transitions from ash-grey ruins through blackened damp soil, tangled roots and slate scree into submerged slabs and calm desaturated slate-blue water. Dark but legible daylight, small realistic wet sheen; no active lava, no blood ocean, no red glow.',
  '灰岩遗址 → 枯根黑泥 → 湿页岩浅滩 → 灰蓝水域'],
];
const shared=`Use case: stylized-concept.
Asset type: finished game environment concept approval sheet, one distinct environment in a ten-arena series for the survival Dota 2 custom game. Concept artwork only, for later Blender modular modeling.
Primary request: a compact ENCLOSED OPEN-AIR DUEL ARENA built on a natural island surrounded by water. The battle space is a broad, nearly rectangular approximately 3:2 clearing inside a fully CONTINUOUS 360-degree low physical boundary, built from the biome's wall and rock language. It is enclosed at all four sides including the near/front side. Open to sky, no roof. No open entrance, no missing wall, no bridge or pier connecting across the enclosing boundary. Two small unlit flat arrival medallions at opposite short sides inside the boundary; combat floor between them wide, flat, continuous, at least two-thirds of interior area clear. Water never cuts through that battle floor. Exact game-unit dimensions are NOT yet assigned to these new arenas: no dimension numbers or scale rulers.
Art direction: high-end Dota 2 inspired hand-painted stylized 3D environment production art, richly worked tactile stone/wood/soil surfaces, broad readable silhouettes, intentional beveled wear, reflected light and controlled highlights, painterly realism with clear material differences. All ten sheets must share this art style and camera. Not photorealistic, not an anime screenshot, not miniature plastic toys. No characters or enemies, no UI, no logos, no particles, no glow or bloom. Each biome has different landforms, plants, boundary construction and water-edge anatomy, not simply different colors on the same stone arena.
Composition: landscape 1536 by 1024 design sheet on a warm neutral grey art-board background with generous clean margins. Large three-quarter orthographic view fills the left two-thirds, looking down around 45 degrees: show the ENTIRE enclosed arena, all four physical boundary sides and the COMPLETE irregular natural shore, with a visible band of surrounding water. Upper right: smaller TRUE TOP-DOWN view of the same exact arena, showing all four sides closed and clear combat space. Lower right: close-up of this SAME biome's ground-wall-shore-water junction, showing dry material, dark wet zone, visible submerged rocks or sediment and progressive water depth. These three views depict ONE design, not alternative scenes. Put a restrained Chinese title across the top and three short view labels only. Do not crop the shore out of the main view.
Coastline requirement: the clean geometric combat enclosure sits within a wider organically irregular island apron. Blend dry terrain into broken stones/soil/vegetation, then damp darker material, then visible submerged shallow shelf, then deeper blue water. Water color and wave scale consistent with a calm surrounding sea while shoreline sediment differs by biome. No obvious square plinth standing vertically in the water, no floating land, no hard straight texture boundary, no uniform white foam outline. Sparse natural foam at exposed rocks only, no massive waves.
Lighting: neutral readable daylight from upper left, coherent soft shadows, sufficient fill light for material reading. Environment architecture supplies the mood, not heavy fog or underexposure.
Exact view labels: “整体” “俯视布局” “岸线衔接”. Keep all text sparse and legible. One completed sheet for the assigned biome only. Do not include any unrelated arena from the series.`;
const chinese=['一','二','三','四','五','六','七','八','九','十'];
const tiers=themes.map(([name,terrain,materials,design,shore],i)=>({rank:i+1,name,terrain,materials,shore,
 file:`realm_${String(i+1).padStart(2,'0')}.png`,
 prompt:shared+`\nAssigned arena: ${i+1} of 10.\nExact title: “${String(i+1).padStart(2,'0')} · ${chinese[i]}戒 · ${name}”.\nBiome and construction: ${design}\nFinal check: all four boundary walls remain closed; combat center open; organic shoreline and surrounding water clearly visible; top view and shore detail match the main design.`}));
const data={generator:'built-in image_gen',status:'concepts_pending_user_approval',modeling_started:false,
 user_term:'1—10戒',enemy_spawn_interpretation:'“地方出生地”暂按敌方夜魇出生地风格理解',
 dimensions:'New closed arenas: no fixed game-unit dimensions assigned; prior 1000x550 applies to separate ascension arenas.',
 layout:'Enclosed open-air arena; same approximate 3:2 interior layout; complete physical perimeter; organic island shore',
 tiers};
fs.writeFileSync(path.join(out,'prompts.json'),JSON.stringify(data,null,2));
console.log('TEN_REALM_CONCEPT_PROMPTS '+tiers.length);
