const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('panorama/src/scripts/custom_game/lumberjack_fusion_queue.js','utf8');
function harness(engineSort=false){
 let now=0,selection=[],cfg={},jobs=[],events={},units={},requests=[],netListener;
 const env={$:{GetContextPanel:()=>({IsValid:()=>true}),Schedule:(sec,fn)=>jobs.push({at:now+sec*1000,fn})},
 Game:{GetLocalPlayerID:()=>0},Players:{GetSelectedEntities:()=>selection},
 Entities:{IsValidEntity:id=>!!units[id],IsAlive:id=>!!units[id]&&!units[id].dead,GetPlayerOwnerID:id=>-1,
 GetUnitName:id=>units[id].name||'npc_survival_lumberjack',GetAbilityCount:()=>1,GetAbility:(id,slot)=>slot!==(units[id].slot||0)||units[id].super?-1:id+1000},
 Abilities:{GetAbilityName:id=>units[id-1000]?'ability_fuse_lumberjack_'+String(units[id-1000].level).padStart(2,'0'):''},
 CustomNetTables:{GetTableValue:(table,key)=>{const u=units[table==='survival_combat_stats'?+key:+key-1000];return !u?null:table==='survival_combat_stats'?{player_id:u.owner||0}:u.noMetadata?{}:{fusion_required_count:u.count||3,fusion_city_ready:u.cityReady===false?0:1,can_afford:u.affordable===false?0:1};},SubscribeNetTableListener:(t,fn)=>netListener=fn},
 GameUI:{CustomUIConfig:()=>cfg,SelectUnit:(id,add)=>{selection=add?selection.concat(id):[id];if(engineSort)selection.sort((a,b)=>b-a);emit('dota_player_update_selected_unit',{});}},
 GameEvents:{Subscribe:(name,fn)=>(events[name]||(events[name]=[])).push(fn),SendCustomGameEventToServer:(name,p)=>requests.push(JSON.parse(JSON.stringify(p)))}};
 function emit(name,p){(events[name]||[]).forEach(fn=>fn(p));}
 function advance(ms=100){const until=now+ms;let steps=0;while(jobs.some(j=>j.at<=until)){jobs.sort((a,b)=>a.at-b.at);const job=jobs.shift();now=job.at;job.fn();assert(++steps<100,'no selection rewrite loop');}now=until;}
 vm.createContext(env);vm.runInContext(source,env);
 return {units,requests,cfg,advance,emit,add:(ids,level,extra={})=>ids.forEach(id=>units[id]={level,...extra}),select:ids=>{selection=ids;emit('dota_player_update_selected_unit',{});advance();},get:()=>Array.from(selection),cast:()=>cfg.SurvivalLumberjackFusionQueue.Cast(selection[0]+1000,selection[0]),
 reply:(consumed,ok=1)=>{const req=requests.at(-1);if(ok){units[consumed[0]].super=true;consumed.slice(1).forEach(id=>units[id].dead=true);selection=selection.filter(id=>!units[id].dead);emit('dota_player_update_selected_unit',{});}emit('ui_ability_cast_result',{success:ok,entindex:req.entindex,ability_entindex:req.ability_entindex,fusion_queue_request_id:req.fusion_queue_request_id,fusion_consumed_entindexes:consumed,fusion_target_entindex:consumed[0]});advance();},
 metadata:()=>{netListener();advance();},reload:()=>vm.runInContext(source,env)};
}
let n=0;function test(name,fn){fn();console.log('PASS '+name);n++;}
test('sort low to high, one request, success advances and excludes transformed product',()=>{const h=harness();h.add([1,2,3],2);h.add([4,5,6],3);h.select([6,4,1,5,3,2]);assert.deepEqual(h.get(),[1,2,3,4,5,6]);assert(h.cast());h.cast();assert.equal(h.requests.length,1);h.reply([1,2,3]);assert.deepEqual(h.get(),[4,5,6]);assert.equal(h.requests.length,1);h.cast();assert.equal(h.requests[1].entindex,4);h.reply([4,5,6]);assert.deepEqual(h.get(),[4]);});
test('same level is exhausted before the next level',()=>{const h=harness();h.add([1,2,3,4,5,6],2);h.add([7,8,9],3);h.select([9,8,7,6,5,4,3,2,1]);h.cast();h.reply([1,2,3]);assert.deepEqual(h.get(),[4,5,6,7,8,9]);});
test('recipe quantities are configured: LV1 needs five; incomplete levels remain at end',()=>{const h=harness();h.add([1,2,3,4],1,{count:5});h.add([5,6,7],2);h.select([1,2,3,4,5,6,7]);assert.deepEqual(h.get(),[5,6,7,1,2,3,4]);h.cast();h.reply([5,6,7]);assert.deepEqual(h.get(),[1,2,3,4]);h.cast();assert.equal(h.requests.length,1,"incomplete group cannot submit");});
test('failed fusion retains group and permits deliberate retry only',()=>{const h=harness();h.add([1,2,3],2);h.select([3,2,1]);h.cast();h.reply([],0);assert.deepEqual(h.get(),[1,2,3]);assert.equal(h.requests.length,1);h.cast();assert.equal(h.requests.length,2);});
test('one leftover stays scoped and cannot consume unselected units',()=>{const h=harness();h.add([1,2,3,4],2);h.select([1,2,3,4]);h.cast();h.reply([1,2,3]);h.cast();assert.equal(h.requests.length,1,"single leftover stays disabled");});
test('manual selection while awaiting response is respected',()=>{const h=harness();h.add([1,2,3,4,5,6],2);h.add([8],9,{name:'npc_dota_hero_axe'});h.select([1,2,3,4,5,6]);h.cast();h.select([8]);h.reply([1,2,3]);assert.deepEqual(h.get(),[8]);});
test('single worker, mixed groups and other players retain normal selection',()=>{for(const kind of ['single','mixed','foreign']){const h=harness();h.add([1,2,3],2);if(kind==='mixed')h.units[3].name='npc_dota_hero_axe';if(kind==='foreign')h.units[3].owner=1;h.select(kind==='single'?[1]:[3,2,1]);assert.equal(h.cast(),false);assert.equal(h.requests.length,0);}});
test('super workers are not queued even when their entity name is unchanged',()=>{const h=harness();h.add([1,2,3,4],2);h.units[1].super=true;h.select([1,2,3,4]);assert.deepEqual(h.get(),[2,3,4]);});
test('delayed recipe metadata resumes sorting without guessing quantities',()=>{const h=harness();h.add([1,2,3],2,{noMetadata:true});h.select([3,2,1]);h.cast();assert.equal(h.requests.length,0);Object.values(h.units).forEach(u=>u.noMetadata=false);h.metadata();h.cast();assert.equal(h.requests.length,1);});
test('reload invalidates stale response handlers',()=>{const h=harness();h.add([1,2,3,4,5,6],2);h.select([1,2,3,4,5,6]);h.cast();h.reload();h.select([6]);h.reply([1,2,3]);assert.deepEqual(h.get(),[6]);});


test('city-gated levels remain grey while a ready lower group can fuse',()=>{const h=harness();h.add([1,2,3],3,{cityReady:false});h.add([4,5,6],2);h.select([1,2,3,4,5,6]);assert.deepEqual(h.get(),[4,5,6,1,2,3]);h.cast();assert.equal(h.requests[0].entindex,4);h.reply([4,5,6]);h.cast();assert.equal(h.requests.length,1);});
test('unknown metadata on another level does not block a complete known group',()=>{const h=harness();h.add([1,2,3],2);h.add([4],6,{noMetadata:true});h.select([4,3,2,1]);h.cast();assert.equal(h.requests.length,1);});
test('selected count overrides all-owner availability for the grey icon',()=>{const h=harness();h.add([1,2,3],2);h.select([1,2]);const r=h.cfg.SurvivalLumberjackFusionQueue.Decorate(1001,{owner_entindex:1,available:1,fusion_city_level:5,fusion_required_city_level:4});assert.equal(r.available,0);assert.equal(r.fusion_count,2);h.cast();assert.equal(h.requests.length,0);});

test('native selection sorting cannot loop or change the logical fusion focus',()=>{const h=harness(true);h.add([1,2,3],2);h.add([4,5,6],3);h.select([6,5,4,3,2,1]);h.advance(1000);assert.equal(h.cfg.SurvivalLumberjackFusionQueue.ResolveFocus(h.get()),1);h.cast();assert.equal(h.requests[0].entindex,1);h.reply([1,2,3]);assert.equal(h.cfg.SurvivalLumberjackFusionQueue.ResolveFocus(h.get()),4);});

// Real workers can have one remaining ability at engine slot 1.
test('sparse engine ability slots still enter the scoped queue',()=>{const h=harness();h.add([1,2,3],1,{slot:1});h.add([4,5,6],2,{slot:1});h.select([6,5,4,3,2,1]);assert(h.cast());assert.equal(h.requests.length,1);assert(h.requests[0].fusion_queue_request_id);h.reply([1,2,3]);assert.deepEqual(h.get(),[4,5,6]);h.cast();assert.equal(h.requests[1].entindex,4);});
test('stale portrait of an excluded super worker cannot force an ordinary cast',()=>{const h=harness();h.add([1],1,{super:true});h.add([4,5,6],2);h.select([1,4,5,6]);assert(h.cfg.SurvivalLumberjackFusionQueue.Cast(1001,1));assert.equal(h.requests.length,1);assert.equal(h.requests[0].entindex,4);});
test('ordinary successful fusion response removes product from actual selected group',()=>{const h=harness();h.add([1,2,3],1);h.add([4,5,6],2);h.select([1,2,3,4,5,6]);h.units[1].super=true;h.units[2].dead=true;h.units[3].dead=true;h.emit('ui_ability_cast_result',{success:1,entindex:1,ability_entindex:1001,ability_name:'ability_fuse_lumberjack_01',fusion_consumed_entindexes:{0:1,1:2,2:3},fusion_target_entindex:1});h.advance();assert.deepEqual(h.get(),[4,5,6]);h.cast();assert.equal(h.requests[0].entindex,4);});
test('successful ack excludes product while native ability removal is delayed',()=>{const h=harness();h.add([1,2,3],1);h.add([4,5,6],2);h.select([1,2,3,4,5,6]);h.cast();const req=h.requests[0];h.units[2].dead=true;h.units[3].dead=true;h.emit('ui_ability_cast_result',{success:1,entindex:1,ability_entindex:1001,ability_name:'ability_fuse_lumberjack_01',fusion_queue_request_id:req.fusion_queue_request_id,fusion_consumed_entindexes:[1,2,3],fusion_target_entindex:1});assert.deepEqual(h.get(),[4,5,6]);h.select([1,4,5,6]);assert.deepEqual(h.get(),[4,5,6]);h.cast();assert.equal(h.requests[1].entindex,4);});
test('ordinary late response does not steal a newly selected group',()=>{const h=harness();h.add([1,2,3],1);h.add([4,5,6],2);h.select([4,5,6]);h.emit('ui_ability_cast_result',{success:1,entindex:1,ability_entindex:1001,ability_name:'ability_fuse_lumberjack_01',fusion_consumed_entindexes:[1,2,3],fusion_target_entindex:1});h.advance();assert.deepEqual(h.get(),[4,5,6]);});
console.log('LUMBERJACK_FUSION_QUEUE_PASS '+n+' scenarios');

test('native death selection arrives before IsAlive and ack',()=>{const h=harness();h.add([1,2,3],1);h.add([4,5,6],2);h.select([1,2,3,4,5,6]);h.cast();h.select([1,4,5,6]);h.emit('survival_lumberjack_fused',{target_entindex:1,consumed_entindexes:[1,2,3]});h.advance();assert.deepEqual(h.get(),[4,5,6]);h.cast();assert.equal(h.requests[1].entindex,4);});
test('engine cast without custom acknowledgement removes product and stale materials',()=>{const h=harness();h.add([1,2,3],1);h.add([4,5,6],2);h.select([1,2,3,4,5,6]);h.emit('survival_lumberjack_fused',{target_entindex:1,consumed_entindexes:{1:1,2:2,3:3}});h.advance();assert.deepEqual(h.get(),[4,5,6]);h.select([1,4,5,6]);assert.deepEqual(h.get(),[4,5,6]);});
test('deliberately selecting surviving subset while awaiting fusion is retained',()=>{const h=harness();h.add([1,2,3],1);h.add([4,5,6],2);h.select([1,2,3,4,5,6]);h.cast();h.select([5]);h.emit('survival_lumberjack_fused',{target_entindex:1,consumed_entindexes:[1,2,3]});h.advance();assert.deepEqual(h.get(),[5]);});
