const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync('panorama/src/scripts/custom_game/topnav_remaining_5d5c1152eb.js','utf8').replace(/\r\n/g,'\n');
const start=src.indexOf('        stats.forEach(function(a,i){\n            var visible=shown.lumberjack');
const end=src.indexOf('        Object.keys(topButtons)',start);
assert(start>=0&&end>start);
const nodes={},stats=[['attack_speed','CombatAttackSpeedValue']];
['HandoffStatIcon_','HandoffStatName_','HandoffStat_','HandoffStatBonus_','HandoffStatPercent_'].forEach(p=>nodes[p+'attack_speed']={style:{}});
let snapshot={attack_speed:1.6,attack_speed_percentage:160,display_attack_speed_bonus:.9333,display_attack_speed_pct:60};
const env={stats,nodes,shown:{combat:true,attributes:true},multi:false,style:(p,s)=>Object.assign(p.style,s),text:(id,t)=>nodes[id].text=t,ctx:{FindChildTraverse:()=>({text:'160%'})},cfg:{HandoffCombat:{Snapshot:()=>snapshot}},selectedUnit:()=>1,compact:String};
vm.createContext(env);vm.runInContext(src.slice(start,end),env);
assert.equal(nodes.HandoffStat_attack_speed.text,'160%','final HUD must preserve percentage despite legacy frequency bonuses');
assert.equal(nodes.HandoffStatBonus_attack_speed.style.visibility,'collapse');
const combat=fs.readFileSync('panorama/src/scripts/custom_game/combat_stats.js','utf8');
const a=combat.indexOf('        // Percentage and frequency have distinct fields;');
const b=combat.indexOf('        officialAttackSpeedText = attackSpeed;',a);
const values={snapshot:{attack_speed:2/3,attack_speed_percentage:100},formatNumber:String};
vm.createContext(values);vm.runInContext(combat.slice(a,b),values);assert.equal(values.attackSpeed,'100%');
values.snapshot={attack_speed:1.6,attack_speed_percentage:160};vm.runInContext(combat.slice(a,b),values);assert.equal(values.attackSpeed,'160%');
values.snapshot={};vm.runInContext(combat.slice(a,b),values);assert.equal(values.attackSpeed,'100%');
console.log('ATTACK_SPEED_PERCENT_PASS: ordinary/fused snapshots, missing-value reset, legacy bonus does not overwrite percent');
