const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('panorama/src/scripts/custom_game/topnav_remaining_5d5c1152eb.js','utf8');
const textValues={},counter={visible:false,classes:{},SetHasClass(k,v){this.classes[k]=v;}},countdown={visible:false};
const env={cfg:{},sequence:-1,text:(k,v)=>textValues[k]=v,enemyCounter:counter,enemyCountdown:countdown};
vm.createContext(env);
vm.runInContext(source.slice(source.indexOf('    function compact('),source.indexOf('    function refreshNow(')),env);
env.data({sequence:1,resources:{gold:150,wood:234,population:3,max_population:10},wave:{current_wave:0,total_waves:30,timer:65,alive:90,alive_limit:90,overflow_active:false}});
assert.equal(textValues.HandoffWave,'下一波次 1  倒计时 01:05');assert.equal(textValues.HandoffEnemyValue,'90 / 90');assert.equal(countdown.visible,false);assert(counter.visible);
env.data({sequence:2,wave:{current_wave:12,total_waves:30,timer:9,alive:91,alive_limit:90,overflow_active:true,overflow_remaining:10}});
assert.equal(textValues.HandoffWave,'下一波次 13  倒计时 00:09');assert.equal(textValues.HandoffEnemyCountdown,'10');assert(countdown.visible);assert(counter.classes.EnemyOverflow);
env.data({sequence:1,wave:{alive:999,alive_limit:90,overflow_active:true,overflow_remaining:0}});assert.equal(textValues.HandoffEnemyValue,'91 / 90','stale private snapshot must not regress count');
env.data({sequence:3,wave:{current_wave:30,total_waves:30,alive:90,alive_limit:90,overflow_active:false}});assert.equal(countdown.visible,false);assert.equal(textValues.HandoffEnemyCountdown,'');assert(!counter.classes.EnemyOverflow);assert(!textValues.HandoffWave.includes('31'),'no fictitious next wave after final wave');
assert.equal(env.waveCaption({current_wave:30,total_waves:30,status:'archive_challenges'}),'挑战阶段');
assert(env.waveCaption({current_wave:0,total_waves:30,status:'selecting_mode'}).endsWith('倒计时 —'));
env.data({sequence:4,wave:{alive:0,alive_limit:90,player_defeated:true,overflow_active:true,overflow_remaining:0}});
assert.equal(textValues.HandoffEnemyTitle,'本局失败');assert.equal(textValues.HandoffEnemyValue,'可继续观战');assert.equal(countdown.visible,false);assert(counter.classes.EnemyDefeated);
env.data({sequence:5,wave:{alive:17,alive_limit:90,player_defeated:false,overflow_active:false}});
assert.equal(textValues.HandoffEnemyTitle,'进攻怪物');assert.equal(textValues.HandoffEnemyValue,'17 / 90');assert(!counter.classes.EnemyDefeated);
console.log('HUD_WAVE_COUNTER_PASS: next wave, server count, numeric-only grace timer, recovery, stale events, final challenge');