const fs=require('fs'),vm=require('vm'),assert=require('assert');
function setup(width=1920,height=1080,uiscale=1,omitNative=false){
 const nodes={},events={},jobs=[],activated=[],calls=[];let top=null;
 class Panel{constructor(type,parent,id){this.id=id||'';this.paneltype=type;this.parent=parent;this.children=[];this.style={};this.classes=new Set();this.events={};this.text='';if(parent)parent.children.push(this);if(id)nodes[id]=this;}IsValid(){return true}GetParent(){return this.parent}GetChildCount(){return this.children.length}GetChild(i){return this.children[i]}FindChildTraverse(id){if(this.id===id)return this;for(const c of this.children){const p=c.FindChildTraverse(id);if(p)return p;}return null}AddClass(c){this.classes.add(c)}RemoveClass(c){this.classes.delete(c)}SetHasClass(c,on){on?this.AddClass(c):this.RemoveClass(c)}ToggleClass(c){this.SetHasClass(c,!this.classes.has(c))}SetImage(s){this.src=s}SetPanelEvent(n,fn){this.events[n]=fn}RemoveAndDeleteChildren(){this.children=[]}}
 const root=new Panel('DOTAHud',null,'Hud'),ctx=new Panel('Panel',root,'Context');ctx.actuallayoutwidth=width;ctx.actuallayoutheight=height;ctx.actualuiscale_x=uiscale;ctx.actualuiscale_y=uiscale;
 for(const m of fs.readFileSync('panorama/src/layout/custom_game/survival_hud.xml','utf8').matchAll(/id="([^"]+)"/g))new Panel('Panel',ctx,m[1]);
 let list;if(!omitNative){const lower=new Panel('Panel',root,'lower_hud'),center=new Panel('Panel',lower,'center_with_stats'),block=new Panel('Panel',center,'center_block'),map=new Panel('Panel',root,'minimap_container'),mini=new Panel('Panel',map,'minimap_block');new Panel('DOTAMinimap',mini,'minimap');new Panel('Panel',block,'PortraitGroup');list=new Panel('DOTAAbilityList',new Panel('Panel',block,'AbilitiesAndStatBranch'),'abilities');for(let i=0;i<8;i++){const p=new Panel('DOTAAbilityPanel',list,'Ability'+i);p.nativeBinding=i;p.events.onactivate=()=>calls.push('ability'+i);if(i===7)p.AddClass('Hidden');}const inv=new Panel('DOTAInventory',block,'inventory');for(let i=0;i<9;i++){const p=new Panel('DOTAItem',inv,'inventory_slot_'+i);p.nativeBinding=i;p.events.ondragstart=()=>calls.push('drag'+i);}for(const id of ['DashboardButton','SettingsRebornButton','SharedUnitsButton','SharedContentButton','CombatLogButton','glyph','RadarButton'])new Panel('Button',root,id);}
 const cfg={SurvivalUILayers:{Top:()=>top},SurvivalArchive:{Toggle:()=>calls.push('archive')},SurvivalLottery:{Open:()=>calls.push('lottery')},SurvivalHudTakeover:{abilities:false,inventory:false,stats:false}};
 function $(id){return nodes[id.slice(1)]}$.CreatePanel=(t,p,id)=>new Panel(t,p,id);$.GetContextPanel=()=>ctx;$.Schedule=(delay,fn)=>jobs.push(fn);$.DispatchEvent=(...args)=>activated.push(args);
 const env={$,GameUI:{CustomUIConfig:()=>cfg},Game:{GetLocalPlayerID:()=>0,GetPlayerInfo:()=>({player_name:'真实玩家',player_kills:7})},GameEvents:{Subscribe:(n,fn)=>events[n]=fn},CustomNetTables:{GetTableValue:()=>null},Players:{},Entities:{}};
 require('./load_shared_ui_test.cjs')(env,Panel,ctx);
 for(const f of ['main_hud_assets.js','main_hud_skin.js'])vm.runInNewContext(fs.readFileSync('panorama/src/scripts/custom_game/'+f,'utf8'),env);
 return {nodes,cfg,events,jobs,activated,calls,ctx,root,list,setTop:t=>top=t};
}
const a=setup();assert(a.cfg.SurvivalMainHUD.Inspect().nativeReady);assert.equal(a.cfg.SurvivalMainHUD.Inspect().scale,1080/941);
for(let i=0;i<8;i++){const n=a.nodes['Ability'+i];assert.equal(n.parent,a.list);assert.equal(n.nativeBinding,i);assert.equal(n.children.length,0,'no injected native ability descendants');}assert(a.nodes.Ability7.classes.has('Hidden'));
a.nodes.Ability0.events.onactivate();a.nodes.inventory_slot_3.events.ondragstart();assert.deepEqual(a.calls,['ability0','drag3']);assert.equal(a.cfg.SurvivalHudTakeover.abilities,false);assert.equal(a.cfg.SurvivalHudTakeover.inventory,false);
a.nodes.MainHudEntry_return.events.onactivate();assert.equal(a.activated.at(-1)[0],'Activated');assert.equal(a.activated.at(-1)[1],a.nodes.DashboardButton);
a.nodes.MainHudEntry_archive.events.onactivate();assert.equal(a.calls.at(-1),'archive');a.setTop('lottery');a.nodes.MainHudEntry_archive.events.onactivate();assert.equal(a.calls.filter(x=>x==='archive').length,1);a.setTop(null);
assert(a.nodes.MainHudEntry_equipment.classes.has('Unavailable'));a.nodes.MainHudEntry_equipment.events.onactivate();assert.equal(a.nodes.MainHudEntry_equipment.enabled,false);
a.events.survival_ui_private_snapshot({sequence:4,city_level:3,resources:{gold:123,wood:456,population:7,max_population:10},wave:{current_wave:8,timer:93,difficulty_id:'N3',alive:12,pending:4}});
assert.equal(a.nodes.MainHudWaveText.text,'第8波 · 1:33');assert.equal(a.nodes.MainHudCurrencyText.text,'123');assert.equal(a.nodes.MainHudWaveTrack.visible,false);assert.equal(a.nodes.MainHudWaveFill.style.width,'0%');assert(a.nodes.MainHudResourcesExtra.text.includes('7/10'));
a.events.survival_ui_private_snapshot({sequence:3,resources:{gold:999}});assert.equal(a.nodes.MainHudCurrencyText.text,'123','stale private snapshot rejected');
a.nodes.SurvivalHeroName.text='当前选中的真实单位';a.nodes.SurvivalHeroHealthText.text='250000 / 500000';a.nodes.SurvivalHeroHealthFill.style.width='50%';a.nodes.CombatAttackValue.text='9000';a.jobs.shift()();assert.equal(a.nodes.MainHudHeroName.text,'当前选中的真实单位');assert.equal(a.nodes.MainHudHealthFill.style.width,'50%');assert.equal(a.nodes.MainHudStat_attack.text,'9000');
for(const [w,h,u] of [[1672,941,1],[1280,720,720/1080],[3440,1440,1440/1080],[1024,768,768/1080]]){const b=setup(w,h,u),s=b.cfg.SurvivalMainHUD.Inspect();assert(Math.abs(s.designWidth*s.scale*u-w)<.01);assert(Math.abs(s.designHeight*s.scale*u-h)<.01);assert.equal(b.nodes.minimap.paneltype,'DOTAMinimap');assert.equal(b.nodes.MainHudFrame_hero.hittest,false);}
const partial=setup(1920,1080,1,true);assert(!partial.cfg.SurvivalMainHUD.Inspect().nativeReady);assert(!partial.ctx.classes.has('MainHudSkinReady'),'do not suppress live HUD before all native anchors exist');
console.log('MAIN_HUD_TEST_PASS: native bindings/tree, hidden ability preservation, official return, modal input guard, real/stale data, no fabricated timer, uniform scaling, delayed anchors');
