// Real production dispatch + native/takeover display, with engine boundaries mocked.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=process.cwd(),sourceRoot=path.resolve(process.argv[2]||root),combatPath=path.join(sourceRoot,'panorama/src/scripts/custom_game/combat_stats.js');
let helper=fs.readFileSync(path.join(root,'tools/test_combat_stats_callbacks.cjs'),'utf8');
helper=helper.replace('hotkeyForAbilityEntry:hotkeyForAbilityEntry,','hotkeyForAbilityEntry:hotkeyForAbilityEntry,bindHotkeys:bindHotkeys,pointTargetMouseHandler:pointTargetMouseHandler,');
helper=helper.replace('GameUI:{CustomUIConfig:()=>cfg},','GameUI:{CustomUIConfig:()=>cfg,GetCursorPosition:()=>[100,100],GetScreenWorldPosition:()=>[128,192,384]},');
const hm={exports:{}};vm.runInNewContext(helper,{require,module:hm,process:{argv:['node','test',combatPath]},console},{filename:'test_combat_stats_callbacks.cjs'});
const ids=[101,102,103,104,105,106],names=['ability_build_wall','ability_build_main_city','ability_build_arrow_tower','ability_build_farm','ability_build_research_lab','ability_build_challenge'],requests=[];let handler,passive=false;
const cfg={SurvivalInputDispatcher:{RegisterKeyHandler:(id,fn)=>{if(id==='ability_input')handler=fn}}};
const t=hm.exports.setup({portrait:true,config:cfg,entities:{GetAbility:(unit,slot)=>unit===7?(ids[slot]??-1):-1,IsValidEntity:unit=>unit===7},abilities:{GetAbilityName:id=>names[ids.indexOf(id)]||'',GetBehavior:id=>id===106&&passive?2:16,IsPassive:id=>id===106&&passive,IsHidden:()=>false},events:{SendCustomGameEventToServer:(name,payload)=>requests.push({name,payload})}});
t.select(7,'npc_survival_builder_proxy');t.runtime['unit:7']={owner_entindex:7,ability_count:ids.length};ids.forEach((id,index)=>t.runtime[id]={owner_entindex:7,ability_entindex:id,builder_slot_order:index+1,available:1,prerequisite_met:1,can_afford:1});
const nativeRoot=new t.Panel('abilities',t.root);ids.forEach((id,index)=>{const slot=new t.Panel('Ability'+index,nativeRoot),anchor=new t.Panel('AbilityButton',slot);new t.Panel('AbilityImage',anchor);new t.Panel('HotkeyContainer',slot);});
t.api.refreshHotkeys(false);const label=index=>nativeRoot.FindChildTraverse('Ability'+index).FindChildTraverse('SurvivalAbilityHotkey');assert.deepEqual(ids.map((id,index)=>label(index).text),['Q','W','E','R','T','C']);assert.equal(nativeRoot.FindChildTraverse('Ability5').FindChildTraverse('HotkeyContainer').values.opacity,'0','native slot key must stay suppressed');
t.api.bindHotkeys();assert.equal(typeof handler,'function');assert.equal(handler('C',false),false,'key release does not cast');assert.equal(handler('A',true),false,'previous builder key no longer routes challenge');assert.equal(cfg.SurvivalPointTargetState,undefined);
t.setTime(.2);assert.equal(handler('C',true),true);assert.equal(cfg.SurvivalPointTargetState.ability,106);assert.equal(cfg.SurvivalPointTargetState.unit,7);assert.equal(cfg.SurvivalPointTargetState.name,'ability_build_challenge');assert.equal(requests.length,0,'C keeps existing point cursor, no early build request');assert.equal(t.api.pointTargetMouseHandler('pressed',0),true);assert.equal(requests.length,1);assert.equal(requests[0].name,'ui_ability_cast_position_request');assert.equal(requests[0].payload.ability_entindex,106);assert.equal(requests[0].payload.entindex,7);assert.deepEqual([requests[0].payload.x,requests[0].payload.y,requests[0].payload.z],[128,192,384]);
t.setTime(.4);assert.equal(handler('T',true),true);assert.equal(cfg.SurvivalPointTargetState.ability,105,'research-building T remains unchanged');cfg.SurvivalPointTargetInput.Cancel('test');t.runtime[106].completed=1;t.setTime(.6);assert.equal(handler('C',true),false);assert.equal(cfg.SurvivalPointTargetState.active,false,'completed challenge is not opened');t.runtime[106].completed=0;passive=true;t.api.refreshHotkeys(false);assert.equal(t.api.hotkeyForAbilityEntry({ability:106,name:names[5]},'npc_survival_builder_proxy'),'','passive contract preserved');passive=false;t.api.refreshHotkeys(false);assert.equal(label(5).text,'C');
// Reused/recreated native slots retain C through existing recovery checks.
const old=label(5);old.alive=false;const parent=old.GetParent();parent.children=parent.children.filter(x=>x!==old);t.api.refreshHotkeys(false);assert.notEqual(label(5),old);assert.equal(label(5).text,'C');t.select(8,'npc_dota_hero_test');t.setTime(.8);assert.equal(handler('C',true),false);assert.equal(handler('A',true),false,'combat-hero native attack is still passed through');
// The fallback HUD uses its actual production mapping too, without initializing layout.
let takeoverHotkey;const takeoverSource=fs.readFileSync(path.join(sourceRoot,'panorama/src/scripts/custom_game/hud_takeover.js'),'utf8'),takeoverSeam='    function selectedUnit() {';assert(takeoverSource.includes(takeoverSeam));vm.runInNewContext(takeoverSource.replace(takeoverSeam,'    __takeover(hotkeyForEntry);return;\n'+takeoverSeam),{$:{GetContextPanel:()=>({})},GameUI:{CustomUIConfig:()=>({})},Game:{GetLocalPlayerID:()=>0},Players:{GetLocalPlayerPortraitUnit:()=>7},Entities:{GetUnitName:()=> 'npc_survival_builder_proxy'},Abilities:{GetBehavior:()=>16},CustomNetTables:{GetTableValue:(table,key)=>t.runtime[key]||{}},__takeover:fn=>takeoverHotkey=fn});assert.equal(takeoverHotkey({ability:106,name:names[5]}),'C');assert.equal(takeoverHotkey({ability:105,name:names[4]}),'T');
// Run the existing real bootstrap dispatch guards with only source reads redirected.
const fixtureSource=fs.readFileSync(path.join(root,'tools/test_minimap_shortcut_input.cjs'),'utf8');const proxyFS=new Proxy(fs,{get:(o,key)=>key==='readFileSync'?((file,...args)=>{const relative=typeof file==='string'&&!path.isAbsolute(file)?path.join(sourceRoot,file):file;return fs.readFileSync(relative,...args);}):o[key]});vm.runInNewContext(fixtureSource+'\nassert(binds.has("C"),"C native fallback registered");assert.equal(typeof commands.get(binds.get("C")),"function");\n',{require:name=>['fs','node:fs'].includes(name)?proxyFS:require(name),console:{log:()=>{}},process},{filename:'test_minimap_shortcut_input.cjs'});

// Verify actual CreateCustomKeyBind C route even without native key callback.
const fallbackFixture=fixtureSource.slice(0,fixtureSource.indexOf('const dispatch =')).replace('SetKeyPressedCallback: fn => { nativeKey = fn; },','')+`
selected=20;units.get(20).skills=[80];abilities.set(80,{name:'ability_build_challenge',level:1,cooldown:0});sandbox.Abilities.GetBehavior=()=>16;
table('survival_ability_runtime','unit:20',{owner_entindex:20,ability_count:1});table('survival_ability_runtime','80',{owner_entindex:20,ability_entindex:80,builder_slot_order:6,available:1,prerequisite_met:1});
assert.equal(typeof nativeKey,'undefined');assert(binds.has('C'));commands.get(binds.get('C'))();assert.equal(cfg.SurvivalPointTargetState.ability,80);assert.equal(cfg.SurvivalPointTargetState.unit,20);
cfg.SurvivalPointTargetInput.Cancel('test');focused=chatInput;advance();commands.get(binds.get('C'))();assert.equal(cfg.SurvivalPointTargetState.active,false,'chat typing cannot trigger C fallback');focused=null;modal='treasures';advance();commands.get(binds.get('C'))();assert.equal(cfg.SurvivalPointTargetState.active,false,'modal cannot trigger C fallback');
`;
vm.runInNewContext(fallbackFixture,{require:name=>['fs','node:fs'].includes(name)?proxyFS:require(name),console:{log:()=>{}},process},{filename:'bootstrap_fallback_c.cjs'});
console.log('BUILDER_CHALLENGE_C_PASS: actual C point cast+confirmation, native/takeover labels, oldA removed, T preserved, passive/completed/recreated-panel/hero guards and native fallback');