const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{spawn}=require('child_process'),{pathToFileURL}=require('url');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),dir=path.resolve('art/ui/development/ui_reuse_import/preview');
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'ui-reuse-review-')),chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+profile,pathToFileURL(path.join(dir,'index.html')).href],{windowsHide:true,stdio:'ignore'});let ws;
try{for(let i=0;i<100&&!fs.existsSync(path.join(profile,'DevToolsActivePort'));i++)await sleep(100);const port=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0],targets=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let serial=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data),p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}};const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++serial,{resolve,reject});ws.send(JSON.stringify({id:serial,method,params}))});const run=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1920,height:1440,deviceScaleFactor:1,mobile:false});await sleep(300);assert(await run('window.previewReady'));await run('document.fonts.ready.then(()=>true)');await sleep(300);assert.equal(await run('[...document.images].filter(i=>!i.complete||!i.naturalWidth).length'),0);
const shot=async name=>{const r=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(dir,name+'.png'),Buffer.from(r.data,'base64'))};await shot('states-1920');
const report={kind:'browser_preview_not_game_capture',checks:[],fontChecksAreNotProofOfInstallation:true,fonts:await run('({serif:document.fonts.check("16px Source Han Serif SC"),sans:document.fonts.check("16px Source Han Sans SC")})')};
for(const[w,h]of[[1280,720],[1920,1080],[2560,1440],[3440,1440]]){await call('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:false});await run('showModal(1208,806);true');await sleep(300);const rect=await run('(()=>{const r=currentModal.panel.el.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()');assert(rect.x>=-1&&rect.y>=-1&&rect.x+rect.width<=w+1&&rect.y+rect.height<=h+1,JSON.stringify(rect));assert(Math.abs(rect.width/rect.height-1208/806)<.001);await shot('modal-'+w+'x'+h);await run('currentModal.panel.el.click()');assert(await run('currentModal.IsOpen()'),'inside click must not close');await run('currentModal.RequestClose()');assert(!(await run('currentModal.IsOpen()')));report.checks.push({width:w,height:h,rect,insideClick:true,close:true});}
fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify(report,null,2));console.log('SHARED_UI_BROWSER_PASS: production factories, images loaded, modal fit at 4 sizes, inside click/close; NOT native Dota capture');
}finally{if(ws)ws.close();chrome.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
