const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{spawn}=require('child_process'),{pathToFileURL}=require('url');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),dir=path.resolve('art/ui/development/daily_rewards_import/preview');
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'daily-review-')),chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless','--disable-gpu','--no-first-run','--remote-debugging-port=0','--user-data-dir='+profile,pathToFileURL(path.join(dir,'index.html')).href],{windowsHide:true,stdio:'ignore'});let ws;
try{for(let i=0;i<100&&!fs.existsSync(path.join(profile,'DevToolsActivePort'));i++)await sleep(100);const port=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0],targets=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let serial=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data),p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}};const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++serial,{resolve,reject});ws.send(JSON.stringify({id:serial,method,params}))});const run=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1672,height:941,deviceScaleFactor:1,mobile:false});await sleep(500);assert(await run('window.previewReady'));await run('document.fonts.ready.then(()=>true)');
const shot=async name=>{const r=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(dir,name+'.png'),Buffer.from(r.data,'base64'))};
assert.equal(await run('[...document.images].filter(i=>!i.complete||!i.naturalWidth).length'),0);assert.equal(await run('nodes.DailyCards.children.length'),7);await shot('actual-code-1672x941');
assert(await run('nodes.DailyClaim.enabled'));await run('nodes.DailyClaim.el.click();nodes.DailyClaim.el.click()');assert.equal(await run('requests.filter(r=>r.n==="survival_daily_claim").length'),1);assert(!(await run('nodes.DailyClaim.enabled')));await shot('busy');
await run('events.survival_daily_snapshot({...fixture,sequence:2,claim_result:{target_day:25000,ok:false,error:"测试：保存失败"}})');assert(await run('nodes.DailyClaim.enabled'));assert.equal(await run('nodes.DailyClaimText.text'),'重试领取');await shot('failed');
await run('nodes.DailyClaim.el.click();events.survival_daily_snapshot({...fixture,sequence:3,claimed:1,ordinary_status:"claimed",count:7})');assert(!(await run('nodes.DailyClaim.enabled')));
await run('events.survival_daily_snapshot({...fixture,sequence:2})');assert(!(await run('nodes.DailyClaim.enabled')),'old snapshot ignored');
await run('events.survival_daily_snapshot({...fixture,sequence:4,today:25001,period_id:"1",count:7,ordinary_status:"claimed",premium:{status:"claimable",name:"测试专属槽"}})');assert.equal(await run('nodes.DailyClaimText.text'),'领取通行证奖励');assert(await run('nodes.DailyClaim.enabled'));await shot('premium-only-preview');
await run('events.survival_daily_snapshot({...fixture,sequence:5,ordinary_status:"claimed",today:25001,premium:{status:"claimed",name:"测试专属槽"}})');assert(!(await run('nodes.DailyClaim.enabled')));await shot('all-claimed-preview');
await run('events.survival_daily_snapshot({...fixture,sequence:6,today:25002,has_pass:0,premium:{status:"requires_pass",name:"测试专属槽"}})');assert(await run('nodes.DailyClaim.enabled'));assert(!(await run('nodes.DailyMakeup.enabled')));await shot('no-pass-preview');
await run('nodes.DailyWindow.el.click()');assert.equal(await run('config.SurvivalUILayers.Top()'),'daily_rewards');await run('nodes.DailyScrim.el.click()');assert.equal(await run('config.SurvivalUILayers.Top()'),null);await run('config.SurvivalDaily.Open(false);nodes.DailyClose.el.click()');assert.equal(await run('config.SurvivalUILayers.Top()'),null);
const checks=[];for(const[w,h]of[[1280,720],[1920,1080],[2560,1440],[3440,1440]]){await call('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:false});await run('config.SurvivalDaily.Open(false)');await sleep(300);const rect=await run('(()=>{const r=nodes.DailyWindow.el.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()');assert(rect.x>=-1&&rect.y>=-1&&rect.x+rect.width<=w+1&&rect.y+rect.height<=h+1,JSON.stringify({w,h,rect}));assert(Math.abs(rect.width/rect.height-1348/758)<.001);checks.push({w,h,rect});await shot('fit-'+w+'x'+h);}
fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify({kind:'browser_actual_code_NOT_game_capture',checks,tests:['7 cards','no duplicate submission','failed retry','server confirmed claim','stale snapshot','new period','independent bonus states (preview only)','inside click','scrim close','close button'],fonts:await run('({sans:document.fonts.check("20px Source Han Sans SC"),serif:document.fonts.check("38px Source Han Serif SC")})')},null,2));console.log('DAILY_BROWSER_PASS: production controller, state matrix, resources, closing, stale snapshots and four scales');
}finally{if(ws)ws.close();chrome.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
