const fs=require('fs'),path=require('path'),z=require('zlib');
const root=path.resolve(__dirname,'../output/xianxia_kit');
function pngWrite(file,w,h,data){function ch(t,v){const c=Buffer.concat([Buffer.from(t),v]);let crc=0xffffffff;for(const a of c){crc^=a;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}const o=Buffer.alloc(c.length+8);o.writeUInt32BE(v.length);c.copy(o,4);o.writeUInt32BE((crc^0xffffffff)>>>0,o.length-4);return o;}const rows=Buffer.alloc((w*4+1)*h);for(let y=0;y<h;y++)data.copy(rows,y*(w*4+1)+1,y*w*4,(y+1)*w*4);const ih=Buffer.alloc(13);ih.writeUInt32BE(w);ih.writeUInt32BE(h,4);ih[8]=8;ih[9]=6;fs.writeFileSync(file,Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),ch('IHDR',ih),ch('IDAT',z.deflateSync(rows)),ch('IEND',Buffer.alloc(0))]));}
function pngRead(p){const b=fs.readFileSync(p);let pos=8,w,h,type,depth,parts=[];while(pos<b.length){const n=b.readUInt32BE(pos),t=b.toString('ascii',pos+4,pos+8),v=b.subarray(pos+8,pos+8+n);if(t==='IHDR'){w=v.readUInt32BE();h=v.readUInt32BE(4);depth=v[8];type=v[9];}if(t==='IDAT')parts.push(v);pos+=n+12;}if(depth!==8||![2,6].includes(type))throw Error('PNG format');const c=type===6?4:3,stride=w*c,raw=z.inflateSync(Buffer.concat(parts)),out=Buffer.alloc(w*h*c);let p0=0;for(let y=0;y<h;y++){const f=raw[p0++];for(let x=0;x<stride;x++){const at=y*stride+x,a=x>=c?out[at-c]:0,b=y?out[at-stride]:0,d=y&&x>=c?out[at-stride-c]:0;let v=0;if(f===1)v=a;if(f===2)v=b;if(f===3)v=(a+b)>>1;if(f===4){const pp=a+b-d,pa=Math.abs(pp-a),pb=Math.abs(pp-b),pc=Math.abs(pp-d);v=pa<=pb&&pa<=pc?a:pb<=pc?b:d;}out[at]=(raw[p0++]+v)&255;}}return{w,h,c,data:out};}
const a=JSON.parse(fs.readFileSync(path.join(root,'asset_manifest.json'))),m=JSON.parse(fs.readFileSync(path.join(root,'material_manifest.json'))),lod=JSON.parse(fs.readFileSync(path.join(root,'lod_manifest.json')));
const validation=JSON.parse(fs.readFileSync(path.join(root,'validation.json')));validation.clouds=[];
const cs=JSON.parse(fs.readFileSync(path.join(root,'clouds/cloud_manifest.json')));
if(cs.complete)for(const item of cs.items){const p=pngRead(path.join(root,'clouds',item.name+'.png'));let edge=0,soft=0,visible=0,transparent=0;for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++){const aa=p.data[(y*p.w+x)*4+3];if(x<4||y<4||x>=p.w-4||y>=p.h-4)edge=Math.max(edge,aa);if(aa>2)visible++;if(aa>2&&aa<243)soft++;if(!aa)transparent++;}validation.clouds.push({name:item.name,borderAlphaMax:edge/255,visibleFraction:visible/(p.w*p.h),softEdgePixels:soft,transparentPixels:transparent,pass:edge===0&&visible>100,method:'raw straight-RGBA PNG decoded without color conversion'});}
fs.writeFileSync(path.join(root,'validation.json'),JSON.stringify(validation,null,2));
// Source 2 requires power-of-two textures. Pad, never stretch, the RGBA bake.
fs.mkdirSync(path.join(root,'clouds/runtime'),{recursive:true});
if(cs.complete)for(const item of cs.items){const p=pngRead(path.join(root,'clouds',item.name+'.png')),side=2048,d=Buffer.alloc(side*side*4),left=(side-p.w)>>1,top=(side-p.h)>>1;for(let y=0;y<p.h;y++)p.data.copy(d,((y+top)*side+left)*4,y*p.w*4,(y+1)*p.w*4);pngWrite(path.join(root,'clouds/runtime',item.name+'.png'),side,side,d);
 for(const mode of ['dark','light','checker']){const composite=Buffer.alloc(p.data.length);for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++){const i=(y*p.w+x)*4,alpha=p.data[i+3]/255,bg=mode==='dark'?28:mode==='light'?226:((Math.floor(x/48)+Math.floor(y/48))%2?90:135);for(let k=0;k<3;k++)composite[i+k]=Math.round(p.data[i+k]*alpha+bg*(1-alpha));composite[i+3]=255;}pngWrite(path.join(root,'previews',item.name+'_'+mode+'.png'),p.w,p.h,composite);}
}
const labels={terrain:'岸线与道路',architecture:'亭阁与器物',vegetation:'植被与岩石'};
const title={t01_shore_straight:'直线岛岸',t02_shore_outer:'外角岛岸',t03_shore_inner:'内角岛岸',t04_stairs:'宽台阶',t04_ramp:'缓坡',a01_pavilion:'四角亭',a02_gateway:'入口门楼',a03_stone_lamp:'石灯',a03_censer:'香炉',v01_pine_0:'松树 · 直立',v01_pine_1:'松树 · 倾斜',v02_peach_0:'桃花 · 主树',v02_peach_1:'桃花 · 小树'};
const engine=fs.existsSync(path.join(root,'previews/engine_assembly.png'));
let html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>修仙组件库 · 首版实物预览</title><style>
*{box-sizing:border-box}body{margin:0;background:#e8ebe8;color:#243732;font:16px/1.7 "Microsoft YaHei",sans-serif}main{max-width:1440px;margin:auto;padding:32px}h1{font-size:34px;margin:0}h2{margin-top:42px}p{max-width:1050px}a{color:#236c70}button,input,select{font:inherit;padding:8px 16px;border:1px solid #acbab3;border-radius:6px;background:#fff;color:#263e3c}button{cursor:pointer}.lead{background:#d8e4dd;padding:20px;border-left:5px solid #427267}.hero{width:100%;border-radius:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:18px}article{background:#f8faf7;padding:14px;border:1px solid #c8d1cb;border-radius:8px}article img{width:100%;border-radius:5px;cursor:zoom-in}small{color:#60726a;display:block}.cloud{background:repeating-conic-gradient(#354654 0% 25%,#566571 0% 50%) 0 /32px 32px}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.pill{background:#dce6df;border-radius:4px;padding:4px 10px;display:inline-block}dialog{border:0;background:#e5e9e4;padding:12px;max-width:95vw}dialog img{max-width:90vw;max-height:85vh;display:block}dialog::backdrop{background:#111c}code{font-size:13px}footer{margin-top:40px;border-top:1px solid #adbdb2;padding:20px 0}</style><main>
<h1>修仙组件库 · 首版实物预览</h1><p>按四张概念板重新建模与制作独立材质。下面显示实际模型渲染与导入验证，不是概念图裁片。</p>
<div class="lead"><b>本轮交付：26 个模型 + 26 个简化版本，10 套表面贴图，2 套几何植被材质，4 类云烘焙源文件。</b><br>这是可复用组件与局部组合样板；还没有替换全图。当前造型与表面细节比概念图简化，云片用于固定俯视角、有限尺度的遮挡，不能无限放大或密集平铺。</div>
${fs.existsSync(path.join(root,'cloud_revision_v2/compile_validation.json'))?'<p><a href="cloud_revision_v2/index.html"><b>查看云组件第二版：新旧对比与实机预览</b></a> · 模型和地面材质沿用本版。</p>':''}
<h2>组合样板</h2><p>开阔石台、384 单位宽台阶、青瓦门楼与角亭；植被集中在角部。下图是 Blender 渲染。</p><img class="hero zoom" src="previews/assembly.png">
${engine?'<h2>Source 2 实际截图</h2><img class="hero zoom" src="previews/engine_assembly.png"><p>独立测试地图：<code>dota_launch_custom_game survival xianxia_kit_review</code></p>':''}
<h2>模型组件</h2><div class="controls"><select id="category"><option value="all">全部组件</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><input id="search" placeholder="搜索名称 / 编号"></div><div class="grid" id="models">`;
for(const x of a){const l=lod.find(y=>y.name===x.name);html+=`<article data-cat="${x.category}" data-name="${x.name} ${title[x.name]||''}"><img class="zoom" loading="lazy" src="previews/${x.name}.png"><b>${title[x.name]||x.name}</b><small>${x.name}</small><small>${x.triangles.toLocaleString()} 三角面 · 简化版 ${l.lod1Triangles.toLocaleString()} 面</small><small>尺寸 ${x.bounds[1].map((v,i)=>Math.round(v-x.bounds[0][i])).join(' × ')} 单位</small><a href="models/${x.name}.fbx">FBX</a> · <a href="source_models/${x.name}.vmdl">ModelDoc</a></article>`;}
html+='</div><h2>独立材质与无缝平铺检查</h2><p>彩色图按 sRGB 使用，法线、高度、粗糙度与遮罩按线性数据使用。法线由独立高度场生成，采用 +Y 切线空间；未从概念图颜色推算法线。点图查看 2 × 2 拼接。</p><div class="grid">';
for(const x of m)html+=`<article><img class="zoom" loading="lazy" src="previews/${x.name}_repeat_2x2.png"><b>${x.name}</b><small>1024 × 1024 · 两轴周期边界验证</small>${Object.keys(x.maps).map(k=>`<a href="materials/${x.name}_${k}.png">${k}</a>`).join(' · ')}</article>`;
html+='</div><h2>云海与云带：透明边缘检查</h2><p>云是在 Blender 中计算体积光照后烘焙成独立 RGBA。当前细节仍偏概括，不能当作最终近景体积云。建议单层少量使用，并在不同高度错开；如需概念图中的近景细节，还需更高分辨率、多视角云图集或专门的运行时云着色器。</p><div class="controls"><button onclick="cloudBg(0)">棋盘底</button><button onclick="cloudBg(1)">深色底</button><button onclick="cloudBg(2)">浅色底</button></div><div class="grid">';
for(const x of cs.items)html+=`<article><img class="cloud zoom" src="clouds/${x.name}.png"><b>${x.name}</b><small>${cs.complete?'烘焙完成':'烘焙中'} · 固定清晨光照 · 1536 × 896 RGBA</small><a href="clouds/${x.name}.blend">体积云 Blender 源文件</a></article>`;
html+=`</div><footer><a href="xianxia_library.blend">模型库 .blend</a> · <a href="xianxia_assembly.blend">组合场景 .blend</a> · <a href="README.md">使用说明与限制</a> · <a href="validation.json">数据验证报告</a></footer></main><dialog id="viewer"><button onclick="viewer.close()">关闭</button><img id="large"></dialog><script>
const viewer=document.getElementById('viewer');document.querySelectorAll('.zoom').forEach(im=>im.onclick=()=>{document.getElementById('large').src=im.src;viewer.showModal()});viewer.onclick=e=>{if(e.target===viewer)viewer.close()};function filter(){document.querySelectorAll('#models article').forEach(a=>a.hidden=!((category.value==='all'||a.dataset.cat===category.value)&&a.dataset.name.toLowerCase().includes(search.value.toLowerCase())))}category.onchange=filter;search.oninput=filter;function cloudBg(n){document.querySelectorAll('.cloud').forEach(x=>x.style.background=n===1?'#1c2c38':n===2?'#e9e4db':'')}
</script></html>`;
fs.writeFileSync(path.join(root,'index.html'),html);console.log('Gallery ready',a.length,'models;',validation.clouds.length,'cloud checks');
